<link href="<?php echo $this->getSkinUrl();?>css/datatables.min.css" rel="stylesheet" />
<script src="<?php echo $this->getSkinUrl();?>js/datatables.min.js" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl();?>css/select2.min.css" rel="stylesheet" />
<script src="<?php echo $this->getSkinUrl();?>js/select2.min.js"></script>
<link href="<?php echo $this->getSkinUrl();?>css/mealorder.css" rel="stylesheet" />
<script src="<?php echo $this->getSkinUrl();?>js/mealorder.js"></script>
<script src="<?php echo $this->getSkinUrl();?>js/jspdf.min.js"></script>
<style>
  .main{  
  width: 100%;   
    margin-top:8rem;
    height:100%;
    margin-bottom: 2rem;
  }
#myDIVweight {
  width: 500px;
padding: 10px 0;
text-align: center;
background-color:lightblue;
margin-top: 20px;
position: absolute;
font-size: 14px;
color:#000;
text-transform: uppercase;
}
	 /* Tooltip */
  .tooltip {
  position: relative;
display: inline-block;
opacity: 1;
height: 40px;
width: 100%;
text-align: justify;
  }

.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0;
  
  /* Position the tooltip */
  position: absolute;
  z-index: 1;
  bottom: 100%;
  left: 50%;
  margin-left: -60px;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
}
	
/*
	#toastshow > a{
   cursor: pointer;
  display: block;
}

#toastshow > .toastweight{
  display: none;
}
#toastshow:focus .toastweight{
  display: block; 
}*/
span a {
    text-decoration: none;
    color: red !important;
    transition: all 0.15s ease-out;
    font-size: 10px !important; 
    font-weight: normal;
}
</style>
<div id="pageloader" class="loader" style="display: none;"></div>
<table id="example" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Order Date</th>
            <th>Mobile</th>
            <th>Target</th>
            <td style="text-align: center;font-weight: bold;">For Daily Delivery</td>
            <th>Note</th>
            <td class="none">Dinner</td>
            <td class="none">Breakfast</td>
            <td class="none">Lunch</td>
            <td class="none">HiTea</td>
            <td class="none"></td>
        </tr>
    </thead>
   
    <tbody>
<?php $limit = 500;

$collection = Mage::getModel("heal/order")->getCollection(); 
$collection->getSelect()->order('id DESC');
$collection->getSelect()->limit($limit); 

    $count=0;
    $style="";
    foreach($collection as $item) {
      $healOrder  = Mage::getModel("heal/order")->load($item['id']);
	  $customerMealDetails = Mage::helper("heal")->getMealInfo($healOrder);
	  $customerName = str_replace("Dear ","",$item['name']);
	  
	  $count++; if($count%2==0){ $style="bgcolor:'#eee'";}else{ $style="bgcolor:'#ffffff'";}  ?>
        <tr id="<?php echo $item['id'];?>" class="lazyload" >
            <td class=" details-control"><?php echo $item['id'];?></td>
            <td><?php echo $customerName;?><br><div>
			<div style="font-size:9px;color:green" class="countDelived_<?php echo $item['id'];?>"  >
			<div style="font-size:9px;color:green">Meal Count : <span style="font-size:9px;color:blue"> <?php echo $customerMealDetails['totalDeliveredMeals'];?></span></div>
			<div style="font-size:9px;color:green">Package Days : <span style="font-size:9px;color:blue"> <?php echo $customerMealDetails['packageDays'];?></span></div>
			<div style="font-size:9px;color:green">In Grace Period : <?php echo $customerMealDetails['usingGracePeriod'];?></div>
			 <div style="font-size:9px;color:green" class="reviewed_<?php echo $item['id'];?>"  >
				<?php if($item['reviewedby']!=''){echo "Reviewed By : ".$item['reviewedby'];} 
		              else { echo "Not reviewed";} ?>
				   </div>
                         <div style="font-size:9px;color:green">Meal Level :
							<span style="font-size:9px;color:red"><?php if(isset($customerMealDetails['carbsCaloryInfo']) && $customerMealDetails['carbsCaloryInfo']!='' )
                                     { $carbsCaloryInfo = explode("_",$customerMealDetails['carbsCaloryInfo']);
                                       ?>
                                         <a class="levelClass" href="#" data-toggle="tooltip" title="Meal carb should less than <?php echo $carbsCaloryInfo[2];?> and calory should be between <?php echo $carbsCaloryInfo[3];?> and <?php echo $carbsCaloryInfo[4];?>">
                                         <?php echo $carbsCaloryInfo[0];?></a>
                                   <?php 
                                     } 
                                     else { echo "Not defined"; }?>
								</a></span></div>
			<div onclick="myFunctionweight()" style="font-size:9px;color:green; cursor:pointer" tabindex="1"><a>Weight : <span style="font-size:9px;color:red">Not Defined</span></a>
				</div>
				<div id="myDIVweight"  style="display:none;">

<form action="">
Weight: <input type="text" name="weight" value="Enter weight">
<button type="button" class="btn btn-primary btn-sm">Submit</button>
</form>
</div>
  
              </div>
			  <?php // echo "<pre>"; print_r($customerMealDetails);?>
		    </td>
			
            <td><?php echo $item['orderdate'];?></td>
            <td><a target="_blank" style="text-decoration: underline;color: blue;" href="<?php echo $customerMealDetails['mobile'];?>" ><?php echo $item['mobile'];?></a></td>
            <td><?php echo $customerMealDetails['target'];?></td>
            <td class="totalsum">
				<div  id="resultRow_<?php echo $item['id'];?>">
                <b  style="text-align:center; width:100%; float:left;">Total Calories:</b> <label id="<?php echo $item['id'];?>_overallCalories"  class="commonboxone"><?php echo (int)$healOrder->getTotalCalories();?></label><span style="margin:3px;"></span>
                Protein : <label id="<?php echo $item['id'];?>_overallProteinPercent" class="commonbox"><?php echo (int)$healOrder->getProteinpercent();?></label> %<span style="margin:3px;"></span>
                Fat : <label id="<?php echo $item['id'];?>_overallFatPercent"  class="commonbox"><?php echo (int)$healOrder->getFatpercent();?></label> %<span style="margin:3px;"></span>
                Carbs : <label id="<?php echo $item['id'];?>_overallCarbohideratePercent"  class="commonbox"><?php echo (int)$healOrder->getCarbohydratespercent();?></label> %<span style="margin:3px;"></span>
                 Fiber : <label id="<?php echo $item['id'];?>_overallFiber"  class="commonbox"><?php echo (int)$healOrder->getTotalFiber();?></label>
                
				Protein (Gm) : <label id="<?php echo $item['id'];?>_overallProteinGram" class="commonbox"><?php echo (int)$healOrder->getTotalProtein();?></label> <span style="margin:3px;"></span>
				Fat (Gm): <label id="<?php echo $item['id'];?>_overallFatGram" class="commonbox"><?php echo (int)$healOrder->getTotalFat();?></label> <span style="margin:3px;"></span>
				Carbs(Gm) : <label id="<?php echo $item['id'];?>_overallCarbsGram" class="commonbox"><?php echo (int)$healOrder->getTotalCarbohydrates();?></label> <span style="margin:3px;"></span>
				<input type="hidden" name="<?php echo $item['id'];?>_isAllowedMeal" id="<?php echo $item['id'];?>_isAllowedMeal" value="<?php echo $customerMealDetails['allowMealDelivery'];?>"/>
			        <input type="hidden" name="<?php echo $item['id'];?>_level" id="<?php echo $item['id'];?>_level" value="<?php echo $customerMealDetails['carbsCaloryInfo'];?>"/>
            </td>
            <td>
                <?php if($item['special_instructions']!='') { ?>
				<span class="tooltip">	<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill:#25B7D3;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
	c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
	<path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
		c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
		c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
		c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
		c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
		c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
		c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
		c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
	<path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
		c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
		c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>

</svg> Instruction 
				
  <span class="tooltiptext"><?php echo $item['special_instructions'];?></span>
</span>
                <?php } ?>				
			
                        <?php if($customerMealDetails['allergyDislike']['allergies']!='') { ?>
			<span class="tooltip">	<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill:#25B7D3;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
	c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
	<path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
		c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
		c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
		c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
		c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
		c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
		c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
		c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
	<path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
		c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
		c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>

</svg> Allergies 
				
  <span class="tooltiptext"><?php echo $customerMealDetails['allergyDislike']['allergies'];?></span>
</span>
                        <?php } ?>  
                
                
                <?php if($customerMealDetails['allergyDislike']['dislike']!=''){?>
                
		<span class="tooltip">	<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill:#25B7D3;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
	c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
	<path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
		c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
		c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
		c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
		c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
		c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
		c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
		c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
	<path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
		c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
		c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>

</svg> Dislikes 
				
  <span class="tooltiptext"><?php echo $customerMealDetails['allergyDislike']['dislike'];?></span>
</span>
                <?php } ?>
			</td>
            
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    <?php } ?>    
    </tbody>
</table> 
<script>
function myFunctionweight() {
  var x = document.getElementById("myDIVweight");
   if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
