  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 <link href="css/singlePageTemplate.css" rel="stylesheet" type="text/css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
	<style>
		#hero{position: relative;
float: none;
width: 1000px;
margin: auto;}
* {box-sizing: border-box}
		.pritnbtn{text-align: right;margin-top: -30px !important;}
		.headerprint{width: 50%;
    float: none;
    margin: auto;}
	.hero_header{    text-align: center;
    width: 100%;max-width:100%;
    float: none;
    margin-bottom: 10px !important;}	
	.mealtable{}
		.meallable h4{margin-bottom:0px; font-size: 11px;line-height: 1.2;}
		.meallable{ width: 6.27cm;
    height: auto;
    font-size: 10px;
    float: left;
    margin: 4px 0px 0px 0px;
    display: block;
    border: 0px solid #000;
    padding: 14px;
    text-align: center;

    }
		.meallable p{float: left;
    text-align: center;
    width: 100%;
    margin: 0;
	line-height: 1.2;
    display: inline-block;
    white-space: unset;
    }
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}

.hasDatepicker{width: 78% !important;
max-width: 100%;
background: #f6fcfc;
height: 35px;
box-shadow: 0px 0px 2px rgba(0,0,0,0.3);
border: 0px;
float: left;
margin:10px;
margin-right: 15px;
}
		span{width: 100%;clear: both;    float: left;}


@media all {
	 .breaking{ display: none;page-break-inside: avoid; page-break-before: always; page-break-after: always;}
}

@media print 
{
    @page {
      size: A4; /* DIN A4 standard, Europe */ 
		 padding:0px;
		margin-top:-10px;
		margin-right:-19px;
		margin-left:-10px;
		margin-bottom:-10px;
    }
    body {
        width: 210mm;
       margin:0px;
		padding:0px;
        font-size: 11px;
        background: #FFF;
		display: table;
       table-layout: fixed;      
       height: 297mm;
    }
   
    .breaking {  display: block; page-break-after: always;page-break-inside: avoid; page-break-before: always;}
    .noprint {display:none;}
}
		

	table{border-collapse: separate;
   }
	.table td, .table th {
    padding: .75rem;
    vertical-align: inherit;
    border-top: 1px solid #dee2e6;
}
	th{font-style: normal;
text-align: left;
display: table-cell;
vertical-align: inherit;
font-weight: bold;}
	td{text-align: left;
display: table-cell;
vertical-align: inherit;
font-weight: 200;
font-style: normal;}
	</style>
	<?php  
	$orderdate='';
 if(isset($_POST))
 {
	 $orderdate   = $_POST['datepicker'];
 }
	 ?>
<div class="noprint">
 <div class="container"> 
<form method="POST" action="<?php echo Mage::getBaseUrl();?>heal/index/meallabel" style="margin-bottom: 20px;">
<div class="loader" style="display: none;"></div>
<table width="800" style="border:0px; margin: auto;width: 100%;" border="1" align="center" style="padding-left: 20px;padding-top:10px;margin: 25px;margin-right: 50px" class="noprint">
  <tbody>
    <tr >
     
     <td style="margin:3px"> <p style="margin-bottom: 0px;float: left;width: 100%;padding: 5px;">
      <span style="width:auto;float: left;height: 35px;line-height: 35px;margin:10px auto;">Order Date:</span>
      <input type="text" id="datepicker" name="datepicker" value="<?php echo $orderdate;?>">
      <input type="submit" name="submit" value="Get Meal Details"  style="margin: 10px auto;padding: 0px 10px;background: #c31f41;border: 1px solid #a61d3f;color: #fff;font-size: 14px;height: 35px;width:auto;line-height: 35px;float: left;"> </button></p></td>
	  
    </tr>
   
   
   
  </tbody>
</table>
</form>
         </div> 
</div>
<?php 
 if(isset($_POST['submit']))
 {
	 $orderdate   = $_POST['datepicker'];
     $dateInfo    = explode("/",$orderdate);
       
       $tmpOrderdateToShow = $dateInfo[2]."-".$dateInfo[0]."-".$dateInfo[1];
       $month = date("M",strtotime($tmpOrderdateToShow));
       $orderdateToShow = $dateInfo[1]."-".$month."-".$dateInfo[2];
	 ?>
   
  <section  id="hero">
  
	
   
	 <?php
	   
       
       
       $dbRead      = Mage::getSingleton('core/resource')->getConnection('core_read');
       
       $QueryGetItems = "select distinct(hid.productid) as itemid from healitemdetails hid join healorder ho on hid.orderid=ho.id and  ho.orderdate= '$orderdate'";
       $itemResult = $dbRead->fetchAll($QueryGetItems);
       
       
       $selectDatewiseOrders= "select * from healorder where status =0 and orderdate='$orderdate'";
       $cuisineResult = $dbRead->fetchAll($selectDatewiseOrders);
       
       $orderResult = '';
       $result = '';
       
       if(count($itemResult)>0)
       {
		  
		   
           $mealItemCount=0;
           $finalProductName ='';

           $countItemRecords=0;
           $finalOutputArray = array();
           foreach($itemResult as $itemInfo)
          {             
                $mealItemInfo = array();
                $mealItemQtyArray = array();
		$finalQty =0;
		++$countItemRecords;
                
            if(count($cuisineResult)>0)
            {
            $mealItemInfo['itemId']=$itemInfo['itemid'];
			
			 $itemid = $itemInfo['itemid'];
                         $mealItemsInfo = array();
               	         $cuisineItemsDesc = array();
            
			
               foreach($cuisineResult as $row)
              {
               
               
               $orderId               =     $row['id'];
               $dinner_items_desc     = 	$row['dinner_items_desc'];    $cuisineItemsDesc['dinner'] = $dinner_items_desc;
               $breakfast_items_desc  = 	$row['breakfast_items_desc']; $cuisineItemsDesc['breakfast'] = $breakfast_items_desc;
               $lunch_items_desc      = 	$row['lunch_items_desc'];     $cuisineItemsDesc['lunch'] = $lunch_items_desc;
               $hightea_items_desc    = 	$row['hightea_items_desc'];	  $cuisineItemsDesc['hightea'] = $hightea_items_desc;
               
               $customerEmail = $row['email'];
               
               $customer='';
               $customer = Mage::getModel("customer/customer");
               $customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
               $customer->loadByEmail($customerEmail);
               $customerName = 	$customer->getFirstname();
               
               foreach($cuisineItemsDesc as $cuisine=>$itemDesc)
               {
				 $orderItemsArray = array();
				 $cuisineDescItems = explode(",",$itemDesc);
				  
				 if(count($cuisineDescItems)>0)
				 {	 
				   foreach($cuisineDescItems as $singleItem)
					{
					  $singleItemInfo = explode("_",$singleItem);
					
					  if($singleItemInfo[1]==$itemid)
					  {       
						   
					    $productid = $singleItemInfo[1]; 

					    $QgetOrderItemsDetails = "select * from  healitemdetails where orderid='$orderId' and cuisine='$cuisine' and productid='$productid'" ;
					
					    $orderItems = $dbRead->fetchAll($QgetOrderItemsDetails) ;
					    if(count($orderItems) >0)
					    {
                                                  $countQtyOfCuisineItem =0; 
						  foreach($orderItems as $orderdetailitem)
						  {
							  
							  $itemId   =  trim($orderdetailitem['productid']);
							  $qty      =  trim($orderdetailitem['qty']);
							  $mealItemInfo['itemName'] =  trim($orderdetailitem['itemname']);
							
							  $productIdValue = array();
							  
							     
								  
									if(!array_key_exists($qty,$mealItemQtyArray) ) 
									{
									   
									   $mealItemQtyArray[$qty] = 1;
									   $finalQty+=$qty;
									}
									else 
									{  
										if(array_key_exists($qty,$mealItemQtyArray) )
										{  
									
									
											$alreadyCountedQty                     = $mealItemQtyArray[$qty];

										    $newQtyCount                           = $alreadyCountedQty + 1;
										    $mealItemQtyArray[$qty]  = $newQtyCount;
											$finalQty+=$qty;
									    }
										else
										{
										  $mealItemQtyArray[$qty] = 1;
										  $finalQty+=$qty;
										}
										

									}
							
							  
							 

						  }
						  

					    }
					 
					}
				}
			}
				
			 
               }
               
           }
         }  
		   $mealItemInfo['mealDate'] = $orderdateToShow;
		   $mealItemInfo['finalQty'] = $finalQty;
		   $mealItemInfo['mealItemQtyArray'] = $mealItemQtyArray;
                          
                        
                   ksort($mealItemInfo['mealItemQtyArray']);
			
                   $finalOutputArray[] = $mealItemInfo;
            
       }
       
  //  echo "<pre>"; print_r($finalOutputArray); //die;
       
       ?>
          
             <div class="mealtable container"> 
               <div class="headerprint">
   <h2 class="hero_header noprint">Meal Details Of <?php echo $orderdateToShow;?> <div class="noprint pritnbtn"><input type="button" onclick="javascript:print()" style="margin: 10px auto;padding: 0px 10px;background: #c31f41;border: 1px solid #a61d3f;color: #fff;font-size: 14px;height: 35px;width:auto;line-height: 35px;float: none;margin:auto;" value="Print" /></div></h2>

                  
		   </div>
          
                 <?php $countLabel =0;
                    foreach( $finalOutputArray as $mealinformationArray)
                    {
                        foreach($mealinformationArray['mealItemQtyArray'] as $gram=>$quantityofgram )
                        {
                            if($gram>0)
                            {   
                                $extraLabels =2;
                                for($i=0;$i< ($quantityofgram+$extraLabels);$i++)
                                { ++$countLabel; if($i<$quantityofgram) {?>
			  
                                   <div class="meallable" >
                                                <span  style="font-weight: bold;height:35px;">  <?php echo $mealinformationArray['itemName'];?></span> 
                                                 <span>  <?php echo $gram.' gm';?></span>
                                                 <span>  <?php echo $mealinformationArray['mealDate'];?></span>

                                  </div>
                                <?php } else { ?> 
                 
                                       <div class="meallable" >
                                                <span style="font-weight: bold;height:35px;">  <?php echo $mealinformationArray['itemName'];?></span>
                                                 <span>&nbsp;  </span>
                                                 <span>  <?php echo $mealinformationArray['mealDate'];?></span>

                                      </div>
				 					 <?php } if($countLabel%56==0){ ?>
                                    <div class="breaking"></div>
                                   
                                    <?php }?>
                           
                                <?php }
                                
                            }
                            
                           
                        }
                    }
              ?>
               
	 	
		</div>
              
     <?php  } ?>
              
</section>
	 
 <?php } ?>


