<script src="<?php echo $this->getSkinUrl();?>js/jspdf.min.js"></script>
<script src="<?php echo $this->getSkinUrl();?>js/html2canvas.js"></script>
<style>
.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin:2px;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #a61d3f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
section, .footer-container, .breadcrumbs{display:none;}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  max-width:560px;
  font-size: 12px;
  margin:auto;
}
input[type=text] {
font-size: 15px;
color: #a61d3f;	
}
textarea{ font-size: 15px; }
h2{font-weight: normal;margin: auto;
width: 560px;font-size:17px;
height: 30px;color: #000;
line-height: 30px;}
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 4px;
}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}

.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}
@media print
{
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
	 div.print-content article.node .node-blog .clearfix div.item-body p a {
    display: none;}
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 11px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }

.header-logo-top{
    padding: 4px;
    width: 100%;
    border-bottom: 1px solid rgba(0,0,0,0.2);
    margin-bottom: 9px;
  }
}

</style>

<?php 
$params = $this->getRequest()->getParams(); 
$orderId =  $params['id']; 
$print =  $params['print'];
$orderInfo =  Mage::getModel("heal/order")->load($orderId);
$specialInstructions ='';
$customerEmail = $orderInfo->getEmail();

$BigGlass=0;
$MediumGlass=0;
$SmallGlass=0;
$MinGlass=0;
$SteelBox = 0;
$PlasticSalad = 0;
$PlasticChutney = 0;
$PlasticVegetable = 0;

$PlasticBox = 0;
$StainlessSteelBox = 0;
$GlassBottle = 0;


       
$customer = Mage::getModel("customer/customer"); 
$customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
$customer->loadByEmail($customerEmail);
$customerBillingAddressId  = $customer->getDefaultBilling();
$customerShippingAddressId  = $customer->getDefaultShipping();
if(is_object($orderInfo )) {
	$totalOrderCalory=0;
	$specialInstructions = 	trim($orderInfo->getSpecialInstructions()); 
 $orderDate = $orderInfo->getOrderdate(); 
$formattedDate = date("d M Y",strtotime($orderDate)); 
$breakfastCollection = $orderInfo->getCusineDetails($orderId,$cusine='breakfast');
$lunchCollection = $orderInfo->getCusineDetails($orderId,$cusine='lunch');
$dinnerCollection = $orderInfo->getCusineDetails($orderId,$cusine='dinner');
$highteaCollection = $orderInfo->getCusineDetails($orderId,$cusine='hightea ');
$AllergiesDislike = Mage::helper("heal")->getAllergiesDislike($customer->getId());
$customerName = str_replace("Dear ","",$orderInfo->getName());
?> 

<div class="loader" style="display: none;"></div>
<div id="pdfContent" style="background-color: white;">
<table style="max-width: 660px;">
<tr> 
	<th colspan="3"> 
		<div class="header-logo">
			<div class="header-logo-top">
				<img src="<?php echo $this->getSkinUrl('images/lifeheal-healthcraft-logo.jpg') ?>" alt="cure my diabetes" />
			</div>
      <div class="header-logo-bottom">
        <div class="header-address1">
          <span><?php echo $customerName;?></span> 
          <span> <?php echo "Mob: ".$customer->getPrimarymobileno() ?></span>
          <span><?php echo $formattedDate;?></span>
        </div>
        <div class="header-address2">
          <?php               
            if ($customerBillingAddressId){
              $billing_address = Mage::getModel('customer/address')->load($customerBillingAddressId); 
              
            $tmpName = $billing_address->getFirstname()." ". $billing_address->getLastname();
            $name = str_replace("Dear ","",$tmpName);
              
            $homeaddress = explode("-", $billing_address->getStreet1());
              
            echo $addressTop ="Home: ".$homeaddress[0].", ".$billing_address->getCity();
             
            if($billing_address->getStreet2()!='') {
              $officeaddress = explode("-", $billing_address->getStreet2());
              echo "<br/>"."Office: ".$officeaddress[0];
            }  
             
            if($customer->getPrimarymobileno() != $billing_address->getTelephone()){
              echo $billing_address->getTelephone();}
           }  

          ?> 
        </div>
      </div>

		</div> 
	</th>
</tr>
</table>

<table style="max-width: 660px;"> 
  <tr>
    <th class="longcol">
      <span style="font-size: 16px; font-style: italic; padding-left: 3px;">
      Allergies &amp; Dislikes:</span>
      <input type="text" id="allergies" placeholder="Allergies" value="<?php echo $AllergiesDislike['allergies'] ?>" />
      <input type="text" id="unlikes" placeholder="Dislikes"  value="<?php echo $AllergiesDislike['dislikename'] ?>" />
    </th>
   <th style="text-align: center;border: 1px solid rgba(0,0,0,0.2);">Grams</th>
    <th style="text-align: center;border: 1px solid rgba(0,0,0,0.2);">Calories</th>
  </tr>
	

  
  <?php if(count($breakfastCollection)>0) {   ?>
  <tr>
    <th colspan="3" style="font-size:16px; font-weight: bold;text-align: center;">
    Breakfast</th>
    
  </tr>
	<?php
		   foreach($breakfastCollection as $iteminfo) { /*$isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */
		if($iteminfo['calories']>0)
		{
		    $totalOrderCalory+=$iteminfo['calories'];
		}
		   	?>
			  <tr>
				<td class="longcol"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
			  <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td> */ ?>
        </tr>
	<?php   } } ?>
  <?php if(count($lunchCollection)>0) { ?>
  <tr>
    <th colspan="3" style="color: #000; font-size:16px; font-weight: bold;text-align: center;">Lunch</th>    
  </tr>
<?php
		   foreach($lunchCollection as $iteminfo) { /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */
		if($iteminfo['calories']>0)
		{
		    $totalOrderCalory+=$iteminfo['calories'];
		}
		   	?>
			  <tr>
				<td class="longcol"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
			  <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td> */ ?>
        </tr>
	<?php   }  } ?>
  <?php if(count($highteaCollection)>0) { ?>
  <tr>
    <th colspan="3" style="color: #000; font-size:16px; font-weight: bold;text-align: center;">HiTea</th>   
  </tr>
  <?php
		   foreach($highteaCollection as $iteminfo) { /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */ 
		if($iteminfo['calories']>0)
		{
		    $totalOrderCalory+=$iteminfo['calories'];
		}
		?>
			  <tr>
				<td  class="longcol"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>			  
        </tr>
	<?php   }  }?>
	
	<?php if(count($dinnerCollection)>0) { ?>
  <tr>
    <th colspan="3" style="color: #000; font-size:16px; font-weight: bold;text-align: center;">Dinner</th>           
  </tr>
 <?php
       foreach($dinnerCollection as $iteminfo) {  /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */
		if($iteminfo['calories']>0)
		{
		    $totalOrderCalory+=$iteminfo['calories'];
		}
		
		?>
        <tr>
        <td class="longcol"><?php echo $iteminfo['itemname'];?></td>
        <td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
        <td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>        
        </tr>
  <?php   } } ?>
  </table>
  <table style="max-width: 660px;">  
  <tr>
<td class="longcol" style="text-align:right;background:#fff; color: #000;font-weight: bold; border: 1px solid rgba(0,0,0,0.2); border-right:0; font-size: 20px;  padding-right: 8px;"><b>Total Calories</b>:<?php echo (int)$totalOrderCalory;?></td> 
    <td style="text-align:center;border-bottom: 0px !important;border: 1px solid rgba(0,0,0,0.2);"><?php echo (int)$orderInfo->getTotalFiber();?> gms</td>
     <td style="text-align:center;border-bottom: 0px !important; border: 1px solid rgba(0,0,0,0.2);"><?php echo (int)$orderInfo->getProteinpercent();?> %</td>
      <td style="text-align:center;border-bottom: 0px !important; border: 1px solid rgba(0,0,0,0.2);"><?php echo (int)$orderInfo->getCarbohydratespercent();?> %</td>
       <td style="text-align:center;border-bottom: 0px !important; border: 1px solid rgba(0,0,0,0.2);"> <?php echo (int)$orderInfo->getFatpercent();?>%</td>
       <!-- <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"> Total Packing</td> -->
  </tr>
  
   <tr>
<th class="longcol" style="text-align:left; color: #fff;font-weight: bold; border: 1px solid rgba(0,0,0,0.2);border-right: 0;">
	<div  class="footer-table-logo">	
		<img src="<?php echo  Mage::getBaseUrl() ?>skin/frontend/rwd/default/images/lifeheal-healthcraft-logo.jpg" />
	</div>	
</th>
<!--    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;">Grams</th>
-->	  <th style="text-align: center;border: 1px solid rgba(0,0,0,0.2); border-top: 0px;">Fiber</th>
    <th style="text-align: center; border: 1px solid rgba(0,0,0,0.2); border-top: 0px;">Protein</th>
    <th style="text-align: center; border: 1px solid rgba(0,0,0,0.2); border-top: 0px;">Carbs</th>
    <th style="text-align: center; border: 1px solid rgba(0,0,0,0.2); border-top: 0px;">Fat</th>
  
  </tr>
</table>
<table border="0" style="max-width: 660px;">
<tr><td><textarea rows="2" cols="100" id="spi" name="spi" ><?php echo $specialInstructions;?></textarea></td></tr>
</table>
</div>
<!--</page>-->
<div class="noprint" data-html2canvas-ignore="true" style="max-width:660px;text-align: center;margin: auto;width: 660px;">
<button onclick="addAllergiesDislike(<?php echo $orderId;?>)"  class="btn btn-danger btn-default pull-left" >Save Changes</button>
<button onclick="printPage();"  class="btn btn-danger btn-default pull-left">Print</button>
<button onclick="goBack()"  class="btn btn-danger btn-default pull-left" data-dismiss="modal">Close and Cancel Printing</button>

<!-- <button class="btn btn-danger btn-default pull-left"  id='print-btn'>Download PDF</button> -->
</div>
<?php } else { echo "No order exist";}?>
<script type="text/javascript">
function addAllergiesDislike(orderid){  
  var Allergies = jQuery("#allergies").val(); 
  var Dislikes = jQuery("#unlikes").val();
  var Notes = jQuery("#notes").val();
  if(Allergies || Dislikes){
  jQuery(".loader").css("display", "block"); 
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/addAllergiesDislike' ?>",
    type: "POST",
    data: {
      customerid: "<?php echo $customer->getId() ?>", 
      customername:"<?php echo $customer->getName() ?>",
      customermobile:"<?php echo $customer->getPrimarymobileno() ?>",
      allergies: Allergies, 
      dislikename:Dislikes
    }, 
    success: function(response) {
      jQuery(".loader").css("display", "none"); 
    }
  }); 
  }
  
  setinstructionAndPrint(orderid);
}

function setinstructionAndPrint(orderid) {
	
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/setspecialinstructions' ?>",
    type: "POST",
    data: {
      orderid: orderid, 
      spi:jQuery("#spi").val()
      
    }, 
    success: function(response) {
     
    }
  }); 
}

function printPage()
{
	 window.print(); 
}

function goBack() {
  window.close();
}

<?php if($params['print']){ ?>

//jQuery('#print-btn').click(()=>{
var pdfilenames = "<?php echo $orderInfo->getName()."_".$formattedDate; ?>";
var pdf = new jsPDF('p','pt','a4');

var options = {
  //Pagesize:2,
  //'background': 'white',
  //totalPdfHeight:5000
  //pages:2
  //pagesplit: true //include this in your code
}; 
pdf.addHTML(jQuery("#pdfContent"),options, function() {
    pdf.save(pdfilenames);
    goBack();
});
//})
<?php } ?>

/*jQuery('#print-btn').click(()=>{
var pdfilenames = "<?php //echo $orderInfo->getName()."_".$formattedDate; ?>";
var pdf = new jsPDF('p','pt','a4');

var options = {
  Pagesize:2;
  //pagesplit: true //include this in your code
}; 
pdf.addHTML(document.body,options, function() {
    pdf.save(pdfilenames);
});
})*/

</script>


<style type="text/css">
  .header-logo{width:100%;}
  .header-logo-top{
    padding: 4px;
    width: 100%;
    box-shadow: 0 2px 1px 0 rgba(0,0,0,0.1);
    margin-bottom: 9px;
  }
  .header-logo-bottom{
    padding: 0 6px;
  }
  .header-address1{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin-bottom: 6px;
  }
  .header-address1 span{
    font-size: 17px;
    font-weight: 600;

  }
  .header-address2 {
    text-align: center;
    font-size: 15px;
    margin-bottom: 8px;
    font-weight: 500;
}
 
input[type="text"] {
    max-width: 100%;
    background: #fff;
    height: 35px;    
    border: 1px solid rgba(0,0,0,0.2);
    margin: 10px 0;
    width: 97%;
    outline: none;
} 
.longcol{
  width:55%;
  box-sizing: border-box;
  padding-left: 9px;
}
</style>