<script src="<?php echo $this->getSkinUrl();?>js/jspdf.min.js"></script>
<script src="<?php echo $this->getSkinUrl();?>js/html2canvas.js"></script>
<style>
.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin:2px;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #a61d3f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
section, .footer-container, .breadcrumbs{display:none;}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  max-width:560px;
  font-size: 12px;
  margin:auto;
}
input[type=text] {
font-size: 15px;
color: #a61d3f;	
}
textarea{ font-size: 15px; }
h2{font-weight: normal;margin: auto;
width: 560px;font-size:17px;
height: 30px;color: #000;
line-height: 30px;}
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 4px;
}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}

.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}
@media print
{
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
	 div.print-content article.node .node-blog .clearfix div.item-body p a {
    display: none;}
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 11px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
}

</style>

<?php 
$params = $this->getRequest()->getParams(); 
$orderId =  $params['id']; 
$print =  $params['print'];
$orderInfo =  Mage::getModel("heal/order")->load($orderId);
$specialInstructions ='';
$customerEmail = $orderInfo->getEmail();

$BigGlass=0;
$MediumGlass=0;
$SmallGlass=0;
$MinGlass=0;
$SteelBox = 0;
$PlasticSalad = 0;
$PlasticChutney = 0;
$PlasticVegetable = 0;

$PlasticBox = 0;
$StainlessSteelBox = 0;
$GlassBottle = 0;


       
$customer = Mage::getModel("customer/customer"); 
$customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
$customer->loadByEmail($customerEmail);
$customerBillingAddressId  = $customer->getDefaultBilling();
$customerShippingAddressId  = $customer->getDefaultShipping();
if(is_object($orderInfo )) {
	$specialInstructions = 	trim($orderInfo->getSpecialInstructions()); 
 $orderDate = $orderInfo->getOrderdate(); 
$formattedDate = date("d M Y",strtotime($orderDate)); 
$breakfastCollection = $orderInfo->getCusineDetails($orderId,$cusine='breakfast');
$lunchCollection = $orderInfo->getCusineDetails($orderId,$cusine='lunch');
$dinnerCollection = $orderInfo->getCusineDetails($orderId,$cusine='dinner');
$highteaCollection = $orderInfo->getCusineDetails($orderId,$cusine='hightea ');
$AllergiesDislike = Mage::helper("heal")->getAllergiesDislike($customer->getId());
$customerName = str_replace("Dear ","",$orderInfo->getName());
?> 

<div class="loader" style="display: none;"></div>
<div id="pdfContent" style="background-color: white;">
<table style="max-width: 660px;">
<tr style="border-bottom: 3px solid #000;"> <th colspan="3" style="padding-bottom: 20px;border:none;"> <img style="width: 250px;" src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="cure my diabetes" /> </th></tr>
</table>
<h2 style="font-weight: normal;max-width: 660px;"><b><?php echo $customerName;?></b> Your Food Diary for <b><?php echo $formattedDate;?></b></h2>
<h2 style="font-weight: normal;max-width: 660px;"><b>Order Id: <?php echo $orderId ?></b></h2>
<table style="max-width: 660px;"> 
  <tr>
    <th style="color: #000;font-weight: bold;border-right: 0px;width:40%"><span style="line-height: 20px;height: 30px;width: 100%;float: left;">Allergies &amp; Dislikes:</span><input type="text" id="allergies" placeholder="Allergies" value="<?php echo $AllergiesDislike['allergies'] ?>" /><input type="text" id="unlikes" placeholder="Dislikes"  value="<?php echo $AllergiesDislike['dislikename'] ?>" /></th>
    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;">Grams</th>
    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;">Calories</th>
    <!-- <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;">Packing</th> -->
  </tr>
	
	<tr>
    <th colspan="3" style="width:40%"><?php 
		  if ($customerBillingAddressId){
        $billing_address = Mage::getModel('customer/address')->load($customerBillingAddressId); 
		$tmpName = $billing_address->getFirstname()." ". $billing_address->getLastname();
		$name = str_replace("Dear ","",$tmpName);
			  
		echo $name; echo "</br>";
        echo $billing_address->getStreet1();echo "</br>"; 
		if($billing_address->getStreet2()!='')
		{
		  echo $billing_address->getStreet2();echo "</br>";
		}
      // echo $billing_address->getRegion(); echo "</br>";
	   echo $billing_address->getCity();  echo "</br>";
        echo $customer->getPrimarymobileno();echo "</br>";
        if($customer->getPrimarymobileno() != $billing_address->getTelephone()){
        echo $billing_address->getTelephone();}
    }?></th>
  </tr>
  
  <?php if(count($breakfastCollection)>0) {   ?>
  <tr>
    <th style="color: #000;font-weight: bold;width:40%">Breakfast</th>
    <th></th>
     <th></th>
     <!-- <th></th> -->
  </tr>
	<?php
		   foreach($breakfastCollection as $iteminfo) { /*$isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */
		   	?>
			  <tr>
				<td style="width:40%"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
			  <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td> */ ?>
        </tr>
	<?php   } } ?>
  <?php if(count($lunchCollection)>0) { ?>
  <tr>
    <th style="color: #000;font-weight: bold;width:40%">Lunch</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
  </tr>
<?php
		   foreach($lunchCollection as $iteminfo) { /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */
		   	?>
			  <tr>
				<td style="width:40%"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
			  <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td> */ ?>
        </tr>
	<?php   }  } ?>
  <?php if(count($highteaCollection)>0) { ?>
  <tr>
    <th style="color: #000;font-weight: bold;width:40%">HiTea</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
  </tr>
  <?php
		   foreach($highteaCollection as $iteminfo) { /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */ ?>
			  <tr>
				<td style="width:40%"><?php echo $iteminfo['itemname'];?></td>
				<td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
				<td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
			  <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td> */ ?>
        </tr>
	<?php   }  }?>
	
	<?php if(count($dinnerCollection)>0) { ?>
  <tr>
    <th style="color: #000;font-weight: bold;width:40%">Dinner</th>
    <th></th>
    <th></th>   
    <!-- <th></th> -->        
  </tr>
 <?php
       foreach($dinnerCollection as $iteminfo) {  /* $isType = '';
        $product = Mage::getModel('catalog/product')->load($iteminfo['productid']);
        if(strtolower(trim($product->getPackingtype())) == 'stainless steel box'){
          $StainlessSteelBox++;$isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'plastic box'){
          $PlasticBox++; $isType = trim($product->getPackingtype());
        }else if(strtolower(trim($product->getPackingtype())) == 'glass bottle'){
          $GlassBottle++; $isType = trim($product->getPackingtype());
        } */?>
        <tr>
        <td style="width:40%"><?php echo $iteminfo['itemname'];?></td>
        <td style="text-align:center;"><?php echo $iteminfo['qty'];?></td>
        <td style="text-align:center;"><?php echo (int)$iteminfo['calories'];?></td>
        <?php /* <td style="color: #777;"> <?php echo $isType; ?> </td>*/?>
        </tr>
  <?php   } } ?>
  </table>
  <table style="max-width: 660px;">  
  <tr>
<td style="text-align:right;background:#fff; color: #000;font-weight: bold;border: 1px solid #ddd;border-right:0px solid #ddd;font-size: 20px;"><b>Total Calories</b>:<?php echo (int)$orderInfo->getTotalCalories();?></td> 
<!--	<td style="text-align:center;"><?php //echo $orderInfo->getTotalGram();?></td>
-->    <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"><?php echo (int)$orderInfo->getTotalFiber();?> gms</td>
     <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"><?php echo (int)$orderInfo->getProteinpercent();?> %</td>
      <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"><?php echo (int)$orderInfo->getCarbohydratespercent();?> %</td>
       <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"> <?php echo (int)$orderInfo->getFatpercent();?>%</td>
       <!-- <td style="text-align:center;border-bottom: 0px !important;border:1px solid #000;"> Total Packing</td> -->
  </tr>
  
   <tr>
<th style="text-align:left;background:#fff;color: #fff;font-weight: bold;border: 1px solid #ddd;border-right: 0px solid #ddd;"><img src="<?php echo  Mage::getBaseUrl() ?>skin/frontend/rwd/default/images/logo.png" style="width: 100px;float: none;margin: auto;"></th>
<!--    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;">Grams</th>
-->	  <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;border-top: 0px;">Fiber</th>
    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;border-top: 0px;">Protein</th>
    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;border-top: 0px;">Carbs</th>
    <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;border-top: 0px;">Fat</th>
    <?php /* <th style="background-color: #fff;color: #000;text-align: center;border:1px solid #000;border-top: 0px;"> <?php echo $PlasticBox. " Plastic Box"; 
echo ", ".$StainlessSteelBox." Stainless Steel Box"; echo ", ".$GlassBottle." Glass Bottle "; ?> </th>*/ ?>
  </tr>
</table>
<table border="0" style="max-width: 660px;">
<tr><td><textarea rows="2" cols="100" id="spi" name="spi" ><?php echo $specialInstructions;?></textarea></td></tr>
</table>
</div>
<!--</page>-->
<div class="noprint" data-html2canvas-ignore="true" style="max-width:660px;text-align: center;margin: auto;width: 660px;">
<button onclick="setinstructionAndPrint(<?php echo $orderId;?>)" class="btn btn-danger btn-default pull-left">Print this Page</button>
<button onclick="goBack()"  class="btn btn-danger btn-default pull-left" data-dismiss="modal">Close and Cancel Printing</button>
<button onclick="addAllergiesDislike()"  class="btn btn-danger btn-default pull-left" >Save Allergies & Dislikes</button>
<!-- <button class="btn btn-danger btn-default pull-left"  id='print-btn'>Download PDF</button> -->
</div>
<?php } else { echo "No order exist";}?>
<script type="text/javascript">
function addAllergiesDislike(){  
  var Allergies = jQuery("#allergies").val(); 
  var Dislikes = jQuery("#unlikes").val();
  if(Allergies || Dislikes){
  jQuery(".loader").css("display", "block"); 
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/addAllergiesDislike' ?>",
    type: "POST",
    data: {
      customerid: "<?php echo $customer->getId() ?>", 
      customername:"<?php echo $customer->getName() ?>",
      customermobile:"<?php echo $customer->getPrimarymobileno() ?>",
      allergies: Allergies, 
      dislikename:Dislikes
    }, 
    success: function(response) {
      jQuery(".loader").css("display", "none"); 
    }
  }); 
  }
}

function setinstructionAndPrint(orderid) {
	
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/setspecialinstructions' ?>",
    type: "POST",
    data: {
      orderid: orderid, 
      spi:jQuery("#spi").val()
      
    }, 
    success: function(response) {
     
    }
  }); 
 window.print();  
  
}

function goBack() {
  window.close();
}

<?php if($params['print']){ ?>

//jQuery('#print-btn').click(()=>{
var pdfilenames = "<?php echo $orderInfo->getName()."_".$formattedDate; ?>";
var pdf = new jsPDF('p','pt','a4');

var options = {
  //Pagesize:2,
  //'background': 'white',
  //totalPdfHeight:5000
  //pages:2
  //pagesplit: true //include this in your code
}; 
pdf.addHTML(jQuery("#pdfContent"),options, function() {
    pdf.save(pdfilenames);
    goBack();
});
//})
<?php } ?>

/*jQuery('#print-btn').click(()=>{
var pdfilenames = "<?php //echo $orderInfo->getName()."_".$formattedDate; ?>";
var pdf = new jsPDF('p','pt','a4');

var options = {
  Pagesize:2;
  //pagesplit: true //include this in your code
}; 
pdf.addHTML(document.body,options, function() {
    pdf.save(pdfilenames);
});
})*/

</script>