<script src="<?php echo $this->getSkinUrl();?>js/jspdf.min.js"></script>
<script src="<?php echo $this->getSkinUrl();?>js/html2canvas.js"></script>
<?php 
    $params = $this->getRequest()->getParams(); 
	$orderId =  $params['id']; 
	$print =  $params['print'];
	$orderInfo =  Mage::getModel("heal/order")->load($orderId);
	 $orderDate = $orderInfo->getOrderdate(); 
     $formattedDate = date("d M Y",strtotime($orderDate)); 
	$specialInstructions ='';
	$customerId = $orderInfo->getCustomerid();
     
	$customer = Mage::getModel("customer/customer"); 
	$customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
	$customer->load($customerId);
    $customerName = str_replace("Dear ","",$orderInfo->getName());
	 
	   $billStreet1='';
	   $billStreet2='';
	   $billCity='';
	   $billCountryid='';
	   $homeAddress='';
	   $officeAddress='';
	       $customerBillingAddressId  = $customer->getDefaultBilling();
	       
		   
            if($customerBillingAddressId){
			 $billing_address = Mage::getModel('customer/address')->load($customerBillingAddressId); 
              $billfistname = $billing_address->getFirstname();
              $billlastname = $billing_address->getLastname();
              $billStreet1 = $billing_address->getStreet1();
              $billStreet2 = $billing_address->getStreet2();
              $billCompany = $billing_address->getCompany();
              $billCity = $billing_address->getCity();
              $billTelephone = $billing_address->getTelephone();
              $billRegion = $billing_address->getRegion();
              $billCountryid = $billing_address->getCountryId();
              if(strtolower($billCountryid) == "us"){
                $billCountryid = 1;
              }else if(strtolower($billCountryid) == "ca"){
                $billCountryid = 2;
              }else { $billCountryid = 3; }
              $billPostcode = $billing_address->getPostcode();
			  
			   
			   
            }
			

			     $AllergiesDislike = Mage::helper("heal")->getAllergiesDislike($customer->getId());
                 $specialInstructions = 	$AllergiesDislike['notes'];
			
	 ?>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


	<style>
		

@media print
{
	.header-wrapper, .footer-container, .breadcrumbs, .bck-btn{display:none;}
	header, footer{display:none;}
	
.noprint {display:none;}
}

@media print {
	.header-wrapper, .footer-container, .breadcrumbs{display:none;}
	header, footer, .bck-btn{display:none;}
	 div.print-content article.node .node-blog .clearfix div.item-body p a {
    display: none;}
    @page {
      size: A2; /* DIN A4 standard, Europe */
      margin:0;
		font-size:10pt;
    }
    html, body {
       /* width: 210mm;
         height: 297mm;
        height: 282mm; */
        
        background: #FFF;
        overflow:visible;
    }
    
		}
		
		@media print {
   
		 .noprint {display:none;}
}
	  	.panel-info {
    border-color: #bce8f1;
    width: 100%;
    float: left;
}
	  input[type=email], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text] {
    width: 100%;
    max-width: 100%;
    background: #f9fafa;
    height: 36px;
    font-size: 14px;
    border: 0;
    box-shadow: 0px 0px 3px rgb(0 0 0 / 20%);
}
		.panel-info > .panel-heading{color:#0EB58F;font-weight:bold;font-size:24px;}
		.panel-footer{background:#fff;text-align:center;}
		.panel-info h3{text-align:center; color:#0EB58F;font-weight:bold;font-size:1.2rem;}
		.panel-info h4{text-align:center; color:#144F5A;font-weight:bold;font-size:1em;} 
		.table > thead > tr > th {
    vertical-align: bottom;
    border-bottom: 1px solid #0EB58F;font-size:7pt;
		} 
		 h2 {
    font-size: 34px;
    font-weight: bold;
    color: #144F5A;
}
		.table-responsive{width:100%;}.experiencethediff{color:#bce8f1;font-weight:500; font-size:16px;}
		.table{border:0px solid #0EB58F;}th{color:#0EB58F; font-weight:600;}

.modal-footer{margin: auto;padding: 10px 0px;}
    body { font-size: 14px }
	  	.panel-info h3{text-align:center; color:#0EB58F;font-weight:bold;font-size:16px;}
		.panel-info h4{text-align:center; color:#144F5A;font-weight:bold;font-size:14px;}
	 .panel-body label {
    font-size: 11pt;
    display: inline-block;
    max-width: 100%;
    margin-bottom: 5px;
    color: #666;
    font-weight: 700;
}
	  img{width:160px !important;}
	  .col1-layout{margin-top:7rem;}
		html {
    font-size: inherit !important;
}
		.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin:2px;
}
	
.header-logo-top{
    padding: 4px;
    width: 100%;
    border-bottom: 1px solid rgba(0,0,0,0.2);
    margin-bottom: 9px;
  }
	.h4, h4, .panel-info h4 {
    font-size: 16px;
}
	.h3, h3, .panel-info h3 {
    font-size: 20px;
}
	.table-responsive > .table > tbody > tr > td, .table-responsive > .table > tfoot > tr > td, .table-responsive > .table > thead > tr > td{
		font-size: 11pt !important;
     white-space: normal !important;
	}
	.table-responsive > .table > tfoot > tr > th,.table-responsive > .table > tbody > tr > th, .table-responsive > .table > thead > tr > th {
		font-size: 14px !important;
    white-space: normal !important;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #0eb58f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

	body, button, input, select, table, textarea, p {
    color: #666;
    font-family: 'Montserrat', sans-serif !important;
    font-weight: 500;
}  
  }
  @media screen, print {
	  .noprint {display:none;}
}
	  	.panel-info {
    border-color: #bce8f1;
    width: 100%;
    float: left;
}
	  input[type=email], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text] {
    width: 100%;
    max-width: 100%;
    background: #f9fafa;
    height: 36px;
    font-size: 14px;
    border: 0;
    box-shadow: 0px 0px 3px rgb(0 0 0 / 20%);
}
		.panel-info > .panel-heading{color:#0EB58F;font-weight:bold;font-size:24px;}
		.panel-footer{background:#fff;text-align:center;}
		.panel-info h3{text-align:center; color:#0EB58F;font-weight:bold;font-size:1.2rem;}
		.panel-info h4{text-align:center; color:#144F5A;font-weight:bold;font-size:1em;} 
		.table > thead > tr > th {
    vertical-align: bottom;
    border-bottom: 1px solid #0EB58F;font-size:7pt;
		} 
		 h2 {
    font-size: 34px;
    font-weight: bold;
    color: #144F5A;
}
		.table-responsive{width:100%;}.experiencethediff{color:#bce8f1;font-weight:500; font-size:16px;}
		.table{border:0px solid #0EB58F;}th{color:#0EB58F; font-weight:600;}

.modal-footer{margin: auto;padding: 10px 0px;}
    body { font-size: 11pt }
	  	.panel-info h3{text-align:center; color:#0EB58F;font-weight:bold;font-size:16px;}
		.panel-info h4{text-align:center; color:#144F5A;font-weight:bold;font-size:14px;}
	 .panel-body label {
    font-size: 11pt;
    display: inline-block;
    max-width: 100%;
    margin-bottom: 5px;
    color: #666;
    font-weight: 700;
}
	  img{width:160px !important;}
	  .col1-layout{margin-top:7rem;}
		html {
    font-size: inherit !important;
}
		.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin:2px;
}
	
.header-logo-top{
    padding: 4px;
    width: 100%;
    border-bottom: 1px solid rgba(0,0,0,0.2);
    margin-bottom: 9px;
  }
	.h4, h4, .panel-info h4 {
    font-size: 16px;   color:#144F5A;
}
	.h3, h3, .panel-info h3 {
    font-size: 20px;    color: #0EB58F;
}
	.table-responsive > .table > tbody > tr > td, .table-responsive > .table > tfoot > tr > td, .table-responsive > .table > thead > tr > td{
		font-size: 11pt !important;
     white-space: normal !important;
	}
	.table-responsive > .table > tfoot > tr > th,.table-responsive > .table > tbody > tr > th, .table-responsive > .table > thead > tr > th {
		font-size: 12pt !important;
    white-space: normal !important;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #0eb58f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

	body, button, input, select, table, textarea, p {
    color: #666;
    font-family: 'Montserrat', sans-serif !important;
    font-weight: 500;
}  
  }

</style>
<div class="loader" style="display: none;"></div>

<div class="noprint container" data-html2canvas-ignore="true" id="hideondownload1">
<button onclick="goBackhtm()"  class="btn bck-btn noprint"  style="color: #fff;width:auto;display: inline-block;padding: 10px;background:#0EB58F;border: 1px solid #0eb58f;" data-dismiss="modal">>>Back</button>
</div>


<div id="pdfContent" style="background-color: white;">
	<div class="container-fluid">
	<div class="container">
		<div class="experiencethediff"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">Experience the difference</div></div>
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
		<h2>Hello, <?php echo $customerName;?><br>Here’s your Healthy Menu</h2></div>
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6"><p style="margin-top: 12%;font-weight:bold;position: relative;display: block;text-align: right;">Report Generation Date: <?php echo $formattedDate;?></p></div>
	<div class="panel panel-info">
  <!-- Default panel contents -->
 
  <div class="panel-body">
    <p>Mob: <?php echo $customer->getPrimarymobileno();?></p> 
	<?php if($billStreet1!=''){ ?>
        <p>Address Home: <?php echo $billStreet1;?>, <?php echo $billCity;?></p>
	<?php } ?>
	<?php if($billStreet2!=''){ ?>
	 <p>Address Office:  <?php echo $billStreet2;?>, <?php echo $billCity;?></p>
	<?php } ?>
  </div>
</div>
	
	<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">About</div>
  <div class="panel-body">
    <p><label style="width:15%;float:left;">DISLIKE:</label> <span style="width:85%;float:left"><input type="text" id="unlikes"  style="
    box-shadow: none; background: none;" placeholder="Dislikes"  value="<?php echo $AllergiesDislike['dislikename'] ?>" /></span></p>
	<p><label style="width:15%;float:left">ALLERGIES:</label> <span style="width:85%;float:left"> <input type="text" id="allergies" placeholder="Allergies" style="box-shadow: none; background: none;" value="<?php echo $AllergiesDislike['allergies'] ?>" /></span></p>
  </div>
</div>
		
<?php if(is_object($orderInfo ))  {
	          
              
               
              $orderDate = $orderInfo->getFormattedOrderdate(); 
              $formattedDate = date("d M Y",strtotime($orderDate)); 
              $breakfastCollection = $orderInfo->getCusineDetails($orderId,$cusine='breakfast');
              $lunchCollection = $orderInfo->getCusineDetails($orderId,$cusine='lunch');
              $dinnerCollection = $orderInfo->getCusineDetails($orderId,$cusine='dinner');
              $highteaCollection = $orderInfo->getCusineDetails($orderId,$cusine='hightea ');
			
 			  $total=0;
			  $totalCalories=0;
			  $totalFiber=0;
			  $otalProtien=0;
			  $totalCarbs=0;
			  $totalFat=0;
			  
			  
			  
	?> 
  <!-- Table -->
	<div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
            <th style="color:#144F5A; font-size:14pt !important;font-weight: bold;">Meal Plan Description</th>
       <th></th>
        <th style="font-weight: 500;color:#0EB58F;">Quantity in grams</th>
        <th style="font-weight: 500;color:#0EB58F;">Calories you get</th>
      </tr>
    </thead>
    <tbody>
	
	   <?php if(count($breakfastCollection)>0)
  		     {?>	<tr>
		<td colspan="4" style="border-top: 1px solid #0EB58F;padding:0px;"></td>
		
		</tr>
		<?php
		
		      $countItem=0;
		      foreach($breakfastCollection as $iteminfo) { 
			  
			  $totalCalories+=$iteminfo['calories'];
			  
			  if($iteminfo['fiber']!='no')   {  $totalFiber+=  $iteminfo['fiber'];   } 
			  if($iteminfo['protein']!='no') {  $totalProtien+= $iteminfo['protein']; } 
			  if($iteminfo['carbohydrates']!='no')   {  $totalCarbs+=  $iteminfo['carbohydrates'];   }
			  if($iteminfo['fat']!='no')     { $totalFat+=     $iteminfo['fat'];     }
			  
			  
			  ?>
	   <tr>
				 
			       <?php if($countItem==0){?>
					<td style="border-top:0px solid #d9edf7;color:#0EB58F;font-weight:bold;border-bottom:0px;font-size: 12pt !important;">BREAKFAST</td>
					<?php } else {?>
					<td style="border-top:0px;border-bottom: 0;">&nbsp;</td>
					<?php } ?>
					<td style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['itemname'];;?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['qty'];?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['calories'];?></td>
			  </tr>
			  
			  
	   <?php  $countItem++; 
	          }
	   } ?>
	
       <?php if(count($lunchCollection)>0)
  		       {?>	<tr>
		<td colspan="4" style="border-top: 1px solid #0EB58F;padding:0px;"></td>
		
		</tr>
		<?php
		      $countItem=0;
		      foreach($lunchCollection as $iteminfo) { 
			  
			  $totalCalories+=$iteminfo['calories'];
			  
			  if($iteminfo['fiber']!='no')   {  $totalFiber+=  $iteminfo['fiber'];   } 
			  if($iteminfo['protein']!='no') {  $totalProtien+= $iteminfo['protein']; } 
			  if($iteminfo['carbohydrates']!='no')   {  $totalCarbs+=  $iteminfo['carbohydrates'];   }
			  if($iteminfo['fat']!='no')     { $totalFat+=     $iteminfo['fat'];     }
			  
			  
			  ?>
		
		<tr>
			
			        <?php if($countItem==0){?>
					<td style="border-top:0px solid #d9edf7;color:#0EB58F;font-weight:bold;border-bottom:0px;font-size:12pt !important;">Lunch</td>
					<?php } else {?>
					<td style="border-top:0px;border-bottom: 0;">&nbsp;</td>
					<?php } ?>
					<td style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['itemname'];;?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['qty'];?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['calories'];?></td>
			  </tr>
			  
			  
	   <?php  $countItem++; 
	          }
	   } ?>
       
       <?php if(count($highteaCollection)>0)
  		     {?>	<tr>
		<td colspan="4" style="border-top: 1px solid #0EB58F;padding:0px;"></td>
		
		</tr>
		<?php
		      $countItem=0;
		      foreach($highteaCollection as $iteminfo) { 
			  
			  $totalCalories+=$iteminfo['calories'];
			  
			  if($iteminfo['fiber']!='no')   {  $totalFiber+=  $iteminfo['fiber'];   } 
			  if($iteminfo['protein']!='no') {  $totalProtien+= $iteminfo['protein']; } 
			  if($iteminfo['carbohydrates']!='no')   {  $totalCarbs+=  $iteminfo['carbohydrates'];   }
			  if($iteminfo['fat']!='no')     { $totalFat+=     $iteminfo['fat'];     }
			  
			  
			  ?>
		
	   <tr>
				
			        <?php if($countItem==0){?>
					<td style="border-top: 0px solid #d9edf7;color:#0EB58F;font-weight:bold;border-bottom:0px;font-size:12pt !important;">HI-TEA</td>
					<?php } else {?>
					<td style="border-top:0px;border-bottom: 0;">&nbsp;</td>
					<?php } ?>
					<td style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['itemname'];;?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['qty'];?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['calories'];?></td>
			  </tr>
			  
			  
	   <?php  $countItem++; 
	          }
	   } ?>
		
       <?php if(count($dinnerCollection)>0)
  		      {?>	<tr>
		<td colspan="4" style="border-top: 1px solid #0EB58F;padding:0px;"></td>
		
		</tr>
		<?php
		      $countItem=0;
		      foreach($dinnerCollection as $iteminfo) { 
			  
			  $totalCalories+=$iteminfo['calories'];
			  
			  if($iteminfo['fiber']!='no')   {  $totalFiber+=  $iteminfo['fiber'];   } 
			  if($iteminfo['protein']!='no') {  $totalProtien+= $iteminfo['protein']; } 
			  if($iteminfo['carbohydrates']!='no')   {  $totalCarbs+=  $iteminfo['carbohydrates'];   }
			  if($iteminfo['fat']!='no')     {  $totalFat+=     $iteminfo['fat'];     }
			  
			  
			  ?>
		
	    <tr>
				 
			        <?php if($countItem==0){?>
					<td style="border-top:0px solid #d9edf7;color:#0EB58F;font-weight:bold;border-bottom:0px;font-size:12pt!important;">DINNER</td>
					<?php } else {?>
					<td style="border-top:0px;border-bottom: 0;">&nbsp;</td>
					<?php } ?>
					<td style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['itemname'];;?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['qty'];?></td>
					<td  style="border-top: 1px solid #d9edf7;border-bottom:0px"><?php echo $iteminfo['calories'];?></td>
			  </tr>
			  
			  
	   <?php  $countItem++; 
	          }
	   } ?>
    </tbody>
  </table>
  </div>
	<?php  $total = $totalCarbs + $totalProtien + $totalFat;
	       $proteinPercent = round(($totalProtien/$total)*100,2);
		   $fatPercent     = round(($totalFat/$total)*100,2);
		   $carbsPercent = round(($totalCarbs /$total)*100,2);	
	?>
	<div class="panel panel-info" style="margin-bottom:50px;">
  <div class="panel-body">
<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
	<h3 style="color:#0EB58F;"><?php echo $totalCalories;?></h3>
	  <h4 style="color:#144F5A;">TOTAL CALORIES</h4>
	  </div>
	  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
	<h3 style="color:#0EB58F;"><?php echo $totalFiber;?> gms</h3>
	  <h4 style="color:#144F5A;">FIBER</h4>
	  </div>
	  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
	<h3 style="color:#0EB58F;"><?php echo (int)$proteinPercent;?>%</h3>
	  <h4 style="color:#144F5A;">PROTEIN</h4>
	  </div>
	  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
	<h3 style="color:#0EB58F;"><?php echo (int)$carbsPercent;?>%</h3>
	  <h4 style="color:#144F5A;">CARBS</h4>
	  </div>
	  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
	<h3 style="color:#0EB58F;"><?php echo (int)$fatPercent;?>%</h3>
	  <h4>FAT</h4>
	  </div>
  </div>
		
		<div class="panel-footer">
			<div data-html2canvas-ignore="true" style="text-align: center;margin: auto;max-width: 100%;">
			<textarea rows="2" cols="100" id="spi" name="spi" ><?php echo $specialInstructions;?></textarea></div>
			<p style="margin: 15px 0px 10px;">This meal plan helps you control your weight and obesity in managed eating habits, giving you desired calories</p>
		</div>

</div>
		
 

<?php }  else { echo "<div class='table-responsive'> There is no meal order of customer.</div> "; }?>
		<div class="container">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
			
		<img src="https://startlifeheal.com/skin/frontend/rwd/default/images/logo.png" style="width: auto;"/>
		</div>
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
			<img src="https://startlifeheal.com/skin/frontend/rwd/default/images/healthcraft.png" style="float:right;width:auto;"/>
		</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
		<hr style="width: 100%;float: left;margin: 20px auto;">
		<p><span href="" style="color: #0EB58F;">www.startlifeheal.com</span></p>
<p>For queries email us at <span style="color: #0EB58F;">Diet@LifeHeal.in</span>.in or call us at <span style="color: #0EB58F;">+91-9999846622 or 1800 212 7212 </span>
</p>
		<p>For delivery status and tracking please contact Healthcraftpune@gmail.com Support Helpline <span style="color: #0EB58F;">+91-9370707004</span></p>
		</div>	
		</div>
		</div>
	</div>
</div>
<!--</page>-->

<div id="hideondownload2" class="noprint" data-html2canvas-ignore="true" style="text-align: center;margin: auto auto 10px auto;max-width: 500px;width: 100%;">
<button onclick="addAllergiesDislike(<?php echo $orderId;?>)"  class="btn btn-danger btn-default pull-left" style="background:#0EB58F;border: 1px solid #0eb58f;">Save Changes</button>
<button onclick="printPage();"  class="btn btn-danger btn-default pull-left" style="background:#0EB58F;border: 1px solid #0eb58f;">Print</button>
<button onclick="goBack()"  class="btn btn-danger btn-default pull-left" style="background:#0EB58F;border: 1px solid #0eb58f;" data-dismiss="modal">Close and Cancel Printing</button>
</div>


<script type="text/javascript">
function addAllergiesDislike(orderid){  
  var Allergies = jQuery("#allergies").val(); 
  var Dislikes = jQuery("#unlikes").val();
  var Notes = jQuery("#spi").val();
  
  if(Allergies || Dislikes){
  jQuery(".loader").css("display", "block"); 
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/addAllergiesDislike' ?>",
    type: "POST",
    data: {
      customerid: "<?php echo $customer->getId() ?>", 
      customername:"<?php echo $customer->getName() ?>",
      customermobile:"<?php echo $customer->getPrimarymobileno() ?>",
      allergies: Allergies, 
      dislikename:Dislikes,
	  notes:Notes
    }, 
    success: function(response) {
      jQuery(".loader").css("display", "none"); 
    }
  }); 
  }
  
  setinstructionAndPrint(orderid);
}

function setinstructionAndPrint(orderid) {
	
  jQuery.ajax({
    url: "<?php echo Mage::getBaseUrl().'heal/index/setspecialinstructions' ?>",
    type: "POST",
    data: {
      orderid: orderid, 
      spi:jQuery("#spi").val()
      
    }, 
    success: function(response) {
     
    }
  }); 
}

function printPage()
{
	 window.print(); 
}

function goBack() {
  window.close();
}
function goBackhtm() {
  window.history.back();
}


//jQuery('#print-btn').click(()=>{
var pdfilenames = "<?php echo $orderInfo->getName()."_".$formattedDate; ?>";
var pdf = new jsPDF('p','pt','a4');

var options = {
  //Pagesize:2,
  //'background': 'white',
  //totalPdfHeight:5000
  //pages:2
  //pagesplit: true //include this in your code
}; 
pdf.addHTML(jQuery("#pdfContent"),options, function() {
    pdf.save(pdfilenames);
    goBack();
	 
});
//})


</script>







