  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
	   $("#tooltip-1").tooltip();
  } );
  </script>
	<style>
		
	.col1-layout {
    width: 100%;
    margin-top: 7rem;
    height: 100%;
    margin-bottom: 1.5rem;
}
		.col1-layout .col-main {
    float: left;
    width: 100%;
    padding: 0;
}
		table{      margin-top: 30px;
    margin: auto;
		}	
	
	table td {
    border-top: thin solid; 
    border-bottom: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	width:80%;
	text-align:left;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}
table td:first-child {
     border-left: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	width: 10%;
}

table td:last-child {
     border-right: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	    padding: 10px;
		width: 10%;
}
.hasDatepicker{width: 78% !important;

max-width: 100%;

background: #f6fcfc;

height: 35px;

box-shadow: 0px 0px 2px rgba(0,0,0,0.3);

border: 0px;

float: left;
margin:10px;
margin-right: 15px;}

@media print
{
.noprint {display:none;}
}

@media print 
{
		.header-wrapper, .footer-container, .breadcrumbs{display:none;}
	header, footer, .bck-btn{display:none;}
	 div.print-content article.node .node-blog .clearfix div.item-body p a {
    display: none;}
	.noprint {
  display:none;
}
	.col1-layout {margin-top:0; margin-bottom:2rem;}
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 11px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
}
@media screen and (min-width:260px) and (max-width:760px){
.hasDatepicker{width: 100% !important;

max-width: 100%;

background: #f6fcfc;

height: 35px;

box-shadow: 0px 0px 2px rgba(0,0,0,0.3);

border: 0px;

float: left;
margin:10px auto;}	
}
		
	</style>

<div class="container">
<table border="1" align="center" style="padding-left: 20px;padding-top:10px;width:100%;"><!--margin: 25px;margin-right: 50px -->
  <tbody>
     <tr  class="noprint">   
    <td style="margin:3px; padding:4px;  border: 1px solid #dddddd;">
        <span class="select_label">Select City hhhh:</span>
        <select id="city" name="city">
		      <option value="Delhi"  >Delhi</option>
		      <option value="Gurgaon"  >Gurgaon</option>
		      <option value="Pune"  >Pune</option>
		    </select>
 	  </td>
    </tr>
    <tr class="noprint">
     
      <td style="margin:3px"> <p style="margin-bottom: 0px;float: left;width: 100%;">
      <span style="width:auto;float: left;height: 35px;line-height: 35px;margin:10px auto;">Order Date:</span>
		
      <input type="text" id="datepicker">
      <input type="button" value="Order Details" onClick="getOrderQuantity();" style="margin: 10px auto;padding: 0px 10px;background: #0EB58F;border: 1px solid #0EB58F;color: #fff;font-size: 14px;height: 35px;width:auto;line-height: 35px;float: left;"> </button></p></td>	  
    </tr>
<!--<tr><td> <span style="width:auto;float: none;height: 35px;line-height: 35px;margin:10px auto;text-align:center;">ADVANCE MENU : FOR ORDERING SUPPLIES ONLY</span></td></tr>-->
    <tr>
		
      <td  id="resultTable" style="text-align:center;margin-left:0px;padding-left:10px;padding-bottom: 34px;">
		
		</td>
			
    </tr>
   
   
  </tbody>
</table>
</div>
<script type="text/javascript">
	//var jQuery = $.noConflict();
function getOrderQuantity()
	{
		
		var orderDate = jQuery("#datepicker").val();
		var city = jQuery("#city").val();
		if(orderDate!='')
		{
		
			jQuery.ajax({
						url: "<?php echo Mage::getBaseUrl().'heal/index/datewiseorderqty' ?>",
						type: "POST",
						data: {
						 orderDate: orderDate,
						 city:city
						},
						  success: function(response)
						 {  
							//  alert(response);
							jQuery("#resultTable").html(response);
								
						 }
			});
		}
		else
		{
				alert("Please select the date");
		}
	}
	
	
	function showdiv(orderdate,productid,cuisine,divId)
	{
		   
		
		
		
			jQuery.ajax({
						url: "<?php echo Mage::getBaseUrl().'heal/index/qtyorderwisedetail' ?>",
						type: "POST",
						data: {
						    orderdate: orderdate,
						    productid: productid,
						    cuisine: cuisine,
						    divId:divId
						},
						  success: function(response)
						 {  
							  jQuery("div."+divId).html(response);
							 
								if(jQuery("div."+divId).css('display') == 'block')
								{
									jQuery("div."+divId).css('display', 'none');
								}
								else if(jQuery("div."+divId).css('display') == 'none')
								{
									jQuery("div."+divId).css('display', 'block');
								}
								
						 }
			});
		
		
		
		
		
		 
		
	}
</script>

