  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
	<style>
.col1-layout .col-main {
    float: left;
    width: 100%;
    padding: 0;
}

		table{  
	width: auto;
margin: auto;
		}	
		.main {
    width: 100%;
    margin-top: 7rem;
    height: 100%;
    margin-bottom: 1.5rem;
}
	table td {
    border-top: thin solid; 
    border-bottom: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	width:80%;
	text-align:left;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}
table td:first-child {
     border-left: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	width: 10%;
}

table td:last-child {
     border-right: thin solid;
	padding-left: 10px;
	padding-right: 10px;
	    padding: 10px;
		width: 10%;
}

@media print{
	.header-wrapper, .footer-container, 
	.breadcrumbs, .bck-btn{display:none;}
	header, footer{display:none;}	
	.noprint {display:none;}
}

@media print {
	.header-wrapper, .footer-container, .breadcrumbs{display:none;}
	header, footer, .bck-btn{display:none;}
	 div.print-content article.node .node-blog .clearfix div.item-body p a { display: none;}
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
		font-size:10pt;
    }
    html, body {
       /* width: 210mm;
         height: 297mm;
        height: 282mm; */        
        background: #FFF;
        overflow:visible;
    } 
		
    body {
        padding-top:15mm;
    }
}
@media screen and (min-width:260px) and (max-width:760px){
	
}
	.qty-wrapper{display: flex; flex-wrap: wrap; align-items: end; padding: 20px; width: 100%; box-sizing: border-box;}	
	.qty-inner{width:calc(100% - 150px);}
	.qty-inner label{display: inline-block; width:130px; height: 35px;line-height: 35px;}
	.qty-inner select, .qty-inner input{
		width:calc(100% - 135px);
		background: #f6fcfc;
		height: 35px;
		box-shadow: 0px 0px 2px rgba(0,0,0,0.3);
		border: 0px;
		margin-bottom: 15px;
		display: inline-block;
	}
	.qty-wrapper input[type="button"]{
		margin: 0 auto 15px auto; width: 120px;	background: #0EB58F;
		border: 1px solid #0EB58F; color: #fff; font-size: 14px;
		height: 35px; line-height: 35px;
	}
</style>


<table width="800" border="1" align="center" style="padding-left: 20px;padding-top:10px;margin: 25px;margin-right: 50px ">
  <tbody>
   
    <tr class="noprint">
     
     	<td style="margin:3px"> 
     		<div class="qty-wrapper">
     			<div class="qty-inner">
     				<label>Select City:</label>
        			<select id="city" name="city">
		      			<option value="Delhi">Delhi</option>
		      			<option value="Gurgaon">Gurgaon</option>
		      			<option value="Pune">Pune</option>
			  			<option value="Surat">Surat</option>
		    		</select>
      				<label>Order Date:</label>
      				<input type="text" id="datepicker" >
      			</div>
      			<input type="button" value="Order Details" onClick="getOrderQuantity();"> </button>
      		</div>
      	</td>	  
    </tr>
    <tr>
      <td  id="resultTable" style="text-align:center;margin-left:0px;padding-left:10px;padding-bottom: 34px;"></td>
    </tr>
   
   
  </tbody>
</table>

<script type="text/javascript">
	//var jQuery = $.noConflict();
function getOrderQuantity()
	{
		
		var orderDate = jQuery("#datepicker").val();
		var city = jQuery("#city").val();
		//alert(orderDate);
		if(orderDate!='')
		{
		
			jQuery.ajax({
						url: "<?php echo Mage::getBaseUrl().'heal/index/datewiseorderqtydetails' ?>",
						type: "POST",
						data: {
						 orderDate: orderDate,
						 city:city
						},
						  success: function(response)
						 {  
							//  alert(response);
							jQuery("#resultTable").html(response);
								
						 }
			});
		}
		else
		{
				alert("Please select the date");
		}
	}
</script>

