<!-- Hero Banner Start -->
	<div class="hero">
		
	<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/obesity_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/obesity_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
				
	<h1>WHY SHOULD LIFE WEIGH YOU DOWN?</h1>
		        	<p>Reduce weight and stay fit with our<br>
Weight Management Plans
 </p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- How it Works Start -->
	<style>
		.disease-single-how-it-works h2, .disease-single-how-it-works h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works disease-single-how-it-works">
		
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Personalised. Holistic. Long-term.</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Does losing weight break you into a sweat? No worries. We go beyond calorie-counting and deep dive into your inner weight-gain drivers. You’ll discover the most effective weight-loss strategies put together by our dieticians, nutritionists, and culinary experts that heal you from within.</p>
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Losing weight is not about calories. Our weight management plans look at inner drivers of weight gain. We change your metabolism through changes in food ingredients, intermittent fasting and more. We see what suits you and adjust plans according to that. You will never go hungry.</p>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000"><span>Steps included in weight management</span></p>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Body Analysis</h3>
					<p>You’ll start your journey with a thorough analysis of your blood tests by our experts. We’ll help you discover the root cause of your obesity and weight gain with our scientific InHealth<sup style="font-size:4px;top: -10px;"><b>TM</b></sup> system.</p>
					
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>One on One Counselling</h3>
					<p>With our experts, you'll get a better understanding of your body, lifestyle, and related weight problems. We’ll set practical goals and timelines for your weight loss journey. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Your Customised Plan</h3>
					<p>Next, you’ll get a 360<span>&deg;</span> plan that suits your body, keeping in mind your lab tests, and lifestyle challenges. Besides your diet, we’ll help you improve your sleep patterns and stress levels.
						</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Personal Follow Up</h3>
					<p>Weight loss is all about staying motivated. With personal follow-ups, you’ll be inspired to follow your weight loss plan, and we’ll keep encouraging you to stay on track with healthy habits.

</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 5</h4>
					<h3> Monitoring and Educating</h3>
					<p>Your meals and your progress will be monitored throughout the process. We’ll nudge you all along to change make small, but significant lifestyle changes that drive your weight loss.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 6</h4>
					<h3>Medical Review</h3>
					<p>Science is at the heart of our Weight Management Plans. With regular health tests, we’ll check how your weight-loss regime is working. Based on your test results and your metabolism, we’ll also adjust and improve your plan.</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->
	
	<!-- Meal Plans Start -->
	<style>
	
		.disease-single-meal-plans {
			background-color: #0EB58F;
		}
		
		.disease-single-meal-plans .single-meal-plans-title {
			color: #FFFFFF;
		}
		
	</style>
	<div class="single-meal-plans disease-single-meal-plans full-height">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>WEIGHT MANAGEMENT <br> MEAL PLANS</h2>
				<p>Losing weight should never be about giving up on the things you love eating. Our Weight Management Meal Plans are created by chefs in consultation with dieticians to ensure you enjoy every bite without worrying about the calories. </p>
			</div>
			
				<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Weight Loss Plan</h3>
						<h2>Rs. 8,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2693)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Weight Loss Plan</h3>
						<h2>Rs. 6,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2692)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Weight Loss Plan</h3>
						<h2>Rs. 5,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2691)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Weight Loss Plan</h3>
						<h2>Rs. 4,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2635)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Meal Plans End -->
	
	<!-- Impact Story Start -->
	<div class="impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
			<img src="<?php echo $this->getSkinUrl('images/impact-story-image.png') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL MONIKA LOST 16 KG IN JUST 3 MONTHS BEFORE MARRIAGE</h2>
				<h3>Monika Singh, <span>A success story</span></h3>
				<p>Losing weight was tough for me. I weighed 70kg when I got engaged. I didn't want to wear an oversized lehenga for my wedding. Thankfully, LifeHeal came to my rescue. After religiously following the LifeHeal diet for 3 months, I lost around 20kg.</p>
				<div class="impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-1.png') ?>"/>
					</a>
					<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
						
					</a>
				</div>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->
	
	<!-- Stats Start -->
	<div class="stats">
		<div class="stats-container">
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
					
			
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	<!-- Stats End -->
	
	<!-- Testimonials Start -->
	<style>
		.disease-single-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
	<div class="testimonials disease-single-testimonials">
		
		<div class="testimonials-container">
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">THEY’VE LOST WEIGHT. ARE YOU NEXT?</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>There was a time when all I could think about was weight…90 kgs and growing! Nothing seemed to be working till I discovered LifeHeal’s Meal Plans. Today, after 6 months I’m at a happy 65!</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-1.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Mridul Asthana Lost 25Kgs</h3>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>Losing weight was my Mt. Everest. I had to conquer it before the biggest day of my life. I had to fit into my dream lehenga. Thanks to LifeHeal’s Diet Plan, constant coaching, and motivation, I lost 16 kgs, and looked just ‘wow’ on my D-day!</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-2.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Monica Singh Lost 25 kgs</h3>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>My obesity was the biggest concern for my family members and me. Not just health-wise but it also caused me severe depression. With LifeHeal, I discovered how small lifestyle changes and the right meals can make all the difference</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-3.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Rahul Arora lost 30 kgs</h3>
							
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans. Additionally, we offer a 30% discount on your first order. </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
	
	