<div class="home-page-banner">
<ul>
	<li>
		<img style="width:100%;" src="<?php echo $this->getSkinUrl('images/home-banner.jpg') ?>" alt="CureMyDiabetes">
	</li>
</ul>
</div>


<div class="homepage-video">
<video id="video" width="640" height="360" poster="https://addpipe.com/sample_vid/poster.png" preload="auto" controls disablepictureinpicture  controlsList="nodownload">
      <source src="/video/rain.mp4" type="video/mp4" />
      <source src="/video/Big_Buck_Bunny_small.ogv" type="video/ogg"/>
</video>
</div>

<div class="home-possible-content" style="margin-top: 50px; text-align: center;">
	<h2 style="font-weight: bold"> Yes It Is Possible To Reverse Diabetes </h2>
	<span>At Cure My Diabetes our focus is to reduce and reverse diabetes.</span>
</div>
<div class="container">
  <div class="row">
	<div class="col-sm-6"> 
		<h2 class="wsite-content-title" style="text-align:center;"><font size="6">LEARN MORE ABOUT OUR INNOVATIVE DIABETES TREATMENT PROGRAM</font></h2>
	</div>
	<div class="col-sm-6"> 
		<label>Name:</label>
		<div class="input">
			<input class="home-input" type="text" name="firstname" value="" placeholder="">
		</div>
		<label>Phone:</label>
		<div class="input">
			<input class="home-input" type="text" name="Phone" value="" placeholder="">
		</div>
		<label>Email:</label>
		<div class="input">
			<input class="home-input" type="text" name="Email" value="" placeholder="">
		</div>
	</div>
  </div>
</div>

