 <style>
	 .addresses-list{float: left;
    margin: 30px;}
	 .back-link{display: inline-flex;margin-top: 10px;width: 100%;}</style>
<div class="col2-set addresses-list">
	  <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <div class="col-1 addresses-primary" style="padding-left:0;">
        <h2><?php echo $this->__('Contact Address') ?></h2>
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()):	?>
            <li class="item">
                <h3><?php //echo $this->__('Default Billing Address') ?></h3>
                <address>
				    <?php $addr = Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses);?>  
					
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" class="changeadd"><?php echo $this->__('Change Contact Address') ?></a></p>
           </li>
        <?php else: ?>
            <li class="item">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            </li>
        <?php endif ?>

            
        </ol>
    </div>
  </div>

