<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.blog {
				background-image: url('<?php echo $this->getSkinUrl("images/blog-hero-banner.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.blog {
					background-image: url('<?php echo $this->getSkinUrl("images/blog-hero-banner-mobile.png")?>');
				}	
			}
			
			.blog h1 {
				color: #FFFFFF;
			}
			
			
			
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner blog">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	 <img src="<?php echo $this->getSkinUrl('images/blog-hero-logo.png') ?>"/>
					<h1>GENERIC THOUGHT OR <br>QUOTE GOES HERE.</h1>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Archive Start -->
	
	<div class="blog-archive">
		<div class="blog-archive-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">GET THE LATEST QUICK-READS ON HEALTH AND FITNESS</h2>
			<div class="blog-archive-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/diabetesblog.jpg")?>')">
					</div>
					<div class="blog-archive-detail-text">
						<h3>Can I Have Sugar, Honey?</h3>
						<p>Diabetes is a metabolic disease that leads to high blood sugar levels. Usually, insulin moves sugar...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single2') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog2img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Should I be drinking milk?</h3>
						<p>Did you know that India is one of the largest producers and consumers of milk? From drinking chai to masala...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single3') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-3.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Pros and Cons of Vegan Diet.</h3>
						<p>Veganism or Vegan Diet has been trending for quite a few years and is one the most vouge diets out there...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single4') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog4img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Trust Your Gut</h3>
						<p>Did you know that our body has over 4 trillion bacteria? Interestingly most of them can be found in the gut...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single5') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog5img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Intermittent Fasting 101</h3>
						<p>The dieting world is ever-changing, and it's hard to keep track of all the diets out there. Additionally, not...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single6') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog6img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('blog-single7') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-3.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="blog-single">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-4.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="blog-single">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-1.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="blog-single">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-2.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="blog-single">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-3.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="blog-single">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-4.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Lorem ipsum dolor sit amet, consetetur</h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				
				
			</div>
		</div>
	</div>
	
	<!-- Blog Archive End -->
	
	