 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>

<script>
  $( function() {
      $( "#datepicker" ).datepicker();
      $("#tooltip-1").tooltip();
    } );


</script>               
               
<?php $uniqueCustomersJson = Mage::helper('heal')->getUniqueCustomersJson();  ?>

  <script>
  var customers = <?php echo $uniqueCustomersJson;?>;
  
  $( function() {
    $( "#datepicker-from" ).datepicker();
	$( "#datepicker-to" ).datepicker();
	   $("#tooltip-1").tooltip();
	  
	   $("#customers").select2({    
				  data: customers
				});
				
	 
	    <?php if(isset($_POST['customers'])) { ?>
		
		$("#customers").val("<?php echo  $_POST['customers'];?>");
	        $('#customers').trigger('change');
	 
			<?php } ?>
	   
	    
  } );
  </script>
  
<style>	
.table-top-row{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin-bottom: 15px;
  }
.table-logo{
    width:33%;
  }
.table-logo img{
    display: block;
    width:65%;
    margin:20px 0 0 0;
  }
.name-content{
    width:33%;
    background:#5599b0;
    box-sizing: border-box;
    padding: 15px 20px;
    color:#fff;
    text-align: center;
  }
.weekly-table{
    width:100%;
  }
.weekly-table thead tr td{
    background:#5599b0;
    text-align: center;
    color:#fff;
    width:16.66%;
    box-sizing: border-box;
  }
.weekly-table tbody tr td{   
    text-align: center;
    border: 5px solid #fff;
    width:16.66%;
    box-sizing: border-box;
  }   
.weekly-table tbody tr:nth-child(even) td{background: #ededed;}
.weekly-table tbody tr:nth-child(odd) td{background: #f4f4f4;} 
.weekly-table tbody tr.collapsiblereport td{font-weight: bold;} 

.print_btn{
  padding: 0px 25px;
  background: #c31f41;
  border: 1px solid #a61d3f;
  color: #fff;
  font-size: 14px;
  height: 35px;
  line-height: 35px;
  text-align:center;    
  margin:10px;
}
.sticky {
  position: sticky;
  top: 0;
  width: 100%;
}
.sticky + .table-scroll {
  padding-top:0px;
}
.table-scroll{
  float: left;
  width: 100%;
  padding: 0px;
  margin-bottom: 20px;
}

#datewise{
  width: 100%;
  padding: 50px 0;
  text-align: center;
  background-color: lightblue;
  margin-top: 20px;
}
		
.select2-container {
  box-sizing: border-box;
  display: inline-block;
  margin: 0;
  position: relative;
  vertical-align: middle;
  width: 100% !important;
  height: 35px;
  line-height: 35px;
  padding: 0;
}
.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 35px;
	}
	.select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 26px;
    position: absolute;
    top:5px;
    right: 10px;
    width: 20px;
}
.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 35px;
}
	.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin: 4px;
}
	.breadcrumbs{display:none;}	
	#myHeaderhead, #oldfooter, .navbar{
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    max-width: 100% !important;
    margin: 0 !important;
	}
	#printdate input[type="text"] {
  max-width: 100%;
  background: #f6fcfc;
  height: 35px;
  box-shadow: 0 0 2px rgba(0, 0, 0, .3);
  border: 0;
  margin: 0;
  width: 100%;
  text-align: left;
}	
#printdate select {
    font-size: 14px;
    margin:0px;
    width: 100%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;text-align: center;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}
.print{width:80%; margin:0 auto;}
 .print2{width:100%; float:left;}
#customerMealResport{
  font-size: 20px;	
  text-transform: 
  capitalize;width: 100%;
  display: block;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #a61d3f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

h2{font-weight: normal;margin: auto; width: 560px;font-size:17px;
height:60px;color: #000; line-height:60px;}
.tabledata td, .tabledata th{padding:10px;font-size:18px;width: auto;}
.dataalign{float: left; text-align: left; margin: auto;}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}

@media print {
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 18px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
    .print{width:92%; margin:0 auto;}
    .table-logo img{ display: block; width:75%; margin:30px auto 0 auto;}

    .weekly-table thead tr td{
    background:#5599b0;
    text-align: center;
    color:#fff;
    width:16.66%;
    box-sizing: border-box;
  }
.weekly-table tbody tr td{   
    text-align: center;
    border: 5px solid #fff;
    width:16.66%;
    box-sizing: border-box;
  }   
.weekly-table tbody tr:nth-child(even) td{background: #ededed;}
.weekly-table tbody tr:nth-child(odd) td{background: #f4f4f4;} 

}

@media all {
.page-break { display: none; }
}

@media print {
.page-break { display: block; page-break-before: always; }
}
@media screen and (min-width:260px) and (max-width:767px){
	.tabledata{width:100%;overflow:scroll;}
	#myHeadertop, .table-scroll{width:600px,font-size: 14px;}
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 68%;
}	
	.dataalign{float: left;
text-align: center;
width: 100%;
margin: 10px;}
#printdate select {
    font-size: 17px;
    margin: 10px;
    width: 68%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
@media screen and (min-width:768px) and (max-width:999px){
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}

}

.hideme{display:none;}
</style>
<?php
$choosenDate='';
$choosenCity='';
$msg ="";
$foundWeeklyReport='no';

$caloryPercent=0; $caloryTotal=0;
$carbsPercent=0;  $carbsTotal = 0;
$fatPercent=0;    $fatTotal=0;
$proteinPercent=0; $proteinTotal=0;
$total=0;
$labelText='';
$countCustomerResult=0;

if (isset($_POST["submit"]) )
{
	 
	  $choosenCustomer    = $_POST['customers'];
       if($choosenCustomer=='')
       {
           $msg.="Please select the customer<br>" ;
        }
	   
}
	

//echo "Week number--".$weekNumber; echo "<br>";
?>
<div class="noprint">
<form method="GET" action="<?php echo Mage::getBaseUrl().'customer-daily-meal-report-info';?>" >

<h1 class="noprint" style="text-align: center;font-size: 24px;text-transform: capitalize;float: left;margin: 20px auto!important;">Customer Daily Meal Report</h1>
<table border="1" align="center" id="printdate" style=" max-width:560px; padding:10px 0 0 20px; margin: 0 auto 40px auto;" rules="none">

  <tbody class="noprint">       
	  <tr style="padding: 20px;float: left;width: 100%;display: block;">  
      <td class="dataalign" style="width:30%;">
				<span style="width:100%;float:left;height: 35px;line-height: 35px;">Select Customer:</span>
			</td>
			<td class="dataalign"  style="width:70%;">
          <select id="customers" name="customers"></select>
      </td>
		</tr>

		<tr style="padding: 20px;float: left;width: 100%;display: block;"> 
      <td class="dataalign"  style="width:30%;">				   
        <span style="width:100%;float:left;height: 35px;line-height: 35px;">Order Date:</span>
			</td>
			<td class="dataalign"  style="width:70%;">
        <input type="text" id="datepicker" name="orderdate">       
      </td>               
 	  </tr>

    

		<tr>
		  <td colspan="2" style="margin: 0px auto 20px;text-align: center;width: 150px;display: block;">
        <input type="submit" name="submit" value="Submit" style="padding: 0px 0px;background: #c31f41;border: 1px solid #a61d3f;color: #fff;font-size:18px;height:45px;border-radius: 4px;line-height:45px;text-align:center;width:100%;">
      </td>
    </tr>
        <?php if($msg!=''){?>
    <tr><td colspan="2"  style="float: left;margin: auto;text-align: left;width: 100%;color:red"><?php echo $msg;?></td>
	  
	  </tr>
        <?php } ?>
     
  </tbody>
</table>
</form>
</div>


