<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/disclaimer.jpg') ?>"  alt="disclaimer">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              DISCLAIMER
            </div>
            <div class="easyway">
            <p>Please Note:</p>
           <p>Results vary from person to person.</p>
           <p>No results are guaranteed.</p>
           <p>Generally, the sooner a diabetic comes to us, the better the chances for best results. 
           At very late stages all we can aim to do is to reduce the damage from the disease. However this varies from person to person.</p>

          <br/>
          
          <p>We do not promise to cure any disease, only to help in the goal to be healthier.</p>
            </div>
            </div>
            </section>
            
            