<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.food-subscription {
				
				background-image: url('<?php echo $this->getSkinUrl("images/meal-plan-hero-banner.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.food-subscription {
					background-image: url('<?php echo $this->getSkinUrl("images/meal-plan-hero-banner-mobile.png")?>');
				}	
			}
			
			.food-subscription h1 {
				color: #FFFFFF;
			}
			
			.food-subscription h1 span {
				color: #FF7129;
			}
			
			
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner food-subscription">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1><span>FOOD SUBSCRIPTION</span><br>LOSE UP TO 10 KGS IN<br>YOUR FIRST 30 DAYS </h1>
		        </div>
		        
		        <div class="food-subscription-logo">
					
					<img src="<?php echo $this->getSkinUrl('images/food-subscription-logo.png') ?>"/>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	<!-- Text Block Start -->
	<style>
		.food-subscription-text h2 {
			color: #FF7129;
		}
			
	</style>
		
	<div class="text-block food-subscription-text">
		<div class="text-block-container">
			<h2>HELLO PUNEKAR! <br>ORDER FOOD SUBSCRIPTION FROM HEALTH CRAFT</h2>
			<p>Are you tired and confused about meal portion size? Is healthy eating stressing you out? Subscribe to our food subscription from Health Craft and enjoy hassle-free healthy eating. Our professional chefs meticulous prepare mouthwatering and seasonal meals, which are precisely weighed out for you.  </p>
		</div>
	</div>
	
	<!-- Text Block End -->
	
	<!-- Tab Block Start -->
	<div class="tab-block food-subscription-benefits">
		<div class="tab-block-container">
			<div class="tab-block-left" style="background-image:url('<?php echo $this->getSkinUrl("images/food-subscription-benefits.png")?>')"></div>
			<div class="tab-block-right" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<div class="tab-block-wrapper">
					<h2>FOOD SUBSCRIPTION BENEFITS</h2>
					<div class="tab-container food-subscription-tab">
						
						<ul class="tabs">
						  <li class="active-tab">Benefit 1</li>
							<li>Benefit 2</li>
							<li>Benefit 3</li>
						</ul>
						
						<ul class="tabs-content">
							<li>
								<img src="<?php echo $this->getSkinUrl('images/food-subscription-benefits-1.png') ?>"/>
								<h3 class="tabs-touch">Benefit 1</h3>
								<p>Portion control is one of the biggest hurdles in your weight loss journey. With our HealthCraft food subscription, you never have to worry about portion size. Our meals are precisely weighed out, so you get appropriate nutrition and aren’t starving. </p>
							</li>
						  <li>
							  <img src="<?php echo $this->getSkinUrl('images/food-subscription-benefits-2.png') ?>"/>
											  	
								<h3 class="tabs-touch">Benefit 2</h3>
								<p>HealthCraft educates you on healthy foods and their benefits. We cook with a wide range of probiotic, gut-friendly, low-carb, keto, and high protein food alternatives. You’ll forget regular biryani after eating our Quinoa biryani. </p>
							</li>
							<li>
								<img src="<?php echo $this->getSkinUrl('images/food-subscription-benefits-3.png') ?>"/>
								<h3 class="tabs-touch">Benefit 3</h3>
								<p>We never compromise with your taste. Our professional chefs curate 5 star meals that are directly delivered to your doorstep. Our meals include exotic dressings, sauerkraut, kombucha, and other artisanal foods. Meals are never repeated. You’ll never be bored, its our promise! </p>
							</li>
						</ul>
						
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
	<!-- Tab Block End -->
	
	<!-- Text Block Start -->
	<style>
	
		.health-craft-text-block .text-block-container {
			padding-bottom: 0;
		}
		
		.health-craft-text-block h2 {
			color: #FF7129;
		}
			
	</style>
		
	<div class="text-block health-craft-text-block">
		<div class="text-block-container">
			<h2>ABOUT HEALTH CRAFT</h2>
			<p>Health Craft consists of trained chefs and food-fanatics, who are passionate about creating healthy and nutritious meals. Recipes are carefully tested in our kitchen in Pune and only meals with best ingredients delivered to you. Our team creates healthy, delicious, protein packed, plant based, crave able meals, that always keep you full. </p>
		</div>
	</div>
	
	<!-- Text Block End -->
	
	<!-- Image Gallery Start -->
	
	<style>
		.health-craft-kitchen-image-gallery h2 {
			color: #FF7129;
		}
			
	</style>
	
	<div class="image-gallery health-craft-kitchen-image-gallery">
		<div class="image-gallery-container">
			<h2>HEALTH CRAFT KITCHEN GALLERY</h2>
			
			<div class="image-gallery-carousel-container">
				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-1.png') ?>"/>
				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-2.png') ?>"/>
  				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-3.png') ?>"/>  				
  				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-3.png') ?>"/>
				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-2.png') ?>"/>
  				<img src="<?php echo $this->getSkinUrl('images/health-craft-kitchen-image-gallery-1.png') ?>"/>
			</div>
		</div>
	</div>
	
	
	<!-- Image Gallery End -->
	
	<!-- Tab Block Start -->
	<div class="tab-block menu-highlights">
		<div class="tab-block-container">
			<div class="tab-block-left" style="background-image:url('<?php echo $this->getSkinUrl("images/menu-highlights.png")?>')"></div>
			<div class="tab-block-right" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<div class="tab-block-wrapper">
					<h2>MENU HIGHLIGHTS</h2>
					<div class="tab-container menu-highlights-tab">
						
						<ul class="tabs">
						  <li class="active-tab">Highlight 1</li>
							<li>Highlight 2</li>
							<li>Highlight 3</li>
						</ul>
						
						<ul class="tabs-content">
							<li>
								<img src="<?php echo $this->getSkinUrl('images/menu-highlights-1.png') ?>"/>
								<h3 class="tabs-touch">Highlight 1</h3>
								<p>On a diet and can’t give up Mughlai? Fret not! With HealthCraft, Mughlai will be delicious and oil-free. Our professional chefs cook dishes like dal makhani, butter chicken, panner makhani, and others without any oil. We never compromise with your taste or waist.  </p>
							</li>
						  <li>
								<img src="<?php echo $this->getSkinUrl('images/menu-highlights-2.png') ?>"/>					  	
								<h3 class="tabs-touch">Highlight 2</h3>
								<p>We put a different and healthy spin on your ordinary Chinese food. At HealthCraft we never deep fry vegetables in your momos, noodles, or fried rice. Our Chinese food is made with freshest ingredients and no added color. Instead of maida, we use buckwheat and whole wheat noodles.</p>
							</li>
							<li>
								<img src="<?php echo $this->getSkinUrl('images/menu-highlights-3.png') ?>"/>
								<h3 class="tabs-touch">Highlight 3</h3>
								<p>Our meals are wholesome and filling. We offer multigrain rotis, that are fiber rich and low-cal. Meals also include a healthy portion of fresh salad with homemade low-cal dressing. To increase metabolism and gut health we provide probiotic foods like buttermilk, yogurt, kimchi, and others. </p>
							</li>
						</ul>
						
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
	<!-- Tab Block End -->
	
	<!-- Food Subscription Plan Start -->
	<div class="food-subscription-plan">
		
		<div class="food-subscription-plan-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">SELECT YOUR PLAN AND TIME</h2>
			
			<div class="food-subscription-plan-detail-wrapper"  data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Details -->
				<div class="food-subscription-plan-detail">
					<img src="<?php echo $this->getSkinUrl('images/food-subscription-plan-1.png') ?>"/>
					<div class="food-subscription-plan-detail-description">
						<h3><span>7 Days Trial </span><br>Weight Management and<br>Food Subscription Plan</h3>
						<h4>Features:</h4>
						<ul>
							<li>3 meals per day (breakfast, lunch, dinner)</li>
							<li>1,2000 calorie per day </li>
							<li>Precisely measured out single serve meals</li>
							<li>Arrives in a heat safe tray, which is easy to reheat </li>
							<li>Highest quality, locally sourced meals  </li>
							<li>Easy to cancel subscription </li>
						</ul>
					</div>
					<div class="food-subscription-plan-detail-price">
						<h3>Rs. 14,000 / 7 Days</h3>
						<a href="javascript:void" onclick="addItemToCart(2636)" class="button cta-food-subscription-plan-detail-price">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Details -->
				<div class="food-subscription-plan-detail">
					<img src="<?php echo $this->getSkinUrl('images/food-subscription-plan-2.png') ?>"/>
					<div class="food-subscription-plan-detail-description">
						<h3><span>30 Days Basic</span><br>Weight Management and <br>Food Subscription Plan</h3>
						<h4>Features:</h4>
						<ul>
							<li>3 meals per day (breakfast, lunch, dinner)</li>
							<li>1,2000 calorie per day </li>
<li>Precisely measured out single serve meals </li>
<li>Arrives in a heat safe tray, which is easy to reheat </li>
<li>Fresh meals are delivered daily at your doorstep</li>
<li>Highest quality, locally sourced meals </li>

						</ul>
					</div>
					<div class="food-subscription-plan-detail-price">
						<h3>Rs. 45,000 / 30 Days</h3>
						<a href="javascript:void" onclick="addItemToCart(2637)" class="button cta-food-subscription-plan-detail-price">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Details -->
				<div class="food-subscription-plan-detail">
					<img src="<?php echo $this->getSkinUrl('images/food-subscription-plan-3.png') ?>"/>
					<div class="food-subscription-plan-detail-description">
						<h3><span>90 Days Fast Track </span><br>Weight Management and <br>Food Subscription Plan</h3>
						<h4>Features:</h4>
						<ul>
							<li>3 meals per day (breakfast, lunch, dinner)</li>
<li>1,2000 calorie per day </li>
<li>Perfect for special occasions like weddings, engagement, or other events</li>
<li>Variety of meals to ensure you never get bored </li>
<li>Fresh meals are delivered daily at your doorstep</li>
<li>Highest quality, locally sourced meals </li>
<li>Lose XYZ weight in 90 days 
</li>
						</ul>
					</div>
					<div class="food-subscription-plan-detail-price">
						<h3>Rs. 125,000 / 90 Days</h3>
						<a href="javascript:void" onclick="addItemToCart(2638)" class="button cta-food-subscription-plan-detail-price">Choose this Meal Plan</a>
					</div>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- Food Subscription Plan End -->
	
	<!-- Impact Story Start -->
	<style>
		.food-subscription-impact-story {
			background-color: #99440F;
		}
		
		.food-subscription-impact-story h2 {
			color: #FF7129;
		}
		
		.food-subscription-impact-story h3, .food-subscription-impact-story p {
			color: #FFFFFF;
		}
		
		
		
		
	</style>
	<div class="impact-story food-subscription-impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<img src="<?php echo $this->getSkinUrl('images/impact-story-image-orange.png') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL MONIKA LOST 16 KG IN JUST 3 MONTHS BEFORE MARRIAGE</h2>
				<h3>Monika Singh, <span>26 Years, Student, New Delhi</span></h3>
				<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
				<div class="impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-1.png') ?>"/>
					</a>
					<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
					</a>
				</div>
				<h3>Create your own impact story with LifeHeal.</h3>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->