
	<!-- Hero Start -->
	<div class="home-hero">
	    
	    <!-- Banner -->
	    <div class="home-hero-banner">
	        <div class="home-hero-banner-container">
	        	
	        	<!-- Search -->
	        	<div class="home-hero-banner-search">
		            <div class="banner-search-text">
		                <h1>A LIFE HEALED<br><span>IS A LIFE LIVED BETTER.</span></h1>
		            </div>
		            <div class="banner-search-field">
		            	<form role="search" method="get" class="search-form" action="">
							<input type="search" class="search-field" placeholder="HOW CAN WE HEAL YOU?..." value="" name="s" title="" />
							<input type="button" class="search-submit" value="&#xf002" />
    					</form>
    					<div class="search-suggestion">
    						<ul>
    							<li><a href="<?php echo $this->getUrl('weight-loss') ?>" target="_blank">Reduce Weight</a></li>
						    <li><a href="<?php echo $this->getUrl('pre-marriage-glow')?>" target="_blank">Pre-Wedding Weight Loss</a></li>
								<li><a href="<?php echo $this->getUrl('gut-health')?>" target="_blank">Gut Health & Digestion</a></li>
								
								
    							<li><a href="<?php echo $this->getUrl('diabetes') ?>" target="_blank">Diabetes Reduction</a></li>
						   <li><a href="<?php echo $this->getUrl('gestational-diabetes')?>" target="_blank">Gestational Diabetes</a></li> 
								<li><a href="<?php echo $this->getUrl('pcod-pcos') ?>" target="_blank">PCOS/PCOD</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('heart-health')?>" target="_blank">Heart Health</a></li>
								<li><a href="<?php echo $this->getUrl('hypertension')?>" target="_blank">Blood Pressure</a></li>
								<li><a href="<?php echo $this->getUrl('hypothyroid')?>" target="_blank">Hypothyroid</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('liver-health')?>" target="_blank">Liver Disorders</a></li>
								<li><a href="<?php echo $this->getUrl('fertility')?>" target="_blank">Boost Infertility</a></li>
								<li><a href="<?php echo $this->getUrl('inflammation')?>" target="_blank">Inflammation Reduction</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('auto-immune')?>" target="_blank">Auto-Immune Disorders</a></li>	
    							<li><a href="<?php echo $this->getUrl('cancer-risk')?>" target="_blank">Reduce Cancer Risk</a></li>
    							
    							
    							
    							
    							
    							
								
    						</ul>
    					</div>
		            </div>
		        </div>
		        
		        <!-- Hero Image -->
		        <div class="home-hero-banner-image">
		           <img src="<?php echo $this->getSkinUrl('images/home-hero-banner.png') ?>"/>
		        </div>
		        
	        </div>
	    </div>
	    
	    <!-- CTA -->
	    <div class="home-hero-cta">
	    	<div class="home-hero-cta-container">
	    		<h2>Weight loss, disease remission, food plans – we’re right here for you.</h2>
	    		<a href="https://lifeheal.zohobookings.in/#/customer/healthreview" class="button cta-button" target="_blank">BOOK YOUR APPOINTMENT</a>
	    	</div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Home Carousel Start -->
	
	<div class="home-carousel">
		<div class="home-carousel-container">
			
			<!-- Carousel Start -->
			<div class="home-carousel-wrapper">
				
				<div class="home-carousel-detail">
					<div class="home-carousel-detail-wrapper">
						<h4>Start healing with our special offers.</h4>
						<h2 style="text-transform: uppercase">SAVE 50% ON OUR WEIGHT LOSS PLAN.
</h2>
						<p>Is losing weight always on your mind? Are you not sure where to begin? Get a head start with our Weight Loss Plan, created with our proven InHealth system. It’s easy to follow, comes with holistic benefits, and shows you how to keep off that weight for good. Hurry! Offer valid till XXXXX
</p>
						
						<a href="<?php echo $this->getUrl('weight-loss') ?>" class="button cta-home-carousel">CHOOSE PLAN</a>
					</div>
				</div>
				
				<div class="home-carousel-image" style="background-image:  url('<?php echo $this->getSkinUrl("images/home-carousel-image-1.png");?>')">
				</div>
				
			</div>
			<!-- Carousel End -->
			
			<!-- Carousel Start -->
			<div class="home-carousel-wrapper">
				
				<div class="home-carousel-detail">
					<div class="home-carousel-detail-wrapper">
						<h4>Start healing with our special offers.</h4>
						<h2 style="text-transform: uppercase">ATTEND OUR FREE WEBINAR ON NUTRITION.</h2>
						<p>There’s too much information on nutrition on the internet. But what’s right and what’s of real use? Attend our easy-to-understand webinar and get clear insights into nutrition, diabetes reversal, intermittent fasting, and more. The best part? It’s FREE just for you! Offer valid till XXXXX

</p>
						<a href="<?php echo $this->getUrl('webinar') ?>" class="button cta-home-carousel">REGISTER NOW</a>
					</div>
				</div>
				
				<div class="home-carousel-image" style="background-image: url('<?php echo $this->getSkinUrl("images/home-carousel-image-2.png");?>')">
				</div>
				
			</div>
			<!-- Carousel End -->
			
			<!-- Carousel Start -->
			<div class="home-carousel-wrapper">
				
				<div class="home-carousel-detail">
					<div class="home-carousel-detail-wrapper">
						<h4>Start healing with our special offers.</h4>
						<h2 style="text-transform:uppercase;">KNOW YOUR HEALTH INSIDE-OUT WITH A FREE REVIEW
</h2>
						<p>The key to good health starts with ‘knowing’ all about it. Get our FREE Health Review and discover what blood tests mean with our Inhealth Dashboard. Only when you know, you can take the next steps to live healthily. Hurry, only a few slots left!
</p>
						<a href="<?php echo $this->getUrl('customer/account/create/') ?>" class="button cta-home-carousel">REGISTER NOW
</a>
					</div>
				</div>
				
				<div class="home-carousel-image" style="background-image: url('<?php echo $this->getSkinUrl("images/home-carousel-image-3.png");?>')">
				</div>
				
			</div>
			<!-- Carousel End -->
			
		</div>
	</div>
	
	<!-- Home Carousel End -->
	
	<!-- Home Featured Items Start -->
	<div class="home-featured">
		<div class="home-featured-container">
			
			<div class="home-featured-left" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<div class="home-featured-wrapper">
					<h2>OUR WEIGHT LOSS AND DISEASE REMISSION PLANS</h2>
					 <img src="<?php echo $this->getSkinUrl('images/home-featured-image-1.png') ?>"/>
					<p>For us, your health is a top priority. Our team of experts has thoughtfully created diet plans that are scientifically proven to bring optimum results. Validated at leading medical conferences, our plans are focused on healing your body for long-lasting gains - topped with our expert health coaching and support at every step. </p>
					<a href="<?php echo $this->getUrl('weight-loss') ?>" class="button cta-home-featured-left">CHOOSE MEAL PLAN</a>
				</div>
			</div>
			
			<div class="home-featured-right" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<div class="home-featured-wrapper">
					<h2>OUR FOOD SUBSCRIPTION PLAN</h2>
					 <img src="<?php echo $this->getSkinUrl('images/home-featured-image-2.png') ?>"/>
					<p>Food heals like no other, but the right food, in the right portions! With our customized meal subscription plans, we bring delicious meals put together by our nutrition and culinary experts, right to your doorstep. What’s more, your body’s healing is tracked via blood tests and regular reviews.</p>
					<a href="<?php echo $this->getUrl('foodmealplan') ?>" class="button cta-home-featured-right">CHOOSE FOOD SUBSCRIPTION</a>
				</div>
			</div>
			
		</div>
	</div>
	
	<!-- Home Featured Items End -->
	
	
	<!-- Home Meal Plans Start -->
	<div class="home-meal-plans">
		<div class="home-meal-plans-container">
			
			<div class="home-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>OTHER MEAL PLANS</h2>
			</div>
			
			<div class="home-meal-plans-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Diabetes Reversal Plans</h3>
						<p>Low-sugar meals with the perfect balance of carbohydrates, healthy fats, and protein to keep your Diabetes in check. </p>
						<a href="<?php echo $this->getUrl('diabetes') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Heart Care Meal Plans</h3>
						<p>Arterial plaque reversing meals with a bounty of nuts, seeds, and fiber-rich foods, just perfect for people with heart ailments.    </p>
						<a href="<?php echo $this->getUrl('heart-health') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Liver Health Plans</h3>
						<p>Mood-boosting meals with the right combo of antioxidants, beta-carotene, and protein.</p>
						<a href="<?php echo $this->getUrl('liver-health') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
						
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Thyroid Control</h3>
						<p>Nutrient rich meals with abundant iodine, selenium, and zinc to combat fatigue and weight gain caused by hypothyroidism. </p>
						<a href="<?php echo $this->getUrl('hypothyroid') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<?php /*<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Muscle Gain</h3>
						<p>Arterial plaque reversing meals with a bounty of nuts, seeds, and fiber-rich foods, just perfect for people with heart ailments.    </p>
						<a href="<?php echo $this->getUrl('muscle-gain') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>*/?>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Pregnancy Diabetes</h3>
						<p>Nutrient-rich meals comprising green leafy vegetables, fortified cereals, beans, and nuts that increase your fertility and control sugar. </p>
						<a href="<?php echo $this->getUrl('fertility') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>PCOD meals</h3>
						<p>Sumptuous low carb, high Vitamin D, Vitamin B, Iodine, and Magnesium meals that reduce weight and PCOD symptoms</p>
						<a href="<?php echo $this->getUrl('pcod-pcos') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Pre-Marriage Weight Loss</h3>
						<p>Holistic weight loss plans that helps reduce 10, 20 and even 30 kgs to usher in the big day.</p>
						<a href="<?php echo $this->getUrl('pre-marriage-glow') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
			
			</div>
			
		</div>
	</div>
	<!-- Home Meal Plans End -->
	
	
	<!-- Home Meet Expert Start -->
	<div class="home-meet-expert">
		
		<div class="home-meet-expert-container">
			
			<div class="home-meet-expert-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h2>MEET JUNIOR ANAND GUPTA<br><span>FOUNDER, COACH, CEO - LIFEHEAL</span></h2>
				<p>“Food is the greatest healer. We are just the medium.”</p>
				<p>Junior A. Gupta is the life force behind LifeHeal. With degrees from Babson and MIT in the USA, he has many years of experience in business and philanthropy. An influential activist, a receiver of APJ Abdul Kalam’s ‘Goodness Award’, and a TEDx speaker, over the years he has been changing lives with his visionary initiatives.</p>

<p>LifeHeal was born from his personal tryst with diabetes. He comes from a family with a history of this disease and was always intrigued by the commonly accepted perception that diabetes was genetic and irreversible. After years of research and consultation with medical experts, he discovered that well-balanced diets and lifestyle changes can control diabetes effectively.</p>
<p>He founded LifeHeal in 2018, and ever since, has helped thousands of people live better, happier, and healthier lives
</p>
				<a href="<?php echo $this->getUrl('aboutus') ?>" class="button cta-home-meet-expert">KNOW MORE</a>
			</div>
			<div class="home-meet-expert-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				 <img src="<?php echo $this->getSkinUrl('images/home-expert-jr.png') ?>"/>
			</div>
			
		</div>
		
	</div>
	<!-- Home Meet Expert End -->
	
	
	
	<!-- Home Why Choose Us Start -->
	<div class="home-why-choose-us">
		
		<div class="home-why-choose-us-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHY LIFEHEAL</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Everything we do at LifeHeal is centred around you. We understand your needs, your health goals and create plans that suit your lifestyle the best. We go beyond weight and focus on holistic health measures to strike at the root of every problem. Most importantly, we are guided by a strong sense of belief in the power of science.</p>
			
			
			<div class="home-why-choose-us-details-wrapper">
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-1.png') ?>"/>
					<h3>Nutritionist approved meals</h3>
					<p>Good nutrition is driven by science. We have the approval of India’s top doctors and nutritionists while creating the most nutritious and results-driven meals for you. No compromises, there!</p>
				</div>
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-2.png') ?>"/>
					<h3>Lifelong Journey</h3>
					<p>With LifeHeal, our care and support don’t begin or end with meal plans or just weight loss. We focus on stress, sleep, healthy habits, and lifestyle changes to help you fight obesity and stay healthy in the long run.</p>
				</div>
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-3.png') ?>"/>
					<h3>Balanced Nutrition</h3>
					<p>We take a wholesome approach to nutrition focusing on micronutrients, macronutrients, and phytochemicals. Our meals are packed with goodness and incorporates everything in the right measure.
</p>
				</div>
				
			</div>
			
		</div>
		
	</div>
	
	<!-- Home Why Choose Us End -->
	
	
	<!-- Home Stats Start -->
	
	<div class="home-stats">
		<div class="home-stats-container">
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">50</span>+</h2>
				<p>Meals <br>Served</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">100</span>%</h2>
				<p>Goal-driven</p>
			</div>
		</div>
	</div>
	
	<!-- Home Stats End -->
	<!-- Home Impact Story Start -->
	<div class="home-impact-story">
		<div class="home-impact-story-container">
			
			<div class="home-impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-image.png') ?>"/>
			</div>
			<div class="home-impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4><strong>THE LIFEHEAL IMPACT</strong></h4>
				<h4>STORIES THAT INSPIRE</h4>
				<h2>"I lost 16 kgs in 3 months with LifeHeal before my wedding."</h2>
				<h3>-Monica Singh</h3>
				<p>“Losing weight was my Mt. Everest. I had to conquer it before the biggest day of my life. I had to fit into my dream lehenga. Thanks to LifeHeal’s Diet Plan, constant coaching and motivation, I lost 16 kgs, and looked just ‘wow’ on my D-day!”</p>
				<div class="home-impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
						 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-1.png') ?>"/>
					</a>
					<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-2.png') ?>"/>
					</a>
				</div>
				<h3>Create your impact story with LifeHeal</h3>
				<a href="<?php echo $this->getUrl('weight-loss')?>" class="button cta-home-impact-story">CHOOSE MEAL PLAN</a>
			</div>
			
		</div>
	</div>
	
	<!-- Home Impact Story End -->
	
	<!-- Home Testimonials Start -->
	
	<div class="home-testimonials">
		<div class="home-testimonials-container">
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS FOR LIFEHEAL</h2>
			
			<div class="home-testimonials-videos" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-1.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-2.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-1.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-2.png') ?>"/>
				</a>
			
			</div>
		</div>
	</div>
	
	<!-- Home Testimonials End -->
	
	
	<!-- Home Contact Start -->
	
	<div class="home-contact">
		<div class="home-contact-container">
			<div class="home-contact-title">
				 <img src="<?php echo $this->getSkinUrl('images/home-contact-title-image.png') ?>"/>
				<h2>LET’S BEGIN YOUR HEALING.</h2>
			</div>
		</div>
	</div>
	
	<div class="home-contact-form-wrapper">
		<div class="home-contact-form-container">
			<div class="home-contact-form-left" style="background-image: url('<?php echo $this->getSkinUrl("images/home-contact-form.png");?>')"></div>
			<div class="home-contact-form-right">
				<h3>CONNECT WITH US TODAY!</h3>
				<p>If you have a query or wish to share any feedback, we are all ears. Our LifeHealers will get back to you within 3 business days. Stay happy, stay healthy!</p>
				<span id="thanksMsg" style="color:red"></span>
				<form action="" method="POST" id="home-contact-form">
					<input type="text" id="name" name="name" placeholder="*Your Name" required>
					<input type="email" id="email" name="email" placeholder="*Your Email" required>
					<textarea name="message" id="message" rows="4" placeholder="*Your message..." required></textarea>
					<input type="button" value="SUBMIT" onclick="sendEmail()">
				</form>
			</div>
		</div>
	</div>
	<script type="text/javascript">
  
function sendEmail()
	{  
		
		var name = jQuery("#name").val();
		var fromEmail = jQuery("#email").val();
		var message = jQuery("#message").val();
		
		//alert(orderDate);
		if(name!='' && fromEmail!='' && message!='')
		{
		
			jQuery.ajax({
						url: "<?php echo Mage::getBaseUrl().'checkout/cart/sendemail' ?>",
						type: "POST",
						data: {
						 name: name,
						 email:fromEmail,
						 message:message
						},
						  success: function(response)
						 {  
							
								//var msg="Thank you for contacting us.";
								jQuery("#thanksMsg").html(response);
							    jQuery("#thanksMsg").show("slow").delay(3000).hide("slow");
							
								jQuery("#name").val('');
								jQuery("#email").val('');
								jQuery("#message").val('');
						 }
			});
		}
		else
		{
				var msg="Please fill the required fields.";
				jQuery("#thanksMsg").html(msg);
				 jQuery("#thanksMsg").show("slow").delay(5000).hide("slow");
		}
	}
</script>
	
	<!-- Home Contact End -->
	
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
