<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>How Reliable Is It?</b>
            </div>
            <div class="easypara">
            <p>Our program is completely based on food. And food is very reliable. We are seeing visible 
and measurable results in 99% of clients with no side effects and lots of other positive effects 
such as: </p>
<p>Simple, we take care of all the work, the planning and of course the scientific research to give you 
daily therapeutic meals.
</p>
            <ul>
            <li> Increased Sensitivity in Feet

            </li>
            <li>
          Weight Loss
            </li>
            <li>Decreased Sleep Apnea
</li>
<li>Increased Energy and much more....
</li>
            </ul>
            <p>We are sure we will see an improvement in every client as our program is backed by over 30 years 
experience from one of the world's leading diabetes reversal doctors, Dr. Joel Fuhrman.</p>
            </div>
            </div>
            </section>