<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/shop-plans.css" type="text/css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<style>
		.list-inline > li#diabetes{font-weight:600;}
		.list-inline > li#weightloss{font-weight:500;}
		.list-inline > li#silver{font-weight:500;}
		.list-inline > li#gold{font-weight:500;}
		.list-inline > li#body-reboot{font-weight:500;}
	.navbar-light .navbar-nav #nav-view-plan {
    background: rgb(26, 204, 205);
    color: #fff !important;
}
* {
  box-sizing: border-box;
}
	.startingheight{height: 70px;
margin-top: 10% !important;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 17.5%;
text-align: center;
margin-top: 7.2%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;}
	.btn{font-weight:600; font-size:1.2em;}
.digitalbox {height:650px;}
	.analysis{height:520px}
@media only screen and (max-width: 600px) {
	.starting{margin-top: 12%;}
  .columnsplan {
    width: 100%;
  }
	.digitalbox {height:auto;}
	.analysis{height:auto;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 87%;
text-align: center;
margin-top:27%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;
background: #fff;}
}
	@media screen and (min-width:768px) and (max-width:991px)
	{
		.startingheight {
    height: 100px;margin-top: 40% !important;
}
		.columnspanh2 {
    font-size: 20px;
position: absolute;
width: 17.5%;
text-align: center;
margin-top: 14%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;
}
		.digitalbox {height:750px;}
	.analysis{height:600px}
		
	}
	@media screen and (min-width:800px) and (max-width:1200px)
	{
		.startingheight {
    height:140px;
}
		.priceplan h2 span{
   width: 100%;
float: left;
}
		.priceplan h2{
   font-size: 1.3em;

}
		.columnsplan {
    float: left;
    width: 20%;
    padding: 4px;
}
		.columnspanh2 {
font-size: 18px;
position: absolute;
width: 17.5%;
text-align: center;
margin-top: 9.8%;
color: red;
line-height: 15px;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;
}
	.digitalbox {height:650px;}
	.analysis{height:600px}
	}
</style>
<nav class="main-navigation">
			<ul class="plans-sub-nav-dt list-inline">
<li id="body-reboot"><a href="<?php echo Mage::getBaseUrl();?>plans" class="text-white text-center">Weight Loss</a></li>
<li id="body-reboot"><a href="<?php echo Mage::getBaseUrl();?>diabetes" class="text-white text-center">Diabetes</a></li>
<li id="silver"><a href="<?php echo Mage::getBaseUrl();?>thyroid" class="text-white text-center">Thyroid</a></li>
<li id="gold"><a href="<?php echo Mage::getBaseUrl();?>pcod" class="text-white text-center">PCOD</a></li>
<li id="diabetes"><a href="<?php echo Mage::getBaseUrl();?>stayfit" class="text-white text-center">Stay Fit</a></li>
</ul>
	</nav>
<div class="southbeach shop-plans hero-bg"  id="top-cards">
		
<div class="container-fluid">
<h1 class="h2 text-center text-sentence fw-600 bot-mar-0">Choose the Immunity Boosting Plan That’s Best for You</h1>
	<h2 class="h4 text-center text-sentence fw-400">Our Immunity Boosting Programs Helps Prevent Chronic Diseases and
Aims to Keep you Healthy </h2>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-xs">
	<div class="col-xs-12 col-md-10"><h3 class="text-center text-sentence fw-600" style="font-size: 1.625em;">Digital</h3></div>
	<div class="col-xs-12 col-md-2"><h3 class="text-center text-sentence fw-600" style="font-size: 1.625em;">Home Delivered</h3></div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-md hidden-sm hidden-xl hidden-lg">
	<div class="col-xs-12 col-md-10"><h3 class="text-center text-sentence fw-600" style="font-size: 1.625em;">Digital</h3></div>	
	</div>
		<div class="columnsplan">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/metabolic.png') ?>" style="width: 50px;margin: auto;"/>Immunity Analysis</li>
	    <li><h2 style="">Rs 3,000</h2></li>  
    <li class="greyplan"><a href="#" class="buttonplan" onclick="addtocartAndWelcome('1998')">Buy Now</a></li>
	   <ul class="list-checkedplan">
    <li>Personalized Immunity Assessment</li>
    <li>Understanding How COVID Specifically Affects You and Mitigation Strategies</li>
    <li>Personalized Health Risks Assessment</li>
    <li>Review of Natural Supplements to Boost Immunity </li>
    <li>Customized Top 5 Key Points of Immunity </li>
	<li>1 Month Subscription to Training Videos</li>
    </ul>
  </ul>
</div>
	<div class="columnsplan">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/metabolic.png') ?>" style="width: 50px;margin: auto;"/>Metabolic Analysis</li>
	    <li><h2>Rs 3,000</h2></li>  
    <li class="greyplan"><a href="#" class="buttonplan" onclick="addtocartAndWelcome('1990')">Buy Now</a></li>
	   <ul class="list-checkedplan">
		    <li>Proprietary Review of Your Metabolic Health 
     (Requires Blood Test Data)</li>
    <li>Personalized Risk Factors Assessment</li>
    <li>Major Organ Health Assessment</li>
    <li>Understanding How COVID Specifically Affects You and Mitigation Strategies</li>
    <li>Customized Action Plan for Metabolic Health</li>
    <li>1 Month Subscription to Training Videos</li>
   
    </ul>
  </ul>
</div>
	<div class="columnsplan">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Menu.png') ?>" style="width: 50px;margin: auto;"/>
		"Lean & Fit"
Consulting</li>
	 <li class="starting" style="margin:0px;"><h3 style="margin: 3px 0px 0px 0px !important;font-size: 1.4em;font-weight: 400;">Individual</h3><h2 style="margin:0px;"><span style="color:red;text-decoration:line-through;margin-right:5px;"><span style="color:black">Rs 6,000 / mo </span></span>Rs 4,000 / Mo</h2></li>
	   <li class="starting" style="margin:0px;"><h3 style="margin: 10px 0px 0px 0px !important;font-size: 1.4em;font-weight: 400;">Family</h3><h2 style="margin:0px;"><span style="color:red;text-decoration:line-through;margin-right:5px;"><span style="color:black">Rs 10,000 / mo </span></span>Rs 6,000 / Mo</h2></li>
   <li class="greyplan"><a href="lean-consulting" class="buttonplan">Select</a></li>
       <ul class="list-checkedplan">
   <li>Includes Immunity Assessment</li>
    <li>Twice a Week Calls with Dedicated Nutritionist</li>   
    <li>Training on Intermittent Fasting Included</li>
    <li>Secret Recipes from our Metabolic Kitchen</li>
    <li>Guided Video Education Package Included</li>
    </ul>
  </ul>
</div>
	
	
		<div class="columnsplan">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Menu.png') ?>" style="width: 50px;margin: auto;"/>
		"Deep Insight"
Consulting</li>
	   <li class="starting" style="margin:0px;"><h3 style="margin: 3px 0px 0px 0px !important;font-size: 1.4em;font-weight: 400;">Individual</h3><h2 style="margin:0px;"><span style="color:red;text-decoration:line-through;margin-right:5px;"><span style="color:black">Rs 6,000 / mo </span></span>Rs 4,000 / Mo</h2></li>
	   <li class="starting" style="margin:0px;"><h3 style="margin: 10px 0px 0px 0px !important;font-size: 1.4em;font-weight: 400;">Family</h3><h2 style="margin:0px;"><span style="color:red;text-decoration:line-through;margin-right:5px;"><span style="color:black">Rs 10,000 / mo </span></span>Rs 6,000 / Mo</h2></li>
   <li class="greyplan"><a href="consulting" class="buttonplan">Select</a></li>
       <ul class="list-checkedplan">
   <li>Includes Metabolic Analysis</li>
    <li>Requires Glucometer or CGM</li>
    <li>Includes Personalized Deep Insight Metabolic Profile</li>
    <li>Twice a Week Calls with Dedicated Nutritionist</li>
    <li>Training on Intermittent Fasting Included</li>
    <li>Secret Recipes from our Metabolic Kitchen</li>
    <li>Guided Video Education Package Included</li>
    </ul>
  </ul>
</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-md hidden-sm hidden-xl hidden-lg">
	<div class="col-xs-12 col-md-7"><h3 class="text-center text-sentence fw-600" style="font-size: 1.625em;">Home Delivered</h3></div>
	</div>
	
		<div class="columnsplan" style="display:none;">
			<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Basic.jpg') ?>" style="width: 50px;margin: auto;"/>Silver
Plan</li>
	  <li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs400 / Day </span></span><br>Rs 300 / Day</h2></li>  
	  <li class="greyplan"><a href="weightlosesilverplan" class="buttonplan">View Menu</a></li>
     <ul class="list-checkedplan">
      <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>1 Oil Free Salad Dressing and 2 Soups a day</li>
    </ul>
  </ul>
</div>
	<div class="columnsplan" style="display:none;">
		<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox"  style="pointer-events: none;opacity: 0.4;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/popular.png') ?>" style="width: 50px;margin: auto;"/>Gold Plan</li>
	<li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs700 / Day </span></span><br>Rs 600 / Day</h2></li> 
	<li class="greyplan"><a href="weightlosegoldplan" class="buttonplan">View Menu</a></li>
      <ul class="list-checkedplan">
     <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>Includes Pro Biotics</li>
    <li>2 Meals a day</li>
    </ul>
    
  </ul>
</div>

	<div class="columnsplan">
	<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
		<p class="plan-callout bg-gray-darker text-white text-uppercase"  style="pointer-events: none;opacity: 0.4;">Top Rated</p>
  <ul class="priceplan analysis"  style="pointer-events: none;opacity: 0.4;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Premium.png') ?>" style="width: 50px;margin: auto;"/>Diamond Plan</li>
	  <li class="starting startingheight" style="margin:0px;"><h3 style="margin: 3px 0px 0px 0px !important;font-size: 1.4em;font-weight: 400;">Starting at</h3><h2 style="margin:0px;"><span style="color:red;text-decoration:line-through;margin-right:5px;"><span style="color:black">Rs 1,200 / Day </span></span>Rs 1,100 / Day</h2></li>
	  
    <li class="greyplan"><a href="weightlosediamondplan" class="buttonplan">View Menu</a></li>
      <ul class="list-checkedplan">
		  <li>Can Lose 2 kgs in 10 days</li>
     <li>Includes Deep Insight Consulting</li>
    <li>Customized, Oil Free Food</li>
    <li>Dedicated Nutritionist</li>
    <li>Includes Pro-Biotics</li>
    <li>4 Meals a Day</li>
    </ul>
  </ul>
</div>
	


	</div>
		<div class="bg-white">
  <div class="container">
    <div class="row below-plan-sect">
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <h3 class="h4 text-secondary fw-600">With All Of Our Plans You'll :</h3>
        <ul class="list-checked pink-bullet">
          <li class="h6 fw-300">Lose weight and learn how to keep it off</li>
          <li class="h6 fw-300">Get A Dedicated Nutritionist</li>
          <li class="h6 fw-300">Pro Biotic Options for Gut Health</li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-5 col-lg-5">
        <hr class="visible-xs">
        <h3 class="h5 text-primary text-uppercase fw-600">Safe &amp; Healthy Weight Loss</h3>
        <ul class="list-checked blue-check">
          <li class="h6 fw-300">Keto-friendly options</li>
          <li class="h6 fw-300">Vegan, whole foods diet</li>
          <li class="h6 fw-300">No artificial sugars or sweeteners</li>
        </ul>
      
      </div>
    </div>
  </div>
</div>
	<div class="closer bg-secondary">
  <div class="container ">
    <div class="row ">
      <div class="center-block no-float text-white col-xs-12 ">
        <div class="row ">
          <div class="text-wrapper col-xs-12 col-sm-6 col-md-4 col-md-offset-2">
            <h2 class="h3 text-white ">Get Healthier Today
</h2>
          </div>
          <div class="button-wrapper col-xs-12 col-sm-4 col-md-3" id="top"> <a href="#top-cards" class="btn btn-default scroll-to bg-white">Get It Now</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>
	</div>
<script>
	// Select all »a« elements with a parent class »links« and add a function that is executed on click
jQuery( '#top a' ).on( 'click', function(e){
	
  // Define variable of the clicked »a« element (»this«) and get its href value.
  var href = jQuery(this).attr( 'href' );
  
  // Run a scroll animation to the position of the element which has the same id like the href value.
  jQuery( 'html, body' ).animate({
		scrollTop: jQuery( href ).offset().top
  }, '300' );
	
  // Prevent the browser from showing the attribute name of the clicked link in the address bar
  e.preventDefault();

});
</script>