<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>Is The Cure Permanent?</b>
            </div>
            <div class="easypara">
            <p>If you return to a non-diabetic state it means you are non diabetic. It means your body is able to 
control your sugar levels, and keep them within 70 - 140 range like a non-diabetic person.
</p>
<p>However if you return to doing the things which made you diabetic before, you will likely return to 
being diabetic again.

</p>
    <p>We will make you healthy and teach you how to stay healthy. The rest will depend on you.</p>       
           
            </div>
            </div>
            </section>