
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


	<style>
		.col1-layout{margin-top:7rem;}
		html {
    font-size: inherit !important;
}
		body {
    font-family: 'Open Sans', sans-serif;
    color: #4B4B4B;
    text-align: left;
    font-weight: 500;
    font-size:14px;
}
		
		.panel-info {
    border-color: #bce8f1;
    width: 100%;
    float: left;
}
		.panel-info .table>tbody>tr>td, .panel-info .table>tbody>tr>th, .panel-info .table>tfoot>tr>td, .panel-info .table>tfoot>tr>th, .panel-info .table>thead>tr>td, .panel-info .table>thead>tr>th {padding:0px 15px;}
		
		.panel-info > .panel-heading{color:#0EB58F;font-weight:bold;font-size:24px;}
		.panel-footer{background:#fff;text-align:center;}
		.panel-info h3{text-align:left; color:#0EB58F;font-weight:bold;}
		.panel-info h4{text-align:left; color:#144F5A;font-weight:bold;} 
		.table > thead > tr > th {
    vertical-align: bottom;
    border-bottom: 2px solid #0EB58F;
		}
		 h2 {
    font-size: 34px;
    font-weight: bold;
    color: #144F5A;
}
		.panel-footer {
    background: #fff;
    text-align: center;
}
		.table-responsive{width:100%;}.experiencethediff{color:#bce8f1;font-weight:500; font-size:16px;}
		.table{border:0px solid #0EB58F;margin-bottom:0px;}th{color:#0EB58F; font-weight:600;}

</style>
		<div class="container-fluid">
	<div class="container">
		<div class="experiencethediff"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">Experience the difference</div></div>
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
		<h2>Hello, Kersy Chindhy<br>Here’s your Healthy Menu</h2></div>
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6"><p style="margin-top: 12%;font-weight:bold;position: relative;display: block;text-align: right;">Report Generation Date: 27 April 2021</p></div>
	<div class="panel panel-info">
  <!-- Default panel contents -->
 
  <div class="panel-body">
    <p>Mob: 9881138124</p>
    <p>Add: Califonia Housing Society Bldg E Flat 401 NIBM, Pune</p>
	 
  </div>
</div>
	

  <!-- Table -->
	<div class="table-responsive">    
		<h2 style="color:#144F5A; font-size:24px;font-weight: bold;">Nutrition Intake</h2>
  <table class="table" style="margin-bottom:20px;">
    <thead>
      <tr>
            <th style="font-weight:normal">Date</th>
       
        <th style="font-weight:normal">Calories</th>
        <th style="font-weight:normal">Carbs(Gm)</th>
		   <th style="font-weight:normal">Fat(Gm)</th>
		   <th style="font-weight:normal">Protien(Gm)</th>
		   <th style="font-weight:normal">Fiber(Gm)</th>
      </tr>
    </thead>
    <tbody>
     
       <tr>
        <td>04-05-21</td>
        <td>1151</td>        
        <td>50</td>
        <td>14</td>
	    <td>189</td>
		<td>144</td>
      </tr>
       <tr>
        <td>04-05-21</td>
        <td>1151</td>        
        <td>50</td>
        <td>14</td>
	    <td>189</td>
		<td>144</td>
      </tr>
		 <tr>
        <td>04-05-21</td>
        <td>1151</td>        
        <td>50</td>
        <td>14</td>
	    <td>189</td>
		<td>144</td>
      </tr>
		 <tr>
        <td>04-05-21</td>
        <td>1151</td>        
        <td>50</td>
        <td>14</td>
	    <td>189</td>
		<td>144</td>
      </tr>
	
    </tbody>
  </table>
  </div>
		<!-- Pie chart panel contents -->
		<br>
		<br>
		<div style="height:100px;width:100%;float:left;"></div>
		<div class="panel panel-info">
  <!-- Default panel contents -->
 
  <div class="panel-body">
	  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
	  <h4>Your Macro-nutrients Chart for the period</h4>
		  <h4 style="color:darkgrey">04-05-2021 to 07-05-2021</h4>
		   <img src="<?php echo $this->getSkinUrl('images/piechart2.png') ?>"/>
	  </div>
	  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6"> <img src="<?php echo $this->getSkinUrl('images/piechart.png') ?>"/></div>
			</div>
		</div>
		<div class="panel panel-info">
  <div class="panel-body">
	  <table class="table">
    <thead>
      <tr>
            <th style="font-weight:normal"></th>
       
        <th style="font-weight:normal"><h4>CALORIES</h4></th>
        <th style="font-weight:normal"><h4>CARBS(Gm)</h4></th>
		   <th style="font-weight:normal"><h4>FAT(Gm)</h4></th>
		   <th style="font-weight:normal"><h4>PROTIEN(Gm)</h4></th>
		   <th style="font-weight:normal"><h4>FIBER(Gm)</h4></th>
      </tr>
    </thead>
    <tbody>
     
       <tr>
        <td><h4>REPORT<br>TOTAL</h4></td>
        <td><h3>1151</h3></td>        
        <td><h3>50</h3></td>
        <td><h3>14</h3></td>
	    <td><h3>189</h3></td>
		<td><h3>144</h3></td>
      </tr>
		 <tr>
        <td style="border:0px;"><h4>AVERAGE DAILY<br>INTAKE</h4></td>
        <td style="border:0px;"><h3>1151</h3></td>        
        <td style="border:0px;"><h3>50</h3></td>
        <td style="border:0px;"><h3>14</h3></td>
	    <td style="border:0px;"><h3>189</h3></td>
		<td style="border:0px;"><h3>144</h3></td>
      </tr>
		  </tbody>
		</table>
			</div>
  <div class="panel-footer">
	  This meal plan helps you control your weight and obesity in managed eating habits, giving you desired calories
	  </div>
</div>
		
		
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
			
		<img src="http://lifeheal.americanarearugs.com/skin/frontend/rwd/default/images/logo.png"/>
		</div>
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
			<img src="http://lifeheal.americanarearugs.com/skin/frontend/rwd/default/images/healthcraft.png" style="float:right"/>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
		<hr>
		<p><a href="www.lifeheal.in" style="color: #0EB58F;">www.LifeHeal.in</a></p>
<p>For queries email us at <a href="mailto:MyMenu@LifeHeal" style="color: #0EB58F;">MyMenu@LifeHeal</a>.in or call us at <a href="tel:+1800 180 2323 / +91 9876 5432 10" style="color: #0EB58F;">+1800 180 2323 / +91 9876 5432 10</a>
</p>
		<p>For delivery status and tracking please contact HealthCraft Support Helpline <a href="telto:+91 1234567890" style="color: #0EB58F;">+91 1234567890</a></p>
		</div>
			</div>
		</div>
	</div>	
