
	<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.meal-plan {
				background-image: url('<?php echo $this->getSkinUrl("images/meal-plan-hero-banner.png")?>');
			
			@media only screen and (max-width: 768px) {
				.meal-plan {
					background-image: url('<?php echo $this->getSkinUrl("images/meal-plan-hero-banner-mobile.png")?>');
				
				}	
			}
			
			.meal-plan h1 {
				color: #FFFFFF;
			}
			
			.meal-plan h1 span {
				color: #FFC23B;
			}
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner meal-plan">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1><span>MEAL PLANS AND COACHING</span><br>Lose up to 10 kgs<br>in your first 30 days!</h1>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- How it Works Start -->
	<style>
		.meal-plan-how-it-works h2, .meal-plan-how-it-works h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works meal-plan-how-it-works">
		
		<div class="how-it-works-container">
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Body Analysis</h3>
					<p>Get LifeHeal’s proprietary blood test analysis to discover the real reason behind your roadblocks to a healthier life. Plus, our InHealth<sup style="font-size:4px;top: -10px;"><b>TM</b></sup> system allows you to see your body analysis at your fingertips.
						</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					
					<h4>STEP 2</h4>
					<h3>Counselling</h3>
					<p>Through our inspiring counselling session, you get macroscopic understanding of your family history and lifestyle challenges that are blocking your progress. You also learn about the root causes blocking your progress. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Your Custom Plan</h3>
					<p>Your personal plan will use a 360<span>&deg;</span> approach to health. Your sleep, stress, and eating patterns will improve. Your plans will start simple and then intensify based on your goal. </p>
				</div>
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Personal Motivator</h3>
					<p>During the personal follow ups, we motivate, inspire, and nudge you to make better food choices. Get weekly check-ups to ensure you’re staying on track </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Awesome Habits</h3>
					<p>As your health improves, your plans will be adapted to your need. Best of all, you learn new secrets that’ll help maintain your health forever. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 6</h4>
					<h3>Medical Review</h3>
					<p>Lab tests will track the root causes of your health problems. Our InHealth system makes it easy to track everything. You will finally be able to achieve a healthy life and maintain it. </p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->
	
	<!-- Feature Meal Plans Start -->
	<style>
	
		.featured-meal-plans {
			background-color: #FFF9E5;
		}
		
		.featured-meal-plans .single-meal-plans-title h2 {
			color: #0EB58F;
		}
		
		.featured-meal-plans .single-meal-plans-title p {
			color: #4B4B4B;
		}
		
	</style>
	<div class="single-meal-plans featured-meal-plans">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>WEIGHT MANAGEMENT <br>MEAL PLANS</h2>
				<p>Plans specially curated around your lifestyle, stress, sleep, and eating patterns. These customized plans aim to help you lose weight and feel more confident. </p>
			</div>
			
			<div class="single-meal-plans-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Weight Management Meal Plan</h3>
						<h2>Rs. 8,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2642)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Weight Management Meal Plan</h3>
						<h2>Rs. 6,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2643)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
					<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Weight Management Meal Plan</h3>
						<h2>Rs. 5,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2644)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Weight Management Meal Plan</h3>
						<h2>Rs. 4,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2645)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	
	<!-- Feature Meal Plans End -->
	
	<!--All Meal Plans Start -->
	<style>
	
		.all-meal-plans {
			background-color: #FFF9E5;
		}
		
		.all-meal-plans .single-meal-plans-title h2 {
			color: #0EB58F;
		}
		
		.all-meal-plans .single-meal-plans-title p {
			color: #4B4B4B;
		}
		
	</style>
	<div class="single-meal-plans all-meal-plans">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>OTHER MEAL PLANS FOR <br>BETTER HEALTH</h2>
				<p>Did you know that better health is a combination of food and lifestyle choices? The holistic plans improve your overall health and help reverse several diseases. </p>
			</div>
			
			<div class="single-meal-plans-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
						
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Diabetes Reversal Plans</h3>
						<p>Low-sugar meals with the perfect balance of carbohydrates, healthy fats, and protein to keep your Diabetes in check. </p>
						<a href="<?php echo $this->getUrl('diabetes') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
						
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Heart Care Meal Plans</h3>
						<p>Arterial plaque reversing meals with a bounty of nuts, seeds, and fiber-rich foods, just perfect for people with heart ailments.</p>
						<a href="<?php echo $this->getUrl('heart-health') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Liver Health Plans</h3>
						<p>Mood-boosting meals with the right combo of antioxidants, beta-carotene, and protein</p>
						<a href="<?php echo $this->getUrl('liver-health') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Thyroid Control</h3>
						<p>Nutrient-rich meals with abundant iodine, selenium, and zinc to combat fatigue and weight gain caused by hypothyroidism. </p>
						<a href="<?php echo $this->getUrl('hypothyroid') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Pregnancy Diabetes</h3>
						<p>Nutrient-rich meals comprising green leafy vegetables, fortified cereals, beans, and nuts that increase your fertility and control sugar. </p>
						<a href="<?php echo $this->getUrl('fertility') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>PCOD Meals</h3>
						<p>Sumptuous low carb, high Vitamin D, Vitamin B, Iodine, and Magnesium meals reduce weight and PCOD symptoms. </p>
						<a href="<?php echo $this->getUrl('pcod-pcos') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
					
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Pre-Marriage Weight Loss</h3>
						<p>Holistic weight loss plans that help reduce 10, 20, and even 30 kgs to usher in the big day.</p>
						<a href="<?php echo $this->getUrl('pre-marriage-glow') ?>" class="button cta-single-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- All Meal Plans End -->
	
	<!-- Meet Expert Start -->
	<style>
		.meal-plan-meet-expert {
			background-color: #B26E00;
		}
		
		.meal-plan-meet-expert h2{
			color: #FFC23B;
		}
		
		.cta-meet-expert-plan {
			background-color:#FFC23B;
		}
	</style>
	<div class="meet-expert meal-plan-meet-expert">
		
		<div class="meet-expert-container">
			
			<div class="meet-expert-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h2>GET 1 TO 1 EXPERT COACHING</h2>
				<p>At LifeHeal, we understand that everyone is different. The coaching sessions will motivate and push you to make healthier choices. Feeling tempted to eat those rasgullas? Just shoot a text to our coach and make the right choice. </p>
				
				<div class="meet-expert-plans-container">
					<div class="meet-expert-plan">
						<h4>Expert Coaching with Junior<br> for 3 Months</h4>
						<h3>Rs. 150,000</h3>
						<a  href="javascript:vpod(0)"  onclick="addItemToCart(2640)" class="button cta-meet-expert-plan">BOOK FOR 3 MONTHS</a>
					</div>
					
					<div class="meet-expert-plan">
						<h4>Expert Coaching with Junior<br>- 1 Session</h4>
						<h3>Rs. 5,000</h3>
						<a  href="javascript:vpod(0)"  onclick="addItemToCart(2641)" class="button cta-meet-expert-plan">BOOK APPOINTMENT</a>
					</div>
					
					<div class="meet-expert-plan">
						<h4> Consultation with <br>Expert Nutritionist</h4>
						<h3>Rs. 800</h3>
						<a  href="javascript:vpod(0)"  onclick="addItemToCart(2639)" class="button">BOOK APPOINTMENT</a>
					</div>
				</div>
			</div>
			<div class="meet-expert-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/home-expert-jr.png') ?>"/>
			</div>
			
		</div>
		
	</div>
	<!-- Meet Expert End -->
	
	<!-- Why Choose US Start -->
	<style>
		.meal-plan-why-choose-us h2, .meal-plan-why-choose-us h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works meal-plan-why-choose-us">
		
		<div class="how-it-works-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h4>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHY CHOOSE US</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">We at LifeHeal speak your language. We customize the plans around your lifestyle. We provide coaching, encouragement, and support for the journey. We are scientific and delve deep to erase obesity and disease from their root cause.</p>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/meal-plan-why-choose-us-1.png') ?>"/>
					<h3>Nutritionists Approved Meals</h3>
					<p>We never compromise on hard-core science. That is why some of India’s top doctors approve of us. We use special blood tests to track and erase health issues from their roots. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/meal-plan-why-choose-us-2.png') ?>"/>
					<h3>Lifetime Journey</h3>
					<p>We follow a holistic approach to healing. Stress, sleep, good habits all contribute to a healthy life. You will learn secrets of a living a healthy life and how to maintain it.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/meal-plan-why-choose-us-3.png') ?>"/>
					<h3>Balanced Nutrition</h3>
					<p>Your plans will provide you well-balanced meals that incorporates all the necessary nutrients both at home and through one of our partner kitchens.</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- Why Choose US End -->
	
	<!-- Stats Start -->
	<div class="stats">
		<div class="stats-container">
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
					
			
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	<!-- Stats End -->
	
	<!-- Testimonials Start -->
	<style>
		.meal-plan-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
	<div class="testimonials meal-plan-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHAT OUR USER SAY ABOUT OUR MEAL PLANS AND COACHING</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I can't imagine my life without LifeHeal's health suggestions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo"  style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-1.png")?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Monika lost 30lbs</h3>
							<p>26 Years, Student, Delhi</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I can't imagine my life without LifeHeal's health suggestions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" 
							  style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-2.png")?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Michael lost 21lbs</h3>
							<p>38 Years, Manager, Pune</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I can't imagine my life without LifeHeal's health suggestions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo"  style="background-image: url('<?php echo $this->getSkinUrl("images/testimonials-detail-profile-photo-3.png")?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Rhea lost 18lbs</h3>
							<p>36 Years, Student, Delhi</p>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans. Additionally, we offer a 30% discount on your first order. </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
	