<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
		#reading0, #reading, #reading1, #reading2, #reading3 {
display:none; }
	#myBtnread{font-weight:600;}
.icon-bar {
  position: fixed;
  top: 50%;left: 0px;z-index: 3;
  -webkit-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}

.icon-bar a {
  display: block;
  text-align: center;
  padding: 16px;
  transition: all 0.3s ease;
  color: white;
  font-size: 20px;
}
	.main-container{min-height: 69vh;
position: relative;
margin: 100px auto auto;
padding: 30px 0;
float: left;
		width: 100%;}
</style>


<section>
  <div class="serviceimage">
	  
	  
	  <div class="container-fluid">
		  <div class="sec-head">
    OUR SERVICES
    </div>
		<div class="ourservices">
<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
        <h3>Therapeutic Food</h3>
        <p>We take all the work and effort out of food. Just Open, heat and eat. All the food is delivered. The simplest easiest and most hassle free way to reduce weight and diabetes</p>
       
        <h3>Consulting</h3>
         <p>Learn our techniques and methodology in managing and reversing diabetes. 
         Recommended for people living far away or ending our subscription program.</p>
        	<a href="<?php echo Mage::getBaseUrl().'our-products'?>" > <button type="button" class="btn bg-light btn-sm read-more" style="color:#fff;">Learn more</button></a>
       
		  </div>		 
			
			</div>
		  
</div>
</div>


</section>  
  
 
<!--question-->
<section class="brief-sec">
    <div class="container">
        <div class="row ">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="detail-txt">  
			<h4>What Is It?</h4>
			</div>
        </div>
            <div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">
                <div class="detail-sec">
					<video width="100%" height="100%" poster="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-2.jpg') ?>" controls>
   <source src="<?php echo $this->getSkinUrl('media/Video3-3.mp4')?>" type="video/mp4" style="vertical-align:top;">
   
   Your browser does not support the video tag.
</video>
					
                  
                </div>
            </div>  
                <div class="col-lg-8 col-md-6 col-sm-7 col-xs-12">
                <div class="detail-sec">
                    
                    <div class="detail-txt">
                <div class="easypara">        

            <p>It has now been proven that food can reverse diabetes. However making this food is very hard, time 
consuming. Simple, we take care of all the work, the planning and of course the scientific research to give you 
daily therapeutic meals.
</p>
    
						
            <ul>
				<p>These meals are customized to your medical needs, for example :</p> 
            <li>Some Diabetics Are Not Obese and Actually Need To Gain Weight
            </li>
            <li>
          Some Diabetics Have Kidney Diseases
            </li>
            <li>Some Diabetics Are Heart Patients
</li>
<li>Some Diabetics Are Pregnant <span id="myBtnread0"><b>Read more</b></span>...</li>
				
            </ul>
          </p>
            <span id="reading0"> <p>These meals are then planned under the medical supervision of an endocrinologist.</p>
            <p>Medications are usually lowered within 12 hours and we have seen in many cases that insulin use 
has dropped 75% within 4 days of starting our program.</p>
						</span>
   </div>         
</div>
                </div>
            </div>
              
            </div>
           
          <div class="row " style="border-top: 1px solid #eee;">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       
        <div class="detail-txt">
                        <h4>How Does It Work?</h4>
                        </div>
                        </div>
           
            <div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">      
            <div class="detail-sec">
                    <img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-3.jpg') ?>" alt="">
                    
                </div>
          </div>  
          <div class="col-lg-8 col-md-6 col-sm-7 col-xs-12">      
            <div class="detail-sec">
                   
                    <div class="detail-txt">
<div class="easypara">
            <p>All you have to do is eat!</p>
<p>We do the planning, cooking and delivery of therapeutic meals. The food is delivered right to your 
doorstep.It is 24 hrs of food. </p>       
            <ul>
				<p>It will reach before 7 pm and will include :</p>
            <li>Dinner
            </li>
            <li>
         Next Day's Breakfast
            </li>
            <li>Next Days's Lunch
</li>
<li>Next Day's High Tea <span id="myBtnread"><b>Read more</b></span>...</li>
            </ul>

	 <span id="reading">
            <p>The food is packed in reusable glass jars. The driver will come back next day and deliver more 
food and pick up the old used glass jars.</p>
	<p>This is repeated everyday till you have hit your targeted 
health goals.In case of travel you can cancel your food delivery one day prior. There is no cancellation charge.</p>
            <p>You can cancel your subscription any time and get reimbursed for unused days of food. However 
any free services or add-ons which are included with a monthly package are charged if the whole 
				month's subscription is not completed. Please see pricing page for more details.</p>
		   </span>
            </div>
              </div>
                </div>
          </div> 
       
          </div>
            <!--row4-->
            <!--row5-->
            <div class="row "  style="border-top: 1px solid #eee;display:none">
             <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       
        <div class="detail-txt">
                           <h4>What will I get to eat?</h4>
                        </div>
                        </div>
                        
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">     
             <div class="detail-sec">
                    <img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-4.jpg') ?>" alt="">
                   
                </div>
          </div>  
           <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">     
             <div class="detail-sec">
                    <div class="detail-txt">
                <div class="easypara">
            <p>There are no known side effects to eating healthy food. </p>
<p>There are no known medicine reactions to eating food.</p>
    <p>There are precautions of course, and we will discuss those with you during our patient intake 
process. 
</p>   
   
            <ul>
				<p>We have seen additional benefits in people, including:</p> 
            <li>Reduction of sleep apnea   </li>
            <li>Increased Energy
</li>
            <li>Better Digestion
</li>
<li>Better Skin Glow
</li>
<li>Decrease in cravings of junk food</li>
            </ul>
          
            </div>
</div>
                </div>
          </div>  
           
          </div>
          <!--row5-->
          <!--row6-->
          <div class="row"  style="border-top: 1px solid #eee;">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       
        <div class="detail-txt">
                          <h4>How Long Does It Take?</h4>
                        </div>
                        </div>
            <div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">      <div class="detail-sec">
                    <img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-5.jpg') ?>" alt="">
                </div>
          </div>  
          <div class="col-lg-8 col-md-6 col-sm-7 col-xs-12">     
			  <div class="detail-sec">
                    <div class="detail-txt">
<div class="easypara">
            <p>It has now been proven that food can reverse diabetes. However making this food is very hard, time 
consuming. </p>
<p>Simple, we take care of all the work, the planning and of course the scientific research to give you 
daily therapeutic meals.
</p>
         
            <ul>
				<p>These meals are customized to your medical needs, for example :</p>  
            <li>Some Diabetics Are Not Obese and Actually Need To Gain Weight
            </li>
            <li>
          Some Diabetics Have Kidney Diseases
            </li>
            <li>Some Diabetics Are Heart Patients
</li>
<li>Some Diabetics Are Pregnant <span id="myBtnread1"><b>Read more</b></span>...</li>
            </ul>
	
            <span id="reading1">
	<p>These meals are then planned under the medical supervision of an endocrinologist.</p>
				
            <p>Medications are usually lowered within 12 hours and we have seen in many cases that insulin use 
has dropped 75% within 4 days of starting our program.</p>
	  </span>
            </div>
 </div>
 </div>
          </div>  
         
          </div>
          
        <!--row6-->
        <!--row7-->
          <div class="row "  style="border-top: 1px solid #eee;display:none;">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="detail-txt" >
                           <h4>What Happens At The End?</h4>
                        </div>
                        </div>
            <div class="col-lg-6 col-md-6 col-sm-5 col-xs-12">      
            <div class="detail-sec">
                    <img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-6.jpg') ?>" alt="">
                </div>
          </div> 
          <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12">      
            <div class="detail-sec">
                    <div class="detail-txt">
<div class="easypara">
            <p>At the end of the program you will return to your home food.
</p>
<p>Let us explain.

</p>
   
            <p><b>THERE IS A DIFFERENCE BETWEEN THE REVERSAL FOODS AND THE MAINTENANCE FOODS.</b>
Cooking and eating to maintain your health is far easier. We will give you a program which can 
be achieved within a normal home's cooking possibilities and time. What we cook in our kitchen 
is very hard to do in a home setting. It takes many many professional chefs, it takes special 
equipment and special training.</p>
            <p>At home you will not have so much time, your chefs might leave and you will have new chefs. <span id="myBtnread2"><b>Read more</b></span>...</p>
	
            <span id="reading2">
				So 
we will leave you with a health maintenance plan. You will yourself be so aware of new foods and 
new items to eat that it will become easy to maintain a healthy lifestyle.</p>
	
<p>Just the reversal diet is close to impossible to do at home. The maintenance diet is not as hard.</p>
	  </span>
            </div>  
 </div>
                </div>
          </div>  
          
        </div>
  <!--row7-->
  <!--row8-->
     <div class="row" style="border-top: 1px solid #eee;display:none;">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="detail-txt">
                  <h4>Is The Cure Permanent ?</h4>
              </div>
              </div>
  <div class="col-lg-6 col-md-6 col-sm-5 col-xs-12">     
	  <div class="detail-sec">
          <img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-1.jpg') ?>" alt="">
      </div>
</div>  
 <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12">
      <div class="detail-sec">
          <div class="detail-txt">
<div class="easypara">
            <p>If you return to a non-diabetic state it means you are non diabetic. It means your body is able to 
control your sugar levels, and keep them within 70 - 140 range like a non-diabetic person.
</p>
<p>However if you return to doing the things which made you diabetic before, you will likely return to 
being diabetic again.

</p>
    <p>We will make you healthy and teach you how to stay healthy. The rest will depend on you.</p>       
           
            </div>
   </div>
      </div>
</div>  


 
</div>
<!--row8-->
<!--row9-->
<div class="row "  style="border-top: 1px solid #eee;">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="detail-txt"> <h4>How Do I Start?</h4> </div>
</div>
<div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">     
<div class="detail-sec">
<img src="<?php echo $this->getSkinUrl('images/Cure-My-Diabetes-7.jpg') ?>" alt="">

</div>
</div> 
<div class="col-lg-8 col-md-6 col-sm-7 col-xs-12">    
<div class="detail-sec">
      <div class="detail-txt">
<div class="easypara">
           
     
            <ul>
				 <p>Starting works as follows :</p>
            <li><b>MEET OUR DIETICIAN:</b> You can come in to our center or our dietician can come and visit you at 
      home. We will learn about your medical history and what are typical problems for you. We will 
      also note your weight, HBA1c and other important details.
            </li>
            <li>
          <b>INSTALL GLUCOSE MONITORING CHIP:</b> This chip is installed on you to get a closer look at how 
      your body's sugar moves during the day. This data is collected for 48-72 hours and reviewed 
      before starting the delivery program. 
            </li>
            <li><b>DOCTOR REVIEW:</b> The doctor will review your glucose levels and your current medications. Any 
      medication changes will be advised by the doctor. 
      <span id="myBtnread3"><b>Read more</b></span>...    
</li>
				
				  <span id="reading3">
<li><b>FOOD DELIVERY BEGINS:</b> Food delivery begins. We work with you to understand your tastes 
      and preferences. So far everyone has complained that there is too much food and they cannot 
      finish it.</li>
      <li><b>GLUCOSE LEVEL REVIEW AND MEDICINE ADJUSTMENT:</b> We review how the food is impacting 
      your blood glucose levels and the doctor adjusts medication accordingly. We keep reviewing 
      your glucose levels and weight to ensure we keep moving forward.</li>
					  </span>
            </ul>
           
            </div>
     </div>
  </div>
</div>  
   
</div>
        <!--row9-->
</div>    
</section>
<script type="text/javascript">
var $j = jQuery.noConflict();

$j(document).ready(function(){
  $j(".myModal").click(function(){
	  $j("#myModal").toggle();

  });
  $j(".close").click(function(){
	  $j("#myModal").toggle();

  });
	$j("#myBtnread0").click(function(){
	  $j("#reading0").toggle();

  });
	$j("#myBtnread").click(function(){
	  $j("#reading").toggle();

  });
	$j("#myBtnread1").click(function(){
	  $j("#reading1").toggle();

  });
	$j("#myBtnread2").click(function(){
	  $j("#reading2").toggle();

  });
	$j("#myBtnread3").click(function(){
	  $j("#reading3").toggle();

  });
});

</script>