
<style>
	.howworkback{margin-bottom: 50px;
float: left;
width: 100%;
background:#f4f3f3;}
	.howworkimg{width: 18%;
float: left;
margin:2% 3.5%;}
	.howworkimg h3{text-align: Center;
color:#df191a;
font-weight: bold;
font-size: 22px;
text-transform: capitalize;}
	.howwork iframe{width:100%; height:500px;}
	.breakline{margin: 0px 3% 40px;
width: 97%;
position: relative;
float: left;}
	.disabledheader{padding: 8px !important;
margin: 0px 5% 0px 3% !important;
background:#edebeb !important;
cursor: pointer;
color:#000 !important;
box-shadow: none !important;
opacity: 0.3;}
	.weightlossprogram, .stayfit, .diabetes{box-shadow: 0 8px 12px 0 rgba(0,0,0,0.4);
    transition: 0.3s;
    margin-top: 0px;
    -ms-transform: scale(1.1,1.1);
    transform: scale(1.1,1.1);
}
	.wlheader, .stheader, .dbheader{text-align: center;
transition: 0.3s;
color:#fff;
font-size: 18px !important;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
padding: 20px 8px 8px 8px;
margin: -12px 5% 0px 3%;
box-shadow: 0 8px 12px 0 rgba(0,0,0,0.4);
text-transform: capitalize;
font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI";
font-weight: 600;
border: 2px solid #269a9b;
background:#269a9b;
float: left;
width: 25%;
}
	.modal-body {
    position: relative;
    padding: 15px;
        padding-bottom: 15px;
    padding-bottom: 30px;
}
	.mySlides {
    display: none;
    height: 340px;
}
	.disabled{background:#edebeb;cursor:pointer;color:#000 !important;box-shadow:none;
opacity: 0.3;margin-top:0px;-ms-transform: scale(1,1);
    transform: scale(1,1);}
	.bannerheight {
    position: relative;
    height: 340px !important;
}
	.howwork{width:100%; float:left;}
	.howwork h2{text-align: center;
font-size: 36px;
padding-bottom: 20px;
color:#269a9b !important;
margin: 40px auto;}
h2{text-align: center;
font-size: 30px;
color:#269a9b !important;
margin: 40px auto;}
	.weightlossbanner{margin:40px auto;}

.button {
background-color:#269a9b;
border: none;
color:#fff !important;
padding: 10px 40px;
text-align: center;
font-size: 22px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
box-shadow: 0 2px 10px rgba(0, 0, 0, .4);
text-transform: uppercase;
font-weight: 600;
}
@media screen and (min-width:260px) and (max-width:767px)
{
	.howworkimg{width: 40%;
float: left;
margin:5% 5%;}
	.howworkimg h3{text-align: Center;
color:#df191a;
font-weight: bold;
font-size:14px;
text-transform: capitalize;}
	.howwork iframe{width:100%; height:100%;}
	.breakline{margin: 0px 3% 30px;
width: 97%;
position: relative;
float: left;}
	.disabledheader{padding:5px !important;
margin: 3px 1% 0px 1% !important;
background:#edebeb !important;
cursor: pointer;
color:#000 !important;
box-shadow: none !important;
opacity: 0.3;}
	.weightlossprogram, .stayfit, .diabetes{box-shadow: 0 8px 12px 0 rgba(0,0,0,0.4);
    transition:none;
    margin-top: -10px;
   -ms-transform:none;
transform:none;
}
	.wlheader, .stheader, .dbheader{text-align: center;
transition: none;
color:#fff;
font-size: 12px !important;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
padding: 20px 5px 5px 5px;
margin: -12px 1% 0px 1%;
box-shadow: 0 8px 12px 0 rgba(0,0,0,0.4);
text-transform: capitalize;
font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI";
font-weight: 600;
border: 2px solid #269a9b;
background:#269a9b;
float: left;
width:30%;
}
	.stayfit{margin-bottom:60px !important;}
.bannerheight {
    position: relative;
    height: 100% !important;
}
			.footer-container, .main-container {  
    padding: 0px; 
}
		.columns {
    float: left;
   padding:0px 15px;margin-bottom:0px;
}
		h2 {
    text-align: center;
    font-size: 30px !important;
    color: #269a9b !important;
    margin:30px auto !important;
	width: 100%;
    float: left;
}
	.contmob{padding:0px}
	}

	@media screen and (min-width:768px) and (max-width:999px){
		.bannerheight {
    position: relative;
    height: 250px !important;
}
		.mySlides {
   
    height: 100%;
}
	}
</style>

<div class="container contmob">
	<div class="weightlossbanner">
		  
		<!--<div class="banner bannerheight">
			   
		<div id="slide">
	<div id="desktopslide">
<div class="slideshow-container">

<div class="mySlides fades">
 <img src="<?php //echo $this->getSkinUrl('images/weight-loss.jpg') ?>">
 
</div>
	<div class="mySlides fades">
 <img src="<?php //echo $this->getSkinUrl('images/SATY-FIT.jpg') ?>">
  
</div>
	
		<div class="mySlides fades">
 <img src="<?php //echo $this->getSkinUrl('images/Diabetes-Plan.jpg') ?>">
  
</div>
	
<a class="prev" onclick="plusSlides(-1)" style="left: 0;">&#10094;</a> <a class="next" onclick="plusSlides(1)">&#10095;</a> 
</div>

<div style="text-align:center"> 
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
<span class="dot" onclick="currentSlide(3)"></span> 
	
</div>
			</div>
		  <!--mobile-->
		<!--
	<div id="mobileslide">
		  <div class="slideshow-container1">
<div class="mySlides1 fades"> 
  <img src="<?php echo $this->getSkinUrl('images/Mobile-pricing-weight-lose-banner.jpg') ?>">  
</div>
	<div class="mySlides1 fades">
 <img src="<?php echo $this->getSkinUrl('images/Mobile-pricing-stay-fit-banner.jpg') ?>">   
</div>
	
	<div class="mySlides1 fades"> 
   <img src="<?php echo $this->getSkinUrl('images/Mobile-pricing-diabetes-banner.jpg') ?>">  
</div>	
     <a class="prev" onclick="plusSlides1(-1)" style="left: 0;">&#10094;</a> <a class="next" onclick="plusSlides1(1)">&#10095;</a> 
		</div>
  </div>
  <div class="dotbox"> 
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span>

  
   </div>
	
		</div>
	</div>-->

<h2 style="padding-bottom:  20px;">PLANS</h2>
<div class="breakline">
	<div class="wlheader">WEIGHT LOSS</div>
		<div class="stheader disabledheader">STAY FIT</div>
	
		<div class="dbheader disabledheader">DIABETES</div>
		</div>


<div class="columns">
	
	<div class="weightlossprogram">
		
  <ul class="price">
    <li class="header">WEIGHT LOSS</li>
    <li class="grey">Estimate 2 kgs for every 10 Days On Full Plan* </li> <hr> 
    <li class="planame">Name Of Plans</li>
<span style="height:90px;display: block;">
    <?php $weightloss =59;
  $weightlosscollection = Mage::getModel('catalog/category')->load($weightloss)
    ->getProductCollection()
    ->addAttributeToSelect('*') // add all attributes - optional
    ->addAttributeToFilter('status', 1) // enabled
    //->addAttributeToFilter('visibility', 4) //visibility in catalog,search
    ->setOrder('price', 'ASC'); 
?>

<?php $i=1; foreach ($weightlosscollection as $key => $value) { ?>
  <li><?php echo $value->getName(); ?>
   <!-- Modal -->
<?php if($i==1) { ?>
  <span id="hm" class="tooltip">  
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
  c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
  <path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
    c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
    c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
    c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
    c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
    c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
    c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
    c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
  <path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
    c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
    c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>
</svg>
	   <span class="tooltiptext">click for more info</span>
 
<?php } else { ?>
  <span id="fm" class="tooltip">  
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
  c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
  <path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
    c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
    c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
    c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
    c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
    c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
    c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
    c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
  <path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
    c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
    c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>
</svg>
	   <span class="tooltiptext">click for more info</span>
<?php } ?>		
  
		 <!-- Modal -->
</span>
<label class="containercheckbox"> 
	
  <?php echo number_format($value->getSpecialPrice()); ?> per day<input <?php if($i ==2){ echo "checked";   } $i++; ?> type="radio" entityId="<?php echo $value->getId();?>" name="weightradio" price="<?php echo $value->getSpecialPrice();?>" value="<?php echo $value->getId() ?>">
  <span class="checkmark"></span>
</label>
	
</li>
<?php } ?>
	 
	  </span> <hr>
	 <span class="mealperarea">
	  <li style="width: 100%;float: left;"><span style="float: left;">Days</span>
		  <div class="weightloss-select" style="float: left;margin-left:10px;">
                  <select class="weightloss-day-select select-selected">
    
    <option value="10">10</option>
    <option value="30">30</option>
  </select>
</div>
		 </li>
	  </span>
	  <hr>
              <li class="planame" style="width:auto;">Total <input value="" readonly id="weightTotalId" type="text" style="color:#000;padding: 0px 0px;border: 0px solid #269a9b;cursor: pointer;user-select:none;background: #fff;box-shadow: none;width:  80px;max-width: 100%;text-align: center;font-weight: bold;font-size: 18px;"> </li>
		<input type ="hidden" id="hidWeight" qty="" entityId="" totalprice="" />
	 
    <li style="padding: 0px !important;text-align: center;"><a  class="button weightlosssubmit">BUY</a></li>
  </ul>
	
</div>
<small style="float:left; width:100%;font-weight: bold;padding: 10px;margin: 20px auto 20px auto;" class="wlsmall">* Individual Results May Vary</small>
	</div>
<div class="columns">
	
	<div class="stayfit disabled">		
  <ul class="price">
    <li class="header">STAY FIT</li>
    <li class="grey">Helps You Maintain Your weight </li><hr>
   <li class="planame">Select Meal</li>
	  <span style="height:90px;display: block;">
    <li>Simple Meal		
	<span id="sm" class="tooltip">	
						<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
	c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
	<path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
		c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
		c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
		c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
		c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
		c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
		c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
		c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.DIABETES653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
	<path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
		c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
		c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>

</svg>
		 <span class="tooltiptext">click for more info</span>		
   <!-- Modal -->

  
		 <!-- Modal -->
</span> 
		<label class="containercheckbox"> 
			
	

 Rs 200/- <input type="radio" productid="1728" value="stayfit1" name="stayfit" checked="checked">
  <span class="checkmark"></span>
</label>
	</li>
    <li>Deluxe Meal
		
				
		<span id="dm" class="tooltip">	
						<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
	c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
	<path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
		c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
		c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
		c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
		c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
		c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
		c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
		c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
	<path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
		c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
		c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>

</svg>
	 <span class="tooltiptext">click for more info</span>			

</span> 

		<label class="containercheckbox">
			
 Rs 350/- <input type="radio" productid="1729"   name="stayfit" value="stayfit2">
  <span class="checkmark"></span>
</label>
	
	  </li>
	   
	  </span>
	  <hr> 
	  <span class="mealperarea">
    <li  style="width: 100%;float: left;"><span style="float: left;">Select Meals</span> 
		<div class="day-select" style="float: left;margin-left:10px;">
  <select class="styfit-day-select select-selected">
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option>
    <option value="13">13</option>

    <option value="14">14</option>
    <option value="15">15</option>
    <option value="16">16</option>
    <option value="17">17</option>
    <option value="18">18</option>
    <option value="19">19</option>
    <option value="20">20</option>
    <option value="21">21</option>
    <option value="22">22</option>
    <option value="23">23</option>
    <option value="24">24</option>
    <option value="25">25</option>
    <option value="26">26</option>
    <option value="27">27</option>
    <option value="28">28</option>
    <option value="29">29</option>
    <option value="30">30</option>
  </select>
</div></li>
<?php /* $simplemealcat =57;
  $simplemealcollection = Mage::getModel('catalog/category')->load($simplemealcat)
    ->getProductCollection()
    ->addAttributeToSelect('*') // add all attributes - optional
    ->addAttributeToFilter('status', 1) // enabled
    //->addAttributeToFilter('visibility', 4) //visibility in catalog,search
    ->setOrder('price', 'ASC'); */
?>
	  <li class="simplemeal" style="width: 100%;float: left;display:none"><span style="float: left;">Select Frequency</span> <div class="styfit-frequency-select" style="float: left;margin-left:10px;">
  <select class="styfit-simple-frequency-select select-selected">
    <option value="4" >4 Meal/Week</option>
    <option value="5" >5 Meal/Week</option>
    <option value="6" >6 Meal/Week</option>
    <option value="7" >7 Meal/Week</option>
    <?php /* foreach ($simplemealcollection as $key => $value) { ?>
      <option value="<?php echo $value->getId(); ?>" data="<?php echo $value->getSpecialPrice(); ?>"><?php echo $value->getMealLabel(); ?></option>
    <?php } */?>
  </select>
</div></li>
<?php /* $deluxmealcat =58;
  $deluxemealcollection = Mage::getModel('catalog/category')->load($deluxmealcat)
    ->getProductCollection()
    ->addAttributeToSelect('*') // add all attributes - optional
    ->addAttributeToFilter('status', 1) // enabled
    //->addAttributeToFilter('visibility', 4) //visibility in catalog,search
    ->setOrder('price', 'ASC'); */
?>
	 
<li class="deluxmeal" style="display: none;float: left;width: 100%;">
	<span style="float: left;">Select Frequency </span>
  <div class="frequency-select " style="float: left;margin-left:10px;">
  <select class="styfit-delux-frequency-select  select-selected">
   <!--  <option value="8" >1 Meal/Week</option>
    <option value="9" >2 Meal/Week</option>
    <option value="10" >3 Meal/Week</option> -->
    <option value="11" >4 Meal/Week</option>
    <option value="12" >5 Meal/Week</option>
    <option value="13" >6 Meal/Week</option>
    <option value="14" >7 Meal/Week</option>
 
    <?php /*foreach ($deluxemealcollection as $key => $value) { ?>
      <option value="<?php echo $value->getId(); ?>" data="<?php echo $value->getSpecialPrice(); ?>"><?php echo $value->getMealLabel(); ?></option>
    <?php } */?>
  </select>
</div>
		    </li>
		  <li>
		   <div style="font-size:x-small;width:  100%;float: left;line-height: 1.4;letter-spacing: 0px;background: #ebe7e7;padding: 5px;border:  1px solid #269a9b;margin-top: 3%;">After you order our nutritionist will call to plan which days to send lunch</div>
	 </li>
	  </span>
	 
		 
	  <hr>
	  <li class="planame" style="width:auto;">Total <input readonly class="stayfitfinalvalue" type="text" style="color:#000;padding: 0px 0px;border: 0px solid #269a9b;cursor: pointer;font-size: 18px;
		  user-select:none;background: #fff;box-shadow: none;width:  80px;max-width: 100%;text-align: center;font-weight: bold;"></li>
    <li style="padding: 0px !important;text-align: center;"><a class="button stayfitsubmit">Buy</a></li>
  </ul>
	</div>
</div>
<div class="columns">
	
	<div class="diabetes disabled">
	
  <ul class="price">
    <li class="header">DIABETES</li>
    <li class="grey">Injections get reduced within days* </li> <hr> 
    <li class="planame">Name Of Plans</li>
	  <span style="height:90px;display: block;">
    <?php $diabetes =60;
  $diabetescollection = Mage::getModel('catalog/category')->load($diabetes)
    ->getProductCollection()
    ->addAttributeToSelect('*') // add all attributes - optional
    ->addAttributeToFilter('status', 1) // enabled
    //->addAttributeToFilter('visibility', 4) //visibility in catalog,search
    ->setOrder('price', 'ASC'); 
?>

<?php $i=1; foreach ($diabetescollection as $key => $value) { ?>
  <li><?php echo $value->getName(); ?>
  <?php if($i ==1) { ?>
 	<span id="b1" class="tooltip">  
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
  c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
  <path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
    c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
    c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
    c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
    c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
    c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
    c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
    c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
  <path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
    c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
    c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>
</svg>
		 <span class="tooltiptext">click for more info</span>
  
</span>
<?php } else { ?>
<span id="b2" class="tooltip">  
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 496.158 496.158" style="enable-background:new 0 0 496.158 496.158;width:16px; height:16px;" xml:space="preserve">
<path style="fill: orange;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085
  c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,496.158,248.085z"/>
<g>
  <path style="fill:#FFFFFF;" d="M315.249,359.555c-1.387-2.032-4.048-2.755-6.27-1.702c-24.582,11.637-52.482,23.94-57.958,25.015
    c-0.138-0.123-0.357-0.348-0.644-0.737c-0.742-1.005-1.103-2.318-1.103-4.015c0-13.905,10.495-56.205,31.192-125.719
    c17.451-58.406,19.469-70.499,19.469-74.514c0-6.198-2.373-11.435-6.865-15.146c-4.267-3.519-10.229-5.302-17.719-5.302
    c-12.459,0-26.899,4.73-44.146,14.461c-16.713,9.433-35.352,25.41-55.396,47.487c-1.569,1.729-1.733,4.314-0.395,6.228
    c1.34,1.915,3.825,2.644,5.986,1.764c7.037-2.872,42.402-17.359,47.557-20.597c4.221-2.646,7.875-3.989,10.861-3.989
    c0.107,0,0.199,0.004,0.276,0.01c0.036,0.198,0.07,0.5,0.07,0.933c0,3.047-0.627,6.654-1.856,10.703
    c-30.136,97.641-44.785,157.498-44.785,182.994c0,8.998,2.501,16.242,7.432,21.528c5.025,5.393,11.803,8.127,20.146,8.127
    c8.891,0,19.712-3.714,33.08-11.354c12.936-7.392,32.68-23.653,60.363-49.717C316.337,364.326,316.636,361.587,315.249,359.555z"/>
  <path style="fill:#FFFFFF;" d="M314.282,76.672c-4.925-5.041-11.227-7.597-18.729-7.597c-9.34,0-17.475,3.691-24.176,10.971
    c-6.594,7.16-9.938,15.946-9.938,26.113c0,8.033,2.463,14.69,7.32,19.785c4.922,5.172,11.139,7.794,18.476,7.794
    c8.958,0,17.049-3.898,24.047-11.586c6.876-7.553,10.363-16.433,10.363-26.393C321.646,88.105,319.169,81.684,314.282,76.672z"/>
</g>
</svg>
	 <span class="tooltiptext">click for more info</span>

</span>

<?php }  ?>
<label class="containercheckbox"> 

	Rs
  <?php echo number_format($value->getSpecialPrice()); ?>/- <input <?php if($i ==1){ echo "checked"; } $i++ ?> type="radio" name="radio" value="<?php echo $value->getId() ?>" price="<?php echo $value->getSpecialPrice() ?>">
  <span class="checkmark"></span>
</label>
	</li>
<?php } ?>
		 
	  </span> <hr style="border-color: white;"> 
	
	   <span class="mealperarea"></span>
	  <hr>
	  <li class="planame" style="width:auto;">Total <input class="diabetesTotal" readonly type="text" style="color:#000;padding: 0px 0px;border: 0px solid #269a9b;cursor: pointer;font-size: 18px;
		  user-select:none;background: #fff;box-shadow: none;width:  80px;max-width: 100%;text-align: center;font-weight: bold;"></li>
    <li style="padding: 0px !important;text-align: center;"><a class="button diabetessubmit">BUY</a></li>
  </ul>
		
</div>
<small style="float:left; width:100%;font-weight: bold;padding: 10px;margin: 20px auto 20px auto;" class="dbsmall">* Individual Results May Vary</small>
</div>
<div class="howwork">
	<h2>Testimonial</h2>
<iframe src="https://www.youtube.com/embed/DsVQtiYsHC4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
</div>
</div>

<div class="howwork">
	<h2>How It Works</h2>
	<div class="howworkback" style="margin-bottom:50px;">
	<div class="howworkimg"><img src="<?php echo $this->getSkinUrl('images/Customized-DIet.png') ?>">
		<h3>1. Customized Diet</h3>
		</div>
	<div class="howworkimg"><img src="<?php echo $this->getSkinUrl('images/Personal-Support-Team.png') ?>">
		<h3>2. Personal Support Team</h3>
		</div>
	<div class="howworkimg"><img src="<?php echo $this->getSkinUrl('images/Tasty-,-Vegan.png') ?>">
		<h3>3. tasty,Vegan & Oil free</h3>
		</div>
	<div class="howworkimg"><img src="<?php echo $this->getSkinUrl('images/Results.png') ?>">
		<h3>4. Incredible Results</h3>
		</div>
	</div>

</div>

<div id="SimpleMeal" style="display:none;">
	<!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closesm" data-dismiss="modal">X</button>
          
        </div>
        <div class="modal-body">
			<h3  style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Simple Meal Plans</h3>

<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Soup and Salad Combo</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;"></span><span style="float:right;text-align: justify;width:97%">or</span></span></p>
<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">2 Subji with Roti/Rice Combo</span></span></p>

<h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Deluxe Meal Plans</h3>

<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Soup, Salad, Subjis, Roti/Rice</span></p>


        </div>
       
      </div>
      
    </div>
  </div>
  
</div>
		

<div id="DeluxeMeal" style="display:none;">
	<!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closedm" data-dismiss="modal">X</button>
          
        </div>
        <div class="modal-body">
				<h3  style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Simple Meal Plans</h3>

<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Soup and Salad Combo</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;"></span><span style="float:right;text-align: justify;width:97%">or</span></span></p>
<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">2 Subji with Roti/Rice Combo</span></span></p>

<h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Deluxe Meal Plans</h3>

<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Soup, Salad, Subjis, Roti/Rice</span></p>

        </div>
       
      </div>
      
    </div>
  </div>
  
</div>

<!-- Modal -->
<div id="id01" style="display:none;">
	<!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closeid1" data-dismiss="modal">X</button>
          
        </div>
        <div class="modal-body">
			   <h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">5 Days Trial Pack</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes 1 Advanced CGM sensor - Rs 2500</span></p>
				 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>		
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">3 days blood glucose detailed analysis - Rs 1000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">2 days trial food - Rs 500</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">5 days Total</span></p>
			
			<h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">30 Days Full Program</h3>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes 2 Advanced CGM sensors - Rs 5000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes Dietician Consult Session - Rs 3000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Dietician Daily Support - worth Rs 200/day</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes Blood Tests To Measure Improvements - Rs 2000</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Will Be Customized To Your Glucose Graphs</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">3 days blood glucose detailed analysis Rs 1000</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">30 days food subscription - Rs 900 per day</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">33 days Total</span></p>
        </div>
        
      </div>
      
    </div>
  </div>
</div>

<div id="id02" style="display:none;">
  <!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closeid2" data-dismiss="modal">X</button>
          
        </div>
        <div class="modal-body">
			  <h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">5 Days Trial Pack</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes 1 Advanced CGM sensor - Rs 2500</span></p>
				 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>		
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">3 days blood glucose detailed analysis - Rs 1000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">2 days trial food - Rs 500</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">5 days Total</span></p>
			
      <h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">30 Days Full Program</h3>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes 2 Advanced CGM sensors - Rs 5000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes Dietician Consult Session - Rs 3000</span></p>
			 <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Dietician Daily Support - worth Rs 200/day</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Includes Blood Tests To Measure Improvements - Rs 2000</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">You Will Get Minute By Minute Glucose Reading And The Food </span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Will Be Customized To Your Glucose Graphs</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">3 days blood glucose detailed analysis Rs 1000</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">30 days food subscription - Rs 900 per day</span></p>
			<p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">33 days Total</span></p>
        </div>
        
      </div>
      
    </div>
  </div>
</div>
	<!-- Modal -->
		
<div id="fullmeal" style="display:none;">
  <!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closefm" data-dismiss="modal">X</button>
          
        </div>
        <div class="modal-body">
			 <h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Half Meal Plans</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Lunch and Dinner only</span></p>
                   <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Oil Free Food</span></p>      
			
			<h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Full Meal Plans</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Breakfast, Lunch, Dinner, Hi Tea, Pro Biotics</span></p>
                   <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Oil Free Food</span></p> 
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Restores Microbiome</span></p>
		</div>
       
      </div>
      
    </div>
  </div>
</div>

 <div id="halfmeal" style="display:none;">
	<!-- Modal -->
  <div class="modalsvg" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closehm" data-dismiss="modal">X</button>
          
        </div>
       <div class="modal-body">
		  <h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Half Meal Plans</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Lunch and Dinner only</span></p>
                   <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Oil Free Food</span></p>      
			
			<h3 style="margin: 20px auto;color: #000;font-weight: 600;float: left;">Full Meal Plans</h3>
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Breakfast, Lunch, Dinner, Hi Tea, Pro Biotics</span></p>
                   <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Oil Free Food</span></p> 
			       <p style="float: left;width: 100%;margin: 5px auto;"><span style="font-size:2em;float:left;width:3%;display: flex;margin-top: -17px;">.</span><span style="float:right;text-align: justify;width:97%">Restores Microbiome</span></p>   
		</div>
       
      </div>
      
    </div>
  </div>
</div>

<script>

	
	
	if (window.matchMedia("(max-width:992px)").matches) 
        { 
            
            // The viewport is less than 768 pixels wide 
			jQuery(document).ready(function(){
	jQuery(".diabetes").hide('')
    jQuery(".stayfit").hide('');
   jQuery(".weightlossprogram").show('');
	 jQuery(".wlsmall").show('');
	jQuery(".dbsmall").hide('');
jQuery(".weightlossprogram").removeClass('disabled');
				
  jQuery(".wlheader").click(function(){
   jQuery(".diabetes").hide('');
	   jQuery(".wlsmall").show('');
	  jQuery(".dbsmall").hide('');
   jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").removeClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
   jQuery(".stayfit").hide('');
   jQuery(".weightlossprogram").show('');
	   jQuery(".diabetes").addClass('disabled');
	   jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").removeClass('disabled');
   
  });
jQuery(".stheader").click(function(){
 jQuery(".stheader").removeClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
	 jQuery(".diabetes").hide('')
	 jQuery(".dbsmall").hide('');
	   jQuery(".wlsmall").hide('');
    jQuery(".weightlossprogram").hide('');
   jQuery(".stayfit").show('');
	 jQuery(".diabetes").addClass('disabled')
    jQuery(".weightlossprogram").addClass('disabled');
   jQuery(".stayfit").removeClass('disabled');
  });
jQuery(".dbheader").click(function(){
	jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").removeClass('disabledheader');
	jQuery(".diabetes").show('')
	 jQuery(".dbsmall").show('');
	   jQuery(".wlsmall").hide('');
     jQuery(".stayfit").hide('');
   jQuery(".weightlossprogram").hide('');
	jQuery(".diabetes").removeClass('disabled')
     jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").addClass('disabled');
  });
});
           
        } else { 
            
            // The viewport is at least 768 pixels wide 
			jQuery(document).ready(function(){
				jQuery(".weightlossprogram").click(function(){
   jQuery(".diabetes").addClass('disabled');
   jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").removeClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
   jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").removeClass('disabled');
   
  });
jQuery(".stayfit").click(function(){
 jQuery(".stheader").removeClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
	 jQuery(".diabetes").addClass('disabled')
    jQuery(".weightlossprogram").addClass('disabled');
   jQuery(".stayfit").removeClass('disabled');
  });
jQuery(".diabetes").click(function(){
	jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").removeClass('disabledheader');
	jQuery(".diabetes").removeClass('disabled')
     jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").addClass('disabled');
  });
				
  jQuery(".wlheader").click(function(){
   jQuery(".diabetes").addClass('disabled');
   jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").removeClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
   jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").removeClass('disabled');
   
  });
jQuery(".stheader").click(function(){
 jQuery(".stheader").removeClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").addClass('disabledheader');
	 jQuery(".diabetes").addClass('disabled')
    jQuery(".weightlossprogram").addClass('disabled');
   jQuery(".stayfit").removeClass('disabled');
  });
jQuery(".dbheader").click(function(){
	jQuery(".stheader").addClass('disabledheader');
   jQuery(".wlheader").addClass('disabledheader');
   jQuery(".dbheader").removeClass('disabledheader');
	jQuery(".diabetes").removeClass('disabled')
     jQuery(".stayfit").addClass('disabled');
   jQuery(".weightlossprogram").addClass('disabled');
  });
});
            
        } 
	
jQuery(document).ready(function(){
  jQuery("#b1").click(function(){
    jQuery("#id01").toggle();
  });
	jQuery(".closeid1").click(function(){
    jQuery("#id01").hide();
  });
	
jQuery("#b2").click(function(){
    jQuery("#id02").toggle();
  });
	jQuery(".closeid2").click(function(){
    jQuery("#id02").hide();
  });
	
  jQuery("#dm").click(function(){
    jQuery("#DeluxeMeal").toggle();
  });
	jQuery(".closedm").click(function(){
    jQuery("#DeluxeMeal").hide();
  });
	
	jQuery("#sm").click(function(){
    jQuery("#SimpleMeal").toggle();
  });
	jQuery(".closesm").click(function(){
    jQuery("#SimpleMeal").hide();
  });
	
	jQuery("#hm").click(function(){
    jQuery("#halfmeal").toggle();
  });
	jQuery(".closehm").click(function(){
    jQuery("#halfmeal").hide();
  });
	
	jQuery("#fm").click(function(){
    jQuery("#fullmeal").toggle();
  });
	jQuery(".closefm").click(function(){
    jQuery("#fullmeal").hide();
  });
});
</script>

<script type="text/javascript">
    
    function checkCalculation(entityId,price,mealQtyId,TotalId,changetype)
    { alert('2');
       /* var qty ='';
        var total='';
        var entityId='';
        
        if(changetype=='radio')
        {
         qty = jQuery('#'+mealQtyId+' :selected').text();
         total = parseInt(price) * parseInt(qty);
        
        }
       else if(changetype=='selectbox') //qty change
        {  
               var weightradio = jQuery("input[name='weightradio']:checked");
             var itemPrice = parseInt(weightradio.attr("price"));
             alert("itemPrice"+itemPrice);
           
             entityId = weightradio.attr("entityId");
             qty = jQuery('#mealQtyId :selected').text();
             total = itemPrice * parseInt(jQuery('#mealQtyId :selected').text());
             
             alert("itemPrice"+itemPrice);
              alert("entityId"+entityId);
               alert("total"+total);
             
        }
       /* jQuery("#"+TotalId).val(total);
        jQuery("#hidWeight").attr("qty",qty);
        jQuery("#hidWeight").attr("entityId",entityId);
        jQuery("#hidWeight").attr("totalprice",total);*/
       
    }

jQuery(document).ready(function(){

var mealplanprice = 250;
var productprice = 250;
var productID = '';
var qty = 3;
 
var weightradio = jQuery("input[name='weightradio']:checked");

var itemPrice = parseInt(weightradio.attr("price"));
var totalPrice = itemPrice * parseInt(jQuery('#mealQtyId :selected').text());

jQuery("#hidWeight").attr("qty",jQuery('#mealQtyId :selected').text());
jQuery("#hidWeight").attr("entityId",weightradio.attr("entityId"));
jQuery("#hidWeight").attr("totalprice", totalPrice ); 
        
        

jQuery(".stayfit input:radio").change(function () {
     if(jQuery('.stayfit input:radio:checked').val() == "stayfit1"){
         mealplanprice = 250;
         jQuery('.simplemeal').show();
         jQuery('.deluxmeal').hide();
         var productprice = jQuery('.styfit-simple-frequency-select option:selected').attr('data');
     }if(jQuery('.stayfit input:radio:checked').val() == "stayfit2"){
        mealplanprice = 350;
        jQuery('.simplemeal').hide();
        jQuery('.deluxmeal').show();
        var productprice = jQuery('.styfit-delux-frequency-select option:selected').attr('data');
     }
     var qty = jQuery('.styfit-day-select').val();
     jQuery(".stayfitfinalvalue").val(mealplanprice*qty);
});

jQuery('.styfit-day-select').change(function(){ 
    var qty = jQuery('.styfit-day-select').val();
    if(jQuery('.stayfit input:radio:checked').val() == "stayfit1"){
      var productprice = jQuery('.styfit-simple-frequency-select option:selected').attr('data');
      mealplanprice = 250;
    }if(jQuery('.stayfit input:radio:checked').val() == "stayfit2"){
      var productprice = jQuery('.styfit-delux-frequency-select option:selected').attr('data');
      mealplanprice = 350;
    } 
    jQuery(".stayfitfinalvalue").val(mealplanprice*qty);
});

/*jQuery('.styfit-simple-frequency-select').change(function(){ 
    var productID = jQuery('.styfit-simple-frequency-select').val();
    var productprice = jQuery('option:selected', this).attr('data');
    var qty = jQuery('.styfit-day-select').val();
    jQuery(".stayfitfinalvalue").val(productprice*qty);
});

jQuery('.styfit-delux-frequency-select').change(function(){ 
    var productID = jQuery('.styfit-delux-frequency-select').val();
    var productprice = jQuery('option:selected', this).attr('data');
    var qty = jQuery('.styfit-day-select').val();
    jQuery(".stayfitfinalvalue").val(productprice*qty);
});*/

jQuery(".stayfitfinalvalue").val(productprice*qty);

jQuery(".stayfitsubmit").click(function(){
    if(jQuery('.stayfit input:radio:checked').val() == "stayfit1"){
      var productID = jQuery('.stayfit input:radio:checked').attr("productid");
      console.log(productID);
      var OptionTypeId = 1;
      var mealoption = jQuery('.styfit-simple-frequency-select').val();
      //var  = jQuery('.styfit-simple-frequency-select').val();
    }if(jQuery('.stayfit input:radio:checked').val() == "stayfit2"){
      var productID = jQuery('.stayfit input:radio:checked').attr("productid");
      console.log(productID);
      var OptionTypeId=2
      var mealoption = jQuery('.styfit-delux-frequency-select').val();
      console.log(mealoption); 
    }  

    var qty = jQuery('.styfit-day-select').val();
    var productdata = 'id='+productID+'&qty='+qty+"&optiontypeid="+OptionTypeId+"&optionid="+mealoption;
    var url = "<?php echo Mage::getBaseUrl().'checkout/cart/customoption?' ?>"+productdata;
    console.log(url);
    window.location.href = url; 
});


});



jQuery(".weightlossprogram input:radio").change(function () {
     var qty = jQuery('.weightloss-day-select').val();
    var itemPrice = parseInt(jQuery('.weightlossprogram input:radio:checked').attr("price"));
     jQuery("#weightTotalId").val(itemPrice*qty);
});
jQuery('.weightloss-day-select').change(function(){ 
    var qty = jQuery('.weightloss-day-select').val();
    var itemPrice = parseInt(jQuery('.weightlossprogram input:radio:checked').attr("price"));
    jQuery("#weightTotalId").val(itemPrice*qty);
});

var weightqty = jQuery('.weightloss-day-select').val();
var weightitemPrice = parseInt(jQuery('.weightlossprogram input:radio:checked').attr("price"));
console.log(weightqty);
console.log(weightitemPrice);
jQuery("#weightTotalId").val(weightitemPrice*weightqty);


jQuery(".weightlosssubmit").click(function(){
  var productID =jQuery('.weightlossprogram input:radio:checked').val();
  var qty = jQuery('.weightloss-day-select').val();
  var productdata = 'id='+productID+'&qty='+qty;
  if (productID != null) {
    var url = "<?php echo Mage::getBaseUrl().'checkout/cart/custom?' ?>"+productdata;
    console.log(url);
    window.location.href = url; 
  }
});


jQuery(".diabetes input:radio").change(function () {
    var itemPrice = parseInt(jQuery('.diabetes input:radio:checked').attr("price"));
     jQuery(".diabetesTotal").val(itemPrice);
});

var itemPrice = parseInt(jQuery('.diabetes input:radio:checked').attr("price"));
jQuery(".diabetesTotal").val(itemPrice);

jQuery(".diabetessubmit").click(function(){
  var productID =jQuery('.diabetes input:radio:checked').val();
  //console.log(productID);
  var qty = 1;// jQuery('.diabetes-day-select').val();
  var productdata = 'id='+productID+'&qty='+qty;
  if (productID != null) {
    var url = "<?php echo Mage::getBaseUrl().'checkout/cart/custom?' ?>"+productdata;
    console.log(url);
    window.location.href = url; 
  }
});
</script>

<script>
var x, i, j, selElmnt, a, b, c;
/*look for any elements with the class "custom-select":*/
x = document.getElementsByClassName("custom-select");
for (i = 0; i < x.length; i++) {
  selElmnt = x[i].getElementsByTagName("select")[0];
  /*for each element, create a new DIV that will act as the selected item:*/
  a = document.createElement("DIV");
  a.setAttribute("class", "select-selected");
  a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
  x[i].appendChild(a);
  /*for each element, create a new DIV that will contain the option list:*/
  b = document.createElement("DIV");
  b.setAttribute("class", "select-items select-hide");
  for (j = 1; j < selElmnt.length; j++) {
    /*for each option in the original select element,
    create a new DIV that will act as an option item:*/
    c = document.createElement("DIV");
    c.innerHTML = selElmnt.options[j].innerHTML;
    c.addEventListener("click", function(e) {
        /*when an item is clicked, update the original select box,
        and the selected item:*/
        var y, i, k, s, h;
        s = this.parentNode.parentNode.getElementsByTagName("select")[0];
        h = this.parentNode.previousSibling;
        for (i = 0; i < s.length; i++) {
          if (s.options[i].innerHTML == this.innerHTML) {
            s.selectedIndex = i;
            h.innerHTML = this.innerHTML;
            y = this.parentNode.getElementsByClassName("same-as-selected");
            for (k = 0; k < y.length; k++) {
              y[k].removeAttribute("class");
            }
            this.setAttribute("class", "same-as-selected");
            break;
          }
        }
        h.click();
    });
    b.appendChild(c);
  }
  x[i].appendChild(b);
 a.addEventListener("click", function(e) {
      /*when the select box is clicked, close any other select boxes,
      and open/close the current select box:*/
      e.stopPropagation();
      closeAllSelect(this);
      this.nextSibling.classList.toggle("select-hide");
      this.classList.toggle("select-arrow-active");
    });
}
function closeAllSelect(elmnt) {
  /*a function that will close all select boxes in the document,
  except the current select box:*/
  var x, y, i, arrNo = [];
  x = document.getElementsByClassName("select-items");
  y = document.getElementsByClassName("select-selected");
  for (i = 0; i < y.length; i++) {
    if (elmnt == y[i]) {
      arrNo.push(i)
    } else {
      y[i].classList.remove("select-arrow-active");
    }
  }
  for (i = 0; i < x.length; i++) {
    if (arrNo.indexOf(i)) {
      x[i].classList.add("select-hide");
    }
  }
}
/*if the user clicks anywhere outside the select box,
then close all select boxes:*/
document.addEventListener("click", closeAllSelect);
	
	
	//slider
	var slideIndex = 0;
showSlides();
var slides,dots;

function showSlides() {
    var i;
    slides = document.getElementsByClassName("mySlides");
    dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    slideIndex++;
    if (slideIndex> slides.length) {slideIndex = 1}    
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";  
    dots[slideIndex-1].className += " active";
    //setTimeout(showSlides, 6000); // Change image every 4 seconds
}

function plusSlides(position) {
    slideIndex +=position;
    if (slideIndex> slides.length) {slideIndex = 1}
    else if(slideIndex<1){slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";  
    dots[slideIndex-1].className += " active";
}

function currentSlide(index) {
    if (index> slides.length) {index = 1}
    else if(index<1){index = slides.length}
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[index-1].style.display = "block";  
    dots[index-1].className += " active";
}
	
	
		
	var slideIndex1 = 1;
showSlides1(slideIndex1);

function plusSlides1(n) {
  showSlides1(slideIndex1 += n);
}

function currentSlide(n) {
  showSlides1(slideIndex1 = n);
}

function showSlides1(n) {
  var i;
  var slides1 = document.getElementsByClassName("mySlides1");
  var dots = document.getElementsByClassName("dot");
  if (n > slides1.length) {slideIndex1 = 1}    
  if (n < 1) {slideIndex1 = slides1.length}
  for (i = 0; i < slides1.length; i++) {
      slides1[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides1[slideIndex1-1].style.display = "block";  
  dots[slideIndex1-1].className += " active";
}
	
</script>
