

    

    

    <div class="main-wrap">
      <div id="wsite-content" class="wsite-elements wsite-not-footer">
	<div class="wsite-section-wrap">
    <section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
 <div class="sec-start-head" style="text-align: center;">
            <b> DIABETES REVERSAL PROGRAM PRICING INFORMATION</b>
            </div>

<section class="padd-10">
        <div class="container">
           
            <div class="easyway">
            <span>
           Glucose Pattern Evaluation:   - Rs 4000/-
           </span>
            <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Registration : </u></h4>
             <span>
Includes Free 3 Days Premium Trial- Rs 2000/- (worth Rs 2400)
</span>


<h4 style="margin:20px auto 0px auto;float: left;width: 100%;"><u>Services Given: </u></h4>  
<ul style="border:0px;margin-bottom: 0px;">
        <li>Dinner/Breakfast/Lunch/ High Tea with Meal Preference on type (Indian/Italian/Mughlai/Chinese)</li>
        <li>Ongoing minute by minute glucose monitoring. Evaluating effects of the diet. Measurements done every 2 days.</li>
        </ul>
       
        <span>
        Trial Period is non-refundable
        </span>
       
        <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Sign up: </u></h4>  

<span>
Full Payment- option for 1 Month / 2 Months / 3 Months- Rs 24000/- , 48000/-, 72000/- in Premium.
</span>

        <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Services Given For Monthly Sign-up </u></h4>  

<span>
 Daily Dinner/Breakfast/Lunch/ High Tea with Meal Preference on type (Indian/Italian/Mughlai/Chinese). 
</span>

        <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Free Diagnostic Tests</u></h4>  

<span>
Lipid profile/ Hba1c / HSCRP at Home or reimbursements. For once a month testing.  
BP Monitoring (Health is not only kgs and inches, it is being healthy from within as well.)
1 Free Review from Dietitian / Week. <br/>Total 4 per month (@ Worth Rs 2000 per Consultation).
</span>


            <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Consulting Services:</u></h4>
            <span>
            Monthly Consulting Package : Rs.5000
            <br/>            
           (Includes 4 consulting sessions)
            </span>
            <h4 style="margin: 20px auto;float: left;width: 100%;"><u>Individual Consulting Sessions:</u></h4>
            <span>
           Endocrinologist consult : Rs.2000
            <br>
            Dietician consult : Rs.2000
            <br>
            At Home Visit By Dietician : Rs.3000
            <br>
            Session with Mr. Junior Gupta : Rs.10,000
            <br>​
            <em>add ons:</em>
            <br>
            CGM - Continuous Glucose Monitoring patch - Rs.4000   
            <br/>
            <br />
            Deliveries: Free delivery within Gurgaon and South Delhi
            <br/>
            Noida, Faridabad, Ghaziabad not serviced at this time        
            </span>
            
            </div>
            </div>
            </section>
            <br/>
            
            <section class="padd-10">
        <div class="container">
          <div class="easyway" style="border-top: 0px solid rgba(0,0,0,0.1);float: left;width: 100%;">
         <!-- <h4 style="margin: 20px auto;float: left;width: 100%;"><strong>Special Discounts for Doctors available</strong></h4>-->
         <p style="margin: 20px auto;float: left;width: 100%;">Note:</p>
<ul style="border:0px;">
<li>In case you cancel subscription before the complete course we will deduct price of CGMs and consultations.</li>
<li>You can cancel anytime with full refund for remaining balance minus any charges for complimentary CGMs or consultations.</li>
<li>If you only pay for 10 days and want the CGM we will charge the full price. 
If you extend the subscription to 1 month we will deduct charges for CGM and consultations.
</li>
</ul>

<p style="background: #fef9f9;border: 2px dotted green;padding: 20px;float: left;text-align:center;">​To enquire please <a href="mailto:team@curemydiabetes.com">email us</a> or WhatsApp to <a href="tel:+91-9999-84-6622">+91-9999-84-6622</a></p>
            </div>
            </div>
            </section>
            </body>