<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121432135-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121432135-1');
</script>
<main role="main">
  <section class="home-section home-section--audience">
    <div class="Wrapper mw75">
      <div class="Grid flex-space-between">
        <div class="Cell l8">
          <h1 class="f1 text-tint">Your Information, Your Rights, Our Responsibilities
          </h1>
          
          <!-- Comman Static Content -->
          <p>
	<strong>Last Updated&nbsp;</strong> : <em>March 16, 2018</em>
</p>

<div class="static-page-data">
	<p>This notice describes how medical information about you may be used and disclosed and how you can get access to this information. <strong>Please review it carefully</strong>.</p>

<h1>Your Rights</h1>

<p>You have the right to:</p>

<ul>
	<li>Get a copy of your paper or electronic medical record</li>
	<li>Correct your paper or electronic medical record</li>
	<li>Request confidential communication</li>
	<li>Ask us to limit the information we share</li>
	<li>Get a list of those with whom we’ve shared your information</li>
	<li>Get a copy of this privacy notice</li>
	<li>Choose someone to act for you</li>
	<li>File a complaint if you believe your privacy rights have been violated</li>
</ul>

<h1>Your Choices</h1>

<p>You have some choices in the way that we use and share information as we:</p>

<ul>
	<li>Tell family and friends about your condition</li>
	<li>Provide disaster relief</li>
	<li>Include you in a hospital directory</li>
	<li>Provide mental health care</li>
	<li>Market our services and sell your information</li>
	<li>Raise funds</li>
</ul>

<h1>Our Uses and Disclosures</h1>

<p>We may use and share your information as we:</p>

<table cellspacing="0" cellpadding="0" border="1">
	<tbody>
		<tr>
			<td style="height:24px; width:552px">
			<ul>
				<li>Treat you</li>
				<li>Run our organization</li>
				<li>Bill for your services</li>
				<li>Help with public health and safety issues</li>
				<li>Do research</li>
				<li>Comply with the law</li>
				<li>Respond to organ and tissue donation requests</li>
				<li>Work with a medical examiner or funeral director</li>
				<li>Address workers’ compensation, law enforcement, and other government requests</li>
				<li>Respond to lawsuits and legal actions</li>
			</ul>
			</td>
		</tr>
	</tbody>
</table>

<h1>Your Rights</h1>

<p><strong>When it comes to your health information, you have certain rights. </strong>This section explains your rights and some of our responsibilities to help you.</p>

<p><strong>Get an electronic or paper copy of your medical record </strong></p>

<ul>
	<li>You can ask to see or get an electronic or paper copy of your medical record and other health information we have about you. Ask us how to do this.</li>
	<li>We will provide a copy or a summary of your health information, usually within 30 days of your request. We may charge a reasonable, cost-based fee.</li>
</ul>

<p><strong>Ask us to correct your medical record</strong></p>

<ul>
	<li>You can ask us to correct health information about you that you think is incorrect or incomplete. Ask us how to do this.</li>
	<li>We may say “no” to your request, but we’ll tell you why in writing within 60 days.</li>
</ul>

<p><strong>Request confidential communications</strong></p>

<ul>
	<li>You can ask us to contact you in a specific way (for example, home or office phone) or to send mail to a different address.</li>
	<li>We will say “yes” to all reasonable requests.</li>
</ul>

<p><strong>Ask us to limit what we use or share</strong></p>

<ul>
	<li>You can ask us not to use or share certain health information for treatment, payment, or our operations. We are not required to agree to your request, and we may say “no” if it would affect your care.</li>
	<li>If you pay for a service or health care item out-of-pocket in full, you can ask us not to share that information for the purpose of payment or our operations with your health insurer. We will say “yes” unless a law requires us to share that information.</li>
</ul>

<p><strong>Get a list of those with whom we’ve shared information</strong></p>

<ul>
	<li>You can ask for a list (accounting) of the times we’ve shared your health information for six years prior to the date you ask, who we shared it with, and why.</li>
	<li>We will include all the disclosures except for those about treatment, payment, and health care operations, and certain other disclosures (such as any you asked us to make). We’ll provide one accounting a year for free but will charge a reasonable, cost-based fee if you ask for another one within 12 months.</li>
</ul>

<p><strong>Get a copy of this privacy notice</strong></p>

<p>You can ask for a paper copy of this notice at any time, even if you have agreed to receive the notice electronically. We will provide you with a paper copy promptly.</p>

<p><strong>Choose someone to act for you</strong></p>

<ul>
	<li>If you have given someone medical power of attorney or if someone is your legal guardian, that person can exercise your rights and make choices about your health information.</li>
	<li>We will make sure the person has this authority and can act for you before we take any action.</li>
</ul>

<p><strong>File a complaint if you feel your rights are violated</strong></p>

<ul>
	<li>You can complain if you feel we have violated your rights by contacting us at privacy@curemydiabetes.com</li>
	<li>We will not retaliate against you for filing a complaint.</li>
</ul>

<h1>Your Choices</h1>

<p><strong>For certain health information, you can tell us your choices about what we share. </strong>If you have a clear preference for how we share your information in the situations described below, talk to us. Tell us what you want us to do, and we will follow your instructions.</p>

<p>In these cases, you have both the right and choice to tell us to:</p>

<ul>
	<li>Share information with your family, close friends, or others involved in your care</li>
	<li>Share information in a disaster relief situation</li>
	<li>Include your information in a hospital directory</li>
</ul>

<p><em>If you are not able to tell us your preference, for example if you are unconscious, we may go ahead and share your information if we believe it is in your best interest. We may also share your information when needed to lessen a serious and imminent threat to health or safety.</em></p>

<p>In these cases we never share your information unless you give us written permission:</p>

<ul>
	<li>Marketing purposes</li>
	<li>Sale of your information</li>
	<li>Most sharing of psychotherapy notes</li>
</ul>

<p>In the case of fundraising:</p>

<ul>
	<li>We may contact you for fundraising efforts, but you can tell us not to contact you again.</li>
</ul>

<p>&nbsp;</p>

<h1>Our Uses and Disclosures</h1>

<h2>How do we typically use or share your health information?</h2>

<p>We typically use or share your health information in the following ways.</p>

<p><strong>Treat you</strong></p>

<p>We can use your health information and share it with other professionals who are treating you.</p>

<p><em>Example: </em><em>A doctor treating you for an injury asks another doctor about your overall health condition.</em></p>

<p><strong>Run our organization</strong></p>

<p>We can use and share your health information to run our practice, improve your care, and contact you when necessary.</p>

<p><em>Example: We use health information about you to manage your treatment and services. </em></p>

<p><strong>Bill for your services</strong></p>

<p>We can use and share your health information to bill and get payment from health plans or other entities.</p>

<p><em>Example: We give information about you to your health insurance plan so it will pay for your services. </em></p>

<p>&nbsp;</p>

<h2>How else can we use or share your health information?</h2>

<p>We are allowed or required to share your information in other ways – usually in ways that contribute to the public good, such as public health and research. We have to meet many conditions in the law before we can share your information for these purposes.&nbsp;</p>

<p><strong>Help with public health and safety issues</strong></p>

<p>We can share health information about you for certain situations such as:</p>

<ul>
	<li>Preventing disease</li>
	<li>Helping with product recalls</li>
	<li>Reporting adverse reactions to medications</li>
	<li>Reporting suspected abuse, neglect, or domestic violence</li>
	<li>Preventing or reducing a serious threat to anyone’s health or safety</li>
</ul>

<p><strong>Do research</strong></p>

<p>We can use or share your information for health research.</p>

<p><strong>Comply with the law</strong></p>

<p>We will share information about you if state or federal laws require it.</p>

<p><strong>Respond to organ and tissue donation requests</strong></p>

<p>We can share health information about you with organ procurement organizations.</p>

<p><strong>Work with a medical examiner or funeral director</strong></p>

<p>We can share health information with a coroner, medical examiner, or funeral director when an individual dies.</p>

<p><strong>Address workers’ compensation, law enforcement, and other government requests</strong></p>

<p>We can use or share health information about you:</p>

<ul>
	<li>For workers’ compensation claims</li>
	<li>For law enforcement purposes or with a law enforcement official</li>
	<li>With health oversight agencies for activities authorized by law</li>
	<li>For special government functions such as military, national security, and presidential protective services</li>
</ul>

<p><strong>Respond to lawsuits and legal actions</strong></p>

<p>We can share health information about you in response to a court or administrative order, or in response to a subpoena.</p>

<h1>Our Responsibilities</h1>

<ul>
	<li>We are required by law to maintain the privacy and security of your protected health information.</li>
	<li>We will let you know promptly if a breach occurs that may have compromised the privacy or security of your information.</li>
	<li>We must follow the duties and privacy practices described in this notice and give you a copy of it.</li>
	<li>We will not use or share your information other than as described here unless you tell us we can in writing. If you tell us we can, you may change your mind at any time. Let us know in writing if you change your mind.</li>
</ul>

<h1>Changes to the Terms of this Notice</h1>

<h1>We can change the terms of this notice, and the changes will apply to all information we have about you. The new notice will be available upon request, in our office, and on our web site.</h1>

<h1>&nbsp;</h1>
</div>

          
        </div>
      </div>
    </div>
  </section>
  <section class="home-section home-section--get-started mb12">
    <div class="Background waves-footer"></div>
    <div class="Wrapper mw50 ta-center">
      <h2 class="f1 text-white">About Us</h2>
      <p class="mb6">CureMyDiabetes is an online specialty medical clinic that is on a mission to reverse type 2 diabetes in 100 million people. Learn how we are rethinking this epidemic.</p>
      <div class="Grid flex flex-justify-center">
        <div class="Cell l8"><a href="#" class="Button Button--primary">Learn more</a>
        </div>
      </div>
    </div>
  </section>
</main>