<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121432135-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121432135-1');
</script>
<main role="main">
  <section class="home-section home-section--audience">
    <div class="Wrapper mw75">
      <div class="Grid flex-space-between">
        <div class="Cell l8">
          <h1 class="f1 text-tint">Reason for Release of Information
          </h1>
          
          <!-- Comman Static Content -->
          <p>
	<strong>Last Updated&nbsp;</strong> : <em>March 16, 2018</em>
</p>

<div class="static-page-data">

<p>This Consent to Use of Telehealth Services (“Telehealth Consent”) is incorporated into the CureMyDiabetes Terms of Service (the “Terms of Service”).</p>


<ol>
	<li>You&nbsp;understand that CureMyDiabetes&nbsp;wishes&nbsp; to engage you in telemedicine consultations, including chat, voice and video communications.</li>
	<li>You understand that&nbsp;such a consultation will not be the same as a direct patient/health care provider visit due to the fact that you will not be in the same room as your care provider.</li>
	<li>You&nbsp;understand there are potential risks to this technology, including interruptions, unauthorized access and technical difficulties.&nbsp;&nbsp;</li>
	<li>You understand that your health care provider or &nbsp;can discontinue the telemedicine consult/visit if it is felt that the videoconferencing connections are not adequate for the situation.</li>
	<li>You understand that your healthcare information may be shared with other individuals for scheduling and billing purposes.&nbsp;&nbsp;Others may also be present during the consultation other than your health care provider and consulting health care provider in order to operate the equipment.&nbsp;&nbsp;The above mentioned people will all maintain confidentiality of the information obtained.&nbsp;</li>
	<li>You further understand that you will be informed of their presence in the consultation and thus will have the right to request the following: (1) omit specific details of my medical history/physical examination that are personally sensitive to me; (2) ask non‐medical personnel to leave the telemedicine examination room: and or (3) terminate the consultation at any time.</li>
	<li>You understand that some parts of the exam involving physical tests may be conducted by individuals at your location at the direction of the consulting health care provider.</li>
	<li>In an emergent consultation, you understand that the responsibility of the telemedicine consulting specialist is to advise your local practitioner and that the specialist’s responsibility will conclude upon the termination of the video conference connection. &nbsp;</li>
	<li>You represent that: a) That you&nbsp;have read or had this form read and/or had this form explained to me b)That you fully understand its contents including the risks and benefits of the procedure(s). c) That you&nbsp;have been given ample opportunity to ask questions and that any questions have been answered to my satisfaction. If you have any questions, please reach out to support@curemydiabetes.com</li>
	<li>You give your informed consent to the use of telehealth by Provider(s) using the Service under the terms described in the Terms of Service and this Telehealth Consent.</li>
</ol>
<p>&nbsp;</p>

</div>

          
        </div>
      </div>
    </div>
  </section>
  <section class="home-section home-section--get-started mb12">
    <div class="Background waves-footer"></div>
    <div class="Wrapper mw50 ta-center">
      <h2 class="f1 text-white">About Us</h2>
      <p class="mb6">CureMyDiabetes is an online specialty medical clinic that is on a mission to reverse type 2 diabetes in 100 million people. Learn how we are rethinking this epidemic.</p>
      <div class="Grid flex flex-justify-center">
        <div class="Cell l8"><a href="#" class="Button Button--primary">Learn more</a>
        </div>
      </div>
    </div>
  </section>
</main>