<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
	.hs-input{width:95% !important}
		#reading0, #reading, #reading1, #reading2, #reading3 {
display:none; }
	#myBtnread{font-weight:600;}
.icon-bar {
  position: fixed;
  top: 50%;left: 0px;z-index: 3;
  -webkit-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}

.icon-bar a {
  display: block;
  text-align: center;
  padding: 16px;
  transition: all 0.3s ease;
  color: white;
  font-size: 20px;
}
	.main-container{min-height: 69vh;
position: relative;
margin: 100px auto auto;
padding: 0px 0;padding-top: 30px;
float: left;
		width: 100%;}
</style>


<section>
  <div class="testimonialimage">
	  
	  
	  <div class="container-fluid">
		  <div class="sec-head">
   TESTIMONIALS
    </div>
		<div class="ourtestimonial">
			<div class="container">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
	<div class="containertestimonials">
  <img src="<?php echo $this->getSkinUrl('images/quotation-marks-left.png') ?>" alt="Avatar" style="width:24px">
  <span>Dr. Kiranjeet Kaur</span>
  <p>I lost 12 kgs on the Cure My Diabetes food program and my diabetes medications reduced. All with minimal exercise</p>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
</div>

<div class="containertestimonials">
  <img src="<?php echo $this->getSkinUrl('images/quotation-marks-left.png') ?>" alt="Avatar" style="width:24px">
  <span>Manoj Sangal</span>
  <p>I had been on a high dose of insulin since 2011. In 5 weeks of diligently adhering to the Cure my Diabetes program, I stopped taking insulin completely. As an add on, I also lost 10 kgs in 3 months.</p>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
</div>
		  
		  <div class="containertestimonials">
  <img src="<?php echo $this->getSkinUrl('images/quotation-marks-left.png') ?>" alt="Avatar" style="width:24px">
  <span>Aditya Dutt</span>
  <p>Went from Pre-Diabetic to Non-Diabetic in 1 month.18Kgs lost in 90 days</p>
			  
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>			  
</div>
		  
		  
		  <div class="containertestimonials">
  <img src="<?php echo $this->getSkinUrl('images/quotation-marks-left.png') ?>" alt="Avatar" style="width:24px">
  <span>Rajiv Gupta</span>
  <p>I have gotten a new innings in my life with Cure My Diabetes. They give very personalized care and take care of me. I have lost 15 kgs and my insulin has gone down to ¼.</p>
 <span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
</div>
		  
		  
		  
		
	</div>	
			
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
			
			    <div class="bookform">
          <h2>+BOOK APPOINTMENT </h2>
          
        <div id="657632826702082412" style="width: 100%; overflow-y: hidden;" class="wcustomhtml" align="left"><script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
<script data-hubspot-rendered="true">
  hbspt.forms.create({
	portalId: "5359263",
	formId: "1c6467c1-3ad3-4af1-819c-05dffadbaa22"
});
</script>
<div class="hbspt-form" id="hbspt-form-1554276053636-8202985449">
<iframe id="hs-form-iframe-0" class="hs-form-iframe" scrolling="no" 
style="position: static; border: medium none; display: block; overflow: hidden !important; width: 100% !important; height:100% !important;">

</iframe>
</div>
</div>
          </div>
				</div>
			</div>
		  </div>
</div>
</div>


</section>  
  
 