<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/shop-plans.css" type="text/css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<style>
		.list-inline > li#diabetes a{font-weight:500;}
		.list-inline > li#weightloss a{font-weight:500;}
		.list-inline > li#silver a{font-weight:600;}
		.list-inline > li#gold a{font-weight:500;}
		.list-inline > li#body-reboot a{font-weight:500;}
	.navbar-light .navbar-nav #nav-view-plan {
    background: rgb(26, 204, 205);
    color: #fff !important;
}
	.list-checkedplan p{font-size:1em}
.columnsplan {
    float: left;
    width: 33%;
    padding: 5px;
}
	.navbar-light .navbar-nav #nav-view-plan {
    background: rgb(26, 204, 205);
    color: #fff !important;
}
	.priceplan .headerplan{height:auto;}
* {
  box-sizing: border-box;
}
	
	.startingheight{height: 70px;
margin-top: 10% !important;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 17.5%;
text-align: center;
margin-top: 7.2%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;}
	.btn{font-weight:600; font-size:1.2em;}
.digitalbox {    height: 580px;
    margin-bottom: 40px;
}
	.analysis{height:520px}
@media only screen and (max-width: 600px) {
	.starting{margin-top: 12%;}
  .columnsplan {
    width: 100%;
  }
	.digitalbox {height:auto;}
	.analysis{height:auto;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 87%;
text-align: center;
margin-top:27%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;
background: #fff;}
}
	
</style>
<nav class="main-navigation">
			<ul class="plans-sub-nav-dt list-inline">
<li id="weightloss"><a href="<?php echo Mage::getBaseUrl();?>plans" class="text-white text-center">Weight Loss</a></li>
<li id="diabetes"><a href="<?php echo Mage::getBaseUrl();?>diabetes" class="text-white text-center">Diabetes</a></li>
<li id="silver"><a href="<?php echo Mage::getBaseUrl();?>thyroid" class="text-white text-center">Thyroid</a></li>
<li id="gold"><a href="<?php echo Mage::getBaseUrl();?>pcod" class="text-white text-center">PCOD</a></li>
<li id="body-reboot"><a href="<?php echo Mage::getBaseUrl();?>stayfit" class="text-white text-center">Stay Fit</a></li>
</ul>
	</nav>
<div class="southbeach shop-plans hero-bg"  id="top-cards">
	
<div class="container">
<h1 class="h2 text-center text-sentence fw-600 bot-mar-0">Choose the Thyroid Remission Plan That’s Best for You</h1>
	<h2 class="h4 text-center text-sentence fw-400">Our Thyroid Program Looks at Improving TSH, Reducing Weight, and<br>also at the 
Root Cause of <i>Why</i> Auto-Immune Disorder Started in the Body</h2>


		<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/metabolic.png') ?>" style="width: 50px;margin: auto;"/>
		Immunity <br> Report Card</li>
	    <li class="well text-center bg-white">
			<div  class="weekly-price-container">
			<h2>Rs 3,000</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Great for Those with Frequent Colds</p></li>
    <li class="greyplan"><a href="#" class="buttonplan" onclick="addtocartAndWelcome('1998')">Buy Now</a></li>
	 
	  
	   <ul class="list-checkedplan">
		   <p class=" text-left fw-600 list-head text-uppercase">Enhancing Your Immunity</p>
    <li>Learn what is Lacking in your Immunity</li>
    <li>Fend off Sickness and Increase Vitality</li>
    </ul>
  </ul>
</div>
	
	<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Menu.png') ?>" style="width: 50px;margin: auto;"/>
		Healthy Home <br>
Family Plan</li>
	    <li class="well text-center bg-white">
			
			<div  class="weekly-price-container">
				<p>Starting at</p>
			<h2>
			Rs 6,000/mo
			</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Reducing Risk Factors of Coronavirus</p></li>
    <li class="greyplan"><a href="familyplan" class="buttonplan">Select</a></li>
	 
	  
	   <ul class="list-checkedplan">
		   <p class=" text-left fw-600 list-head text-uppercase">Weight Loss + Immunity<br>Right From Home</p>
    <li>Boost Immunity for the Whole Family</li>
    <li>Lose Weight/Simplifies Task of Meal Planning </li>
    </ul>
  </ul>
</div>
	<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Menu.png') ?>" style="width: 50px;margin: auto;"/>
		Fit &amp; <br>
		Fabulous Plan</li>
	    <li class="well text-center bg-white">
			
			<div  class="weekly-price-container">
				<p>Starting at</p>
			<h2>
			Rs 4,000/mo
			</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Attacking the Root Cause of Obesity</p></li>
    <li class="greyplan"><a href="individualplan" class="buttonplan">Select</a></li>
	 
	  
	   <ul class="list-checkedplan">
		   <p class=" text-left fw-600 list-head text-uppercase">Scientific Approach<br>Looking Beyond Calories</p>
    <li>Validated by Over 300 Doctors</li>
    <li>Repairs Metabolism</li>
		   <li>Proven Results</li>
    </ul>
  </ul>
</div>
	

	
		<div class="columnsplan" style="display:none;">
			<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Basic.jpg') ?>" style="width: 50px;margin: auto;"/>Silver
Plan</li>
	  <li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs400 / Day </span></span><br>Rs 300 / Day</h2></li>  
	  <li class="greyplan"><a href="weightlosesilverplan" class="buttonplan">View Menu</a></li>
     <ul class="list-checkedplan">
      <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>1 Oil Free Salad Dressing and 2 Soups a day</li>
    </ul>
  </ul>
</div>
	<div class="columnsplan" style="display:none;">
		<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox"  style="pointer-events: none;opacity: 0.4;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/popular.png') ?>" style="width: 50px;margin: auto;"/>Gold Plan</li>
	<li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs700 / Day </span></span><br>Rs 600 / Day</h2></li> 
	<li class="greyplan"><a href="weightlosegoldplan" class="buttonplan">View Menu</a></li>
      <ul class="list-checkedplan">
     <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>Includes Pro Biotics</li>
    <li>2 Meals a day</li>
    </ul>
    
  </ul>
</div>

	</div>
	<div class="bg-white">
  <div class="container">
    <div class="row below-plan-sect">
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <h3 class="h4 text-secondary fw-600">With All Of Our Plans You'll :</h3>
        <ul class="list-checked pink-bullet">
          <li class="h6 fw-300">Lose weight and learn how to keep it off</li>
          <li class="h6 fw-300">Get A Dedicated Nutritionist</li>
          <li class="h6 fw-300">Pro Biotic Options for Gut Health</li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-5 col-lg-5">
        <hr class="visible-xs">
        <h3 class="h5 text-primary text-uppercase fw-600">Safe &amp; Healthy Weight Loss</h3>
        <ul class="list-checked blue-check">
          <li class="h6 fw-300">Keto-friendly options</li>
          <li class="h6 fw-300">Vegan, whole foods diet</li>
          <li class="h6 fw-300">No artificial sugars or sweeteners</li>
        </ul>
      
      </div>
    </div>
  </div>
</div>
	<div class="closer bg-secondary ">
  <div class="container ">
    <div class="row ">
      <div class="center-block no-float text-white col-xs-12 ">
        <div class="row ">
          <div class="text-wrapper col-xs-12 col-sm-6 col-md-4 col-md-offset-2">
            <h2 class="h3 text-white ">Get Healthier Today
</h2>
          </div>
          <div class="button-wrapper col-xs-12 col-sm-4 col-md-3" id="top"> <a href="#top-cards" class="btn btn-default scroll-to bg-white">Get It Now</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>
	</div>
<script>
	// Select all »a« elements with a parent class »links« and add a function that is executed on click
jQuery( '#top a' ).on( 'click', function(e){
	
  // Define variable of the clicked »a« element (»this«) and get its href value.
  var href = jQuery(this).attr( 'href' );
  
  // Run a scroll animation to the position of the element which has the same id like the href value.
  jQuery( 'html, body' ).animate({
		scrollTop: jQuery( href ).offset().top
  }, '300' );
	
  // Prevent the browser from showing the attribute name of the clicked link in the address bar
  e.preventDefault();

});
</script>