<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/silverform.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/ratecard_min.css" type="text/css"/>

<nav class="main-navigation">
			<ul class="plans-sub-nav-dt list-inline">
<li id="body-reboot"><a href="<?php echo Mage::getBaseUrl();?>plans" class="text-white text-center">Weight Loss</a></li>
<li id="silver"><a href="<?php echo Mage::getBaseUrl();?>thyroid" class="text-white text-center">Thyroid</a></li>
<li id="gold"><a href="<?php echo Mage::getBaseUrl();?>pcod" class="text-white text-center">PCOD</a></li>
<li id="body-reboot"><a href="<?php echo Mage::getBaseUrl();?>diabetes" class="text-white text-center">Diabetes</a></li>
<li id="diabetes"><a href="<?php echo Mage::getBaseUrl();?>stayfit" class="text-white text-center">Stay Fit</a></li>
</ul>
	</nav>
<main id="content" tabindex="-1" class=" silver-plan">
<div id="pane">

<section class="hero full-img" id="orderOptions"> 
<div class="container">
<div class="intro-text-wrapper"> 
<img src="<?php echo $this->getSkinUrl('images/Basic.jpg') ?>" class="silver-icon" alt=""> 
<h1 class="h2 fw-600 text-center">Silver Plan</h1> 
<h2 class="text-center h3"><em>OUR PLANS ARE SIMPLE, CONVENIENT AND DELICIOUS</em></h2>
</div> 
<div id="product-pane">	
<div class="product-image no-float full-img col-xs-12 col-md-12 col-sm-12 col-xl-7">
<p class="text-center text-uppercase"><strong>Oil Free</strong> & Vegan </p> 
</div>
<div class="product-info no-float col-xs-12 col-sm-12 col-md-12 col-xl-5"> 				
<div class="text-wrapper"> 					
	<h3><span class="highlight">Customize Your Plan</span></h3>  					
	<!-- pane1-main-content --> 					
<form method="POST" id="testForm" name="testForm" class="ordering-options"> 						
<fieldset id="gender-options"> 							
<legend> <strong>1. Your Meal Plan</strong> 
<a data-target="#rebootModal" data-toggle="modal" href="#rebootModal" id="reboot-modal" class="text-medium text-right pull-right" onclick="omni_track('LearnMore')">What's included?</a> 
</legend> 							
	<div class="btn-group" role="group"> 								
<span  class="btn-interstitial text-futura selected"   option-id="3" option-type-id ="6"  value="women" id="women" name="gender" aria-pressed="true"
 onclick="selectGender('women');">Women</span> 
<span  class="btn-interstitial text-futura unselected" option-id="3" option-type-id ="7" value="men" id="men" name="gender" aria-pressed="false"
onclick="selectGender('men');"
>Men</span> 	
			</div> 						
</fieldset> 						
<fieldset id="meal-plan-options"> 							
<legend> 
<strong>2. Your Menu</strong> 
<a data-target="#chooseMenu" data-toggle="modal" href="#chooseMenu" id="choose-menu" class="text-medium text-right pull-right" onclick="omni_track('FindOutWhy')">Which is best for me?</a> 
</legend> 							
<div class="btn-group" role="group"> 								
<span  class="btn-interstitial text-futura selected" option-id="2" option-type-id ="4" onclick="selectMenu(this.id);" value="favorite" id="favorite" name="mealplan" aria-pressed="true">
<span class="text-uppercase best-first" >Best for 1st Order</span> Chef’s Picks
</span> 								
<span  class="btn-interstitial text-futura unselected" option-id="2" option-type-id ="5" onclick="selectMenu(this.id);" value="custom" id="custom" name="mealplan" aria-pressed="false">I’ll Pick My Menu</span> 							
</div> 						
</fieldset> 						
<fieldset id="delivery-options" class="form-group"> 						
<legend id="delivery-options-legend" class="pull-left text-sentence">
<strong>3. Delivery:</strong> 
<span>Monthly Doorstep Delivery</span>
</legend> 							
	<a id="choose-delivery" aria-controls="delivery-options" class="text-medium edit pull-right" href="javascript:void();"  tabindex="0" onclick="myFunctionedit()">Edit</a> 
	<a id="delivery-options-link" class="text-medium" data-target="#difference" data-toggle="modal" href="#"  style="display:none;" onclick="omni_track('WhatsTheDifference')">What's the difference?</a> 							 							 												  							
<div id="delivery-options-collapse" style="display:none;"> 								
<div class="btn-group" role="group"> 									 									
<span  class="btn-interstitial unselected btn-block text-futura fw-700" option-id="1" option-type-id ="1" value="autodelivery" id="10day" onclick="delivery(this.id);" name="delivery" aria-pressed="true">
<span class="ship-btn-txt">10 Day Trial</span><span class="del-price fw-300"><sup>Rs</sup>1200 <br aria-hidden="true"><span class="del-a-day">/ Day</span></span>
</span> 								
<span  class="btn-interstitial btn-block text-futura fw-700 selected" option-id="1" option-type-id ="2" value="month2month" id="1month"  onclick="delivery(this.id);" name="delivery" aria-pressed="false">
<span class="ship-btn-txt">1 Month Delivery</span><span class="del-price fw-300"><sup>Rs</sup>1100 <br aria-hidden="true"><span class="del-a-day">/ Day</span></span>
</span> 	
<span  class="btn-interstitial btn-block text-futura fw-700 unselected" option-id="1" option-type-id ="3" value="month2month" id="2month"  onclick="delivery(this.id);" name="delivery" aria-pressed="false"><span class="ship-btn-txt">3 Month Delivery<br>Get 4th Month Free</span><span class="del-price fw-300"><sup>Rs</sup>1100 <br aria-hidden="true"><span class="del-a-day">/ Day</span></span>
</span> 	
</div> 							
</div> 	
</fieldset> 					
<div class="row price-container"> 							
<div class="col-xs-4  no-pad-left"> 								
<div class="dailyprice text-center"> 	
<div class="price"><sup>Rs</sup><span id="planprice">1100</span></div> 							
<div class="fw-300 a-day">per Day</div> 						
</div> 							
</div>						
<div class="col-xs-8 no-pad-right no-pad-left"> 								
<div id="autodelivery-price"> 
								
<p id="DeliveryText" class="text-medium pane1price">30 Days Price: <s><span class="sr-only">price was</span><span class="itemListPrice">Rs 36,000</span></s>
<span class="sr-only">now</span><strong><span class="orderAmountStr">Rs 33,000</span></strong>
 </p> 
 
<p id="autodelivery-price-text" class="text-medium"  style="display:none;">
	Auto-delivery savings applied
	<br class="hidden-xs" aria-hidden="true"> 
	to each monthly shipment.
	<span class="pane1weekprice"> 
	<a href="#" onclick="omni_track('DeliverySavingsDetails')" data-target="#difference" class="" data-toggle="modal">Details</a> 
	</span> 									
</p> 								
</div> 								
<div id="month2month-price" style="display: none;"> 									
<p class="text-medium one-time-ship pane1price">One-Time 4-Week Price: <span class="orderAmountStr">$553.83</span> Priced at full retail value.
<span class="pane1weekprice"> 
<a href="#" onclick="omni_track('WhatsTheDifference')" data-target="#difference" class="" data-toggle="modal">Details</a>
</span>
</p> 								
</div> 								 								
<p class="free-ship-txt text-uppercase text-medium text-purple-lighter no-margin" style="display: none;">free shipping</p> 							
</div> 	
</div>
</form> 			 
<!-- Name:	rc_xs_prod_silvgold_chkbox_cnt id:	rc_xs_prod_silvgold_chkbox_cnt -->
<!-- key: rc-cross-sell-selection -->

    					
	
<input type="submit" value="CONTINUE" class="btn btn-default btn-block btn-lg" onclick="checkSelected()"> 									
<!-- Start Auto Delivery Copy --> 					
<p class="text-medium text-center exp-del-over">Expect delivery within 1-2 business days. 
<a href="#expectDelivery" data-toggle="modal" data-target="#expectDelivery" class="" onclick="omni_track('deliveryDetailsOverlay')">details</a>
</p> 				
</div> 			
</div> 		
</div> 	
</div> 
</section>
<div class="reboot-modal modal fade" id="rebootModal" tabindex="-1" role="dialog" aria-labelledby="reboot-modal" style="display: none;">         
	<div class="modal-dialog" role="document">             
	<div class="modal-content">                 
	<div class="modal-header">                     
	<button type="button" class="close" data-dismiss="modal" aria-label="Close">                         
	<span class="mobile-close" aria-hidden="true">×</span>                   
	</button>                     
	<h4 class="modal-title">What’s Included in Your Plan?</h4>                 
	</div>                 
	<div class="modal-body">                     
                  
	<ul class="list-checked check-primary">                       
    <li>
	<strong>10 Day Trial Pack</strong>                             
	       <ol>
		<li>Our oil-free trial pack includes 10 days of breakfast, lunch, high-tea, and dinner. As we all crave some sweetness, dinner also includes a dessert!</li>
		    <li>You'll be receiving your order which includes dinner for the same day, breakfast, lunch and high-tea snack for next day.</li>
			<li>Remember : it takes 2-3 days for meal calibration - is the food more / less than required</li>
			<li>You don't necessary have to finish the meals, eat till you are 80% full</li>
			<li>Meals are designed to fully support your health goals. We'll guide you throughout with helpful tips specific to your plan.</li>
	</ol> 
	</li>                      
	<li> 
	<strong>Silver Plan</strong>         
		<ol>
	   <li>Includes 1 fresh oil-free dressing and 2 soups of choice per day  </li>
		<li>Everyday fresh food will be delivered to your doorstep between 3-7pm.</li>
		<li>Based on your health goals, customized recipes and nutrition guidance for rest of the day will be provided</li>
		<li>Meals are designed to fully support your health goals. We'll guide you throughout with helpful tips specific to your plan.</li>
		</ol>
		</li>  
	                    
	</ul>                 
	</div>                 
	<div class="modal-footer">                     
	<button type="button" class="btn btn-info btn-block visible-xs" aria-label="Close" data-dismiss="modal">         
		<span class="mobile-close" aria-hidden="true">×</span> Close                     
	</button>                
	</div>             
	</div>         
	</div>     
	</div>
<div class="chooseMenu-modal modal fade" id="chooseMenu" tabindex="-1" role="dialog" aria-labelledby="menu" style="display: none;">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="mobile-close" aria-hidden="true">×</span></button>
               <h4 class="modal-title" id="menu">Which is best for me?</h4>
            </div>
            <div class="modal-body">
               <p><strong class="text-secondary">OURS PICK—<em>Best for your first
                        order!</em></strong></p>
               <ul class="list-checked check-secondary">
                  <li>We did the work for you by selecting your meals based on your nutritional requirements- save time and start seeing health benefits!</li>
                  <li>You'll receive a weblink where you can mark your favorites and also the items you want to try.</li>
                  <li>You can discover your favorites and customize future meals.</li>
				   <li>If you opt to pick your menu for first order, please NOTE that the first meal will be selected specially for you for the initial delivery, and future choices you may select.</li>
               </ul>
              
            </div>
            <div class="modal-footer" style="display:none;"> <button class="btn btn-default btn-block-mobile close-modal" type="button" id="check-chef-picks" onclick="chooseMealPlan('favorite'); omni_track('getChefsPicksOverlay')">Get
                  Chef’s Picks</button><br> <button type="button" class="btn btn-info btn-block-mobile visible-xs" aria-label="Close" data-dismiss="modal"><span class="mobile-close" aria-hidden="true">×</span> Close</button> </div>
         </div>
      </div>
   </div>
<div class="modal fade" id="expectDelivery" tabindex="-1" role="dialog" aria-labelledby="expectDelivery" style="display: none;">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span class="mobile-close" aria-hidden="true">×</span>
</button>
<h4 class="modal-title">How is my order shipped?</h4>
</div>
<div class="modal-body">
<ul>
<li>Your daily meal ships FREE and will be delivered to your home between 3-7pm by our delivery executives.</li>
	<li>We maintain cold chain throughout the packaging and delivery process.</li>
	<li>We maintain the highest hygiene levels with masks and gloves at all times.</li>
	<li>As soon as we prepare the food, we bring it to 4°C before packing and deliver at same temperature.</li>
	<li>For diabetic patients - delivery executive will bring a reader to scan the CGM sensor.</li>
	<li>Express lunch delivery will be delivered at your address by 1pm.</li>
</ul>
	
</div>
<div class="modal-footer">
 <button type="button" class="btn btn-info btn-block visible-xs" aria-label="Close" data-dismiss="modal">
<span class="mobile-close" aria-hidden="true">×</span> Close
</button>
 </div>
</div>
</div> 
	</div>
<div class="plan-claim">
   <div class="container">
       <div class="row">
           <div class="col-xs-12 col-sm-6 col-md-6 col-xl-6">
               <p class="h1">Lose up to <strong class="text-phase2">10 Kgs</strong> in<br aria-hidden="true"> your first <strong class="text-phase2">30 Days</strong></p>
               <p class="h3">And Learn What Truly Affects Your Weight</p>
               <p class="small">In a review avg. weight loss for first month was 6 Kgs</p>
           </div>
       </div>
       <span class="sr-only">2 women laughing at the beach</span>
       <div class="row">
           <div class="col-xs-12 hidden-lg">
               <div class="claim-img-mob"></div>
           </div>
       </div>
   </div>
</div>
<div class="typical-day">
 <div class="container">
    <h2 class="text-center"><strong class="highlight"><span>Eat Deliciously.&nbsp;<span class="hidden-md hidden-lg"><br aria-hidden="true">&nbsp;</span>Feel Full and Satisfied!</span></strong></h2>
	 <p class="text-center sub-head">SEE A SAMPLE OF A DAY'S MEAL ON THE WEIGHT LOSS PLAN <br> All The Food Below is Oil Free</p>
  
    <div class="text-center collapse-link">
       <a role="span" class="read-more-link collapsed" data-toggle="collapse" href="#typicalDayCollapse" aria-expanded="false" aria-controls="typicalDayCollapse" onclick="omni_track('SeeWhatsCooking');">
          <img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt="open">
          <img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt="close">
          <strong>more of the menu</strong></a></div>
    <div class="collapse" id="typicalDayCollapse">
       <div class="row"> 
       <!-- breakfast -->
          <div class="col-xs-12 col-sm-6 col-sm-push-6 breakfast-text">
             <hr class="meal-time">
             <h3 class="text-uppercase">Breakfast</h3>
             <p>Red Rice Idli With Sambhar</p>
			 <p>Fresh Made Almond Milk or </p>
             <p>Turkish Kefir (A Pro Biotic drink)</p>
		   </div>
          <div class="col-xs-12 col-sm-6 col-sm-pull-6 breakfast">
             <img src="<?php echo $this->getSkinUrl('images/silver-breakfast-typ-day-2019.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
          <!-- lunch -->
          <div class="col-xs-12 col-sm-6 lunch-text">
             <hr class="meal-time lunch-rule">
             <div class="clearfix"></div>
             <h3 class="text-uppercase">Lunch</h3>
             <p>Apple & Arugula Salad with Fresh Dressing</p>
             <p>Tomato Basil Soup</p>
			  <p>Hing Matar ke Kabab</p>
			  <p>Shaahi Paneer (Vegan)</p>
			  <p>Low Carb Atta Rot</p>
			  <h3 class="text-uppercase">Snack</h3>
             <p>Whole Grain Momo</p>
		   </div>
          <div class="col-xs-12 col-sm-6 lunch">
             <img src="<?php echo $this->getSkinUrl('images/silver-lunch-typ-day-2019.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
          <!-- dinner -->
          <div class="clearfix"></div>
          <div class="col-xs-12 col-sm-6 col-sm-push-6 dinner-text">
             <hr class="meal-time dinner-rule">
             <h3 class="text-uppercase">Dinner</h3>
             <p>Spiralized Vegetable Salad with Fresh Dressing</p>
			  <p>Cream Of Carrot Soup (Vegan)</p>
			  <p>Bhindi Tak a Tak</p>
			  <p>Daal Makhani</p>
			  <p>Brown Rice & Quinoa Pulao</p>
             <h3 class="text-uppercase">Dessert</h3>
             <p>Fruit Cream (Vegan & No Sugar or Sweetener)</p>
		   </div>
          <div class="col-xs-12 col-sm-6 dinner col-sm-pull-6">
             <img src="<?php echo $this->getSkinUrl('images/gold-dinner-2019.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
          <div class="container visible-xs">
            <div class="col-xs-12 text-center">
              <a data-target="#moreMenuModal" data-toggle="modal" href="#moreMenuModal" id="moremenu-modal-mob" onclick="omni_track('MoreMenuMbl')" class="btn btn-default bg-white btn-menu">More of the Menu</a>
            </div>
         </div>
       </div>
    </div>
 </div>
</div>
<div class="plus-sect">
 <div class="container">
 <div class="plus-sect-wrap">
    <div class="col-xs-12 col-sm-6 col-md-4 plus-bg">
       <div class="plus-wrap"><span class="caveat">Bonus!</span></div>
       <h3 class="text-uppercase fw-700 h5">Enjoy to cook at home <br aria-hidden="true"> or enjoy a meal out?</h3>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 desc plus-bg">
       <h4 class="fw-400 h6">Prepare you favorite meal with our customized recipes or have your dedicated nutritionist coach you as to what you can eat when you need to or want to step out</h4>
    </div>
 </div>
 </div>
 <div class="container hidden-xs">
   <div class="col-xs-12 text-center">
     <a data-target="#moreMenuModal" data-toggle="modal" href="#moreMenuModal" id="moremenu-modal" onclick="omni_track('MoreMenu')" class="btn btn-default bg-white btn-menu">More of the Menu</a>
   </div>
 </div>
</div>
<div class="more-menu-modal modal fade" id="moreMenuModal" tabindex="-1" role="dialog" aria-labelledby="reboot-modal" style="display: none;">
   <div class="modal-dialog" role="document">
       <div class="modal-content">
           <div class="modal-header">
               <span type="span" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">
                      <img src="http://lifeheal.americanarearugs.com/skin/frontend/rwd/default/images/x-circle-icon.svg" class="center-block x-circle" alt="close" style="width: 30px;">
                   </span>
               </span>
               <h4 class="modal-title">Delicious Meals. Delicious Variety!</h4>
           </div>
           <div class="modal-body">
               <p class="ms-margin-btm">Check out some of the delicious menu variety you’ll enjoy on the Gold and Platinum Plan:</p>
               <p><strong>Breakfasts</strong><br>
               <ul>
			   <li>Red Rice Idli with Sambhar + Chutney</li>
			    <li>Egg White Frittata</li>
			    <li>Dal chilla with Vegetable Stuffing</li>
			    <li>Red Rice Poha</li>
			    <li>Vegan Keema Parantha with Green Vegetable & Oil Free Pickle</li>
			   </ul>
			   </p>
			   <p><strong>Beverages</strong><br>
				  <ul>
		         <li> Almond Milk, Turkish Kefir, Green Smoothie</li>
		        </ul>
			   </p>			   
               <p><strong>Lunches</strong><br>
               <ul>
			   <li>Mixed Greens with Seeds and Fresh Dressing, Mushroom Soup, Jalfrezi, Shahi Paneer, Lauki Roti, Probiotic</li>
			    <li>Kuchumber Salad, Dal Soup, Beetroot & Tofu Kebab</li>
			    <li>Minestrone Soup, Sauteed Herbed Vegetables, Tofu Steak with Bar-be-que Sauce</li>
			    <li>Apple & Arugula Salad, Tomato Shorba, Nizami Handi Sabji, Vegan Kadhi, Lauki Roti, Probiotic</li>
			    <li>Shredded Bokchoy Salad, Clear Lemon & Coriander Soup, Vegetable in Garlic Sauce,  Quinoa and Brown Fried Rice</li>			   
			   </ul>	  
               </p>
			    <p><strong>Snacks</strong><br>
			    <ul>
			   <li>Wholegrain Momos</li>
			    <li>Matara Chaat</li>
			    <li>Ragi Nachos with Fresh Salsa Dip</li>
			    <li>Multigrain Cookies</li>
			    <li>Savory Namkeens</li>			    
			   </ul>	
			   </p>
               <p><strong>Dinners</strong><br>
               <ul>
			   <li>Italian Vegetable Soup, Sauteed Vegetable, Homemade Fresh Pasta with Pesto Sauce</li>
			    <li>Spiralized Salad, Tom Yum Soup, Red Thai Curry, Steamed Rice with Quinoa</li>
			    <li>Cucumber & Tomato Salad, Cream of Carrot Soup, Bhindi Takatak, Dal Makhani, Brown Rice & Quinoa Biryani</li>
			    <li>Som Tam Salad, Manchow Soup, Manchurian with Gravy, Veggie Noodles, Wholegrain Momos</li>
			    <li>Pickled Vegetable Salad, Spinach Soup, Cauliflower Mash, Garlic Herb Chicken with Redwine Sauce</li>
			   </ul>
	           </p>
           </div>
           <div class="modal-footer">
               <span type="span" class="btn btn-info btn-block visible-xs" aria-label="Close" data-dismiss="modal">
                   <span class="mobile-close" aria-hidden="true">×</span> Close
               </span>
           </div>
       </div>
   </div>
</div>
<div class="faqs">
<div class="container">
 <h2 class="h4 text-center fw-600"><strong class="highlight"><span>Frequently Asked Questions</span></strong></h2>
 <div class="row">
   <div class="col-lg-10 col-md-12 col-lg-offset-1">
     <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingOne">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseOne" aria-expanded="false" aria-controls="faq-collapseOne" onclick="omni_track('Faq1');">Will I be hungry on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingOne">
           <div class="panel-body">
			   <p>On any LHF Plan, you will be eating a variety of nutrient dense—high in protein and healthy fat—foods throughout the day to help keep you feeling full. Our portion is also surprisingly large, and most clients say they are unable to finish their entire meals.  If you feel that you are still hungry after eating all the food on your recommended meal plan, you have the flexibility to enjoy additional servings of snacks recommended by your dedicated dietician.</p>
             </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingTwo">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseTwo" aria-expanded="false" aria-controls="faq-collapseTwo" onclick="omni_track('Faq2');">Do the LHF foods taste good?</a></h3>
         </div>
         <div id="faq-collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingTwo">
           <div class="panel-body">
             <p>LHF offers a wide variety of delicious, healthy breakfasts, lunch and dinner entrées, and sweet and savory snacks, in a range of globally inspired flavors that you’ll love, including Indian, Mughlai, Chinese, Continental, and Italian. Our head chefs are formerly 5 star restaurant chefs, and along with our founder who is a food expert, taste will never be compromised. </p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingThree">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseThree" aria-expanded="false" aria-controls="faq-collapseThree" onclick="omni_track('Faq3');">Is LHF a Keto diet?</a></h3>
         </div>
         <div id="faq-collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingThree">
           <div class="panel-body">
             <ul>
			   <li>As keto continues to be a growing trend in the health and wellness world, we’ve created some Keto options in our LHF plan to help people lose weight.</li>
				 <li>Depending on your requirements, we have different levels of Keto-Friendly foods. This means you’ll enjoy more quality carbs, higher protein levels and more food variety, including foods that are off-limits on the keto diet like milk, whole grains and beans.</li>
				 <li>Our keto–friendly approach to weight loss delivers below 50 grams of net carbs per day. (Net carbs are the total carbohydrates in a food or beverage, minus dietary fiber and erythritol, a type of sugar alcohol.)</li>
				 <li>While LHF is a low-carb, good-fat approach, it’s not “strict keto” or intended to allow individuals to achieve or maintain nutritional ketosis.</li>
				 
			   </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFour">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFour" aria-expanded="false" aria-controls="faq-collapseFour" onclick="omni_track('Faq4');">Is the LHF Program gluten-free?</a></h3>
         </div>
         <div id="faq-collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFour">
           <div class="panel-body">
             <p>Although LHF does not currently offer certified gluten-free foods, we do offer menu items that do not include gluten ingredients, and can customize further with your dedicated nutritionist. 
</p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFive">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFive" aria-expanded="false" aria-controls="faq-collapseFive" onclick="omni_track('Faq5');">Can a vegan be on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFive">
           <div class="panel-body">
             <p>Yes, LHF is very aligned with a Vegan diet and can be further customized with your dedicated nutritionist.</p>
           </div>
         </div>
       </div>  
	      </div>
   </div>
 </div>	
	 
    <div class="collapse" id="faqCollapse">
       <div class="row" style="padding-top:0px;"> 
		      <div class="col-lg-10 col-md-12 col-lg-offset-1">
     <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingSix">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseSix" aria-expanded="false" aria-controls="faq-collapseFive" onclick="omni_track('Faq6');">What to do if I cheat or feel like cheating on the Program?
</a></h3>
         </div>
         <div id="faq-collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingSix">
           <div class="panel-body">
             <ul>
			   <li>We understand cravings occur. If you do “cheat” please inform your dedicated nutritionist. She will adjust your calories for the day to help you stay within your health goals. She can also offer advice on how to avoid cheating again in the future or substitute options to satiate the same craving. Don’t worry, you will not be reprimanded, rather coached to discourage the same thing happening too often.</li>
			   <li>If you feel like “cheating”, let your nutritionist know which craving you have, and she will offer you healthier substitute options or even customize your plan to include a healthier version of your craving.</li>
			   </ul>
           </div>
         </div>
       </div> 	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingSeven">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseSeven" aria-expanded="false" aria-controls="faq-collapseSeven" onclick="omni_track('Faq7');">Is the LHF food only what I'm supposed to eat all day if I'm on full meals?</a></h3>
         </div>
         <div id="faq-collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingSeven">
           <div class="panel-body">
             <p>To maximize disease reversal and weight loss, yes, you should ideally only be eating the food from your LHF Program. Even with the best of intentions, our home cooked food ends up being too high in carbohydrates or unhealthy fats. So to truly achieve your goals from LHF, please stick as close to the plan as possible.</p>
           </div>
         </div>
       </div> 
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingEight">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseEight" aria-expanded="false" aria-controls="faq-collapseEight" onclick="omni_track('Faq8');">What if I have to attend a social event or want to eat out?</a></h3>
         </div>
         <div id="faq-collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingEight">
           <div class="panel-body">
             <ul>
			   <li>We understand social commitments will happen as well as the desire to eat out once in a while. If you do eat out please inform your dedicated nutritionist. She will adjust your calories for the day to help you stay within your health goals. She can also offer advice on how to make healthy choices while eating out in a restaurant or at a social event. </li>
				 <li>Your dedicated nutritionist can also share healthy recipes for your favorite dishes so you can occasionally cook at home. </li>
			   </ul>
           </div>
         </div>
       </div>
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingNine">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseNine" aria-expanded="false" aria-controls="faq-collapseNine" onclick="omni_track('Faq9');">What are probiotics and why should I consume them?</a></h3>
         </div>
         <div id="faq-collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingNine">
           <div class="panel-body">
             <p>Probiotics are live microorganisms that may be able to help prevent and treat some illnesses. Promoting a healthy digestive tract and a healthy immune system are their most widely studied benefits. These are also commonly known as friendly, good, or healthy bacteria. LHF incorporates probiotics into our meals to keep your body, specifically your gut, as healthy as possible, which is now known to play a very important role in overall health. </p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingTen">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseTen" aria-expanded="false" aria-controls="faq-collapseTen" onclick="omni_track('Faq10');">Can I drink alcohol on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapseTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingTen">
           <div class="panel-body">
             <p>The LHF principles do allow minimal alcohol: it is recommended to limit consumption to 2 servings per week and pay attention to portion sizes. Choose only dry wines and avoid sweet wines and wine coolers, as they provide more sugar and carbohydrates. Limit beer to light beers to keep the carbohydrates lower and avoid serving liquor with high sugar mixers. Also discuss with your dedicated nutritionist so she may adjust your calories to maintain your health goals. 
</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading11">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse11" aria-expanded="false" aria-controls="faq-collapse11" onclick="omni_track('Faq11');">How many times can I eat non-veg?</a></h3>
         </div>
         <div id="faq-collapse11" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading11">
           <div class="panel-body">
             <p>For patients on insulin, we do not recommend consuming non-veg, but if you are truly craving it, speak with your dedicated nutritionist so she may coach you and offer some more options.  If you are not diabetic, we recommend having non-veg not more than 1-2 times a week.
 </p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading12">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse12" aria-expanded="false" aria-controls="faq-collapse12" onclick="omni_track('Faq12');">Are there restrictions on who can use the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse12" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading12">
           <div class="panel-body">
             <ul>
			   <li>Under 18 years of age without parental supervision</li>
				 <li>Allergies: NUTS, SOY, LATEX</li>
				 <li>Anorexia, Bulimia Nervosa</li>
				 <li>Breastfeeding an Infant under 4 month of age</li>
				 <li>Celiac disease</li>
				 <li>Congestive Heart Failure</li>
				 <li>Dialysis</li>
				 <li>Hypoglycemia</li>
				 <li>Kidney Disease, Renal Disease, Renal Failure</li>
			   <li>Pregnancy without OB supervision	</li>
				 <p>*This list is not exhaustive. Other medical conditions exist that may restrict you from following the LHF Program. You should consult with your healthcare provider before beginning this or any diet program.</p>
			   </ul>
           </div>
         </div>
       </div>	   
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading13">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse13" aria-expanded="false" aria-controls="faq-collapse13" onclick="omni_track('Faq13');">What does the LHF Program Include?</a></h3>
         </div>
         <div id="faq-collapse13" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading13">
           <div class="panel-body">
             <p>Depending on which program you choose, you will receive your respective number of meals, delivered for FREE, and all you have to do is eat! The weight loss and disease reversal programs include regular consulting with a dedicated nutritionist and all meals. LHF shares your journey and is committed to your success. </p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading14">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse14" aria-expanded="false" aria-controls="faq-collapse14" onclick="omni_track('Faq14');">What is the LHF Program? How does the plan work?</a></h3>
         </div>
         <div id="faq-collapse14" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading14">
           <div class="panel-body">
             <p>Our passion is to help as many people as possible reverse their disease, lose weight, and stay healthy and fit.  We also aim to teach our clients how to live a high-quality, healthy life, without hunger or deprivation. The LHF Program is a safe, effective method of disease remission, weight loss, and introduces easy-to-follow principles that allow people to enjoy eating and achieve optimal health. LHF will deliver your customized meals for FREE. You have to simply heat and eat!
</p>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading15">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse15" aria-expanded="false" aria-controls="faq-collapse15" onclick="omni_track('Faq15');">How can I pause my subscription when I am traveling?</a></h3>
         </div>
         <div id="faq-collapse15" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading15">
           <div class="panel-body">
             <p>Yes. Please give your dedicated nutritionist 48 hours notice of when you need your food subscription paused and restarted. Since we plan your meals well in advance and procure the necessary grocery items for your meal specifically, we require 48 hour notification. Less than that and we will have to charge you for that day’s food as the grocery items would have already been purchased. To restart after traveling, please also try to inform us 48 hours in advance</p>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading16">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse16" aria-expanded="false" aria-controls="faq-collapse16" onclick="omni_track('Faq16');">How can I pause my subscription when I am traveling?</a></h3>
         </div>
         <div id="faq-collapse16" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading16">
           <div class="panel-body">
             <p>Yes. Please give your dedicated nutritionist 48 hours notice of when you need your food subscription paused and restarted. Since we plan your meals well in advance and procure the necessary grocery items for your meal specifically, we require 48 hour notification. Less than that and we will have to charge you for that day’s food as the grocery items would have already been purchased. To restart after traveling, please also try to inform us 48 hours in advance</p>
           </div>
         </div>
       </div>
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading17">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse17" aria-expanded="false" aria-controls="faq-collapse17" onclick="omni_track('Faq17');">Can I do the LHF Program if I have diabetes?</a></h3>
         </div>
         <div id="faq-collapse17" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading17">
           <div class="panel-body">
             <p>Yes, this is actually our most popular program. please choose the Diabetes Program (this should be a clickable link)  from the disease reversal program options. </p>
           </div>
         </div>
       </div>
	   
	 
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading18">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse18" aria-expanded="false" aria-controls="faq-collapse18" onclick="omni_track('Faq18');">How is "Stay Fit" different from the other LHF Programs?</a></h3>
         </div>
         <div id="faq-collapse18" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading18">
           <div class="panel-body">
             <p>Our Stay Fit Program (clickable link) is ideal for those who want to have 1-2 healthful meals during the day, but not our full weight loss or disease reversal programs. This program is recommended for clients who have successfully met their weight loss or disease remission goals and want to maintain a healthful diet. Stay fit is also recommended for people who want to stay as healthy as possible and maintain their weight and maximize nutrition levels. </p>
           </div>
         </div>
       </div>
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading19">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse19" aria-expanded="false" aria-controls="faq-collapse19" onclick="omni_track('Faq19');">Do I have to exercise on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse19" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading19">
           <div class="panel-body">
             <p>Exercise is encouraged on the LHF Program for optimal health, but is not required. We recommend at least 30 minutes of activity each day as it is important to move your body and stay active. This can even be light yoga or evening walks.</p>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading20">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse20" aria-expanded="false" aria-controls="faq-collapse20" onclick="omni_track('Faq20');">How much weight will I lose on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse20" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading20">
           <div class="panel-body">
             <ul>
			   <li>Experts agree that losing 0.5-1 kg per week is a healthy and sustainable weight loss range, and you can expect to lose weight within this range on the LHF Weight Loss Program (clickable link)</li>
			   <li>On average, participants on the LHF Program lose an average of 6 kg per month.</li>
			   </ul>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading21">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse21" aria-expanded="false" aria-controls="faq-collapse21" onclick="omni_track('Faq21');">Is there a LHF maintenance program?</a></h3>
         </div>
         <div id="faq-collapse21" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading21">
           <div class="panel-body">
             <p>Yes. After you have reached your disease reversal or weight loss goal, you can transition to the Stay Fit (clickable link) Program. Also, throughout your full plan, your dedicated nutritionist will have helped you to understand how to make good food choices, how to prepare healthful meals at home and will also offer you to stay on a consulting only package. You can also purchase some products (Clickable link) directly from LHF to aid you in food preparation at home.
</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading22">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse22" aria-expanded="false" aria-controls="faq-collapse22" onclick="omni_track('Faq22');">What is the LHF cancellation policy?</a></h3>
         </div>
         <div id="faq-collapse22" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading22">
           <div class="panel-body">
             <ul>
			   <li>A 10 day meal plan is non refundable</li>
			   <li>A 30 day subscription is cancellable within 10 days for refund. </li>
			<li>After 10 days of a 30 day subscription, the food subscription can be cancelled and the remaining balance can be used as store credit towards any purchase from Life Healing Food. Reimbursements are not possible at this time.</li>
		    <li>Any balance store credit can be used towards any plan, product or service in case the client wants to change their plan.</li>
				 <li>Store credit can be transferred to another client for a Rs 500 administrative fee.</li>
				 <li>Your services can be cancelled by us for any reason.</li>
				 <li>Prices subject to change.</li>
			   </ul>
           </div>
         </div>
       </div>   
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading23">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse23" aria-expanded="false" aria-controls="faq-collapse23" onclick="omni_track('Faq23');">How much weight will I lose on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse23" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading23">
           <div class="panel-body">
             <ul>
			   <li>Experts agree that losing 0.5-1 kg per week is a healthy and sustainable weight loss range, and you can expect to lose weight within this range on the LHF Weight Loss Program (clickable link)</li>
			   <li>On average, participants on the LHF Program lose an average of 6 kg per month.</li>
			   </ul>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading24">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse24" aria-expanded="false" aria-controls="faq-collapse24" onclick="omni_track('Faq24');">How much weight will I lose on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse24" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading24">
           <div class="panel-body">
             <p>Yes. After you have reached your disease reversal or weight loss goal, you can transition to the Stay Fit (clickable link) Program. Also, throughout your full plan, your dedicated nutritionist will have helped you to understand how to make good food choices, how to prepare healthful meals at home and will also offer you to stay on a consulting only package. You can also purchase some products (Clickable link) directly from LHF to aid you in food preparation at home.</p>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading25">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse25" aria-expanded="false" aria-controls="faq-collapse25" onclick="omni_track('Faq25');">What is the LHF cancellation policy?</a></h3>
         </div>
         <div id="faq-collapse25" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading25">
           <div class="panel-body">
          <ul>
		      <li>A 10 day meal plan is non refundable</li>	   
			 <li>A 30 day subscription is cancellable within 10 days for refund. </li>	
			  <li>After 10 days of a 30 day subscription, the food subscription can be cancelled and the remaining balance can be used as store credit towards any purchase from Life Healing Food. Reimbursements are not possible at this time.</li>	
			  <li>Any balance store credit can be used towards any plan, product or service in case the client wants to change their plan.</li>	
			  <li>Store credit can be transferred to another client for a Rs 500 administrative fee.</li>			 
			  <li>Your services can be cancelled by us for any reason.</li>
			  <li>Prices subject to change.</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading26">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse26" aria-expanded="false" aria-controls="faq-collapse26" onclick="omni_track('Faq26');">Is there a referral program?</a></h3>
         </div>
         <div id="faq-collapse26" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading26">
           <div class="panel-body">
			    <p>Yes, Get a Referral to Join and both you and they will save 20% </p>	
			   <p>Terms & Conditions:</p>	
          <ul>		        
			  <li>Referrals save 20% on sign up</li>	
			  <li>Referee's earn store credit in the same amount of savings as their referral to apply towards next renewal or extra days</li>	
			  <li>Offer valid only for new sign ups to the program</li>			 
			  <li>If new sign up cancels then store credit to the referee is also withdrawn.</li>
			  <li>Cannot be combined with any other promotions or discounts</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading27">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse27" aria-expanded="false" aria-controls="faq-collapse27" onclick="omni_track('Faq27');">How is delivery done? </a></h3>
         </div>
         <div id="faq-collapse27" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading27">
           <div class="panel-body">
		
          <ul>		        
			  <li>For any of our subscriptions, all meals will be delivered together.</li>	
			  <li>Our delivery person can only wait at your door for 5 minutes to not cause delay in other
deliveries. Please be aware and respectful of that time limit.</li>	
			  <li> At this same time, please give our delivery person your bag and dishes from the
previous day. (Remember, to stay cost effective and eco-friendly, we reuse/recycle all containers. There is also a Rs100 charge for any stainless steel container which is not returned.)</li>			 
			  <li>Please place your food in the refrigerator asap.</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading28">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse28" aria-expanded="false" aria-controls="faq-collapse28" onclick="omni_track('Faq28');">What will happen when I leave the LHF Program completely ?
</a></h3>
         </div>
         <div id="faq-collapse28" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading28">
           <div class="panel-body">
		<p>After you have reached your disease reversal or weight loss goal, you can transition to the Stay Fit (clickable link) Program. Also, throughout your full plan, your dedicated nutritionist will have helped you to understand how to make good food choices, how to prepare healthful meals at home and will also offer you to stay on a consulting only package. You can also purchase some products (Clickable link) directly from LHF to aid you in food preparation at home.
</p>
           </div>
         </div>
       </div>
	   
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading29">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse29" aria-expanded="false" aria-controls="faq-collapse29" onclick="omni_track('Faq29');">Will I get any discounts ?</a></h3>
         </div>
         <div id="faq-collapse29" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading29">
           <div class="panel-body">
		<p>Yes, Get a Referral to Join and both you and they will save 20% </p>
			   <p>Terms & Conditions:</p>
          <ul>		        
			  <li>Referrals save 20% on sign up</li>	
			  <li>Referee's earn store credit in the same amount of savings as their referral to apply towards next renewal or extra days</li>	
			  <li>Offer valid only for new sign ups to the program</li>			 
			  <li>If new sign up cancels then store credit to the referee is also withdrawn.</li>
			  <li>Cannot be combined with any other promotions or discounts</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading30">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse30" aria-expanded="false" aria-controls="faq-collapse30" onclick="omni_track('Faq30');">Will LHF help me to get 6 pack abs ?
</a></h3>
         </div>
         <div id="faq-collapse30" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading30">
           <div class="panel-body">
		<p>With the LHF plan and dedicated fitness goals, you may be able to achieve the fittest, healthy body possible. To achieve “6 pack” abdominals, you may also need to include a fitness instructor into your health regimine who can guide you specifically to shape the body parts you want. We have numerous athletes on our program who have achieved and even surpassed their fitness goals.</p>
           </div>
         </div>
       </div>
	   
		</div>
	   </div>
	 </div>
	</div>
	  <div class="text-center collapse-link">
       <a role="span" class="read-more-link collapsed" data-toggle="collapse" href="#faqCollapse" aria-expanded="false" aria-controls="faqCollapse" onclick="omni_track('SeeWhatsCooking');">
          <img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt="open">
          <img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt="close">
          <strong>See more FAQ's</strong></a></div>
	 <!--morefaqs-->
	 
	 </div>
	</div>
  
<div class="anh-quote">
 <div class="container">
    <div class="row">
       <div class="col-sm-5 col-lg-4">
          <img src="<?php echo $this->getSkinUrl('images/anh-quote-2020.jpg') ?>" class="img-responsive center-block" alt="Anh in a bathing suit smiling on the beach">
          <p class="small hidden-xs">Average weight loss expected 6 Kgs per month.</p>
       </div>
       <div class="col-sm-7 col-lg-offset-1"><h2 class="fw-400 h6">ADITYA LOST <b>24 KGS .</b></h2>
          <hr>
          <h3>“I NEVER THOUGHT I WOULD BE ABLE TO LOSE WEIGHT AND HAD TRIED EVERYTHING BEFORE. I DIDN'T EVEN HAVE TO EXERCISE”</h3>
          
          <p class="small visible-xs">Average weight loss expected 6 Kgs per month.</p>
       </div>
    </div>
 </div>
</div>
<div class="bg-secondary closer">
 <div class="container">
    <div class="row">
       <div class="col-xs-12 center-block no-float text-white">
          <div class="row">
             <div class="col-xs-12 col-lg-7 col-lg-offset-1 col-md-6 col-md-offset-1 col-sm-7 text-wrapper">
                <h3 class="text-white">Lose weight fast with the Silver Plan!</h3></div>
             <div class="col-xs-12 span-wrapper col-md-3 col-sm-5" id="top">
               <a href="#product-pane" class="btn btn-default btn-lg bg-white">Get Started</a> 
             </div>
          </div>
       </div>
    </div>
 </div>
</div>
	</div>
</main>
<script>


function selectGender(gender)
{
	if(gender=='men')
	{
		jQuery("#men").removeClass("unselected");
		jQuery("#men").addClass("selected");
		
		jQuery("#women").addClass("unselected");
		jQuery("#women").removeClass("selected");
	}
	else if(gender=='women')
	{
		jQuery("#women").removeClass("unselected");
		jQuery("#women").addClass("selected");
		
		jQuery("#men").addClass("unselected");
		jQuery("#men").removeClass("selected");
	}
}

function selectMenu(menu)
{
	if(menu=='favorite')
	{
		jQuery("#favorite").removeClass("unselected");
		jQuery("#favorite").addClass("selected");
		
		jQuery("#custom").addClass("unselected");
		jQuery("#custom").removeClass("selected");
	}
	else if(menu=='custom')
	{
		jQuery("#custom").removeClass("unselected");
		jQuery("#custom").addClass("selected");
		
		jQuery("#favorite").addClass("unselected");
		jQuery("#favorite").removeClass("selected");
	}
}

function delivery(plan)
{
	//10day 1month 2month
	if(plan=='10day')
	{
		
		jQuery("#10day").addClass("selected");
		jQuery("#10day").removeClass("unselected");
		
		jQuery("#1month").addClass("unselected");
		jQuery("#1month").removeClass("selected");
		
		jQuery("#2month").addClass("unselected");
		jQuery("#2month").removeClass("selected");
		
		jQuery("#planprice").text(1200);
		
		var DeliveryText ='10 Days Price: <s><span class="sr-only">price is</span><span class="itemListPrice">Rs 14,000</span></s>';
            DeliveryText+='<span class="sr-only">now</span><strong><span class="orderAmountStr">Rs 12,000</span></strong>';
        jQuery("#DeliveryText").html(DeliveryText);
	}
	else if(plan=='1month')
	{
		
		jQuery("#10day").addClass("unselected");
		jQuery("#10day").removeClass("selected");
		
		jQuery("#1month").addClass("selected");
		jQuery("#1month").removeClass("unselected");
		
		jQuery("#2month").addClass("unselected");
		jQuery("#2month").removeClass("selected");
		jQuery("#planprice").text(1100);
		
		var DeliveryText ='30 Days Price: <s><span class="sr-only">price was</span><span class="itemListPrice">Rs 36,000</span></s>';
            DeliveryText+='<span class="sr-only">now</span><strong><span class="orderAmountStr">Rs 33,000</span></strong>';
        jQuery("#DeliveryText").html(DeliveryText);
	}
	else if(plan=='2month')
	{
		
		jQuery("#10day").addClass("unselected");
		jQuery("#10day").removeClass("selected");
		
		jQuery("#1month").addClass("unselected");
		jQuery("#1month").removeClass("selected");
		
		jQuery("#2month").addClass("selected");
		jQuery("#2month").removeClass("unselected");
		
		jQuery("#planprice").text(1100);
		var DeliveryText ='90 Days Price: <s><span class="sr-only">price was</span><span class="itemListPrice">Rs 110,000</span></s>';
            DeliveryText+='<span class="sr-only">now</span><strong><span class="orderAmountStr">Rs 108,000</span></strong>';
        jQuery("#DeliveryText").html(DeliveryText);
	}
	
}



function checkSelected()
{
	//var optionId = jQuery(".selected").attr("option-id");
	//alert('optionId='+optionId);
	
	//var mvar = "";
	var all_optionId_optiontypeId='';
jQuery(".selected").each(function() {
	
	var optionId = jQuery( this ).attr( "option-id" );
    var optionTypeId = jQuery( this ).attr( "option-type-id" );
	
	var single_optionid_optiontypeId = optionId+'_'+optionTypeId+',';
	all_optionId_optiontypeId = all_optionId_optiontypeId + single_optionid_optiontypeId
	
   
});
	
	//alert(all_optionId_optiontypeId); 
	window.location.href = "<?php echo Mage::getBaseUrl();?>checkout/cart/addmultiplecustomoptions?selected="+all_optionId_optiontypeId+"&id=1992"; 
	
	  
}
  
function myFunctionedit() {
  var x = document.getElementById("delivery-options-collapse");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>