<section class="mysec"> 
  <div class="videoWrapper">
  
      <iframe width="560" height="315" src="https://www.youtube.com/embed/pWYxb6OzseY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <p>Nice! Aspect Ratio!</p>
</section>

<style type="text/css">
.videoWrapper {
  position: relative;
  padding-bottom: 56.25%; /* 16:9 */
  height: 0;
}
.videoWrapper iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.mysec {
  background: white;
 width:80%;
  margin: 0 auto;
  padding: 1rem;
}
	
</style>