
<style>
body, html {
  height: 100%;
  margin: 0;
}
.main {
    width: 100%;
    margin-top: 6rem;
    height: 100%;
}
.bgimg {
  background:#fff;
  height: 500px;
  width:100%;
  background-position: center;
  background-size: cover;
  position: relative;
  color: white;
  font-size: 25px;
}

.topcenter{
 padding-top: 5%;
margin: auto;
width: 100px;
float: none;
display: block;
}

.bottomleft {
    margin: 9% auto auto auto;
    width: 200px;
    float: none;
    display: block;
    text-align: center;
}
	.bottomleft span{background: #269a9b;
color: #fff;
padding: 10px;
border-radius: 8px;
font-size: 14px;
font-weight: bold;
float: left;
margin: 1% auto;
text-align: center;
display: block;
width: 100%;}
	.bottomleft span a{color:#fff;}
.middle {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}
	.middle h1{text-transform: capitalize;color:#000;}
	.middle p{color:#000;}
hr {
  margin: auto;
  width: 40%;
	}
@media screen and (min-width:640px) and (max-width:767px){
		.logomob {
    width: 25% !important;
    float: right;
    margin-left: 0;
    margin-top: 0%;
}
		.bottomleft span {
    background: #269a9b;
    color: #fff;
    padding: 10px;
    border-radius: 8px;
    font-size: 14px;
    font-weight: bold;
    float: none;
    margin: 1% auto;
    text-align: center;
    width: 200px;
    display: block;
}
.bottomleft {
    margin: 20% auto auto auto;
    width: 100%;
    float: none;
    display: block;
}
		.topcenter {
    padding-top: 12%;
    margin: auto;
    width: 100px;
    float: none;
    display: block;
}
	.container {
    max-width: 670px;
}
	}
	@media screen and (min-width:260px) and (max-width:640px){
		.topcenter {
    padding-top: 20%;
    margin: auto;
    width: 100px;
    float: none;
    display: block;
}
		.middle {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    text-align: center;
}
		.bottomleft span {
    background: #269a9b;
    color: #fff;
    padding: 10px;
    border-radius: 8px;
    font-size: 14px;
    font-weight: bold;
    float: none;
    margin: 1% auto;
    text-align: center;
    width: 200px;
    display: block;
}
		.bottomleft {
    margin: 45% auto auto auto;
    width: 100%;
    float: none;
    display: block;
}
	}
	@media screen and (min-width:800px) and (max-width:1200px)
	{
		.bottomleft {
    margin: 15% auto auto auto;
    width: 200px;
    float: none;
    display: block;
}
	}
	@media screen and (min-width:768px) and (max-width:999px)
	{
		.bottomleft {
    margin: 16% auto auto auto;
    width: 200px;
    float: none;
    display: block;
}
		.topcenter {
    padding-top: 11%;
    margin: auto;
    width: 100px;
    float: none;
    display: block;
}
	}
</style>

<?php

if(Mage::getSingleton('customer/session')->isLoggedIn()){
	$LoggedIncustomer = Mage::helper('customer')->getCustomer();
    $customerId = $LoggedIncustomer->getId();
    $customerName = $LoggedIncustomer->getFirstname();
    $mobileno = $LoggedIncustomer->getPrimarymobileno();
	$encryptedMobileno = base64_encode($mobileno);
	?>

<div class="bgimg">
  <div class="topcenter">
    <img src="<?php echo $this->getSkinUrl('images/tickcircle.png') ?>" >
  </div>
  <div class="middle">
    <h1>Thank you</h1>
    
    <p id="demo" style="font-size:15px">You can now continue using any link below</p>
  </div>
  <div class="bottomleft">
	  <span><a href="<?php echo Mage::getBaseUrl();?>patientintakeform?ctrl=<?php echo $encryptedMobileno;?>">Fill Patient Intake Form</a></span>
	  <span><a href="https://lifeheal.zohobookings.in/#/customer/healthreview">Book a consultation</a></span>
	  <span><a href="<?php echo Mage::getBaseUrl();?>foodmealplan">Sign up for a 10 day trial</a></span>
  </div>
</div>

<?php } else { echo 'please login '; } ?>