<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>Will It Help Me?</b>
            </div>
            <div class="easypara">
            <p>We have seen improvements in 99% of our clients. Medications are reduced within 12 hours of 
starting the program. The results are visible thanks to the most advanced glucose monitoring 
technology we use.</p>
<p>Clinically scientists have proven that 86% of patients returned to "non-diabetic biochemical marker 
without the need for drugs" in a study published last year in The Lancet. It is called the DiRECT study.
</p>
    <p>This program will help you if you are :</p>       
            <ul>
            <li>Type II Diabetic
            </li>
            <li>
          Type I Diabetic

            </li>
            <li>Gestational Diabetes

</li>
<li>Obese</li>
            </ul>
            <p>Senior Clients: We will be more helpful to someone who has been diabetic for a shorter time versus 
someone who has been diabetic for 30 years and their pancreas are burnt out. In those extreme 
cases our program is still helping but it takes longer time and the clients will probably not return 
to a complete non-diabetic state. They will still see medication reductions which we are finding 
in 99% of clients and this helps them protect their kidneys and cardiovascular system.</p>
            </div>
            </div>
            </section>