	
	<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.hero {
				background-color: #FFFFFF;
				height: auto;
				min-height: auto;
			}
			
			
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner about">
	        <div class="hero-banner-container">
	        	
	        	<div class="about-banner-left">
						<img src="<?php echo $this->getSkinUrl('images/about-hero-banner.png') ?>"/>
	        	</div>
	        	
	        	<div class="about-banner-right">
	        		<h4>ABOUT LIFEHEAL</h4>
	        		<h1>Why We Are Here</h1>
	        		<p>Having seen how our own family members suffer from chronic disease and,
knowing that there are new ways to treat chronic disease which reverse the disease we pursue the goal of innovating, researching and promoting body repair science so that people’s lives can be re-energized, lifespans lengthened and diseases pushed away.
</p>
					<p>We implement cutting edge science in chronic disease reversal and longevity. They say the first human to live beyond 200 has now been born and we hope that person is a LifeHeal customer.</p>
	        	</div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	<!-- Who We Are Start -->
	
	<div class="who-we-are">
		<div class="who-we-are-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHO WE ARE</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">We are activists, nutritionists, doctors who want to see the world change. The epidemic of chronic disease can be treated and new ways to treat them is the only way forward. </p>
		<?php/*	<div class="who-we-are-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<div class="who-we-are-detail">
					<div class="who-we-are-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/who-we-are-1.png') ?>"/>
					</div>
					<div class="who-we-are-detail-text">
						<h3>Lorem ipsum dolor sit<br> amet, consetetur</h3>
					</div>
				</div>
				
				<div class="who-we-are-detail">
					<div class="who-we-are-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/who-we-are-2.png') ?>"/>
					</div>
					<div class="who-we-are-detail-text">
						<h3>Lorem ipsum dolor sit<br> amet, consetetur</h3>
					</div>
				</div>
				
				<div class="who-we-are-detail">
					<div class="who-we-are-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/who-we-are-3.png') ?>"/>
					</div>
					<div class="who-we-are-detail-text">
						<h3>Lorem ipsum dolor sit<br> amet, consetetur</h3>
					</div>
				</div>
				
				<div class="who-we-are-detail">
					<div class="who-we-are-detail-image">
					
						<img src="<?php echo $this->getSkinUrl('images/who-we-are-4.png') ?>"/>
					</div>
					<div class="who-we-are-detail-text">
						<h3>Lorem ipsum dolor sit<br> amet, consetetur</h3>
					</div>
				</div>
			</div> */?>
			<div class="single-meal-plans-container">
			
			
			
			<div class="single-meal-plans-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/who-we-are-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Activists</h3>
						<p>Why is the medical system focused on managing your sickness? We see a future where we manage your health.</p>
						
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/who-we-are-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Certified</h3>
						<p>Only Certified Diabetes Educators work on our clients. This certification is the highest certification a nutritionist can get in India.</p>
						
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
					<img src="<?php echo $this->getSkinUrl('images/who-we-are-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Doctor Approved</h3>
						<p>Having presented to over 300 doctors our research is doctor approved. This includes some of the top doctors in India in diabetes, cardiology and hepatalogy.</p>
						
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
							<img src="<?php echo $this->getSkinUrl('images/who-we-are-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>Innovative</h3>
						<p>We fuse food and lifestyle with amazing scientific tools, research and data so you can live longer and keep clear of diseases before they happen.</p>
						
					</div>
				</div>
				
			</div>
			
		</div>
		</div>
	</div>
	
	<!-- Who We Are End -->
	<!-- Feature Meal Plans Start -->
	<style>
	
		.featured-meal-plans {
			background-color: #FFF9E5;
		}
		
		.featured-meal-plans .single-meal-plans-title h2 {
			color: #0EB58F;
		}
		
		.featured-meal-plans .single-meal-plans-title p {
			color: #4B4B4B;
		}

	</style>
	
	<!-- Feature Meal Plans End -->
	<!-- Tab Block Start -->
	<style>
			.about-tab {
				background-color: #DCF3ED;
			}
			
			.about-tab .active-tab {
				color: #0EB58F;
			}
			
			.about-tab .tabs-touch {
				color: #0EB58F;
			}
			
			
	</style>
		
	<div class="tab-block about-tab">
		<div class="tab-block-container">
			<div class="tab-block-left" style="background-image: url('<?php echo $this->getSkinUrl("images/about-tab.png")?>')"></div>
			<div class="tab-block-right" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<div class="tab-block-wrapper">
					<div class="tab-container food-subscription-tab">
						
						<ul class="tabs">
						  <li class="active-tab">Vision</li>
							<li>Mission</li>
							<li>Values</li>
						</ul>
						
						<ul class="tabs-content">
							<li>
								<h3 class="tabs-touch">Vision</h3>
								<p>A world where more people are leading a longer life, without chronic disease.</p>
							</li>
						  <li>
								<h3 class="tabs-touch">Mission</h3>
								<p>To help the body need minimum medicines.</p>
							</li>
							<li>
								<h3 class="tabs-touch">Values</h3>
								<p><b>Genuine -</b> We are sincere and transparent.</p>
<p><b>Exceptional -</b> Good is the enemy of great. We push the limits.</p>
<p><b>Innovative -</b> We are highly creative and scientific.</p>
<p><b>Involved -</b> We are engaged with our customers, employees, and the communities we serve.
</p>
							</li>
						</ul>
						
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
	<!-- Tab Block End -->
	
	<!-- Our Strength Start -->
	<style>
		.our-strength h2, .our-strength h3 {
			color: #0EB58F;
		}
		
		.our-strength .how-it-works-detail {
			margin-top: 2rem;
		}
		
	</style>
	<div class="how-it-works our-strength">
		
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">OUR STRENGTH</h2>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<h3>Experience</h3>
					<p>Having served over 80,000 meals we know how food affects the body</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<h3>Scientific</h3>
					<p>With our InHealth system your plan is built 100% with science </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<h3>Holistic</h3>
					<p>Your treatment will restore your inner health and bring long lasting transformation</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- Our Strength End -->
	

	<!-- Our Team Start -->
	<div class="our-team">
		<div class="our-team-container">
			
			<div class="our-team-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>OUR TEAM</h2>
			</div>
			
			<div class="our-team-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="our-team-detail">
					<div class="our-team-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/our-team-1.png') ?>"/>
					</div>
					<div class="our-team-detail-text">
						<h3>Junior Gupta <span>CEO, Expert Coach</span></h3>
						<p>Junior A. Gupta is the founder of LifeHeal. His family has a strong history of Diabetes. Mr. Gupta says that "Growing up, the question wasn't If I would get diabetes, but When." He wanted to change the Indian mindset about Diabetes being genetic and irreversible. After many years of research, he realized that well-balanced diets are proven to control Diabetes. He started LifeHeal in 2018 to help people live healthier, stronger, and longer. He has degrees from Babson and MIT in the USA. He's a receiver of APJ Abdul Kalam's "Goodness Award" and also a TedX speaker. </p>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="our-team-detail">
					<div class="our-team-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/our-team-3.png') ?>"/>
					</div>
					<div class="our-team-detail-text">
						<h3>Jasmine Chanana <span>Chief Dietitian, LifeHeal</span></h3>
						<p>Jasmine Chanana, is an experienced clinical nutritionist focused on conducting detailed nutrition consultations to achieve your health targets. She is also a Certified Diabetes Educator and has also done a Diploma in Cognitive Fitness from Harvard School of learning. She believes in lifestyle modifications for overall well-being rather than following a very strict diet. </p>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="our-team-detail">
					<div class="our-team-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/our-team-2.png') ?>"/>
					</div>
					<div class="our-team-detail-text">
						<h3>Sneha Salian <span>Senior Dietitian, LifeHeal</span></h3>
						<p>Sneha Salian is a Registered Dietician and a Certified Diabetes Educator with over 5 years of experience in the hospital & health care industry. She had previously worked with a prestigious hospital that helped her gain exposure to different areas of clinical nutrition. She has completed her Master in Dietetics & Applied Nutrition from Manipal University in Mangalore.</p>
					</div>
				</div>
				
				<!-- Plan Details -->
				<!--<div class="our-team-detail">
					<div class="our-team-detail-image">
						<img src="<?php //echo $this->getSkinUrl('images/our-team-4.png') ?>"/>
					
					</div>
					<div class="our-team-detail-text">
						<h3>Junior Gupta <span>CEO, Expert Coach</span></h3>
						<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magnoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  </p>
					</div>
				</div>-->
				
				
			</div>
			
		</div>
	</div>
	
	<!-- Our Team End -->	