<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>Any Side Effects?</b>
            </div>
            <div class="easypara">
            <p>There are no known side effects to eating healthy food. </p>
<p>There are no known medicine reactions to eating food.</p>
    <p>There are precautions of course, and we will discuss those with you during our patient intake 
process. 
</p>   
<p>We have seen additional benefits in people, including:</p>    
            <ul>
            <li>Reduction of sleep apnea   </li>
            <li>Increased Energy
</li>
            <li>Better Digestion
</li>
<li>Better Skin Glow
</li>
<li>Decrease in cravings of junk food</li>
            </ul>
          
            </div>
            </div>
            </section>