	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/stress-blog-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>The Three Triggers of Stroke</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>September 08, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>The Three Triggers of Stroke</h2>
				<p>We all have fears about stroke. It is one of the worst things that could happen to a person. But is it actually possible to predict a stroke? And, can you do something about it? <br/> Strokes are one of the worst things that can happen. Even thinking about strokes makes me scared. The fear of it always looms upon you, especially if you have old parents. It is one of those things that hits from nowhere, and you are shell-shocked by the time it's over. Having personally seen some family members suffer from strokes, I can indeed say, Oh, man! I hate strokes. I really do.</p>	
				<img src="<?php echo $this->getSkinUrl('images/stress-blog-detail-1.jpg') ?>"/>			
				

				<h3>The Three Triggers of Stroke</h3>
				
				<p>After reading tons of books, articles, and journals, I discovered a gem from the American Heart Association. It came to me as I was reading up on reversing heart disease for the LifeHeal program. It turns out the American Heart Association has made clear guidelines for stroke risk. </p>
				<p>I was surprised to learn that we are at a higher risk for a stroke when 3 specific biomarkers rise together. These 3 markers together, not 1, not 2, but when these 3 markers are up together your chance of stroke are elevated. </p>
				<p>Somehow no one had told me that before, and I am hoping to inform everyone I can so I can save someone’s life.</p>
				<p>Why do I care? I have seen stroke victims as young as 38 being brought into a hospital ER. I wish someone had just checked these 3 simple markers and informed them of the elevated risks of stroke. Some of these risk factors can be fixed within days.  </p>
				<h3>What are the Three Triggers of Stroke?</h3>
				<p>I'm sure you're wondering, so what exactly are the three sisters of stroke? How do you identify them and, more importantly, prevent strokes? You'll be surprised to see that these three Triggers of strokes are pretty standard and defined by the American Heart Association. They are:</p>
				<ul>
					<li><strong>High Blood Pressure:</strong> High blood pressure significantly increases chances of stroke.</li>
					<li><strong>High Central Obesity:</strong> Obesity with particularly a wide waist, along with high blood pressure.</li>
					<li><strong>High Triglycerides:</strong> From the common cholesterol blood test called Lipid profile.</li>
				</ul>
				<p>I never knew the 3 risk factors above, when combined together, means you need to watch out for strokes. You should remedy this immediately.</p>

				<h3>HOW TO REDUCE RISK FACTORS:</h3>
				<p><strong>High Blood Pressure:</strong> Blood pressure should be brought down quickly with the right medications. The long term solution is to reduce blood pressure from the source and not need medications (because they have side effects) but we suggest to immediately remedy high blood pressure with medications.</p>
				<img src="<?php echo $this->getSkinUrl('images/stress-blog-detail-2.jpg') ?>"/>	
				
				
				
				<p> <strong> High Triglycerides:</strong> Triglycerides can be brought under control within 2 - 4 weeks using a nutrition based therapy. At LifeHeal we always promote healing the root cause so we would not suggest taking medications for this. Medications only treat symptoms, not the root cause. </p>
				<img src="<?php echo $this->getSkinUrl('images/stress-blog-detail-3.jpg') ?>"/>
				
				<p> <strong> High Central Obesity: </strong> Having your weight accumulate around your waist is more harmful metabolically than it being spread all around your body. Most of your organs are around the middle section of your body and the extra fat around them reduces their efficiency. This is very treatable but is a slow and long term process and is always encouraged to increase longevity and disease free living.</p>	
				<img src="<?php echo $this->getSkinUrl('images/stress-blog-detail-4.jpg') ?>"/>
								
				<p>Of the above 3 factors, 2 can be improved very quickly. We strongly encourage you to monitor and manage these to reduce stroke risks. 
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	