	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/pregnancy-blog-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Pregnancy & Nutrition: Mayo Clinic’s Guide to Fertility</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>September 08, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>Pregnancy & Nutrition: Mayo Clinic’s Guide to Fertility</h2>
				<p>Mayo Clinic is rated as the #1 Gynecology department in the USA. <br/> Here are key highlights of Mayo Clinic’s “Guide to Fertility and Conception”. In this article, we have focused on sections related to nutrition and its role in fertility.</p>	
				<img src="<?php echo $this->getSkinUrl('images/pregnancy-blog-detail-1.jpg') ?>"/>			
				<p>According to Mayo Clinic, Nutrition is imperative for fertility and health during pregnancy. Switching to a healthy diet helps you reach a healthy weight. More importantly, it improves the metabolic functioning of the body. </p>

				<h3>Nutrition - Eating to Conceive :</h3>
				
				<p>What you put into your body matters and can have a big impact on your health and fertility. The Mayo Clinic looked at an 18,000 women study called the Nurses Health Study to learn about the impact of nutrition on fertility.  </p>
				<h4>1.	Carbohydrates: Can reduce ovulatory fertility or, help keep hormones in balance</h4>
				<img src="<?php echo $this->getSkinUrl('images/pregnancy-blog-detail-2.jpg') ?>"/>	
				
				<ol type="a">
					<li>Your body uses carbohydrates to make blood glucose, which acts as a fuel to give you the energy to function.</li>
					<li>There are 2 types of Carbohydrates: Simple and Complex.</li>
					<li>Simple carbohydrates put you at a greater risk of ovulatory infertility. </li>
					<li>Complex carbs will provide your body with healthy, long-lasting fuel. They keep your blood sugar in balance and your hormones running smoothly.</li>
					<li>Complex carbs include foods like starchy vegetables, legumes, and whole grains. These take a longer time to release sugar in the blood.</li>
					<li>Simple carbs include naturally occurring sugars found in milk, fruits and certain vegetables. They are also found in refined and processed foods. These release sugars faster in the bloodstream, hence have a higher glycemic index.</li>
					<li>Excessive consumption of simple carbs results in large spikes in blood sugar levels. More of these spikes cause an equal number of insulin spikes, eventually leading to Insulin Resistance. </li>
					<li>Insulin Resistance is associated with health problems like type 2 diabetes, heart disease and fertility problems.</li>
					<li>Rather than avoiding all the carbs, it is more important to choose the right type of carb.</li>
					<li>According to LifeHeal in the Indian context, we have to look at reducing processed carbs and simple carbs in our diets. For example, white rice is a simple carb, and so is milk. Reducing these, amongst other things, will help fertility.</li>
					<li>Parameters relating to insulin resistance and glucose tolerance should be tracked and improved. Make sure your plans combine food with metabolic tracking.</li>
				</ol>
				
				<h4>2.	Dietary Fats: Go for good fats</h4>
				<img src="<?php echo $this->getSkinUrl('images/pregnancy-blog-detail-3.jpg') ?>"/>
				
				<ol type="a">
					<li>When it comes to fats and fertility, the biggest villain is “trans fat”.</li>
					<li>Trans Fat consumption has shown to have an increased risk of ovulatory infertility.</li>
					<li>Commercial baked and fried foods such as crackers, cookies, cakes, doughnuts and fries contain trans fat. Shortenings and stick margarine also are sources of trans fat.</li>
					<li>Instead, opt for fats that are found naturally in foods- Nuts & seeds,  ghee, coconut oil, olive oil are a few of the healthiest options.</li>
					<li>In the Indian context we also.
						<ol type="i">
							<li>
								have to look at traditional snacks purchased from local vendors, who often have poor quality control on the oil used.
							</li>
							<li>
								Look at packaged foods such as kurkure or anything coming from a packet.
							</li>
							<li>
								Avoid the use of vegetable oils.
							</li>
						</ol>
					</li>
					<li>For more information please read our blog on <a href="https://startlifeheal.com/best-oil-for-cooking/" target="_blank">“What is the right oil to use?”</a></li>			
				</ol>
				<h4>3.	Protein: Eat more beans and nuts</h4>	
				<img src="<?php echo $this->getSkinUrl('images/pregnancy-blog-detail-4.jpg') ?>"/>
				<ol type="a">
					<li>Making small changes can add up.</li>
					<li>Reduce meat-based protein.</li>
					<li>Research suggests that women consuming animal sources of protein are at higher risk of ovulatory infertility than women consuming plant sources of protein.</li>
					<li>Few options of Vegetarian protein: Beans, peas and lentils in soups & stews, adding chickpeas or black beans to salads. Using soy foods like tofu, soya chunks, and soy milk.</li>
					<li>In the Indian context, we often don't pay any attention to how much protein we are having. </li>
					<li>In most cases having 1 katori of dal is considered sufficient.</li>
					<li>Ensuring you are having enough protein, including a variety in protein types, along with the right type of carbohydrates requires a well thought out nutrition plan.</li>
				</ol>
				<h4>4. Nutrients: Powering your body’s self-repair mechanisms</h4>
				<ol type="a">
					<li>Getting enough phytonutrients and micronutrients play a big role in the functioning of every part of your body.</li>
					<li>Raw vegetables contain phytonutrients that often disappear with boiling or high heat cooking.</li>
					<li>Ensuring you are having enough salads will also boost nutritional intake while helping with weight loss.</li>
					<li>Nutrient boosts can be achieved with vegetable juices. Specific combinations of juices can be used to target specific nutritional deficiencies.</li>
					<li>The section on nutrients is not from Mayo’s current book. With our experience, we are sure these above pointers will come in a future Mayo fertility guidebook.</li>
					<p>In our next blog post, read Mayo Clinic’s opinion on the impact of weight, exercise and stress on fertility.</p>

				

	

			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	