<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.blog {
				background-image: url('<?php echo $this->getSkinUrl("images/blog-hero-banner.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.blog {
					background-image: url('<?php echo $this->getSkinUrl("images/blog-hero-banner-mobile.png")?>');
				}	
			}
			
			.blog h1 {
				color: #FFFFFF;
			}
			.hero-banner-text {
    			width: 100%;
    			max-width: 37rem;
			}
			
			
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner blog">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        <img src="<?php echo $this->getSkinUrl('images/blog-hero-logo.png') ?>"/>
				<h1>SPREAD THE KNOWLEDGE <br> AS  SAME AS LIGHT.</h1>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Archive Start -->
	
	<div class="blog-archive">
		<div class="blog-archive-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">GET THE LATEST QUICK-READS ON HEALTH AND FITNESS</h2>
			<div class="blog-archive-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('can-i-have-sugar-or-honey') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/diabetesblog.jpg")?>')">
					</div>
					<div class="blog-archive-detail-text">
						<h3>Can I Have Sugar, Honey?</h3>
						<p>Diabetes is a metabolic disease that leads to high blood sugar levels. Usually, insulin moves sugar...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('should-i-be-drinking-milk') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog2img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Should I be drinking milk?</h3>
						<p>Did you know that India is one of the largest producers and consumers of milk? From drinking chai to masala...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('pros-and-cons-of-vegan-diet') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-3.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Pros and Cons of Vegan Diet</h3>
						<p>Veganism or Vegan Diet has been trending for quite a few years and is one the most vouge diets out there...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('trust-your-gut') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog4img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>How To Improve Your Gut</h3>
						<p>Did you know that our body has over 4 trillion bacteria? Interestingly most of them can be found in the gut...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('intermittent-fasting-guide') ?>" target="_blank">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog5img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Intermittent Fasting 101</h3>
						<p>The dieting world is ever-changing, and it's hard to keep track of all the diets out there. Additionally, not...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('benefits-of-hydration') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/Blog6img1.jpeg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>7 Benefits Of Hydration</h3>
						<p>We’ve all seen celebrities carry a bottle of water with them. In fact, many have even preached and promoted...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				<!-- Blog -->
				<a class="blog-archive-detail" href="<?php echo $this->getUrl('tips-to-reduce-processed-food') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-3.png")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Tips To Reduce Processed Food</h3>
						<p>There is no denying that since the past 5 years, our dependence on processed food has increased. It all...</p>
						<h4>READ MORE ></h4>
					</div>
				</a>


				<a class="blog-archive-detail" href="<?php echo $this->getUrl('best-oil-for-cooking') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/blog-oil.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>What is the right oil to use?</h3>
						<p>Oil is an essential ingredient of our diet. While we know there are many options for cooking oil ... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>

				<a class="blog-archive-detail" href="<?php echo $this->getUrl('fertility-nutrition') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/mayo-blog.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Pregnancy & Nutrition: Mayo Clinic’s Guide to Fertility</h3>
						<p>Mayo Clinic is rated as the #1 Gynecology department in the USA. Here are key highlights of Mayo Clinic’s... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>

				<a class="blog-archive-detail" href="<?php echo $this->getUrl('triggers-of-stroke') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/stress-blog.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>The Three Triggers of Stroke</h3>
						<p>We all have fears about stroke. It is one of the worst things that could happen to a person. But is it actually... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>

				<a class="blog-archive-detail" href="<?php echo $this->getUrl('fertility-factors') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/mayo-blog2.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>Mayo Clinic’s Guide to Fertility:The Role of Weight, Stress & Exercise</h3>
						<p>In our previous blog, we learned about the role of nutrition in fertility. If you haven’t read the Nutrition guide... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>

				<a class="blog-archive-detail" href="<?php echo $this->getUrl('smart-goals') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/smart-blog.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>How to set Smarter Goals?</h3>
						<p>We all struggle with hitting goals. There is a new more effective way. Have you ever heard of SMART goals?... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>

				<a class="blog-archive-detail" href="<?php echo $this->getUrl('diabetes-reversal') ?>">
					<div class="blog-archive-detail-image" style="background-image: url('<?php echo $this->getSkinUrl("images/reversal_blog.jpg")?>')"></div>
					<div class="blog-archive-detail-text">
						<h3>What is Diabetes Reversal?</h3>
						<p>When I was a kid back in the 1980’s, it seems like everyone told me “Diabetes is lifelong”, “Diabetes is genetic” ... </p>
						<h4>READ MORE ></h4>
					</div>
				</a>
				
				
				
			</div>
		</div>
	</div>
	
	<!-- Blog Archive End -->
	
	