	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/oil-blog-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>What is the right oil to use?</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>September 08, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>What is the right oil to use? </h2>	
				<img src="<?php echo $this->getSkinUrl('images/blog-oil-detail-1.jpg') ?>"/>			
				<p>Oil is an essential ingredient of our diet. While we know there are many options for cooking oil to fit our health and taste, we all wonder about which oil is the right one for our kitchen. Well, choosing the right oil for our health depends on your cooking methods and the desirable health we are seeking. </p>

				<h3>NATURAL VS PROCESSED</h3>
				
				<p>Vegetable oils are processed 7 to 14 times to make them shelf stable and palatable. Whereas olive oil, ghee, coconut oil are natural and don’t need industrial processing. Therefore at LifeHeal we fundamentally believe natural, less refined products are better for your body. <br/>
					Read more to get the scientific details about the composition of each oil.<br/>
				</p>
				<p>Edible oils contain different antioxidants like tocopherols, oryzanol, carotenes, tocotrienols, etc. as well as phytosterols, and micronutrients improving your heart health. Similarly, every oil has a different fatty acid composition classifying the oils into SFA, MUFA, PUFA and trans fats. You must have come across these terminologies on the television oil commercials. But did you know what they actually meant or how they really affected our health?</p>


				<p>The SFA’s i.e Saturated Fatty Acid have been considered as harmful for our health as they tend to increase LDL and total cholesterol. On the other hand, MUFA and PUFA are the fatty acids that help to lower LDL cholesterol and have been proven to protect cardiac health.</p>
				<p>But, with Indian cooking methods, be it any vegetable or a gravy preparation or for that matter any other preparations, each one includes a common process of stir-frying and the oils are subjected to relatively higher temperatures. Exposure of oils to such higher temperatures not just destroys the antioxidant present but also produces toxic compounds that may increase the risk of cardiac diseases as well as cancer. Hence it is advisable to choose the oils having a higher smoke point, meaning they can be heated to higher temperatures.  </p>
				<p>Similarly, it is better to avoid refined oil, specifically the one’s high in PUFA degrades easily generating toxic substances harmful to our health. Hence refined vegetable oils are a complete NO-NO for cooking.</p>

				<p>Are we all confused and back to square one wondering which oil is the right oil for consumption? So, here comes the most favourite twist to all this theory.</p>

				<img src="<?php echo $this->getSkinUrl('images/blog-oil-detail-4.jpg') ?>"/>	

				<p>The <strong>Desi Ghee,</strong> sourced from Cow’s Milk, a natural source, being rich in SFA and free of PUFA, comes with the highest smoke point. This makes the Ghee the most favourable fat for cooking as well as for frying purposes.</p>

				<img src="<?php echo $this->getSkinUrl('images/blog-oil-detail-2.jpg') ?>"/>
				<p>Also, certain short and medium chained SFA’s are not harmful as they do not affect the blood lipids. Several studies have suggested that Coconut Oil, which is rich in SFA, has not affected the blood lipids when compared to Sunflower Oil. Yes, <strong> Coconut Oil,</strong> which has been portrayed as the demon all this while, is really good for your health.</p>

				<p>In fact, oils containing higher SFA like ghee and coconut oil can be used for Indian cooking, as they are relatively stable during frying. Earlier, oils high in SFA were considered harmful since they increase LDL cholesterol but the latest studies suggest otherwise.</p>
				<img src="<?php echo $this->getSkinUrl('images/blog-oil-detail-3.jpg') ?>"/>
				<p><strong>Olive Oil</strong> contains oleic acid which is a MUFA, known to suppress the oncogene in the body, thus reducing the risk of cancer. But let us not forget the fact that we still want an oil that is not refined. So opting for an “extra virgin” labelled olive oil would be a preferred choice anytime.</p>
				<p>On the contrary, the hydrogenation of vegetable fat (Vanaspati ghee) produces trans fats, which affect blood lipids, posing a higher risk of heart diseases, worse than the SFA’s. They have also been associated with other chronic diseases like Alzheimer's disease, cancer, diabetes, obesity, inflammation, depression, etc.</p>
				<p><strong>To summarize it, the top-most choices of fat for cooking would be:<br/> Ghee, followed by Coconut Oil and Olive Oil.</strong></p>
				<p>Is that all one can use in their kitchen?</p>

				<p><strong>Mustard oil</strong> due to their low SFA and higher MUFA content are also relatively stable for cooking in comparison to refined vegetable oils. If you wish to use mustard oil ensure a non-refined i.e cold-pressed form, which can be safe for consumption.</p>

				<p>Now that you are aware of the right oil to be used, it is very necessary to understand that all fats are higher in calories and using them in moderation is key to further maintaining good health.</p>
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	