	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/blog-1.png")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Can I Have Sugar, Honey? </h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>March 11, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>What is Diabetes?</h2>
				
				
				<p>Diabetes is a metabolic disease that leads to high blood sugar levels. Usually, insulin moves sugar from the blood to your cells, which can later be used in energy. However, people with diabetes can't make enough insulin or can't use the body's insulin. Severe diabetes can damage your nerves, eyes, kidney, and other organs. </p>
				<!--<img src="<?php //echo $this->getSkinUrl('images/blog-1-image.png') ?>">-->
				<img src="<?php echo $this->getSkinUrl('images/diabetesblog.jpg') ?>" style="width:100%;"/>
				
				<h3>Should Diabetics avoid sugar altogether? </h3>
								
				<p>People often wonder if diabetics should avoid all kinds of sugar, all together. Of course, diabetics need to monitor their diet like a hawk. But incorporating occasional sweet treats into your diet can be okay. However, the amount of sugar a person with diabetes can consume depends on the following factors:</p>
				
				<ul>
					<li>Their activity levels. </li>
					
					<li>Are they trying to lose or maintain a healthy weight?</li>
					
					<li>Do they aspire to lower their blood glucose levels?</li>
				</ul>
				
				<p>The best way to set personal goals for proper nutrition and a well-balanced diet is by contacting a doctor or dietician. This is where LifeHeal comes to your rescue. Our certified dieticians specially curate plans for you by keeping your personal preferences in mind. 

</p>
				<img src="<?php echo $this->getSkinUrl('images/glucose-meter.jpg') ?>" style="width:100%;"/>
				
			<p>Additionally, according to organizations like American Diabetes Association, diabetics can eat occasional treats like chocolate, sweets, and other sugary foods, as long as they eat a well-balanced diet and do some form of physical activity. </p><ul><li>Have limited saturated fat.</li>
<li>Contain a modest amount of salt and sugar.</li>
<li>Contain plentiful protein, non-starchy vegetables, whole grains, fruits, and healthy fats like avocado. 
	</li></ul>
				
				
				
				<p>
Diabetics should have a sparse amount of sugar and be extra cautious about food labels. Foods claiming to be "sugar-free" or have "no added sugar" should be avoided. These usually contain calories and carbohydrates that can impact your blood sugar levels. Foods containing these sugar substitutes can also alter a person's sense of taste. </p>

<p>Common added sugars that are found in regular food items and people with diabetes should avoid are:</p>
<ul><li>Table sugar </li>
				<li>High fructose corn syrup</li>
				<li>Brown rice syrup</li>
				<li>Agave nectar </li>
				<li>Maple syrup</li>
				<li>Glucose</li>
				<li>Beet sugar</li>
				<li>Honey </li>
				</ul>

<img src="<?php echo $this->getSkinUrl('images/blogbanner1.jpg') ?>" style="width:100%;"/>
				<p>Did you get scared or feel intimidated by the long list of no-noes? Well, fret not! But there are a lot of everyday food items that are diabetic-friendly. However, portion control is the key here. 
				</p>
				<p>Make sure you eat these diabetic-friendly sweets in moderation: </p>
				<ul>
					
					
<li>Granola (with no added sugar) and fresh fruits </li>
<li>Trail mix with nuts and seeds</li>
<li>Graham crackers with nut butter (no added sugar)</li>
<li>Chia seed pudding </li>
<li>Low sugar avocado mousse </li>
<li>Mixed berries and homemade whipped cream </li>
<li>Low sugar brownies </li>
				</ul>
<p>Be aware, though these foods may not have added sugar, it's important to remember that they may be loaded with carbs and calories. Make sure to eat these foods on special occasions only. </p>


			
				
				
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	