	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/blog-1.png")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Should I be drinking milk?</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>March 11, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>Should I be drinking milk?</h2>
				
				<img src="<?php echo $this->getSkinUrl('images/Blog2img1.jpeg') ?>"/>
				<p>Did you know that India is one of the largest producers and consumers of milk? From drinking chai to masala milk, milk is widely enjoyed and savored in India. But in recent years, milk consumption has been one of the hotly debated topics. As many are turning towards milk alternatives like soy, cashew, and almond milk, it's to wonder, "Should you be really drinking milk"? </p>
				<p>Like all things in the world, there are pros and cons to everything. However, it's a total myth that milk is bad for you. Several studies have been published highlighting the benefits of milk. Below are some scientifically-backed reasons why you shouldn't stop drinking milk. </p>
				
				
				<h3>Great source of protein </h3>
								
				<p>One cup of milk contains about 8 grams of protein, making it perfect for vegetarians. Protein is an essential component that helps build and maintain healthy muscles, teeth, and muscles. Based on some research, an appropriate amount of milk is linked to greater muscle mass and better physical performance. It is also one of the best sources of muscle repair in athletes. </p>
				
				<h3>Appetite control</h3>
			<p>Are you shocked by the heading? It's a general myth that milk leads to weight gain. In fact, according to several studies conducted, drinking milk curbs your appetite. Studies have even shown that drinking full-fat milk dairy helps lower body weight. So, throw away those low-fat pints of milk in your fridge.  </p>
				
				<img src="<?php echo $this->getSkinUrl('images/Blog2img2.jpeg') ?>"/>
				<h3>Nutrient packed</h3>
<p>Apart from protein, fat, and good carbohydrates, milk is packed with some essential nutrients that help your body function like a well-oiled machine. Some important nutrients found in milk are: </p>

				
				<ul><li>Calcium </li>
<li>Riboflavin</li>
<li>Phosphorous</li>
		<li>Vitamin A and B12</li>
					<li>Potassium</li>
					<li>Magnesium</li>
					<li>Zinc</li>

				</ul>
				
				<h3>Improves bone health</h3>
				
				<p>
One cup of milk contains about 305mg of calcium, which constitutes about 30% of the daily requirement of calcium. Along with calcium, milk is rich in potassium and magnesium, which are essential for bone development. Chances of osteoporosis and fractures are also reduced by drinking milk. Consuming milk is especially important for women as they may have to embrace motherhood. </p>
<h3>Type 2 Diabetes prevention and Heart health </h3>
<p>Type 2 Diabetes is mainly associated with high blood sugar levels. According to several studies, milk may prevent chances of type 2 diabetes because of the protein in milk, which may improve blood sugar balance. Milk also helps raise the HDL cholesterol levels due to the fat content in it. This may help prevent heart diseases and strokes. Additionally, Omega-3 fatty acids found in milk can help protect blood vessel health. </p>
				<img src="<?php echo $this->getSkinUrl('images/Blog2img3.jpeg') ?>"/>
	<h3>Side effects of milk </h3>
<p>Though milk's benefits outweigh its disadvantages, there is no denying that milk isn't for everyone. Some people can't digest lactose in milk and hence are lactose intolerant. People who are lactose intolerant can't usually have other dairy products, too, such as yogurt, cheese, and paneer. For others, milk may affect skin leading to acne and exacerbate their eczema. </p>

<p>But if you love milk and just can't give it up, then fear not. There are plenty of milk alternatives that taste pretty good. Some popular alternatives available are soy milk, almond milk, oat milk, coconut milk, cashew milk, rice milk, etc. However, before buying milk alternatives, make sure to read product labels for any added sugar or artificial sweeteners. </p>

				<h3>Final Thoughts</h3>
<p>Milk is one of the most nutrient-rich food out there. It's packed with protein and calcium, which help in bone and teeth development. Shockingly it may also help lose or maintain your weight as it keeps you full for longer. And an increasing number of people are intolerant towards and drink milk alternatives. </p>


			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	