	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/pregnancy-blog-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Mayo Clinic’s Guide to Fertility:The Role of Weight, Stress & Exercise</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>September 28, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>Mayo Clinic’s Guide to Fertility:The Role of Weight, Stress & Exercise</h2>
				<p>In our previous blog, we learned about the role of nutrition in fertility. If you haven’t read the Nutrition guide, please click <a href="https://startlifeheal.com/fertility-nutrition/" target="_blank"> here</a>.</p>	
				<img src="<?php echo $this->getSkinUrl('images/fertility-blog-detail-1.jpg') ?>"/>					
				<p>In this blog post we will review the effects of body weight, exercise and stress levels on fertility. This is all a summary of Mayo clinic’s guide to fertility.  </p>

				<h3>Weight:</h3>
				<p>Weight can have a big impact on fertility. Below are key points by Mayo clinic regarding weight and fertility </p>
				<img src="<?php echo $this->getSkinUrl('images/fertility-blog-detail-2.jpg') ?>"/>	
				
				<ol type="1">
					<li>Weight can sometimes be a factor in a couple's effort to have a baby.  Being underweight or overweight may affect the ovaries’ capability to release an egg(ovulate) and, as a result, reduce chances of conception.</li>
					<li>Being very thin - having a BMI less than 19 - Can disrupt the cyclical production of FSH and LH </li>
					<li>Being obese - having BMI of 27 or higher -  may lead your body to over produce insulin, which can then lead to production of too many androgens, hormones that can disrupt regular egg development and result in lack of ovulation. Other hormones may also affect ovulation and ovarian function.</li>
					<li>Obesity itself is associated with conditions in women that may undermine their ability to conceive, such as polycystic ovary syndrome, a hormonal disorder characterized by menstrual abnormalities, acne, excess facial and body hair, and other changes throughout the body.</li>
					<li>Obesity is not just a factor for women. Excess weight may also be a factor for men.</li>
					<li>Taking steps to achieve a more healthy body weight can improve the frequency and regularity of ovulation and the likelihood of getting pregnant. If you're overweight, even losing as little as 5 to 10% of your bodyweight can improve fertility.</li>
					<li>Together, as a partner you can always opt for a weight loss program with a certified coach.</li>
					<li>For lower BMI, ensure gaining weight with right food and beverages, maintaining a schedule of regular meals.</li>
					<li>From LifeHeal’s experience weight also has an effect on gestational diabetes. Maintaining a healthy weight will reduce the chance of diabetes and the need of taking extra medications while pregnant.</li>
					<li>Another LifeHeal perspective on weight is that being on a health plan means healthier organs. When everything works well then pregnancies and child development will also be better.</li>
				</ol>
				<h3>Exercise: </h3>
				<p>Exercise is considered beneficial and these are the main points for exercise.</p>
				<img src="<?php echo $this->getSkinUrl('images/fertility-blog-detail-3.jpg') ?>"/>	
				<ol type="1">
					<li>A study suggests that women who engaged in 5 hours or more of moderate physical activity (no vigorous activity) had the shortest time to pregnancy.</li>
					<li>Moderate physical activity includes: Brisk Walking, Leisurely bike riding, golfing, etc.</li>
					<li>Too much exercise on the other hand might have the opposite effect. More than 5 hours of vigorous aerobic activity like running, fast cycling impairs fertility.</li>
					<li>In case you need weight loss, vigorous exercise will be beneficial, but for a healthy weight, vigorous activity will act opposite.</li>
					<li>
						<p>Ideal Fitness Program:</p>
						<p><strong>Aerobic Activity </strong> maximises the supply of oxygen to your blood. It includes exercises like brisk walking, swimming, dancing, etc is recommended for 30 minutes on most days of the week.</p>
						<p> <strong> Strength Training </strong> exercises help to maintain muscle mass and lose weight and to strengthen bones. Including strength training twice a week is recommended.</p>
						<p> <strong> Core Exercises </strong> helps train your muscles to brace your spine, enabling you to use your upper and lower body muscles more effectively. It includes exercises like abdominal crunches (situps), planks, etc</p>
						<p> <strong> Flexibility & Stretching </strong> exercises improve your flexibility and range of motion. These exercises also improve your posture. It is necessary to perform stretching after workouts. If you are not exercising regularly, then stretching should be done at least 3 times a week.</p> </li>
					<li>From LifeHeal’s experience - our bodies are designed to move. There are 3 million years of evolution that have designed our body to function with a certain amount of exercise. When we follow our natural design everything tends to work better.</li>
				</ol>

				<h3>Stress:</h3>
				<p>Stress, as per Mayo clinic, does play a part and these are the key points.</p>
				<img src="<?php echo $this->getSkinUrl('images/fertility-blog-detail-4.jpg') ?>"/>
				<ol type="1">
					<li>Under stress your brain signals your body to release hormones : Adrenaline & Cortisol.</li>
					<li>After a stressful event is over, your body returns to its normal state. But if stress is chronic, your mind and body remains in a constant state of alert.</li>
					<li>Not being able to conceive is stressful and the longer it takes to conceive, the more stress a couple begins to experience. It further leads to sexual problems and depression.</li>
					<li>Balancing out the stress by reducing a certain workload can help you have more time with your partner.</li>
					<li>Other stress management strategies include regular exercise, adequate sleep, a healthy diet, and practicing relaxation techniques like meditation.</li>
				</ol>
				<p> Fertility is a complex process and is also affected by a broad range of factors like your genes, your environment and other factors that may be out of your control. </p>

				<p>However getting the body the right support it needs will always help in anything you are trying to do. </p>

				<p>I am happy to say that after having read Mayo clinic’s guide over 3 years after we started LifeHeal we are happy that we deliver all the required support a natural nutrition plan can and should do. </p>				
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	