	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/blog-reversal-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Diabetes reversal uses food to reduce glucose spikes and improve fasting glucose</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>December  20, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>What does LifeHeal do in its Diabetes reversal program?</h2>
				<img src="<?php echo $this->getSkinUrl('images/reversal-blog-details.jpg') ?>" alt="Diabetes Reversal is proven in clinical studies"/>
				<p><strong>I want to start with my story. Maybe this is a lot like your story.</strong></p>
				<p>When I was a kid back in the 1980’s, it seems like everyone told me: <br/>“Diabetes is lifelong” <br/>“Diabetes is genetic” <br/>“Once you have it, it can’t be stopped” </p>
				<p>It was fate, it was destiny... And it would always get worse over time. Insulin too, once started, was a lifelong medication. </p>

				
									
				<p>I had so much diabetes in my family that we used to play “pichkari” with diabetes syringes, there were just so many of them. I grew up thinking not <span style="font-style:italic;">if</span> &nbsp; I would get diabetes, but rather <span style="font-style:italic;"> when</span> I would get diabetes. </p>

				<p>When I came across the concept of “Diabetes Reversal”, it sounded like  fantasy. Like a movie about a flying car, or time travel. Not possible. But I like to read, so I started reading about it. I read and I read and I read. </p>

				<p>After a good 10 books on it I was convinced that diabetes reversal is possible. There were so many <span style="font-style:italic;"> success  </span> stories about diabetes reversal. Not from random doctors but doctors associated with Harvard, MIT, Carnegie Mellon and Cleveland Clinic. These are some of the top universities and hospitals in the world ! </p>

				<h3 style="text-decoration: underline;">So, What is Diabetes Reversal?</h3>				
				
				<h3>Diabetes Reversal is:</h3>
				<ol type="1">					
					<li>Restoring glucose control in the body</li>
					<li>Restoring pancreatic function</li>
					<li>Improving fasting glucose</li>
					<li>Eliminating the need for all diabetic medications.</li>
				</ol>				
				
				<h3>If you were to speak of blood tests, it would mean:</h3>			
				<ul>					
					<li>Improving fasting glucose</li>
					<li>Improving HBA1c</li>					
				</ul>
				
				<p>The <a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(17)33102-1/fulltext" target="_blank">DIRECT study </a> was the landmark study, conducted in the UK and Scotland, which finally proved to doctors around the world that Diabetes Reversal is medically possible. The NHS  thereon   set a goal of achieving diabetes reversal in 10% of all diabetic patients  in the UK. Until that study came out, I was considered a lunatic <span>by doctors </span> in India!  </p>

				<p style="margin:0 !important; padding: 0;">
					Other things also happen during the diabetes reversal process, but for which there is no large western study published yet. <br/>The same solutions for diabetes reversal also help in:					
				</p>
				<ul style="margin:6px 0 6px 15px !important; padding: 0 inherit;">
					<li> fatty liver reversal. </li>
					<li> reversal of cardiac disease and </li>
					<li> pretty much all chronic diseases. </li>
					
				</ul>
				<p style="margin:0 0 1.5rem 0 !important; padding: 0;">The body’s metabolism is one connected unit.</p>
					

				<h3 style="text-decoration: underline;">So what does LifeHeal do in its Diabetes reversal program?</h3>

				<p>In very simple terms - the body is a self healing machine. When you cut your skin, the body self heals.  We harness the body’s self healing systems.  Pancreas and liver improve their functioning.</p>			

				
				<p><strong> Your food - </strong> many times you do not know what food is right for you. Take 5 magazines on health of any given month and you will not know what is right for you; every magazine has different advice. We take a food plan and make it precisely for you. </p>
				<p> The self-repair mechanism, where does it get spare parts from? It comes from the food. We design the food plan around what you need. There are a small but growing number of studies showing that beta cell function in pancreas can be restored with these processes.</p>

				<p>The food is also designed to start changing your metabolism. <strong> The glucose spikes start coming down.  </strong> In our diabetes reversal plans a lot of research is done to customize your food to minimize glucose spikes. This process helps in weight loss. Weight loss helps in better glucose control. </p>

				<p>We also adjust eating in such a way that <strong> fasting glucose comes down. </strong> Usually this is associated with liver health. We heal the liver. The liver is one of the largest organs in the body. It is the chemical factory of the body. As we heal the liver, your metabolic functions further improve.</p>
				<p> These are virtuous cycles; as one part improves, it helps the other part improve, and this goes round and round.</p>

				<p>Finally, <strong> we improve your microbiome. </strong> This is the millions of bacteria living inside you.  We have diseases of extreme bacterial dysfunction, like CIBO, but in lesser forms, they still affect your health. You may feel it in formats of energy, immunity, brain fog, IBS or more. We see this as a restoration of your human holistic make up. </p>
				<p>Gut health restoration benefits all aspects of health including depression, thyroid, arthritis and more, and YES we do believe it helps in METABOLIC HEALTH of the body.    </p>
				<p>The probiotic healing is not a required part of the diabetes reversal process, but a recommended part. All of the other above-mentioned components are standard in our diabetic reversal protocol.</p>


				<h3 style="text-decoration: underline;">In Summary, Diabetes Reversal involves:</h3>
				<ol type="1">
					<li>Boosting the body’s self-healing - helping pancreas and liver self-repair</li>
					<li>Reducing glucose spikes and harm from diabetes</li>
					<li>Improving liver health and function </li>
					<li>Resulting in 
						<ol type="a">
							<li>Better Fasting Glucose</li>
							<li>Better HBA1c</li>
							<li>Reduction or stoppage of diabetic medications</li>
						</ol>

					</li>

				</ol>
				<p> We hope you found this article helpful. If you want to learn more about diabetes reversal, be sure to book an appointment for a no-obligation <a href="https://startlifeheal.com/start-new-life" target="_blank" style="color:blue"> free call.</a></p>
				<p>Our mission is to help people need minimum medicines and we will gladly help you with a call and a free plan.</p>

				
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	