	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/blog-1.png")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Intermittent Fasting 101</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>March 11, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>Intermittent Fasting 101</h2>
				<img src="<?php echo $this->getSkinUrl('images/Blog5img1.jpeg') ?>"/>
				
				<p>The dieting world is ever-changing, and it's hard to keep track of all the diets out there. Additionally, not all diets are effective for weight loss. Some simply are just fad diets. But, intermittent fasting isn't one of your fad diets. In recent years, it has become one of the most popular diets out there. It not only helps you reduce weight but also improves your overall health. So what exactly is an Intermittent Fasting Diet? </p>
				<!--<h3>The most common signs of poor gut health are:</h3>-->
				<h3>What is Intermittent Fasting? </h3>
				<p>Firstly, you might be surprised to know that intermittent fasting isn't exactly a diet; it's an eating pattern. The diet/eating pattern doesn't change <strong>what</strong> you eat but focuses on <strong>when</strong> you eat. There are several intermittent fasting methods, but the most common method is 16:8 or 24 hours fasting, twice a week.</p>
<p>Fasting isn't new to Indians. Our rishis and ancestors had been fasting for years. It has modified our bodies and allowed us to function well without food for extended hours. 

</p>
				<h3>Types of intermittent fasting</h3>
				<p><strong>16:8 method:</strong> This is one of the most popular methods of intermittent fasting. The method involves fasting for 16 hours and eating within the 8 hours window. Most people who follow this method skip breakfast and eat during 1–9 pm. You can usually fit in 2-3 meals within the 8-hour eating window. This method can seem difficult for people who love breakfast. However, you can drink water, coffee, zero-cal beverages, and tea during your 16-hour fasting window. </p> 
<p><strong>5:2 diet:</strong> The 5:2 method doesn't restrict your eating hours for 5 days of the week. You can practically eat everything that you eat daily during those 5 days. But for the remaining 2 days, your daily calorie intake is restricted to 500-600 calories. For example, you can generally eat every day apart from Tuesday and Friday. On those days, women can eat 2 small meals 250 calories each, and men can eat 2 small meals 300 calories each. </p>

<p><strong>Eat-Stop-Eat:</strong> As the name suggests, you can usually eat every day but fast for 24 hours once or twice a week. For example, you can fast after your 7 pm Thursday meal to 7 pm Friday. Depending on your schedule, you can also fast breakfast to breakfast or lunch to lunch. Drink water, coffee, zero-calorie drinks, and tea are allowed during the fasting hours. Fasting for 24-hours could be challenging for many people out there. </p>

<p><strong>Warrior diet:</strong> Warrior diet slightly alters what you eat throughout the day. People using the warrior diet usually eat small amounts of raw fruits and vegetables during the week and eat one big meal at night. Though you can eat anything for your huge dinner meal, unprocessed, healthy, and natural food is usually recommended. 
	<a href="https://startlifeheal.com/start-new-life" target="_blank">Book Call</a>
</p>

				
				<h3>Benefits of intermittent fasting</h3>
				<p><strong>Weight Loss:</strong> For many, the reason for giving intermittent fasting a shot is weight loss. In a short period, many studies have anchored that intermittent fasting helps weight loss. Through this method, you end up eating fewer calories than usual. Of course, that's considering you are eating somewhat healthy during the non-fasting window.  

<p><strong>Reduce Inflammation:</strong> Several studies have shown that fasting reduces inflammation in our bodies. During fasting, pro-inflammatory markers are present at a lower level than usual, and the same can be said about blood pressure, body weight, and body fat. </p>

<p><strong>Improves Hormone and Cell Function:</strong> Fasting can cause several changes in your body. During fasting periods, your levels of insulin drop significantly, which helps burn fat faster. Intermittent fasting can also increase your human growth hormone levels (HGH), helping burn fat more quickly and increase muscle gain. </p>

<p><strong>Benefits For the Brain:</strong> Intermittent fasting increases your metabolic rate, which is indirectly vital for your brain. Brain hormone BNF is increased during intermittent fasting. IF also helps the growth of new nerve cells. Several studies have also shown that IF reduces the risk of neurological disorders like Alzheimer's disease, Parkinson's disease, and stroke. </p>

<p><strong>Reduce Insulin Resistance:</strong> Intermittent fasting resets insulin levels and stabilizes blood sugar levels for people with diabetes. During IF, the calorie intake of a person reduces and eventually improves insulin resistance.</p>

<p><strong>Increased Cell Turnover:</strong> Fasting gives a break to your body and gives it a chance to self-heal and repair. Intermittent fasting helps with autophagy, which is a process where cells digest and remove old and non-functional proteins in our cells. It will also get rid of old and damaged cells that may accelerate aging.</p>

				<h3>Final Thought:</h3>

<p>Intermittent fasting is one of the most popular diets out there. While it's an excellent diet for weight loss, it may not be for everyone. 'IF' goes beyond weight loss. It helps you live a better, healthier, and longer life. Just like we give a break to ourselves for working hard throughout the week, it's safe to say that our body also needs rest every once in a while. However, with all its benefits, this diet should be avoided by people with eating disorders. People with diabetes or heart conditions should also talk to their dietician before starting the diet. 
</p>			

			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	<style type="text/css">
		.blog-single-content a{
			display: inline-block;
			font-size: 1em;
		    color: #fff;
		    background-color: #0EB58F;
		    padding: 0.5rem 1.5rem;
		    font-weight: 500;
		    text-decoration: none;
		    margin-top: 12px;
		}
	</style>
	
	