	<!-- Hero Banner Start -->
	<div class="hero">
		
	    <!-- Banner -->
	    <div class="hero-banner blog-single"  style="background-image: url('<?php echo $this->getSkinUrl("images/smart-blog-heading.jpg")?>')">
			 <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>How to set Smarter Goals?</h1>
		        	<p><span>Junior Gupta</span> <span class="divider">|</span> <span>September 18, 2021</span></p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Blog Start -->
	
	<div class="blog-single-detail">
		<div class="blog-single-detail-container">
			
			
			<div class="blog-single-content">
				
				<h2>How to set Smarter Goals?</h2>
				<p>We all struggle with hitting goals. There is a new more effective way. Have you ever heard of SMART goals?</p>	
				<img src="<?php echo $this->getSkinUrl('images/smart-blog-detail-1.jpg') ?>"/>					
				<p>What is the difference between a regular goal and a smart goal? Let me give an example.  </p>

				<h3>Regular Goal:</h3>
				<p>I want to eat healthy </p>		
				
				<h3>SMART Goal:</h3>
				<ol type="1">					
					<li>I will eat salad 4 times a week</li>
					<li> I will eat dessert only once a week</li>
					<li> I will eat pizza once a fortnight</li>
				</ol>				
				<p>SMART goals help you be more structured in your approach.</p>

				<h3>What is the meaning of SMART? It is:</h3>			
				<ul>					
					<li>S - Specific</li>
					<li>M - Measurable</li>
					<li>A - Attainable</li>
					<li>R - Realistic</li>
					<li>T - Tangible</li>
				</ul>
				<p>With a smart goal approach you set clear timelines and activities and expectations. Now they need to be realistic.</p>

				<h3>Ordinary Goal:</h3>
				<p>I will work out this year</p>

				<h3>SMART Goal:</h3>
				<ol type="1">
					<li>I will work out 3 times a week for 45 min</li>
					<li>I will eat salads 5 meals a week</li>
					<li>I will eat pizza no more than twice a month</li>

				</ol>
				<p> At LifeHeal our coaches are trained to use SMART goals and other techniques to help you succeed. To learn about our innovative plans which blend coaching, psychology and nutrition please visit <a href="https://startlifeheal.com/meal-plan-coaching/" target="_blank">this page</a> </p>

				
			</div>
		
		</div>
	</div>
	
	<!-- Blog End -->
	
	