<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/p-contact-us.min.css">
<article class="p-contact-us" aria-hidden="false">

<section class="hero">
<div class="bg"></div>
<div class="grid container">
<div class="row">
<div class="col col-small-6">
<h1 class="strong katamari-field" data-katamari-field-id="1">Contact us</h1>
</div>
<div class="col col-small-6">
</div>
</div>
<div class="row">
<div class="col col-small-5">
<div class="card">
<img src="https://web-assets.zendesk.com/images/p-contact-us/avatar1.svg" alt="">
<h3 class="katamari-field center" data-katamari-field-id="2">Talk to a member of our team</h3>
<p class="katamari-field center" data-katamari-field-id="3">We’ll help you find the right products and pricing for your business.</p>
	<p class="contact" data-katamari-field-id="10" data-katamari-field-type="html">
<a href="tel:9370707004" class="anchor" target=""><span>+91 93707 07004</span></a><br>
</p>
	
<a href="#" class="katamari-field js-open-modal button button-medium button-primary-default" data-modal-id="contact-form-modal" aria-haspopup="dialog" data-katamari-field-id="4" target="">HealthCraft Helpline</a> </div>
</div>
<div class="col col-small-5">
<div class="card">
<img src="https://web-assets.zendesk.com/images/p-contact-us/avatar2.svg" alt="">
<h3 class="katamari-field center" data-katamari-field-id="5">Contact Customer support</h3>
<p class=" katamari-field center" data-katamari-field-id="6">HealthCraft 
Brinda A , 122/a North main road , next to Windermere, opposite indusind bank. Koregaon park. Pune 411001</p>
<a href="https://support.zendesk.com/hc/en-us/" class="katamari-field js-localized-hc-link button button-medium button-primary-default" data-katamari-field-id="7" target="_blank" rel=" noopener">Go to the help center</a> </div>
</div>
</div>
</div>
</section>

</article>
