 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>

<script>jQuery.noConflict();</script>
<script>
  jQuery( function() {
      jQuery( "#datepicker" ).datepicker();
      jQuery("#tooltip-1").tooltip();
    } );
	
	jQuery( function() {
      jQuery( "#datepicker2" ).datepicker();
      jQuery("#tooltip-1").tooltip();
    } );

  
</script>               
               
<?php $uniqueCustomersJson = Mage::helper('heal')->getUniqueCustomersJson();  ?>

  <script>
  var customers = <?php echo $uniqueCustomersJson;?>;
  
  jQuery( function() {
    jQuery( "#datepicker-from" ).datepicker();
	jQuery( "#datepicker-to" ).datepicker();
	   jQuery("#tooltip-1").tooltip();
	  
	   jQuery("#customers").select2({    
				  data: customers
				});
				
	 
	    <?php if(isset($_POST['customers'])) { ?>
		
		jQuery("#customers").val("<?php echo  $_POST['customers'];?>");
	        jQuery('#customers').trigger('change');
	 
			<?php } ?>
	   
	    
  } );
  </script>
  
<style>	
.main{  
  width: 100%;   
    margin-top:8rem;
    height:100%;
    margin-bottom: 2rem;
  }  
.table-top-row{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin-bottom: 15px;
  }
.table-logo{
    width:33%;
  }
.table-logo img{
    display: block;
    width:65%;
    margin:20px 0 0 0;
  }
.name-content{
    width:33%;
    background:#5599b0;
    box-sizing: border-box;
    padding: 15px 20px;
    color:#fff;
    text-align: center;
  }
.weekly-table{
    width:100%;
  }
.weekly-table thead tr td{
    background:#5599b0;
    text-align: center;
    color:#fff;
    width:16.66%;
    box-sizing: border-box;
  }
.weekly-table tbody tr td{   
    text-align: center;
    border: 5px solid #fff;
    width:16.66%;
    box-sizing: border-box;
  }   
.weekly-table tbody tr:nth-child(even) td{background: #ededed;}
.weekly-table tbody tr:nth-child(odd) td{background: #f4f4f4;} 
.weekly-table tbody tr.collapsiblereport td{font-weight: bold;} 

.print_btn{
  padding: 0px 25px;
  background: #c31f41;
  border: 1px solid #a61d3f;
  color: #fff;
  font-size: 14px;
  height: 35px;
  line-height: 35px;
  text-align:center;    
  margin:10px;
}
.sticky {
  position: sticky;
  top: 0;
  width: 100%;
}
.sticky + .table-scroll {
  padding-top:0px;
}
.table-scroll{
  float: left;
  width: 100%;
  padding: 0px;
  margin-bottom: 20px;
}

#datewise{
  width: 100%;
  padding: 50px 0;
  text-align: center;
  background-color: lightblue;
  margin-top: 20px;
}
		
.select2-container {
  box-sizing: border-box;
  display: inline-block;
  margin: 0;
  position: relative;
  vertical-align: middle;
  width: 100% !important;
  height: 35px;
  line-height: 35px;
  padding: 0;
}
.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 35px;
	}
	.select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 26px;
    position: absolute;
    top:5px;
    right: 10px;
    width: 20px;
}
.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 35px;
}
	.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin: 4px;
}
	.breadcrumbs{display:none;}	
	#myHeaderhead, #oldfooter, .navbar{
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    max-width: 100% !important;
    margin: 0 !important;
	}
	#printdate input[type="text"] {
  max-width: 100%;
  background: #f6fcfc;
  height: 35px;
  box-shadow: 0 0 2px rgba(0, 0, 0, .3);
  border: 0;
  margin: 0;
  width: 100%;
  text-align: left;
}	
#printdate select {
    font-size: 14px;
    margin:0px;
    width: 100%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;text-align: center;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}
.print{width:80%; margin:0 auto;}
 .print2{width:100%; float:left;}
#customerMealResport{
  font-size: 20px;	
  text-transform: 
  capitalize;width: 100%;
  display: block;
}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #a61d3f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

h2{font-weight: normal;margin: auto; width: 560px;font-size:17px;
height:60px;color: #000; line-height:60px;}
.tabledata td, .tabledata th{padding:10px;font-size:18px;width: auto;}
.dataalign{float: left; text-align: left; margin: auto;}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}

@media print {
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 18px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
    .print{width:92%; margin:0 auto;}
    .table-logo img{ display: block; width:75%; margin:30px auto 0 auto;}

    .weekly-table thead tr td{
    background:#5599b0;
    text-align: center;
    color:#fff;
    width:16.66%;
    box-sizing: border-box;
  }
.weekly-table tbody tr td{   
    text-align: center;
    border: 5px solid #fff;
    width:16.66%;
    box-sizing: border-box;
  }   
.weekly-table tbody tr:nth-child(even) td{background: #ededed;}
.weekly-table tbody tr:nth-child(odd) td{background: #f4f4f4;} 

}

@media all {
.page-break { display: none; }
}

@media print {
.page-break { display: block; page-break-before: always; }
}
@media screen and (min-width:260px) and (max-width:767px){
	.tabledata{width:100%;overflow:scroll;}
	#myHeadertop, .table-scroll{width:600px,font-size: 14px;}
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 68%;
}	
	.dataalign{float: left;
text-align: center;
width: 100%;
margin: 10px;}
#printdate select {
    font-size: 17px;
    margin: 10px;
    width: 68%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
@media screen and (min-width:768px) and (max-width:999px){
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}

}

.hideme{display:none;}
</style>
<?php
$choosenDate='';
$choosenCity='';
$msg ="";
$foundWeeklyReport='no';

$caloryPercent=0; $caloryTotal=0;
$carbsPercent=0;  $carbsTotal = 0;
$fatPercent=0;    $fatTotal=0;
$proteinPercent=0; $proteinTotal=0;
$total=0;
$labelText='';
$countCustomerResult=0;

if (isset($_POST["submit"]) )
{
	 
	  $choosenCustomer    = $_POST['customers'];
       if($choosenCustomer=='')
       {
           $msg.="Please select the customer<br>" ;
        }
	   
}
	

//echo "Week number--".$weekNumber; echo "<br>";
?>
<div class="noprint">
<form method="POST" action="<?php echo Mage::getBaseUrl().'customer-meal-report-of-week';?>" >

<h1 class="noprint" style="text-align: center;font-size: 24px;text-transform: capitalize;float: left;margin: 20px auto!important;">Customer Meal Report Of A Week</h1>
<table border="1" align="center" id="printdate" style=" max-width:560px; padding:10px 0 0 20px; margin: 0 auto 40px auto;" rules="none">

  <tbody class="noprint">       
	  <tr style="padding: 20px;float: left;width: 100%;display: block;">  
      <td class="dataalign" style="width:30%;">
				<span style="width:100%;float:left;height: 35px;line-height: 35px;">Select Customer:</span>
			</td>
			<td class="dataalign"  style="width:70%;">
          <select id="customers" name="customers"></select>
      </td>
		</tr>

		<tr style="padding: 20px;float: left;width: 100%;display: block;"> 
      <td class="dataalign"  style="width:30%;">				   
        <span style="width:100%;float:left;height: 35px;line-height: 35px;">Start Date:</span>
			</td>
			<td class="dataalign"  style="width:70%;">
        <input type="text" id="datepicker" name="startdate">       
      </td>               
 	  </tr>

    <tr style="padding: 20px;float: left;width: 100%;display: block;"> 
      <td class="dataalign"  style="width:30%;">           
        <span style="width:100%;float:left;height: 35px;line-height: 35px;">End Date:</span>
      </td>
      <td class="dataalign"  style="width:70%;">
        <input type="text" id="datepicker2" name="enddate">       
      </td>               
    </tr>

		<tr>
		  <td colspan="2" style="margin: 0px auto 20px;text-align: center;width: 150px;display: block;">
        <input type="submit" name="submit" value="Submit" style="padding: 0px 0px;background: #0EB58F;border: 1px solid #0EB58F;color: #fff;font-size:18px;height:45px;border-radius: 4px;line-height:45px;text-align:center;width:100%;">
      </td>
    </tr>
        <?php if($msg!=''){?>
    <tr><td colspan="2"  style="float: left;margin: auto;text-align: left;width: 100%;color:red"><?php echo $msg;?></td>
	  
	  </tr>
        <?php } ?>
     
  </tbody>
</table>
</form>
</div>
<?php 

if (isset($_POST["submit"]) && $_POST['customers']!=''){ 
	 
    $startdate = $_POST["startdate"];
    $enddate = $_POST["enddate"];

    $startdate = date_create($startdate);
    $startdate = date_format($startdate,"Y-m-d");

    $enddate = date_create($enddate);
    $enddate = date_format($enddate,"Y-m-d");
	 
    $customerEmail  = strtolower($_POST['customers']);
    $msg='';
	
    $dbRead = Mage::getSingleton('core/resource')->getConnection('core_read');
    $selectDatewiseOrders='';
    $cuccrentDate = date('Y-m-d');
    if($customerEmail!='') {
		
		if($startdate!='' && $enddate!='')
		{
           $selectDatewiseOrders= "SELECT * FROM healorder WHERE email = '".$customerEmail."' and formatted_orderdate >= '".$startdate."' and formatted_orderdate <= '".$enddate."' order by formatted_orderdate asc";
		}
		else if($startdate!='' && $enddate=='')
		{
			$enddate=date("Y-m-d");
			 $selectDatewiseOrders= "SELECT * FROM healorder WHERE email = '".$customerEmail."' and formatted_orderdate >= '".$startdate."' and formatted_orderdate <= '".$enddate."' order by formatted_orderdate asc";
		}
      
     $customerResult = $dbRead->fetchAll($selectDatewiseOrders);
	 $countCustomerResult= count($customerResult);
		   
    }
    else 
	{
         $msg="Please select the customer name";
    }

        if($msg=='' && $countCustomerResult>0) {
             $customerEmail = $_POST['customers'];
             $customer = Mage::getModel("customer/customer"); 
             $customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
             $customer->loadByEmail($customerEmail);
             $name = ucfirst($customer->getFirstname()). " ".  ucfirst($customer->getLastname());  
             $labelText = $name." ".$countCustomerResult." Days Information";
             
            
         foreach($customerResult as $row)
		 { 
                 $orderId   =  $row['id']; 
                 $mealsByWeekNumber[]= $orderId;
          }
          $finalArray = getWeeklyItemsArray( $mealsByWeekNumber); 
		  
			  ?>

  <div class="table-top-row">
    <div class="table-logo">
      <img src="http://lifeheal.americanarearugs.com/skin/frontend/rwd/default/images/logo.png" alt="Life Healing Food">
    </div>
    <div class="name-content">
      <span id="customerMealResport">
          <b><?php echo $name;?> </b> <br/> Daily Meal Report<br/>
          <span id="customerMealResport">
            <?php echo $startdate. " to " .$enddate; ?> 
         </span>
      </span>
    </div>   
  </div>

  <div class="tabledata">	
    <table class="weekly-table">
	
	    <thead>
        <tr>
          <td> Date </td>
          <td> Cal </td>
          <td> Carbs (Gm) </td>
          <td> Fat (Gm) </td>
          <td> Protein (Gm) </td>
          <td> Fiber (Gm) </td>
        </tr>
      </thead>
	
		  <tbody>
    <?php 
         $coujtRow=0;
				  $total= ((int)$finalArray['totalDesc']['sumCarbs']) + ((int)$finalArray['totalDesc']['sumFat'])+((int)$finalArray['totalDesc']['sumProt']) ;
				  $totalToShow=0;
				  $totalToShow = ((int)$finalArray['totalDesc']['sumCal']) + ((int)$finalArray['totalDesc']['sumFiber'])+$total;
				  				  
				/*  $caloryTotal = (int)$finalArray['totalDesc']['sumCal'];
				  $caloryPercent = round(($caloryTotal/$total )*100,2);*/
				  			  
				  $proteinTotal = (int)$finalArray['totalDesc']['sumProt'];
				  $proteinPercent = round(($proteinTotal/$total)*100,2);
				  
				  $fatTotal = (int)$finalArray['totalDesc']['sumFat'];
				  $fatPercent = round(($fatTotal/$total)*100,2);
				  
				  $carbsTotal = (int)$finalArray['totalDesc']['sumCarbs'];
				  $carbsPercent = round(($carbsTotal /$total)*100,2);				  
              ?>
          <tr id="<?php echo $week;?>" class="collapsiblereport" collapsiblereport="<?php echo $week;?>">
           
            <td> Total </td>
            <td><?php echo (int)$finalArray['totalDesc']['sumCal'];?></td>
            <td><?php echo (int)$finalArray['totalDesc']['sumCarbs'];?></td>
            <td><?php echo (int)$finalArray['totalDesc']['sumFat'];?></td>
            <td><?php echo (int)$finalArray['totalDesc']['sumProt'];?></td>
            <td><?php echo (int)$finalArray['totalDesc']['sumFiber'];?></td>
          </tr>
	        
				  <?php	 
			      foreach($finalArray['weeklyItems'] as $dayMealInfo){ ?>	
            <tr id="datewise_<?php echo $week;?>" class="collapsiblereportprint">	
            <td> <?php echo $dayMealInfo['date'];?></td>									 
            <td> <?php echo (int)$dayMealInfo['calory'];?></td>	
            <td> <?php echo (int)$dayMealInfo['carbs'];?></td>
            <td> <?php echo (int)$dayMealInfo['fat'];?></td>
            <td> <?php echo (int)$dayMealInfo['protein'];?></td>
            <td><?php echo (int)$dayMealInfo['fiber'];?></td>
            </tr> 
            <?php } ?>  
		                 
			  
			 </tbody> 
      </table>
 <?php
}
else {  ?>
            <div style="text-align: center">No meal record found.</div>
<?php  }

}?>


<?php if($total>0) {?>
<div class="print2">
 <style>
.highcharts-figure, .highcharts-data-table table {
  min-width: 320px; 
  max-width: 660px;
  margin: 1em auto;
}

.highcharts-data-table table {
	font-family: Verdana, sans-serif;
	border-collapse: collapse;
	border: 1px solid #EBEBEB;
	margin: 10px auto;
	text-align: center;
	width: 100%;
	max-width: 500px;
}
.highcharts-data-table caption {
  padding: 1em 0;
  font-size: 1.2em;
  color: #555;
}
.highcharts-data-table th {
	font-weight: 600;
  padding: 0.5em;
}
.highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
  padding: 0.5em;
}
.highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
  background: #f8f8f8;
}
.highcharts-data-table tr:hover {
  background: #f1f7ff;
}
</style>
<script src="https://code.highcharts.com/highcharts.js"></script>
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>-->
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
  <div id="container"></div>
  <p class="highcharts-description"></p>
</figure>


<script type="text/javascript">

// Radialize the colors
Highcharts.setOptions({
  colors: Highcharts.map(Highcharts.getOptions().colors, function (color) {
    return {
      radialGradient: {
        cx: 0.5,
        cy: 0.3,
        r: 0.7
      },
      stops: [
        [0, color],
        [1, Highcharts.color(color).brighten(-0.3).get('rgb')] // darken
      ]
    };
  })
});

// Build the chart
Highcharts.chart('container', {
  chart: {
    plotBackgroundColor: null,
    plotBorderWidth: null,
    plotShadow: false,
    type: 'pie'
  },
  credits:{
            enabled:false
        },
  title: {
    text: "<?php //echo $labelText;?>"
  },
  colors:['#5a93ca','#ff6600','#72cf5f'],  
  plotOptions: {
    pie: {
      allowPointSelect: true,
      cursor: 'pointer',
      dataLabels: {
        enabled: true,
        format: '<b>{point.name}</b>: {point.percentage:.1f} %',
        connectorColor: 'silver'
      }
    }
  },
  series: [{
    name: 'Share',
    data: [
    //  { name: 'Calory', y: <?php echo $caloryPercent;?>},
       { name: 'Protein', y: <?php echo $proteinPercent;?> },
	   { name: 'Fat', y: <?php echo $fatPercent;?> },
	   { name: 'Carbs', y: <?php echo $carbsPercent;?>},
      
    ]
  }]
});

</script>
</div>
<?php } ?>


<div>
	  <?php if(isset($_POST["submit"])){
			   if($countCustomerResult>0){?>
			     <div colspan="6" style="text-align:center" class="noprint"> 
			       <input type="button" value="Print" onclick="window.print();" class="print_btn" />
				 <?php } ?>
			 </div>
		 <?php } ?>
</div>

<?php
function getWeeknumber($checkDate)
{
    $tmpDate = explode("-", $checkDate);
    $date  = mktime(0, 0, 0, $tmpDate[1], $tmpDate[2], $tmpDate[0]);
   return $week  = (int)date('W', $date);
    
}

function getMealDate($checkDate)
{
    $tmpDate = explode("-", $checkDate);
    $date  = mktime(0, 0, 0, $tmpDate[1], $tmpDate[2], $tmpDate[0]);
    $week  = (int)date('W', $date);
    $dateToShow   = date('d',$date);
    $day = date('dd',$date);
    $month = date('m',$date);
    $year = date('y',$date);
    
    return $dateToShow.'/'.$month.'/'.$year; 
}


  
  
  function getWeeklyItemsArray($mealsByWeekNumber) {
	//  echo "11111";
	 // print_r($mealsByWeekNumber); die;
      $finalArray = array();
        
         $recordCount=0;
         $weekCount=1;
         $weekDay=0;  
         $weekDayCounter=0;
         $allDinnerCal=0; 
         $allBreakfastCal=0;         
         $allLunchCal=0; 
         $allHighteaCal=0; 
         $totalCal=0;
         $totalProteinGm=0;
         $totalFatGm=0;
         $totalCarbohydreteGm=0;
         $totalFiberGm=0;
         $countWeeklyMeals=0;
         
         $weeklyItems = array();
             foreach($mealsByWeekNumber as $orderId)
             {
                
                $rowTotalCal=0;
                $rowTotalFiberGm=0;
                $rowTotalProteinGm=0;
                $rowTotalFatGm=0;
                $rowTotalCarbohydreteGm=0;
                 
                 $recordCount++;  
                 $weekNumer = $weekNumber;
                 $orderInfo =  Mage::getModel("heal/order")->load($orderId);
                 
                 $customerEmail = $orderInfo->getEmail();
                 $orderFormattedDate = date_create($orderInfo->getFormattedOrderdate());
              
                 $orderDate = date_format($orderFormattedDate,'d/m/Y');

                 $dinnerTotalCalories = $orderInfo->getDinnerTotalCalories(); $rowTotalCal+=$dinnerTotalCalories;
                 
                 $allDinnerCal+= $dinnerTotalCalories; 
                
                 $breakfastTotalCalories = $orderInfo->getBreakfastTotalCalories();  $rowTotalCal+=$breakfastTotalCalories;
                
                 $allBreakfastCal+=     $breakfastTotalCalories; 
                
                 $lunchTotalCalories = $orderInfo->getLunchTotalCalories();    $rowTotalCal+=$lunchTotalCalories;
                 $allLunchCal+=     $lunchTotalCalories; 
                 $highteaTotalCalories = $orderInfo->getHighteaTotalCalories();  $rowTotalCal+=$highteaTotalCalories;
                 $allHighteaCal+=     $highteaTotalCalories; 
                  $totalCal+=$rowTotalCal;
                  $rowTotalCarbohydreteGm =  $orderInfo->getTotalCarbohydrates();
                  $rowTotalProteinGm      =  $orderInfo->getTotalProtein();
                  $rowTotalFatGm          =  $orderInfo->getTotalFat();
                  $rowTotalFiberGm        = $orderInfo->getTotalFiber();
                  
                  $totalCarbohydreteGm+= $rowTotalCarbohydreteGm;
                  $totalProteinGm+= $rowTotalProteinGm;
                   $totalFatGm+= $rowTotalFatGm;
                  $totalFiberGm+= $rowTotalFiberGm;
                  
                  $weeklyItems[] = array('date'=>$orderDate,'calory'=>$rowTotalCal,'carbs'=>$rowTotalCarbohydreteGm,'protein'=>$rowTotalProteinGm,'fat'=>$rowTotalFatGm,'fiber'=>$rowTotalFiberGm);
				    
               
       }  
	   
	  // echo "<pre>"; print_r($weeklyItems); die;
       
        $finalArray['totalDesc'] = array('sumCal'=>$totalCal,'sumProt'=>$totalProteinGm,'sumFat'=>$totalFatGm,'sumCarbs'=>$totalCarbohydreteGm,'sumFiber'=>$totalFiberGm) ;
        $finalArray['weeklyItems'] = $weeklyItems;
    
  
      
      
       return $finalArray;
  }
			

?>
 
	 </div> 

</div>
