
      <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/preloader.css">

    <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/perfect-scrollbar.min.css">
   
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/catalog-page.css">
 
<script src="<?php echo $this->getSkinUrl();?>js/catalog.min.js"></script>


<style>
	.site__content{position: relative;width: 100%;float: left;}
	.dVfvkq2 .dd-wrpr {
    position: absolute;
    z-index: 4;
    bottom: 0rem;
}
	.stand-out__content .itm-dsc__actn__sz {
    flex-flow: column nowrap;
    width: 100%;
    margin: auto;
}
	.stand-out__content .itm-dsc__actn {
    flex-basis: auto;
    flex-flow: row nowrap;
    display: flex;
    margin-top: 0.4rem;
    margin-bottom: 1.5rem;
    margin-top: 0rem;
    margin-bottom: 0.5rem;
    width: 100%;
}
	p {
    margin-top: 0;
    margin-bottom: 0rem;
}
	.itm-dsc__actn__sz__dd-ttl {
    font-size: 13px;
	}
	.iwmcbq {   
    min-width: 3.3em;
    min-height: 3.3em;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    position: relative;
    right: 0px;
}
	.jrxrSi button {
    cursor: pointer;
    padding: 0.433rem;
    border: 0px solid rgb(38, 154, 155) !important;
color:rgb(38, 154, 155);
    background: none;
}
	.box, .box2, .box3, .box4{
        float: left;
overflow: hidden;
background:#f0e68c;
height: 142px;
width: 100%;
position: absolute;
z-index: 3;
right: 0%;
		 display:none;
    }
	 
    /* Add padding and border to inner content
    for better animation effect */
    .box-inner{
        width: 100%;		
        padding: 5px;
        border: 1px solid #a29415;
    }
	 .cCbxqa .itm-dsc__actn__sz {
    flex-flow: column nowrap;
    width: 100%;
    margin: auto;
}
	 .SSFcO {
   float: right;
color:#3d4152;
cursor: pointer;
font-size: 24px;
position: absolute;
right: 10px;
padding: 5px;
top: -5px;
}
	
#myInput {
  box-sizing: border-box;
background-position: 14px 12px;
background-repeat: no-repeat;
font-size: 14px;
padding: 0px 0px 0px 15px;
border: none;
	text-align: left;
    border-bottom-color: currentcolor;
    border-bottom-style: none;
    border-bottom-width: medium;
border-bottom: 1px solid #ddd;

height: 50px !important;
border-radius: 4px;
background:#fff;
color:#000;
width: 100% !important;
}

#myInput:focus {outline: 3px solid #ddd;}



	/*.main-container .container{max-width:100%;padding:0px;}*/

	@media screen and (min-width:260px) and (max-width:760px)
	{
		.site__content{position: relative;width: 100%;float: left;margin-top: 10%;}
		.catalog__filter, .catalog__filter-item {
    display: block;
}
		.itm-dsc__actn__sz__dd-ttl {
    font-size: 12px !important;
}
		.catalog__list {
    max-width: 100%;
    margin: 20px auto;
}
		.SSFcO {
    float: right;
    color:#fff;
    cursor: pointer;
    font-size: 24px;
    position: absolute;
    right: 10px;
    padding: 5px;
    top: -5px;
}
.stickyhead{position: fixed;
top:23px !important;
width: 100%;
}
	 }
	 
</style>
    <!-- site -->
    <div class="site container">

        <!-- site__content -->
        <div class="site__content">

            <!-- catalog -->
            <div class="catalog">

              
                <!-- catalog__frame -->
                <div class="catalog__frame">

              <!--Subscribers Please <Span style="font-weight:bold;">Mark</Span> Your Favorite Items-->
                <h3 style="text-transform: initial;color: #000;text-decoration: underline;margin-top: 30px;text-align: center;">Subscribers please <Span style="font-weight:bold;">Mark</Span> your favorite items. Our nutritionist will then build your personalized menu based on your preferences.</h3>

                      <div class="catalog__filter">
                   <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">
                            <strong>Cuisine:</strong>
                        </button>
                        <!-- /catalog__filter-item -->
						  	  <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="breakfastall"  onclick="showCategoryProducts(this.id)" >
                            <strong>Breakfast</strong>
						</button>		
						
                        <!-- /catalog__filter-item -->
                        <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="saladall"  onclick="showCategoryProducts(this.id)" >
                            <strong>Salad</strong>
						</button>						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="soupall"  onclick="showCategoryProducts(this.id)">
                            <strong>Soup</strong>
						</button>						
                        <!-- /catalog__filter-item -->
						
						  <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="ricerotiall"  onclick="showCategoryProducts(this.id)" >
                            <strong>Rice/Roti</strong>
						</button>		
						
                        <!-- /catalog__filter-item -->
						  <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="dessertall"  onclick="showCategoryProducts(this.id)" >
                            <strong>Desserts</strong>
						</button>		
						
                        <!-- /catalog__filter-item -->
					
                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" id="indianitem"  onclick="showCategoryProducts(this.id)">
                            <strong>Indian</strong> 
                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" id="chineseall" onclick="showCategoryProducts(this.id)">
                            <strong>Chinese Combo</strong>
                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" id="italianall"  onclick="showCategoryProducts(this.id)">
                            <strong>Italian Combo</strong> 
                       </button>
                        <!-- /catalog__filter-item -->
<!-- catalog__filter-item -->
                         <!--<button type="button" class="catalog__filter-item" id="gharkakhanna"  onclick="showCategoryProducts(this.id)">
                            <strong>Ghar Ka Khanna</strong> 
                       </button>-->
                        <!-- /catalog__filter-item -->
						
							
                    </div>
                    <!-- /catalog__filter -->
					
					
                   
					
                    <!-- catalog__wrap -->
                    <div class="catalog__wrap" id="category-products-container">

                        <!-- catalog__wrap -->
                        <div class="catalog__list">

                       

                        </div>

                    </div>
                    <!-- /catalog__wrap -->

                  

                </div>
                <!-- /catalog__frame -->

            </div>
            <!-- /catalog -->

           

        </div>
        <!-- /site__content -->


    </div>
    <!-- /site -->


     <script src="<?php echo $this->getSkinUrl();?>js/perfect-scrollbar.jquery.min.js"></script>
<script src="<?php echo $this->getSkinUrl();?>js/jquery-3.2.1.min.js"></script>

<script type="text/javascript">
        
       function showCategoryProducts(buttonId)
       {   catid=125;
		//alert(buttonId);
           if(buttonId=='indianitem' || buttonId=='indianitem')
           {
               catid=92;
			      jQuery("#chineseall").removeClass("active");
			    	jQuery("#indianitem").addClass("active");		 
			     jQuery("#indianitem").show();  
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			   jQuery("#saladall").removeClass("active");			   
			    jQuery("#italianall").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");		   
			   jQuery("#soupall").removeClass("active");
			    jQuery("#gharkakhanna").removeClass("active");
           }
          
		else if (buttonId=='gharkakhanna')
           {
              catid=134 
			   jQuery("#gharkakhanna").addClass("active");
			     jQuery("#gharkakhanna").show();  
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			   jQuery("#indianitem").removeClass("active");			   
			    jQuery("#italianall").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
           }
          else if (buttonId=='chineseall')
           {
              catid=124; 
			    jQuery("#gharkakhanna").removeClass("active");
			   jQuery("#chineseall").addClass("active");
			     jQuery("#chineseall").show();  
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			   jQuery("#indianitem").removeClass("active");			   
			    jQuery("#italianall").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
           }
			
		else if (buttonId=='italianall')
           {
              catid=93; 
			     jQuery("#italianall").addClass("active");			   
			   jQuery("#italianall").show();
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			      jQuery("#chineseall").removeClass("active");			  	
			   jQuery("#indianitem").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
			 
           }	
		else if (buttonId=='breakfastall')
           {
              catid=125; 
			    jQuery("#gharkakhanna").removeClass("active");
			        jQuery("#italianall").removeClass("active");
			    jQuery("#breakfastall").addClass("active");
			   jQuery("#breakfastall").show();	
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			      jQuery("#chineseall").removeClass("active");			
			   jQuery("#indianitem").removeClass("active");			  
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
			 
           }	
		else if (buttonId=='soupall')
           {
              catid=126; 
			    jQuery("#gharkakhanna").removeClass("active");
			   jQuery("#chineseall").removeClass("active");
			      jQuery("#soupall").addClass("active");			 
			     jQuery("#soupall").show();
			   jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#dessertall").removeClass("active");
			   jQuery("#indianitem").removeClass("active");			   
			    jQuery("#italianall").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");
			   	 			
			   jQuery("#saladall").removeClass("active");
           }	
		else if (buttonId=='saladall')
           {
              catid=127; 
			    jQuery("#gharkakhanna").removeClass("active");
			     jQuery("#chineseall").removeClass("active");
			    	jQuery("#saladall").addClass("active");		 
			     jQuery("#saladall").show();  
			      jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#desssertall").removeClass("active");
			   jQuery("#indianitem").removeClass("active");			   
			    jQuery("#italianall").removeClass("active");
			   jQuery("#breakfastall").removeClass("active");		   
			   jQuery("#soupall").removeClass("active");	
           }	
		else if (buttonId=='ricerotiall')
           {
              catid=128; 
			    jQuery("#gharkakhanna").removeClass("active");
			        jQuery("#italianall").removeClass("active");
			    jQuery("#ricerotiall").addClass("active");
			   jQuery("#ricerotiall").show();	
			     jQuery("#dessertall").removeClass("active");
			    jQuery("#breakfastall").removeClass("active");	
			      jQuery("#chineseall").removeClass("active");			
			   jQuery("#indianitem").removeClass("active");			  
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
			 
           }	
		else if (buttonId=='dessertall')
           {
              catid=129; 
			    jQuery("#gharkakhanna").removeClass("active");
			        jQuery("#italianall").removeClass("active");
			    jQuery("#desssertall").addClass("active");
			   jQuery("#dessertall").show();
			    jQuery("#ricerotiall").removeClass("active");	
			    jQuery("#breakfastall").removeClass("active");	
			      jQuery("#chineseall").removeClass("active");			
			   jQuery("#indianitem").removeClass("active");			  
			    jQuery("#soupall").removeClass("active");			   	 			
			   jQuery("#saladall").removeClass("active");
			 
           }	
          jQuery.ajax({
                        url: "<?php echo Mage::getBaseUrl().'override/index/getcategoryproducts' ?>",
                        type: "POST",
                        data: {
                                 catid: catid
                              }, 
                        success: function(response) {
                            //alert(response);
                            jQuery("#category-products-container").html(response);

                        }
                      }); 
      }
        </script>
<script>

jQuery(document).ready(function(){
	 var buttonId = 'breakfastall';
	//alert(buttonId);
	 showCategoryProducts(buttonId);
 jQuery("#indianitem").click(function(){   
	 jQuery("#indianitem").addClass("active");
	 jQuery("#chineseitem").removeClass("active");	 
	  jQuery("#italianitem").removeClass("active");	 
	   jQuery("#italiansubitem").hide();
  });
	
	jQuery("#chineseitem").click(function(){
   jQuery("#chinesesubitem").show();
		jQuery("#indianitem").removeClass("active");
		jQuery("#chineseitem").addClass("active");	
	  jQuery("#italianitem").removeClass("active");
		jQuery("#indiansubitem").hide();	  
	   jQuery("#italiansubitem").hide();
  });
	

	
		jQuery("#italianitem").click(function(){
   jQuery("#italiansubitem").show();
			jQuery("#indianitem").removeClass("active");
		jQuery("#chineseitem").removeClass("active");		
	  jQuery("#italianitem").addClass("active");
	   jQuery("#indiansubitem").hide();
	   jQuery("#chinesesubitem").hide();
	  
  });
	
});
</script>

 