
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/preloader.css">

    <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/perfect-scrollbar.min.css">
   
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/catalog-page.css">
 <script src="<?php echo $this->getSkinUrl();?>js/jquery-3.2.1.min.js"></script>

<script src="<?php echo $this->getSkinUrl();?>js/catalog.min.js"></script>
 
    <!-- site -->
    <div class="site">

        <!-- site__content -->
        <div class="site__content">

            <!-- catalog -->
            <div class="catalog">

              
                <!-- catalog__frame -->
                <div class="catalog__frame">

                

                    <!-- catalog__filter -->
                    <div class="catalog__filter">
                   <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">

                            <strong>Cuisine:</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" id="indianitem"  onclick="showCategoryProducts(this.id)">

                            <strong>Indian</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item" id="chineseitem">

                            <strong>Chinese</strong>

                            

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item active" id="mughlaiitem"  onclick="showCategoryProducts(this.id)">

                            <strong>Mughlai</strong>

                          

                       </button>
                        <!-- /catalog__filter-item -->

						 <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item" id="italianitem">

                            <strong>Italian</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
                        <button type="button" class="catalog__filter-all">
                            <span>See all filters</span>
                        </button>

                    </div>
                    <!-- /catalog__filter -->
					
                    <!-- catalog__filter -->
                    <div class="catalog__filter" id="indiansubitem" style="display: none;">
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">

                            <strong>Items:</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->


                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" onclick="showCategoryProducts(this.id)" id="indiancombo">

                            <strong>Combo</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight">

                            <strong>All</strong>

                            

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight">

                            <strong>Soup</strong>

                          

                       </button>
                        <!-- /catalog__filter-item -->

						 <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Salad</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Rice</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Roti</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Desserts</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
					</div>
					
					 <!-- catalog__filter -->
                    <div class="catalog__filter" id="chinesesubitem" style="display: none;">
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">

                            <strong>Items:</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" onclick="showCategoryProducts(this.id)" id="chineseall">

                            <strong>All</strong>                           

                        </button>
                        <!-- /catalog__filter-item -->

                     
                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="chinesesoup"  onclick="showCategoryProducts(this.id)" >

                            <strong>Soups</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="chinesesalad"  onclick="showCategoryProducts(this.id)" >

                            <strong>Salads</strong>

                            

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="chinesemomos"  onclick="showCategoryProducts(this.id)" >

                            <strong>Momos</strong>

                          

                       </button>
                        <!-- /catalog__filter-item -->

						 <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chineseappetizers"  onclick="showCategoryProducts(this.id)" >
                            <strong>Appetizers</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chinesetofu"  onclick="showCategoryProducts(this.id)" >

                            <strong>Tofu</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chinesemains"  onclick="showCategoryProducts(this.id)" >

                            <strong>Mains</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chinesechicken"  onclick="showCategoryProducts(this.id)" >

                            <strong>Chicken</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chineserice"  onclick="showCategoryProducts(this.id)" >

                            <strong>Rice</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chinesenoodles"  onclick="showCategoryProducts(this.id)" >

                            <strong>Noodles</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="chinesedesserts"  onclick="showCategoryProducts(this.id)" >

                            <strong>Desserts</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
					</div>					
					
					 <!-- catalog__filter -->
					<div class="catalog__filter" id="mughlaisubitem">
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">

                            <strong>Items:</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->
                  <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="mughlaiall" onclick="showCategoryProducts(this.id)">

                            <strong>All</strong>

                         

                        </button>
                        <!-- /catalog__filter-item -->
						
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="mughlaicombo" onclick="showCategoryProducts(this.id)" >

                            <strong>Combo</strong>

                         

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="kabab-mughlai" onclick="showCategoryProducts(this.id)" >

                            <strong>Kababs</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="Shorbha-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Shorbha</strong>

                            

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" id="Salads-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Salads</strong>

                          

                       </button>
                        <!-- /catalog__filter-item -->

						 <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Subji-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Subji</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Paneer-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Paneer</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Daal-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Daal</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Chicken-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Chicken</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Rice-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Rice</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						
						
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Raita-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Raita</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Breads-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Breads</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight" id="Desserts-mughlai" onclick="showCategoryProducts(this.id)">

                            <strong>Desserts</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
					</div>
					
					 <!-- catalog__filter -->
                    <div class="catalog__filter" id="italiansubitem"  style="display: none;">
						<!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight" style="text-decoration:underline;border: 2px solid #e9e3d5;color: #333 !important;background: #fff;">

                            <strong>Items:</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->


                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight">

                            <strong>Combo</strong>

                           

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight">

                            <strong>All</strong>

                            

                        </button>
                        <!-- /catalog__filter-item -->

                        <!-- catalog__filter-item -->
                         <button type="button" class="catalog__filter-item btnheight">

                            <strong>Soup</strong>

                          

                       </button>
                        <!-- /catalog__filter-item -->

						 <!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Salad</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Rice</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Roti</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
						<!-- catalog__filter-item -->
                         <button type="button"class="catalog__filter-item btnheight">

                            <strong>Desserts</strong>

                          

						</button>
						
                        <!-- /catalog__filter-item -->
					</div>
                    <!-- catalog__wrap -->
                    <div class="catalog__wrap" id="category-products-container">

                        <!-- catalog__wrap -->
                        <div class="catalog__list">

                           

                        </div>

                    </div>
                    <!-- /catalog__wrap -->

                  

                </div>
                <!-- /catalog__frame -->

            </div>
            <!-- /catalog -->

           
            <!-- filter -->
            <div class="filter">

                <div class="filter__header">
                    <a href="#" class="filter__close">

                        <svg viewBox="0 0 512 512"><path d="M437.5,386.6L306.9,256l130.6-130.6c14.1-14.1,14.1-36.8,0-50.9c-14.1-14.1-36.8-14.1-50.9,0L256,205.1L125.4,74.5  c-14.1-14.1-36.8-14.1-50.9,0c-14.1,14.1-14.1,36.8,0,50.9L205.1,256L74.5,386.6c-14.1,14.1-14.1,36.8,0,50.9  c14.1,14.1,36.8,14.1,50.9,0L256,306.9l130.6,130.6c14.1,14.1,36.8,14.1,50.9,0C451.5,423.4,451.5,400.6,437.5,386.6z"/></svg>

                        <span>
                        <span>
                            <svg viewBox="0 0 17 16">
                                <g>
                                    <path d="M6.7,7.8L1.3,0H4c0.2,0,0.4,0,0.5,0.1c0.1,0.1,0.2,0.2,0.3,0.3l3.9,6C8.8,6.1,9,5.8,9.1,5.5l3.4-5.1
                                        c0.1-0.1,0.2-0.3,0.3-0.4C13,0,13.1,0,13.3,0h2.6l-5.4,7.6l5.6,8.4h-2.7c-0.2,0-0.4-0.1-0.5-0.2c-0.1-0.1-0.2-0.3-0.3-0.4l-4-6.3
                                        C8.4,9.5,8.3,9.7,8.2,10l-3.7,5.5c-0.1,0.1-0.2,0.3-0.3,0.4C4,15.9,3.8,16,3.6,16H1.1L6.7,7.8z"/>
                                </g>
                            </svg>
                        </span>
                        <span>Close filter</span>
                    </span>

                    </a>
                </div>

                <!-- filter__wrap -->
                <div class="filter__wrap">

                    <!-- filter__wrap-head -->
                    <div class="filter__wrap-head">
                        <span class="filter__title">Filter by</span>
                        <a href="#" class="filter__clear-all">Clear All</a>
                    </div>
                    <!-- /filter__wrap-head -->

                    <!-- filter__item -->
                    <div class="filter__item">

                        <div class="filter__item-topic">
                            <span>Indian</span>
                            <a href="#" class="filter__item-clear">Clear</a>
                        </div>

                         <!-- filter__item-wrap -->
                        <div class="filter__item-wrap">

                            <div class="filter__item-list">
                               <label class="containerradio" onclick="showCategoryProducts('indiancombo')">Combo
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">All
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Soup
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio">Salad
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Rice
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Roti
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio">Desserts
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                            </div>

                        </div>
                        <!-- /filter__item-wrap -->

                    </div>
                    <!-- /filter__item -->
                    <!-- filter__item -->
                    <div class="filter__item">

                        <div class="filter__item-topic">
                            <span>Chinese</span>
                            <a href="#" class="filter__item-clear">Clear</a>
                        </div>

                        <!-- filter__item-wrap -->
                        <div class="filter__item-wrap">
 <label class="containerradio"  onclick="showCategoryProducts('chineseall')">All
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                            <div class="filter__item-list">
                               <label class="containerradio" onclick="showCategoryProducts('chinesesoup')" >Soup
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('chinesesalad')" >Salads
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('chinesemomos')">Momos
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('chineseappetizers')">Appetizers
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                  <label class="containerradio" onclick="showCategoryProducts('chinesetofu')">Tofu
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio" onclick="showCategoryProducts('chinesemains')">Mains
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio" onclick="showCategoryProducts('chinesechicken')">Chicken
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								   <label class="containerradio" onclick="showCategoryProducts('chineserice')">Rice
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                   <label class="containerradio" onclick="showCategoryProducts('chinesenoodles')">Noodles
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								  <label class="containerradio" onclick="showCategoryProducts('chinesedesserts')">Desserts
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                            </div>

                        </div>
                        <!-- /filter__item-wrap -->

                    </div>
                    <!-- /filter__item -->

                     <!-- filter__item -->
                    <div class="filter__item">

                        <div class="filter__item-topic">
                            <span>Mughlai</span>
                            <a href="#" class="filter__item-clear">Clear</a>
                        </div>

                        <!-- filter__item-wrap -->
                        <div class="filter__item-wrap">

                            <div class="filter__item-list">
							 <label class="containerradio" onclick="showCategoryProducts('mughlaiall')">All
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>				
							 <label class="containerradio" onclick="showCategoryProducts('mughlaicombo')">Combo
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
				  <label class="containerradio" onclick="showCategoryProducts('Shorbha-mughlai')">Shorbha
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('kabab-mughlai')">Kababs
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                              <label class="containerradio" onclick="showCategoryProducts('Salads-mughlai')">Salads
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('Subji-mughlai')">Subji
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio" onclick="showCategoryProducts('Paneer-mughlai')">Paneer
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                  <label class="containerradio" onclick="showCategoryProducts('Daal-mughlai')">Daal
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                  <label class="containerradio" onclick="showCategoryProducts('Chicken-mughlai')">Chicken
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								  <label class="containerradio" onclick="showCategoryProducts('Rice-mughlai')">Rice
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								  <label class="containerradio" onclick="showCategoryProducts('Raita-mughlai')">Raita
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								  <label class="containerradio" onclick="showCategoryProducts('Breads-mughlai')">Breads
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
								  <label class="containerradio" onclick="showCategoryProducts('Desserts-mughlai')">Desserts
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                
                            </div>

                        </div>
                        <!-- /filter__item-wrap -->

						</div>
                    <!-- /filter__item -->
					
                    <!-- filter__item -->
                    <div class="filter__item">

                        <div class="filter__item-topic">
                            <span>Italian</span>
                            <a href="#" class="filter__item-clear">Clear</a>
                        </div>

                        <!-- filter__item-wrap -->
                        <div class="filter__item-wrap">

                            <div class="filter__item-list">
                               <label class="containerradio">Combo
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">All
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Soup
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio">Salad
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Rice
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                 <label class="containerradio">Roti
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                                <label class="containerradio">Desserts
  <input type="radio"  name="radio">
  <span class="radiomark"></span>
</label>
                            </div>

                        </div>
                        <!-- /filter__item-wrap -->

                    </div>
                    <!-- /filter__item -->
                    

                </div>
                <!-- /filter__wrap -->

            </div>
            <!-- /filter -->

        </div>
        <!-- /site__content -->


    </div>
    <!-- /site -->
    <script src="<?php echo $this->getSkinUrl();?>js/perfect-scrollbar.jquery.min.js"></script>

<script type="text/javascript">
        
       function showCategoryProducts(buttonId)
       {   catid=61;
           if(buttonId=='mughlaiall' || buttonId=='mughlaiitem')
           {
               catid=61;
			   jQuery("#mughlaiall").addClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
			  
           }
          else if (buttonId=='mughlaicombo')
           {
              catid=84; 
			      jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").addClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='Shorbha-mughlai')
           {
              catid=62; 
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").addClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='Salads-mughlai')
           {
              catid=64; 
			    jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").addClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='Subji-mughlai')
           {
              catid=65; 
			    jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").addClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		 else if (buttonId=='kabab-mughlai')
           {
              catid=66; 
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").addClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Paneer-mughlai')
           {
              catid=67; 
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").addClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Daal-mughlai')
           {
              catid=68; 
			    jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").addClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Chicken-mughlai')
           {
              catid=69; 
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").addClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Rice-mughlai')
           {
              catid=70; 
			  		   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").addClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Raita-mughlai')
           {
              catid=71; 
			   	   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").addClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Breads-mughlai')
           {
              catid=72; 
			    	   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").addClass("active");
			   jQuery("#Desserts-mughlai").removeClass("active");
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
			   jQuery("#chinesesubitem").hide();
           }
		else if (buttonId=='Desserts-mughlai')
           {
              catid=73; 
			   	   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#mughlaicombo").removeClass("active");
			   jQuery("#Shorbha-mughlai").removeClass("active");
			   jQuery("#Salads-mughlai").removeClass("active");
			   jQuery("#Subji-mughlai").removeClass("active");
			   jQuery("#kabab-mughlai").removeClass("active");
			   jQuery("#Paneer-mughlai").removeClass("active");
			   jQuery("#Daal-mughlai").removeClass("active");
			   jQuery("#Chicken-mughlai").removeClass("active");
			   jQuery("#Rice-mughlai").removeClass("active");
			   jQuery("#Raita-mughlai").removeClass("active");
			   jQuery("#Breads-mughlai").removeClass("active");
			   jQuery("#Desserts-mughlai").addClass("active");			   
			   jQuery("#mughlaisubitem").show();
			   jQuery("#mughlaiitem").show();
			   jQuery("#mughlaiitem").addClass("active");			
			   jQuery("#chineseitem").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		
		
          else if (buttonId=='chineseall')
           {
              catid=63; 
			   jQuery("#chineseall").addClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaiitem").hide();
			   jQuery("#mughlaisubitem").hide();
           }
		else if (buttonId=='chinesesoup')
           {
              catid=74; 
			     jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").addClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesesalad')
           {
              catid=75; 
			      jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").addClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			 jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesemomos')
           {
              catid=76; 
			       jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").addClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			 jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
			   
           }
		 else if (buttonId=='chineseappetizers')
           {
              catid=78;
			       jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").addClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesetofu')
           {
              catid=77; 
			      jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").addClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesemains')
           {
              catid=79; 
			     jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").addClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesechicken')
           {
              catid=80; 
			    jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").addClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chineserice')
           {
              catid=81; 
			      jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").addClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			    jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
		   }
		else if (buttonId=='chinesenoodles')
           {
              catid=82; 
			     jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").addClass("active");
			   jQuery("#chinesedesserts").removeClass("active");
			   jQuery("#mughlaiall").removeClass("active");
		       jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			   jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }
		else if (buttonId=='chinesedesserts')
           {
              catid=83; 
			    jQuery("#chineseall").removeClass("active");
			   jQuery("#chinesecombo").removeClass("active");
			   jQuery("#chinesesoup").removeClass("active");
			   jQuery("#chinesesalad").removeClass("active");
			   jQuery("#chinesemomos").removeClass("active");
			   jQuery("#chineseappetizers").removeClass("active");
			   jQuery("#chinesetofu").removeClass("active");
			   jQuery("#chinesechicken").removeClass("active");
			   jQuery("#chineserice").removeClass("active");
			   jQuery("#chinesemains").removeClass("active");
			   jQuery("#chinesenoodles").removeClass("active");
			   jQuery("#chinesedesserts").addClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").show();
			   jQuery("#chineseitem").show();
			   jQuery("#chineseitem").addClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			  jQuery("#indianitem").removeClass("active");
			   jQuery("#indiansubitem").hide();
           }		
		else if (buttonId=='indiancombo')
           {
              catid=87; 
			    jQuery("#indiancombo").removeClass("active");
			   jQuery("#indiansubitem").show();
			   jQuery("#indianitem").show();
			   jQuery("#indianitem").addClass("active");
			   jQuery("#mughlaiall").removeClass("active");
			   jQuery("#chinesesubitem").hide();
			   jQuery("#chineseitem").show();
			    jQuery("#mughlaiitem").show();
			   jQuery("#chineseitem").removeClass("active");			
			   jQuery("#mughlaiitem").removeClass("active");
			   jQuery("#mughlaisubitem").hide();
			 
           }		
           jQuery.ajax({
                        url: "<?php echo Mage::getBaseUrl().'override/index/getcategoryproducts' ?>",
                        type: "POST",
                        data: {
                                 catid: catid
                              }, 
                        success: function(response) {
                            //alert(response);
                            jQuery("#category-products-container").html(response);

                        }
                      }); 
       }
        </script>
<script>

jQuery(document).ready(function(){
	 var buttonId = 'mughlaiall';
	 showCategoryProducts(buttonId);
 jQuery("#indianitem").click(function(){
   jQuery("#indiansubitem").show();
	 jQuery("#indianitem").addClass("active");
	 jQuery("#chineseitem").removeClass("active");
	  jQuery("#mughlaiitem").removeClass("active");
	  jQuery("#italianitem").removeClass("active");
	   jQuery("#chinesesubitem").hide();
	   jQuery("#mughlaisubitem").hide();
	   jQuery("#italiansubitem").hide();
  });
	
	jQuery("#chineseitem").click(function(){
   jQuery("#chinesesubitem").show();
		jQuery("#indianitem").removeClass("active");
		jQuery("#chineseitem").addClass("active");
		  jQuery("#mughlaiitem").removeClass("active");
	  jQuery("#italianitem").removeClass("active");
	   jQuery("#indiansubitem").hide();
	   jQuery("#mughlaisubitem").hide();
	   jQuery("#italiansubitem").hide();
  });
	
	jQuery("#mughlaiitem").click(function(){
   jQuery("#mughlaisubitem").show();
		jQuery("#indianitem").removeClass("active");
		jQuery("#chineseitem").removeClass("active");
		  jQuery("#mughlaiitem").addClass("active");
	  jQuery("#italianitem").removeClass("active");
	   jQuery("#indiansubitem").hide();
	   jQuery("#chinesesubitem").hide();
	   jQuery("#italiansubitem").hide();
  });
	
		jQuery("#italianitem").click(function(){
   jQuery("#italiansubitem").show();
			jQuery("#indianitem").removeClass("active");
		jQuery("#chineseitem").removeClass("active");
		  jQuery("#mughlaiitem").removeClass("active");
	  jQuery("#italianitem").addClass("active");
	   jQuery("#indiansubitem").hide();
	   jQuery("#chinesesubitem").hide();
	   jQuery("#mughlaisubitem").hide();
  });
});
</script>

   
	

