<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/diabetes_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/diabetes_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>NO NEED TO CHEAT</h1>		        	
		        	<p>Reverse your diabetes and increase freedom.</p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- How it Works Start -->
	<style>
		.disease-single-how-it-works h2, 
		.disease-single-how-it-works h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works disease-single-how-it-works">
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">80% clients completing 1 month successfully reduced medications.</p>

			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">The LifeHeal plan normally stops insulin, improves blood glucose and reduces medications. You get a digital approach to your glucose and diet.</p>			

			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000"><span>Steps included in diabetes management</span></p>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Deep Dive</h3>
					<p>You get one the most advanced  analyses exploring the source of your diabetes using our A.I. tool. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>Customizing</h3>
					<p>Your plan is built around you using your inputs, goals and current capacity. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Start</h3>
					<p>You get positive changes in energy, mood and biomarkers.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-4.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Support</h3>
					<p>Most failures happen in the mind. We give a plan and support you through it.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-5.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Track & Guide</h3>
					<p>You are skillfully guided to your next steps. We track over 65 biomarkers.</p>					
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-6.png') ?>"/>
					<h4>STEP 6</h4>					
					<h3>Success</h3>
					<p>Your health goes beyond your diseases. True health is in prevention.</p>
				</div>				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->	
	<!-- Meal Plans Start -->
	<style>
	
		.disease-single-meal-plans {
			background-color: #0EB58F;
		}
		
		.disease-single-meal-plans .single-meal-plans-title {
			color: #FFFFFF;
		}
		
	</style>
	<div class="single-meal-plans disease-single-meal-plans full-height">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>DIABETES MANAGEMENT <br>MEAL PLANS</h2>
				<p>Let's face it, you need to start treating your diabetes and not its symptoms. Medications ought to be reducing and you should try to eliminate them, not live with them. Find out why some of India’s top doctors use LifeHeal. Start Now.</p>
			</div>
			
			<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Diabetes Reduction</h3>
						<h2>Rs. 8,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2683)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Diabetes Reduction</h3>
						<h2>Rs. 6,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2638)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Diabetes Reduction</h3>
						<h2>Rs. 5,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2637)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Diabetes Reduction</h3>
						<h2>Rs. 4,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2636)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Meal Plans End -->
	
	<!-- Impact Story Start -->
	<div class="impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
			<img src="<?php echo $this->getSkinUrl('images/manoj_sangal.jpg') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL MANOJ SANGAL STOPPED INSULIN IN 35 DAYS</h2>
				<h3>Manoj Sangal, 50 Years, Businessman, <span>New Delhi</span></h3>
				<p>I had been on a high dose of insulin since 2011. In 5 weeks of diligently adhering to the LifeHeal program, I stopped taking insulin completely. As an add on, I also lost 10 kgs in 3 months.</p>
				<!-- https://www.youtube.com/watch?v=598Y6Vhq7bw -->
				<div class="impact-story-detail-videos" style="display: block;">
					<a href="https://www.youtube.com/watch?v=If7ZrY-yudA" data-youtube-id="If7ZrY-yudA" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/manoj_sangal_video_1.jpg') ?>"/>
					</a>
					
					<!--<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
						
					</a>-->
				</div>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->
	
	<!-- Stats Start -->
	<div class="stats">
		<div class="stats-container">
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
					
			
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	<!-- Stats End -->
	
	<!-- Testimonials Start -->
	<style>
		.disease-single-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
	<div class="testimonials disease-single-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHAT OUR USERS SAY ABOUT OUR MEAL PLANS</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I was a little nervous and skeptical before starting my diet. I was afraid I'd have to give up my favorite foods. But surprisingly, the diet created by LifeHeal had all my favorite foods, of course, with delicious tweaks and modifications. The progress was simply tremendous. Within a few weeks, my blood sugar levels started coming down from 300+ to 150.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test9.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Shalini Mehta, Diabetes reduction</h3>
							<p>50 Years, Homemaker, kanpur</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>In my routine health checkup I discovered I was pre-diabetic. As I already have family history of diabetes I knew I had to do something. Within 2 months of following the diet my HbA1c came 5.4.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test14.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Jital Kumar, From <br>pre-diabetic to non-diabetic</h3>
							<p>42 Years, Businessman, Pune</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>LifeHeal plans weren't just about changing diet. Their holistic approach and open consultation educated me on the mistakes I was making in my daily routine. The results were beyond my imagination. Within a few days, my constipation improved, and I lost 1.5kgs. My blood sugar levels also started improving. I couldn't be happier.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test1.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Vineet Sagar, Lost 6 kgs, With Improved Blood Glucose</h3>
							<p>50 Years, Businessman, Hyderabad</p>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans.  </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->


<!--=========================MODAL NEW =================-->

<div class="custom_modal">
	<div class="inner_custom_modal">
		<span id="modal_close"><i class="far fa-times-circle"></i></span>
		<h2>Get a Free info packet on <br/>
		Diabetes Reversal from LifeHeal.</h2>
		
		<form action='https://crm.zoho.in/crm/WebToLeadForm' name=WebToLeads126676000004773036 method='POST' onSubmit='javascript:document.charset="UTF-8"; return checkMandatory126676000004773036()' accept-charset='UTF-8'>
 			<input type='text' style='display:none;' name='xnQsjsdp' value='b43efcd5d07598c5a2dec7cbbd9f0a4a4778bde7ffbd77b08070784d65801fa2'></input> 
 			<input type='hidden' name='zc_gad' id='zc_gad' value=''></input> 
 			<input type='text' style='display:none;' name='xmIwtLD' value='5f229f01e98885a79974c37c8c9fe2b598a1db383d716183c21b1ba5b3897c28'></input> 
 			<input type='text'  style='display:none;' name='actionType' value='TGVhZHM='></input>
 			
 			<!--<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;startlifeheal.com&#x2f;hypertension&#x2f;' > </input>-->
 			<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;startlifeheal.com&#x2f;heal-diabetes&#x2f;' > </input>
			<div class='wfrm_fld_dpNn'>
				<select class='zcwf_col_fld_slt' id='LEADCF1' name='LEADCF1' multiple >
					<option selected value='Weight&#x20;Loss'>Weight Loss</option>
					<option value='Diabetes'>Diabetes</option>
					<option value='Cardiac'>Cardiac</option>
					<option value='Fatty&#x20;Liver'>Fatty Liver</option>
					<option value='Fitness'>Fitness</option>
					<option value='Thyroid'>Thyroid</option>
					<option value='PCOD'>PCOD</option>
					<option value='Pregnancy'>Pregnancy</option>
					<option value='Gut&#x20;Issues'>Gut Issues</option>
					<option value='Constipation'>Constipation</option>
					<option value='Immunity'>Immunity</option>
				</select>
			</div>	
			<input type='text' ftype='email' id='Email' name='Email' placeholder="e-mail"></input>
			<input type='hidden' id='Last_Name' name='Last Name' value="Diabetes Pop Up"></input>
			<div class='wfrm_fld_dpNn'>
				<input type='checkbox' class='zcwf_ckbox' id='LEADCF101' name='LEADCF101' maxlength='3' checked='true'></input>
			</div>
				
			<input type='submit' id='formsubmit' class='formsubmit zcwf_button' value='Submit' title='Submit'>
			<input type='reset' style="display: none;" class='zcwf_button' name='reset' value='Reset' title='Reset'>
		</form>
		<p>FREE info pocket will be delivered on your email within few minutes.</p>
	</div>

	<script>
	function validateEmail126676000004773036()
	{
		var form = document.forms['WebToLeads126676000004773036'];
		var emailFld = form.querySelectorAll('[ftype=email]');
		var i;
		for (i = 0; i < emailFld.length; i++)
		{
			var emailVal = emailFld[i].value;
			if((emailVal.replace(/^\s+|\s+$/g, '')).length!=0 )
			{
				var atpos=emailVal.indexOf('@');
				var dotpos=emailVal.lastIndexOf('.');
				if (atpos<1 || dotpos<atpos+2 || dotpos+2>=emailVal.length)
				{
					alert('Please enter a valid email address. ');
					emailFld[i].focus();
					return false;
				}
			}
		}
		return true;
	}

 	  function checkMandatory126676000004773036() {
		var mndFileds = new Array('Last Name');
		var fldLangVal = new Array('Last\x20Name');
		for(i=0;i<mndFileds.length;i++) {
		  var fieldObj=document.forms['WebToLeads126676000004773036'][mndFileds[i]];
		  if(fieldObj) {
			if (((fieldObj.value).replace(/^\s+|\s+$/g, '')).length==0) {
			 if(fieldObj.type =='file')
				{ 
				 alert('Please select a file to upload.'); 
				 fieldObj.focus(); 
				 return false;
				} 
			alert(fldLangVal[i] +' cannot be empty.'); 
   	   	  	  fieldObj.focus();
   	   	  	  return false;
			}  else if(fieldObj.nodeName=='SELECT') {
  	   	   	 if(fieldObj.options[fieldObj.selectedIndex].value=='-None-') {
				alert(fldLangVal[i] +' cannot be none.'); 
				fieldObj.focus();
				return false;
			   }
			} else if(fieldObj.type =='checkbox'){
 	 	 	 if(fieldObj.checked == false){
				alert('Please accept  '+fldLangVal[i]);
				fieldObj.focus();
				return false;
			   } 
			 } 
			 try {
			     if(fieldObj.name == 'Last Name') {
				name = fieldObj.value;
 	 	 	    }
			} catch (e) {}
		    }
		}
		if(!validateEmail126676000004773036()){return false;}
		document.querySelector('.crmWebToEntityForm .formsubmit').setAttribute('disabled', true);
	}

function tooltipShow126676000004773036(el){
	var tooltip = el.nextElementSibling;
	var tooltipDisplay = tooltip.style.display;
	if(tooltipDisplay == 'none'){
		var allTooltip = document.getElementsByClassName('zcwf_tooltip_over');
		for(i=0; i<allTooltip.length; i++){
			allTooltip[i].style.display='none';
		}
		tooltip.style.display = 'block';
	}else{
		tooltip.style.display='none';
	}
}
</script>
	<!-- Do not remove this --- Analytics Tracking code starts --><script id='wf_anal' src='https://crm.zohopublic.in/crm/WebFormAnalyticsServeServlet?rid=5f229f01e98885a79974c37c8c9fe2b598a1db383d716183c21b1ba5b3897c28gidb43efcd5d07598c5a2dec7cbbd9f0a4a4778bde7ffbd77b08070784d65801fa2gid534cb20477b1d28b5f45f7cc241888c5gid4ee3a7e9ace6ab1be7c541b329164307'></script>
	
</div>
<!--=====================END MODAL NEW ===============-->



<style type="text/css">
	.wfrm_fld_dpNn{display: none;}
	.dIB{display: inline-block;}
	.how-it-works-detail img { width: auto;	}
	.how-it-works-detail h3, .hero-banner-text h1,
	.how-it-works-container h2{	font-weight: 700;}

	.custom_modal {	
		display: none;	width: 460px;
		height: auto;	box-sizing: border-box;	text-align: center;	
		position: fixed; top: 50%;	margin-top: -50px;
		left: 50%;	margin-left: -230px;	z-index: 99;
		background: transparent linear-gradient(0deg, #144f5a 0, #0eb58f 100%) 0 0 no-repeat padding-box;
		box-shadow: 5px 5px 5px rgba(0,0,0,0.2);
	}
	.inner_custom_modal{
		position: relative;
		width: 100%;
		box-sizing: border-box;
		padding: 50px 50px 25px 50px;
		color: #fff;
	}
	#modal_close{
		display: inline-block;	position: absolute;
		top:20px; right: 20px;	color: #fff; cursor: pointer;
	}
	.inner_custom_modal h2{	font-size: 20px; margin-bottom: 20px;}	

	.inner_custom_modal input {
	    background-color: #fff;    padding: 0.5rem 1rem;
	    margin:  0;    color: #333;    width: 100%;
	    border: none;    border-radius: 6px;    font-size: 14px;
	}
	.inner_custom_modal input[type="submit"] {
	  	display: block;    background-color: #0eb58f;
	    color: #fff;   width: 7.5rem;    font-size: 14px;
	    line-height: 1.3rem;    border-radius: 1.625rem;
	    margin: 1rem auto;    text-transform: uppercase;
	    text-decoration: none;    transition: transform .5s ease;
	}
	.inner_custom_modal p{	font-size: 10px;}
		


@media only screen and (min-width: 210px) and (max-width: 642px) {
	.how-it-works-container p, .impact-story-detail p,
	.single-meal-plans-title p, .testimonials-detail p,
	.accordion-content p, .impact-story-detail h3 {    
    	text-align: center;
	}
	.accordion-header h4 { font-size: 0.9rem;  	width: 90%; }
    .faq-container h2 {	font-size: 1.1rem; 	text-align: center;	}
	.single-meal-plans-title h2, 
	.impact-story-detail h2 {  text-align: center;	}
	.how-it-works-detail h4, 
	.how-it-works-detail h3 { padding-bottom: 0.4rem;}
}

@media only screen and (min-width: 210px) and (max-width: 480px) {
	.custom_modal {		
		width: 316px;	
		margin-left: -158px;
	}
	.inner_custom_modal{	
		padding: 40px 20px 25px 20px;
	}
	.inner_custom_modal h2{
		font-size: 16px;
	}
	#modal_close{	
		top:15px;
		right: 15px;	
	}
}
</style>

<script>
jQuery(document).ready(function(){	
	setTimeout(function() {
		if (jQuery(window).width() > 620) {
   			jQuery('.custom_modal').show(); 
		}    
    }, 5000);

    jQuery('.custom_modal #modal_close').click(function(){			
			jQuery('.custom_modal').hide();		
		});	
});

</script>
<style type="text/css">
	
</style>

	
	
