
<!-- Hero Banner Start -->
	<div class="hero">		
		<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/diabetes_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/diabetes_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	<div class="hero-banner-text">
					<h1>NO NEED TO CHEAT</h1>
		        	<p>Reverse your diabetes and increase freedom.</p>
		        </div>		        
	        </div>
	    </div>	    
	</div>
	<!-- Hero Banner End -->

	<div class="why-choose-lifeheal">
		<div class="why-choose-lifeheal-container">
			<h2>Book your call right now</h2>
		</div>
	</div>

	<!-- Success Start -->

	<div class="appointment-success">
		<iframe id="testframe" src='https://booking.startlifeheal.com/portal-embed#/customer/63311000000260028' frameborder='0' allowfullscreen='' > </iframe>
	</div>
	<!-- Success End -->
<style type="text/css">
	.appointment-success{
		padding:  0;
		/*background: green;*/
	}
	.appointment-success h1{
		font-size: 20px;
	}
	.appointment-success iframe{
		height: 780px;
		width:100%;
	}	
	@media only screen and (max-width: 768px) {
		.appointment-success iframe{
		height: 880px;
		width:100%;
	}
		h1.mb10.zb-btone-title {
    		font-size: 22px !important;
		}
		.zb-btone-bookbutton {
    		border-radius: 2px;
    		height: 50px;
		}

		.zb-btone-field-icon {
    		width: 90px;
    		height: 60px;
    		font-size: 22px;
    		border-radius: 2px 0 0 2px;
		}
	}
</style>

<script type="text/javascript">
	jQuery(document).ready(function(){		
		var iFrameDOM = jQuery("#testframe").contentWindow.document;
		//console.log(iFrameDOM);
		iFrameDOM.body.style.backgroundColor = "blue";
		console.log('heooo');
		iFrameDOM.find(".zb-btone-title").css("background-color", "yellow");
		jQuery(".zb-btone-title").css("fontSize", "20px");
		jQuery(".appointment-success").css("background-color", "red");
	});
</script>