<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/diabetes_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/diabetes_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	<div class="hero-banner-text">
					<h1>NO NEED TO CHEAT</h1>
		        	<p>Reverse your diabetes and increase freedom.</p>
		        </div>		        
	        </div>
	    </div>	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Why Choose Lifeheal Strat -->
	<div class="why-choose-lifeheal">
		<div class="why-choose-lifeheal-container">
			<h2>WHY LIFEHEAL IS SO GOOD!</h2>
			<p>See what you get from LifeHeal when you choose healthy meal plans from us.</p>
			<div class="download-info-pack-wrapper">
				<!--<div class="download-info-pack-image">					
					<video controls>
  						<source src="<?php echo $this->getSkinUrl('images/heal-diabetes.mp4') ?>"  type="video/mp4">
					</video>
				</div>-->
				<div class="download-info-pack-video">
					<video muted="muted" playsinline="" preload="auto" autoplay="autoplay" loop="loop" id="download-info-pack-video">		               
		                <source src="<?php echo $this->getSkinUrl('images/disease-single-video.webm') ?>"  type="video/webm">		               
		                <source src="<?php echo $this->getSkinUrl('images/disease-single-video.mp4') ?>"  type="video/mp4">
		            </video>
				</div>
				<button type="button" class="download-info-pack-cta">DOWNLOAD&nbsp;INFO&nbsp;PACKET&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-down" aria-hidden="true"></i></button>
			</div>
		</div>
	</div>
	<div class="why-choose-lifeheal-modal">
		<div class="why-choose-lifeheal-modal-wrapper">
			<div class="why-choose-lifeheal-modal-close">
				<i class="far fa-times-circle"></i>
			</div>
			<h3>Get a Free info packet on <br>Diabetes Reversal from&nbsp;LifeHeal.</h3>
			<!--<form class="why-choose-lifeheal-infopack">
				<input type="text" ftype="email" id="Email" name="Email" placeholder="e-mail">
				<input type="submit" value="SUBMIT"/>
			</form>-->
			<form class="why-choose-lifeheal-infopack" action='https://crm.zoho.in/crm/WebToLeadForm' name=WebToLeads126676000004773036 method='POST' onSubmit='javascript:document.charset="UTF-8"; return checkMandatory126676000004773036()' accept-charset='UTF-8'>
 			<input type='text' style='display:none;' name='xnQsjsdp' value='b43efcd5d07598c5a2dec7cbbd9f0a4a4778bde7ffbd77b08070784d65801fa2'></input> 
 			<input type='hidden' name='zc_gad' id='zc_gad' value=''></input> 
 			<input type='text' style='display:none;' name='xmIwtLD' value='5f229f01e98885a79974c37c8c9fe2b598a1db383d716183c21b1ba5b3897c28'></input> 
 			<input type='text'  style='display:none;' name='actionType' value='TGVhZHM='></input>
 			
 			<!--<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;startlifeheal.com&#x2f;hypertension&#x2f;' > </input>-->
 			<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;startlifeheal.com&#x2f;heal-diabetes&#x2f;' > </input>
			<div class='wfrm_fld_dpNn'>
				<select class='zcwf_col_fld_slt' id='LEADCF1' name='LEADCF1' multiple >
					<option selected value='Weight&#x20;Loss'>Weight Loss</option>
					<option value='Diabetes'>Diabetes</option>
					<option value='Cardiac'>Cardiac</option>
					<option value='Fatty&#x20;Liver'>Fatty Liver</option>
					<option value='Fitness'>Fitness</option>
					<option value='Thyroid'>Thyroid</option>
					<option value='PCOD'>PCOD</option>
					<option value='Pregnancy'>Pregnancy</option>
					<option value='Gut&#x20;Issues'>Gut Issues</option>
					<option value='Constipation'>Constipation</option>
					<option value='Immunity'>Immunity</option>
				</select>
			</div>	
			<input type='text' ftype='email' id='Email' name='Email' placeholder="e-mail"></input>
			<input type='hidden' id='Last_Name' name='Last Name' value="Diabetes Pop Up"></input>
			<div class='wfrm_fld_dpNn'>
				<input type='checkbox' class='zcwf_ckbox' id='LEADCF101' name='LEADCF101' maxlength='3' checked='true'></input>
			</div>
				
			<input type='submit' id='formsubmit' class='formsubmit zcwf_button' value='Submit' title='Submit'>
			<input type='reset' style="display: none;" class='zcwf_button' name='reset' value='Reset' title='Reset'>
		</form>
			<p>FREE info pocket will be delivered on your email within few minutes.</p>
		</div>
	</div>
	
	<!-- Why Choose Lifeheal End -->
	
	
	<!-- How it Works Start -->
	<div class="how-it-works">
		
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">80% clients completing 1 month successfully reduced medications.</p>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">he LifeHeal plan normally stops insulin, improves blood glucose and reduces medications. You get a digital approach to your glucose and diet.</p>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000"><span>Steps included in diabetes management</span></p>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Deep Dive</h3>
					<p>You get one the most advanced  analyses exploring the source of your diabetes using our A.I. tool. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>Customizing</h3>
					<p>Your plan is built around you using your inputs, goals and current capacity. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Start</h3>
					<p>You get positive changes in energy, mood and biomarkers.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-4.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Support</h3>
					<p>Most failures happen in the mind. We give a plan and support you through it.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-5.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Track & Guide</h3>
					<p>You are skillfully guided to your next steps. We track over 65 biomarkers.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-6.png') ?>"/>
					<h4>STEP 6</h4>					
					<h3>Success</h3>
					<p>Your health goes beyond your diseases. True health is in prevention.</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->
	
	<!-- Meal Plans Start -->
	<style>
	
		.disease-single-meal-plans {
			background-color: #0EB58F;
		}
		
		.disease-single-meal-plans .single-meal-plans-title {
			color: #FFFFFF;
		}
		
	</style>
	<div class="single-meal-plans disease-single-meal-plans full-height">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>DIABETES MANAGEMENT <br>MEAL PLANS</h2>
				<p>Let's face it, you need to start treating your diabetes and not its symptoms. Medications ought to be reducing and you should try to eliminate them, not live with them. Find out why some of India’s top doctors use LifeHeal. Start Now.</p>
			</div>
			
			<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Diabetes Reduction</h3>
						<h2>
							<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
								<span style="font-size: 18px; color: #fff;">Rs. 8,000/month </span> 
							</s>
						</h2>
						<h2 class="offer">Rs. 4,000/month  </h2>
						<p style="font-size: 0.8rem; color:#fff;">
							Use code FIT50 to avail this offer
						</p>
						<a href="javascript:void"   onclick="addItemToCart(2683)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Diabetes Reduction</h3>
						<h2> 
							<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
								<span style="font-size: 18px; color:#fff;">Rs. 6,000/month </span>
							</s>
						</h2>
						<h2 class="offer">Rs. 3,000/month</h2>
						<p style="font-size: 0.8rem; color:#fff;">
							Use code FIT50 to avail this offer
						</p>
						<a href="javascript:void"   onclick="addItemToCart(2638)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Diabetes Reduction</h3>
						<h2>&nbsp;</h2>
						<h2>Rs. 5,000/month</h2>
						<p>&nbsp;</p>
						<a href="javascript:void"   onclick="addItemToCart(2637)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Diabetes Reduction</h3>
						<h2>&nbsp;</h2>
						<h2>Rs. 4,000/month</h2>
						<p>&nbsp;</p>
						<a href="javascript:void"   onclick="addItemToCart(2636)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Meal Plans End -->
	
	<!-- Impact Story Start -->
	<div class="impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<img src="<?php echo $this->getSkinUrl('images/manoj_sangal.jpg') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL MANOJ SANGAL STOPPED INSULIN IN 35 DAYS</h2>
				<h3>Manoj Sangal, <span> 50 Years, Businessman, New Delhi</span></h3>
				<p>I had been on a high dose of insulin since 2011. In 5 weeks of diligently adhering to the LifeHeal program, I stopped taking insulin completely. As an add on, I also lost 10 kgs in 3 months.</p>
				<div class="impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=If7ZrY-yudA" data-youtube-id="If7ZrY-yudA" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/manoj_sangal_video_1.jpg') ?>"/>
					</a>
					<!--<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						<img src="<?php //echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
					</a>-->
				</div>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->
	
	<!-- Disease Feature Start -->
	<div class="single-meal-plans disease-feature">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>REVERSE YOUR DIABETES <br> & GET OFF MEDICATION</h2>
				<p>With a clinically proven program, we have inspired 10,000+ participants to improve their blood sugar control, reduce medication and lose significant weight.</p>
			</div>
			
			<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Feature Details -->
				<div class="single-meal-plans-detail">
					<div class="disease-feature-wrapper">
						<div class="disease-feature-wrapper-top">
							<img src="<?php echo $this->getSkinUrl('images/disease-feature-1.png') ?>"/>
							<h3>95%</h3>
							<h4>Improved HBA1c</h4>
						</div>
						<div class="disease-feature-wrapper-bottom">
							<p>Blood Glucose improvement</p>
						</div>
					</div>
				</div>
				
				<!-- Feature Details -->
				<div class="single-meal-plans-detail">
					<div class="disease-feature-wrapper">
						<div class="disease-feature-wrapper-top">
							<img src="<?php echo $this->getSkinUrl('images/disease-feature-2.png') ?>"/>
							<h3>100%</h3>
							<h4>of insulin use reduced</h4>
						</div>
						<div class="disease-feature-wrapper-bottom">
							<p>Medication Reduction</p>
						</div>
					</div>
				</div>
				
				<!-- Feature Details -->
				<div class="single-meal-plans-detail">
					<div class="disease-feature-wrapper">
						<div class="disease-feature-wrapper-top">
							<img src="<?php echo $this->getSkinUrl('images/disease-feature-3.png') ?>"/>
							<h3>80%</h3>
							<h4>Clients reduced weight</h4>
						</div>
						<div class="disease-feature-wrapper-bottom">
							<p>Weight Loss</p>
						</div>
					</div>
				</div>
				
				<!-- Feature Details -->
				<div class="single-meal-plans-detail">
					<div class="disease-feature-wrapper">
						<div class="disease-feature-wrapper-top">
							<img src="<?php echo $this->getSkinUrl('images/disease-feature-4.png') ?>"/>
							<h3>98%</h3>
							<h4>Clients improved HSCRP</h4>
						</div>
						<div class="disease-feature-wrapper-bottom">
							<p>Immunity Boost</p>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Disease Feature End -->
	
	
	<!-- Testimonials Start -->
	<style>
		.disease-single-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
	<div class="testimonials disease-single-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHAT OUR USERS SAY ABOUT OUR MEAL PLANS</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl('images/rajiv-small.png') ?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Rajiv Gupta</h3>
							<p>HbA1C Drop - <strong> 2.3 </strong> <br>Weight Drop - <strong> 12 kgs </strong> </p>
						</div>
					</div>
					<p>My doctors were surprised to see my fasting sugar levels decrease to 89-110 from a soaring high 200. My PP levels also reduced to 110-125 from 300+, and my liver improved from a Grade II to a Grade I. My diabetes medicine was reduced to half, insulin stopped completely with improvement in sugar levels, and my blood pressure medicines stopped altogether.</p>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl('images/sushil-small.png') ?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Sushil Singhal</h3>
							<p> HbA1c Drop - <strong> 1.5 </strong> <br> 4Weight Drop - <strong> 9.2 kgs</strong></p>
						</div>
					</div>
					<p>My whole life revolved around medicines & insulin to control my sugar levels, when a friend recommended me LifeHeal. As I started with the plan with expert coaching, my medicines were reduced to half in first two weeks advised by my own endourologist and it kept on reducing. It was a shocking experience for me to learn the power of food.</p>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl('images/jital-small.png') ?>')"></div>
						<div class="testimonials-detail-profile-detail">
							<h3>Jital Kumar</h3>
						<p>HbA1c Drop -  <strong> 0.5 </strong> <br/> Weight Drop - <strong> 7 kgs </strong> </p>
						</div>
					</div>
					<p>In my routine health checkup I discovered I was pre-diabetic. As I already have family history of diabetes I knew I had to do something. Within 2 months of following the diet my HbA1c dropped to 5.4.</p>
				</div>
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans?</h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions?</h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here.</p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans?</h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans. </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
	
	<!-- Floating CTA Start -->
	<div style="min-height: 76px; background-color: #144F5A">
		<div class="floating-cta">
			<div class="floating-cta-container">
				<h2>Book a 1-on-1 consultation with our Certified experts</h2>
				<a class="button cta-button" href="<?php echo $this->getUrl('startnow') ?>">
					FIRST CALL ONLY RS. 200
				</a>
			</div>
		</div>
	</div>
	<!-- Floating CTA End -->

<style type="text/css">
	.wfrm_fld_dpNn{display: none;}
	.dIB{display: inline-block;}
	.download-info-pack-video video {
    	width: 100%;
    	height: 100%;
    	display: block;
    	object-fit: cover;
	}
	.download-info-pack-video {
    	width: 100%;
    	max-width: 300px;
    	margin: 0 auto;
    	position: relative;
    	top: -3rem;
    	box-shadow: 0px 4px 20px rgb(0 0 0 / 20%);
	}
</style>
	