
	<div class="hero">
		
		<style>
			
	
			.disease-remission {
				background-image: url('<?php echo $this->getSkinUrl("images/disease_remission_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-remission {
					background-image: url('<?php echo $this->getSkinUrl("images/disease_remission_mobile.png")?>');
				}	
			}
			
			.disease-remission h1 span {
				color: #0EB58F;
			} 
		</style>
	    	    <!-- Banner -->
	    <div class="hero-banner disease-remission">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1><span>DISEASE REMISSION</span><br>Scientific plans verified by blood tests.</h1>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	<!-- Diseases We Manage Start -->
	<div class="disease-we-manage">
		<div class="disease-we-manage-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">DISEASES WE REVERSE</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Recent studies have shown that chronic diseases can be reversed. LifeHeal brings this science
to you in our proprietary way. All our results are measured. You will feel and see the
difference through graphs, lab tests and more.</p>
			
			<div class="disease-we-manage-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('weight-management') ?>">
				 <img src="<?php echo $this->getSkinUrl('images/disease-we-manage-1.png') ?>"/>
					<h3>Obesity Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('heal-diabetes') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/disease-we-manage-2.png') ?>"/>
					<h3>Diabetes Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('liver-health') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/disease-we-manage-3.png') ?>"/>
					<h3>Fatty Liver Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('hypothyroid') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/disease-we-manage-4.png') ?>"/>
					<h3>Thyroid Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('heart-health') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Group308.png') ?>"/>
					<h3>Cardiac Disease Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('gestational-diabetes') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Gestational-diabetes.svg') ?>"/>
					<h3>Gestational Diabetes</h3>
				</a>
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('hypertension') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Union7.png') ?>"/>
					<h3>Hypertension Management</h3>
				</a>
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('pcod-pcos') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/17-ovary.png') ?>"/>
					<h3>PCOD Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('gut-health') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Union6.png') ?>"/>
					<h3>Gut Health & Digestion</h3>
				</a>
			
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('auto-immune') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Layer24.png') ?>"/>
					<h3>Auto-immune Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('cancer-risk') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Path289.png') ?>"/>
					<h3>Cancer Management</h3>
				</a>
				
				<a class="disease-we-manage-detail" href="<?php echo $this->getUrl('fertility') ?>">
					 <img src="<?php echo $this->getSkinUrl('images/Maternity-Issue.svg') ?>"/>
					<h3>Maternity Issues</h3>
				</a>
				
				
				
			</div>
		</div>
	</div>
	<!-- Diseases We Manage Start -->
	
	<!-- Customised Meal Plan Start -->
	<div class="customised-meal-plan">
		<div class="customised-meal-plan-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">SCIENTIFIC PLANS FOR DISEASE REVERSAL</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">We focus on the root cause of your disease using 20 metabolic parameters. Our plans include food charts, nurturing, support and coaching. Our patients get measurable and long lasting results. </p>
			<div class="customised-meal-plan-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<div class="customised-meal-plan-detail" onclick="addItemToCart(2687)" href="javascript:void" style="cursor:pointer">  
					<h4>1 Month Meal Plan</h4>					
					<h3>
						<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
							<span style="font-size: 18px; color: #3551AA;">Rs. 8,000/month </span> 
						</s>
					</h3>
					<h3 class="offer">Rs. 4,000/month  </h3>
				</div>
				
				<div class="customised-meal-plan-detail" onclick="addItemToCart(2686)" href="javascript:void" style="cursor:pointer">
					<h4>3 Months Meal Plan</h4>
					<h3>
						<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
							<span style="font-size: 18px; color: #3551AA;">Rs. 6,000/month </span> 
						</s>
					</h3>
					<h3>Rs. 3,000/month</h3>
				</div>
				
				<div class="customised-meal-plan-detail" onclick="addItemToCart(2685)"href="javascript:void" style="cursor:pointer">
					<h4>6 Months Meal Plan</h4>
					<h3>&nbsp;</h3>
					<h3>Rs. 5,000/month</h3>
				</div>
				
				<div class="customised-meal-plan-detail" onclick="addItemToCart(2684)" href="javascript:void" style="cursor:pointer">
					<h4>12 Months Meal Plan</h4>
					<h3>&nbsp;</h3>
					<h3>Rs. 4,000/month</h3>
				</div>
			
			</div>
						
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">LifeHeal has a proprietary InHealth<sup style="font-size:4px;top: -10px;"><b>TM</b></sup>  dashboard to track all your health parameters. Disease reversal is measured through blood test scores and for serious diseases they can include echocardiograms and ultra-sounds.</p>
		</div>
	</div>
	<!-- Customised Meal Plan End -->
	
	<!-- How it Works Start -->
	<div class="how-it-works disease-remission-how-it-works">
		
		<div class="how-it-works-container">
		
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Deep Dive</h3>
					<p>You get one the most advanced analyses exploring the source of your gut issues using our A.I. tool. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>Customizing</h3>
					<p>Your plan is built around you using your inputs, goals and current capacity. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Start</h3>
					<p>You get positive changes in energy, mood and biomarkers.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-4.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Support</h3>
					<p>Most failures happen in the mind. We give a plan and support you through it.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-5.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Track & Guide</h3>
					<p>You are skillfully guided to your next steps. We track over 65 biomarkers.</p>					
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-6.png') ?>"/>
					<h4>STEP 6</h4>					
					<h3>Success</h3>
					<p>Experience life without gut issues, better bowel movement and no symptoms.</p>
				</div>
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->
	
	<!-- Testimonials Start -->
	<div class="testimonials disease-remission-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW WE CHANGED LIVES.</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>LifeHeal plans weren't just about changing diet. Their holistic approach and open consultation educated me on the mistakes I was making in my daily routine. The results were beyond my imagination. Within a few days, my constipation improved, and I lost 1.5kgs. My blood sugar levels also started improving. I couldn't be happier.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test1.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Vineet Sagar, Lost 6 Kgs</h3>
							<p>50 Years, Businessman, Hyderabad</p>
						</div>
					</div>
				</div>
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>LifeHeal just fell into my lap after a friend's recommendation. LifeHeal's in-house portal (InHealth) educated me on the potential dangers to my health. This was a wake-up call for me, and I started working towards being healthy & fit. Plans were catered based on my preferences, and the changes were evident. I felt healthier, much lighter, my mood improved, and the persistent headaches were also sparse.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/raman-small.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Dr. Raman Wasir, Lost 4 Kgs</h3>
							<p>35 Years, Doctor, Gurgaon</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I'm a commercial pilot by profession, and the fear of losing my job during the lockdown impacted my mental health. I approached LifeHeal with my health issues and weird work schedule. They understood my concerns and helped me get in shape. To my surprise, I was able to stop my blood pressure medicines within two months. My general physician was surprised and happy with my progress.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test10.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Ajay Mandal, BP Medicine Stopped</h3>
							<p>40 Years, Pilot, Gurgaon</p>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>	

	<!-- Testimonials End -->

	<style type="text/css">
	.disease-remission-how-it-works h3 {
    	color: #fff;
	}
	</style>
