<!DOCTYPE html>
<html>
<head>
<style>
.mainbox {
 width: 31%;
float: left;
margin: 0% .8% 0% 1.2%;
border: 1px solid #000;
	padding: 10px;
}
	.insidebox {
 width:100%; float:left;
}
.insideboxpic{width: 2em;
margin: 1.1em auto;
height: 2em;
background-repeat: no-repeat;
float: left;
background-size: 100% 100%;}
.insideboxname{width: 54%;
float: left;
text-align: left;
font-size: 16px;
margin: 1.1em .5em;}
.insideboxlike{background-image: url("https://lifeheal.in/skin/frontend/rwd/default/images/favorite.svg");
min-width: 2em;
margin: 1.3em auto;
min-height: 2em;
background-repeat: no-repeat;
float: left;
background-size: 100% 100%;}
.insideboxselect{width: 25%;
float: right;
text-align: center;}
</style>
</head>
<body>

<div class="mainbox">
	
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">gaajar Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Patta Gobi Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
		<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
			<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
</div>

	<div class="mainbox">
	
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">gaajar Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Patta Gobi Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
		<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
			<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	
	
	
</div>
	
	<div class="mainbox">
	
<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">gaajar Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Patta Gobi Matar</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
		<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Matar Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
			<div class="insidebox">
<div class="insideboxpic"><img src="https://lifeheal.in/skin/frontend/rwd/default/images/apple_salad_1.jpeg"></div>
<div class="insideboxname">Palak Mashroom</div>
<div class="insideboxlike"></div>
<div class="insideboxselect">
	<label class="checkbox-inline">
		B<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">L<br>
      <input type="checkbox" value="">
    </label>
    <label class="checkbox-inline">T<br>
      <input type="checkbox" value="">
    </label>
	<label class="checkbox-inline">D<br>
      <input type="checkbox" value="">
    </label>
	</div>
		</div>
	
	
	
</div>
</body>
</html>
