<?php $groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
      if(!isset($groupId) || $groupId!=5)
      {
          echo "<script type='text/javascript'>window.location = '".Mage::getBaseUrl()."'</script>";
      }
?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/preloader.css">
 <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/perfect-scrollbar.min.css">
 <link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/catalog-page.css">
 <script src="<?php echo $this->getSkinUrl();?>js/catalog.min.js"></script>

<style>
  .modal {
    display: none;
    position: fixed;
    z-index: 1;
    padding-top: 100px;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0);
    background: none;
}
.hrline{
  padding-top:0px;
}
/* Modal Content */
.modal-content {
  margin: auto;
margin-top: 30%;
  width:50%;
}

	.highlight{color:#fff;
background:#269a9b;}
	.stand-out__content .itm-dsc__actn {
    flex-basis: auto;
    flex-flow: row nowrap;
    display: flex;
    margin-top: 0.4rem;
    margin-bottom: 1.5rem;
    margin-top: 0rem;
    margin-bottom: 0.5rem;
    width: 100%;
}
	p {
    margin-top: 0;
    margin-bottom: 0rem;
}
	.itm-dsc__actn__sz__dd-ttl {
    font-size: 13px;
	}
	.iwmcbq {   
    min-width: 3.3em;
    min-height: 3.3em;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    position: relative;
    right: 0px;
}
	.jrxrSi button {
    cursor: pointer;
    padding: 0.433rem;
    border: 0px solid 
rgb(38, 154, 155) !important;
color:
    rgb(38, 154, 155);
    background: none;
}
	.box, .box2, .box3, .box4{
        float: left;
overflow: hidden;
background:#f0e68c;
height: 142px;
width: 100%;
position: absolute;
z-index: 3;
right: 0%;
		 display:none;
    }
	 
    /* Add padding and border to inner content
    for better animation effect */
    .box-inner{
        width: 100%;		
        padding: 5px;
        border: 1px solid #a29415;
    }
	 .cCbxqa .itm-dsc__actn__sz {
    flex-flow: column nowrap;
    width: 100%;
    margin: auto;
}
	 .SSFcO {
   float: right;
color:#3d4152;
cursor: pointer;
font-size: 24px;
position: absolute;
right: 10px;
padding: 5px;
top: -5px;
}
	
#myInput {
  box-sizing: border-box;
background-position: 14px 12px;
background-repeat: no-repeat;
font-size: 14px;
padding: 0px 0px 0px 15px;
border: none;
	text-align: left;
    border-bottom-color: currentcolor;
    border-bottom-style: none;
    border-bottom-width: medium;
border-bottom: 1px solid #ddd;

height: 50px !important;
border-radius: 4px;
background:#fff;
color:#000;
width: 100% !important;
}

#myInput:focus {outline: 3px solid #ddd;}


	/*.main-container .container{max-width:100%;padding:0px;}*/

	@media screen and (min-width:260px) and (max-width:760px)
	{
		.site{padding:0px 15px;}
		.eRJwMX{box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 2px 0px, rgba(0, 0, 0, 0.12) 1px 2px 4px 1px;}
		.catalog_product_view {
    display: block;
}
		.catalog__filter, .catalog__filter-item {
    display: block;
}
		.catalog__list {
    max-width: 100%;
    margin: 20px auto;
}
		.SSFcO {
    float: right;
    color: 
    #fff;
    cursor: pointer;
    font-size: 24px;
    position: absolute;
    right: 10px;
    padding: 5px;
    top: -5px;
}
		.stickyhead{position: fixed;
top:0px !important;
width: 100%;
}
	 }
	@media screen and (min-width:768px) and (max-width:1200px)
	{
		.site{padding:0px 15px;}
	}
	 
</style>



    <!-- site -->
    <div class="site">

        <!-- site__content -->
        <div class="site__content">

            <!-- catalog -->
            <div class="catalog">

              
                <!-- catalog__frame -->
                <div class="catalog__frame">


     	
<?php  $customerCollection = Mage::getModel('customer/customer')->getCollection()
         ->addAttributeToSelect('*')
        ->addAttributeToSort('firstname','ASC')
        ->addAttributeToSort('lastname','ASC')
        
         ->addFieldToFilter('mealstatus', array("eq" => 1));
         //->addFieldToFilter('group_id', array("neq" => 4));
//echo '';
$customerLi='';
foreach($customerCollection as $custinfo)
{
    $customerId = $custinfo->getEntityId();
    $firstName =  $custinfo->getFirstname();
    $customerName='';
    $isDr = false;
    $isDiabetes = false;
    
    $foundItem = strpos( $firstName,'Dr');   if($foundItem!==false){  $isDr= true;  $firstName = str_replace("Dr",'',$firstName); }
   $foundItem2 = strpos( $firstName,'.');   if($foundItem2!==false){   $firstName = str_replace(".",'',$firstName); }
    $foundItem3 = strpos( $firstName,'Diabetes');   if($foundItem3!==false){ $isDiabetes = true;  $firstName = str_replace("(Diabetes Educator )",'',$firstName); }
   
   
    $lastName =  $custinfo->getLastname();
    if($firstName!='')
    {
        $customerName = trim($firstName);
        
    }
    
    if($lastName!='')
    {
        if($firstName!=''){ $customerName.=' ' ;}
        $customerName.= trim($lastName);   
        
        if($isDr==true)
        {
          //  $customerName.= ' ( Dr )'; 
        }
        if($isDiabetes==true)
        {
          //  $customerName.= ' (Diabetes Educator )'; 
        }
    }
   
    $customerName = str_replace("Dear ","",$customerName);
  //  print_r($custinfo); die;
    $customerLi.='<li id="'.$customerId.'" value="'.$customerId.'" onclick="getFavitems('.$customerId.')">'.$customerName.'</li>';
}

 $tomorrowDay = ucfirst(date("l", strtotime('tomorrow')));
 $curentdataetime = Mage::getModel('core/date')->date('m/d/Y');
?> <div class="datewisefilter">
    Select Day Of Meal:<select id="meal_day" onchange="getFavouriteOfDay(this.value)">
        <option orderdate ="<?php echo date('m/d/Y', strtotime($curentdataetime. ' + 0 days')); ?>" value="Sunday" <?php if($tomorrowDay=='Sunday'){ echo 'selected'; } ?> >Sunday</option> 
        <option orderdate ="<?php echo date('m/d/Y', strtotime($curentdataetime. ' + 1 days')); ?>" value="Monday" <?php if($tomorrowDay=='Monday'){ echo 'selected';} ?>>Monday</option>
        <option orderdate ="<?php echo date('m/d/Y', strtotime($curentdataetime. ' + 2 days')); ?>" value="Tuesday" <?php if($tomorrowDay=='Tuesday'){ echo 'selected';} ?>>Tuesday</option>
        <option value="Wednesday" <?php if($tomorrowDay=='Wednesday'){ echo 'selected';} ?>>Wednesday</option>
        <option value="Thursday" <?php if($tomorrowDay=='Thursday'){ echo 'selected';} ?>>Thursday</option>
        <option value="Friday" <?php if($tomorrowDay=='Friday'){ echo 'selected';} ?>>Friday</option>
        <option value="Saturday" <?php if($tomorrowDay=='Saturday'){ echo 'selected';} ?>>Saturday</option>
    </select>
      Select Order Date:<select id="orderdateplace">
      <option >Select</option>
      <?php for($i=0; $i <= 6; $i++){ ?>
        <option value="volvo"><?php echo date('m/d/Y', strtotime($curentdataetime. ' + '.$i.' days')); ?></option>
    <?php } ?>
    </select>
    <button type="button" id="cickbtnform"  class="button submit" onclick="OrderPlaceController()"><span>Submit Order</span></button>
</div>
                    <div id="loader" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='<?php echo $this->getSkinUrl();?>images/demo_wait.gif' width="64" height="64" /><br>Loading..</div>
    <div style="margin-bottom:10px;float:left; width:100%">Select Customer:</div>    
	<ul id="my-list">
  <?php echo $customerLi;?>
</ul>
			
                   
		<?php 	
                $comboLI='';   $countComboLI =0 ;
                $comboLIGharkakhana ='';   $countComboLIGharkakhana =0 ;
                $soupLI='';    $countSoupLI =0 ;
                $saladLI='';   $countSaladLI =0 ;
                
			$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
                        
$sqlDistinctCombo = "SELECT  distinct combo_id FROM  customerfavourite where combo_id!='NULL' and product_is_combo_child='yes'";
$favComboCollection = $connection->fetchAll($sqlDistinctCombo);
// die;
 $comboName  =  ''; 
  $customerName =  ''; 
 if(sizeof($favComboCollection) >0)
 {
           foreach($favComboCollection as $value)
           {
              $comboItemnameArray = array();
              $comboId = $value['combo_id']; 
              $bundled_product = Mage::getModel("catalog/product")->load($comboId);
              $isMealToShow = checkMealDayAvailability($bundled_product,$tomorrowDay);
              if($isMealToShow==true)
              { 
              $countComboLI++;
              $comboName='';
              /////////////////////
            
              $combosBYCustomerId = "SELECT custid from customerfavourite where combo_id='".$comboId."' group by custid";
              $uniqueCustomerCollection = $connection->fetchAll($combosBYCustomerId);
              
              foreach( $uniqueCustomerCollection as $custValue)
              {  
                
                  
                 $favComboItemCollection='';
                 $sqlComboItems = "SELECT custname,combo_name,productname,combo_option_id,combo_selection_id,product_is_combo_child  from customerfavourite  where combo_id='".$comboId."' and custid='".$custValue['custid']."'"; //die;
                 $favComboItemCollection = $connection->fetchAll($sqlComboItems);
            
                if(sizeof($favComboItemCollection) >0)
                 {         $comboItemnameArray = array();
                           foreach($favComboItemCollection as $value)
                           {

                              $comboName             =  $value['combo_name']; 
                              $customerName          =  $value['custname']; 
                              $comboItemnameArray[]  =  $value['productname'];
                                
                           }
                           
                           
                 }
              ////////////////////  end of combocollection loop/////////////
           
                   
			   
                  $comboLI.='<li class="item">
				<div class="itm-wrppr">
		<div class="sc-bbmXgH gfbLKA">
		<div class="injectStyles-sc-1jy9bcf-0 eRJwMX">
			<div class="wd-100">
				<div class="sc-ksYbfQ PVrMb">
					<div class="img-cvr">
						<img id="product-collection-image-'.$bundled_product->getId().'"  class="img-wrpr__img"
                         src="'. Mage::helper('catalog/image')->init($bundled_product, 'small_image')->resize(null).'" />
					</div>
				</div>
			</div>
			<div class="sc-hmzhuo cCbxqa">
				<div class="itm-nm-dsc ">
					<span class="itm-dsc__nm">'.$comboName.'</span>	
					 <span style="color:blue; font-size:10px;">('.$customerName.')</span>
					
				</div>';                  
                                if(sizeof($comboItemnameArray)>0)
                                {
                                     for($i=0;$i< sizeof($comboItemnameArray);$i++)
                                     {
				$comboLI.='<div class="itm-dsc__actn">
                         <div class="itm-dsc__actn__crst" data-label="selectCrust"  style="width:100%;">
						<div>
							<div class="injectStyles-sc-1jy9bcf-0 dVfvkq">
								<div class="nm-icn">
									<div datalabel="crust" class="itm-dsc__actn__sz__dd-ttl" >'.$comboItemnameArray[$i].'</div>
								</div>							
								<div class="dd-wrpr" ></div>
							</div>
						</div>
						<div class="sz-ln drp-dwn-crst-hr"></div>
				    </div>
				</div>';
                                 }	
                               }
				$comboLI.='</div>';
                   }   
                               
				 $comboLI.='</div>
			</div>
		</div>
            </li>';
                   
                   
                 //  die;
              }
             
         }
 }  
 ///////////////////////////////////////// Start Ghar Ka Khana Checkbox Combo //////////////////////////////
 
   $sqlDistinctCombo = "SELECT  distinct combo_id FROM  customerfavourite where combo_id!='NULL' and combo_options='checkbox' and product_is_combo_child='yes'";
$favComboCollection = $connection->fetchAll($sqlDistinctCombo);
// die;
 $comboName  =  ''; 
  $customerName =  ''; 
 if(sizeof($favComboCollection) >0)
 {
           foreach($favComboCollection as $value)
           {
              $comboItemnameArray = array();
              $comboId = $value['combo_id']; 
              $bundleProduct = Mage::getModel("catalog/product")->load($comboId);
              
              $optionCollection = $bundleProduct->getTypeInstance(true)->getOptionsCollection($bundleProduct);
              $selectionCollection = $bundleProduct->getTypeInstance(true)->getSelectionsCollection(
              $bundleProduct->getTypeInstance(true)->getOptionsIds($bundleProduct),$bundleProduct
            );

            $allOptions = $optionCollection->appendSelections($selectionCollection);
            
            
              $isMealToShow = checkMealDayAvailability($bundled_product,$tomorrowDay);
              if($isMealToShow==true)
              { 
              $countComboLIGharkakhana++;
              $comboName='';
              /////////////////////
            
              $combosBYCustomerId = "SELECT custid from customerfavourite where combo_id='".$comboId."' group by custid";
              $uniqueCustomerCollection = $connection->fetchAll($combosBYCustomerId);
              
              foreach( $uniqueCustomerCollection as $custValue)
              {  
                
                        
          $custID =  $custValue['custid'];
                $customer = Mage::getModel('customer/customer')->load($custID);
           $customerEmail = $customer->getEmail();
               
          
          
          $customerFirstName = $customer->getFirstname();   
			   
                   $comboLIGharkakhana.='<li class="item">
				<div class="itm-wrppr">
		<div class="sc-bbmXgH gfbLKA">
		<div class="injectStyles-sc-1jy9bcf-0 eRJwMX">
			<div class="wd-100">
				<div class="sc-ksYbfQ PVrMb">
					<div class="img-cvr">
						<img id="product-collection-image-'.$bundleProduct->getId().'"  class="img-wrpr__img"
                         src="'. Mage::helper('catalog/image')->init($bundleProduct, 'small_image')->resize(null).'" />
					</div>
				</div>
			</div>
			<div class="sc-hmzhuo cCbxqa">
				<div class="itm-nm-dsc ">
					<span class="itm-dsc__nm">'.$bundleProduct->getName().' <span style="color:blue">('.$customerFirstName.')</span></span>					
						
				</div>';                  
                                //////////////////////////////////////////
                  
                         

           foreach ($allOptions as $option) 
           {

             $selections = $option->getSelections();

             $optionId    = $option->getId();
             $countItemSelection=0;
             if(isset($selections) && sizeof($selections)>0)
             {
                foreach ($selections as $selection)
                    {  
                    $countItemSelection++;

             //$optionTitle = $options->getDefaultTitle();
             $selectionId = $selection->getSelectionId();
             $productIdFromSelection = $selection->getProductId();
             $selectionPrice = round($selection->getSelectionPriceValue(),4); 
             $optionTitle = $selection->getName();

            /////////////////Check selection product is in databast or not ///////////////
              $checked='';
              $heartClass='';
              $checkSingleProductCollection = Mage::getModel('favourite/customerfavourite')->getCollection()
                          ->addFieldToFilter('custid',$custID)
                          ->addFieldToFilter('combo_id',$comboId )
                          ->addFieldToFilter('productid',$productIdFromSelection)
                          ->addFieldToFilter('product_is_combo_child','yes');
              if(count($checkSingleProductCollection)==1)
              {
                  $checked='checked';
                  $heartClass=' heart';
              }
				$comboLIGharkakhana.='<div class="itm-dsc__actn">
                                        <div class="itm-dsc__actn__crst" data-label="selectCrust"  style="width:100%;">
						<div>
							<div class="injectStyles-sc-1jy9bcf-0 dVfvkq">
								<div class="nm-icn">
									<div datalabel="crust" class="itm-dsc__actn__sz__dd-ttl'.$heartClass.'" >'.$optionTitle.'</div>
                                                                         <input  type="checkbox" '.$checked.' name="check_'.$productIdFromSelection.'" productid="'.$productIdFromSelection.'" optionid="'.$optionId.'" selectionid="'.$selectionId.'" />    
								</div>							
								<div class="dd-wrpr" ></div>
							</div>
						</div>
						<div class="sz-ln drp-dwn-crst-hr"></div>
				       </div>
				   </div>';
                                ///////////////////////////////////////
				  
                    }
             }
           }
                   }   
                               
				 $comboLIGharkakhana.='</div></div></div>
			</div>
		
            </li>';
                   
                   
                 //  die;
              }
             
         }
 }  
 
 ///////////////////////////////////////// End Ghar Ka Khana Checkbox Combo ///////////////////////////////
 
$sqlSoup = "SELECT distinct productid  FROM  customerfavourite where product_is_combo_child='no' and productname like '%soup%'";
$favSoupCollection = $connection->fetchAll($sqlSoup);
 
 
 if(sizeof($favSoupCollection) >0)
 {
           foreach($favSoupCollection as $value)
           {
                $soup_product = Mage::getModel("catalog/product")->load($value['productid']);
                //echo $soup_product->getSku().'----'.$soup_product->getName(); echo '<br>';
              $isMealToShow = checkMealDayAvailability($soup_product,$tomorrowDay);
              if($isMealToShow==true)
              { 
                  
              $countSoupLI++;
              
              $soupBYCustomerId = "SELECT custid from customerfavourite where productid='".$value['productid']."' group by custid";
              $soupUniqueCustomerCollection = $connection->fetchAll($soupBYCustomerId);
              
              foreach($soupUniqueCustomerCollection as $soupCustValue )
              {
               $customer = Mage::getModel('customer/customer')->load($soupCustValue['custid']);
               $countIteminPreviousOrder='';
               $customerEmail = $customer->getEmail();
             //  $countIteminPreviousOrder = itemcountinpreviousorder($customerEmail,$value['productid'],$connection);
                $soupLI.='<li class="item">
	<div class="itm-wrppr">
		<div class="sc-bbmXgH gfbLKA">
                        <div class="injectStyles-sc-1jy9bcf-0 eRJwMX">
                                <div class="wd-100">
                                        <div class="sc-ksYbfQ PVrMb">
                                                <div class="img-cvr">
                                                        <img id="product-collection-image-'.$soup_product->getId().'"  class="img-wrpr__img"
                                 src="'. Mage::helper('catalog/image')->init($soup_product, 'small_image')->resize(null).'"       />

                                                </div>

                                        </div>
                                </div>
                                <div class="sc-hmzhuo cCbxqa">
                                        <div class="itm-nm-dsc ">
                                          <span class="itm-dsc__nm">'. $soup_product->getName().' </span>
				                                  <span style="color:blue; font-size:10px;">('.$customer->getFirstname().')</span> 
                                          <span>
                                          <input type="checkbox" productid="'.$soup_product->getId().'" name="breakfast" value="'. $soup_product->getName().'">
                                          <input type="checkbox" productid="'.$soup_product->getId().'" name="lunch" value="'. $soup_product->getName().'"> 
                                          <input type="checkbox" productid="'.$soup_product->getId().'" name="hightea" value="'. $soup_product->getName().'"> 
                                          <input type="checkbox" productid="'.$soup_product->getId().'" name="dinner" value="'. $soup_product->getName().'">  
                                          </span>            
                                        </div>
                                 </div>
                        </div>
		  </div>
		</div>
	
            </li>';  
              }
              }
           }
  }
  
  
  
  $sqlSalad = "SELECT distinct productid  FROM  customerfavourite where product_is_combo_child='no' and productname like '%salad%'";
$favSaladCollection = $connection->fetchAll($sqlSalad);
 
 
 if(sizeof($favSaladCollection) >0)
 {
           foreach($favSaladCollection as $value)
           {
                $salad_product = Mage::getModel("catalog/product")->load($value['productid']);
                $isMealToShow = checkMealDayAvailability($salad_product,$tomorrowDay);
              if($isMealToShow==true)
              { 
               $countSaladLI++;
               
                  $saladBYCustomerId = "SELECT custid from customerfavourite where productid='".$value['productid']."' group by custid";
              $saladUniqueCustomerCollection = $connection->fetchAll($saladBYCustomerId);
              
              foreach($saladUniqueCustomerCollection as $saladCustValue )
              {
               $customer = Mage::getModel('customer/customer')->load($saladCustValue['custid']); 
               $countIteminPreviousOrder='';
               $customerEmail = $customer->getEmail();
              // $countIteminPreviousOrder = itemcountinpreviousorder($customerEmail,$value['productid'],$connection);
                $saladLI.='<li class="item">
	<div class="itm-wrppr">
		<div class="sc-bbmXgH gfbLKA">
                        <div class="injectStyles-sc-1jy9bcf-0 eRJwMX">
                                <div class="wd-100">
                                        <div class="sc-ksYbfQ PVrMb">
                                                <div class="img-cvr">
                                                        <img id="product-collection-image-'.$salad_product->getId().'"  class="img-wrpr__img"
                                 src="'. Mage::helper('catalog/image')->init($salad_product, 'small_image')->resize(null).'"       />

                                                </div>

                                        </div>
                                </div>
                                <div class="sc-hmzhuo cCbxqa">
                                        <div class="itm-nm-dsc ">
                                         <span class="itm-dsc__nm">'. $salad_product->getName().' </span>
					                            <span style="color:blue; font-size:10px;">('.$customer->getFirstname().')</span> 
                                        <span>
                                          <input type="checkbox" productid="'.$salad_product->getId().'" name="breakfast" value="'. $salad_product->getName().'">
                                          <input type="checkbox" productid="'.$salad_product->getId().'" name="lunch" value="'. $salad_product->getName().'"> 
                                          <input type="checkbox" productid="'.$salad_product->getId().'" name="hightea" value="'. $salad_product->getName().'"> 
                                          <input type="checkbox" productid="'.$salad_product->getId().'" name="dinner" value="'. $salad_product->getName().'">  
                                          </span>            
                                        </div>
                                 </div>
                        </div>
		  </div>
		</div>
	
            </li>';    
              }
           }
               
           }
  }
                        
     ?>			
                   
					
                    <!-- catalog__wrap -->
                    <div class="catalog__wrap" id="category-products-container">

                        <!-- catalog__wrap -->
                        <div class="catalog__list">
                           
                               
                            <h3 style="font-weight: 600;color: #000;width: 100%;float: left;border-bottom: 2px solid #000;padding-bottom: 10px;">Favourite Soup Of <?php echo $tomorrowDay;?> </h3>
                             <?php if($countSoupLI>0) {  ?>
                                    <ul class="products-gridnew products-grid--max-3-col">

                                        <?php echo  $soupLI;?>
                                   </ul>
                                      <?php } else { echo 'There is no soup.'; } ?>
                             <h3 style="font-weight: 600;color: #000;width: 100%;float: left;border-bottom: 2px solid #000;padding-bottom: 10px;">Favourite Salad Of <?php echo $tomorrowDay;?> </h3>
                            <?php if($countSaladLI>0) { ?>
			    
                             <ul class="products-gridnew products-grid--max-3-col">
								  
		                <?php echo  $saladLI;?>
			   </ul>
                            <?php } else { echo 'There is no salad.'; } ?>
                             
                             <h3 style="font-weight: 600;color: #000;width: 100%;float: left;border-bottom: 2px solid #000;padding-bottom: 10px;">Favourite Combos Of <?php echo $tomorrowDay;?> </h3>
                            <?php if($countComboLI>0) { ?>
			  
                             <ul class="comboheight comboheightsingle products-grid--max-3-col">
								  
		                <?php echo  $comboLI;?>
			     </ul>
                            <?php } else { echo 'There is no combo.';} ?>
                            
                            <h3 style="font-weight: 600;color: #000;width: 100%;float: left;border-bottom: 2px solid #000;padding-bottom: 10px;">Favourite Combos- Ghar Ka Khana- Of <?php echo $tomorrowDay;?> </h3>
                            <?php if($countComboLIGharkakhana>0) { ?>
			  
                             <ul class="comboheight products-grid--max-3-col">
								  
		                <?php echo  $comboLIGharkakhana;?>
			     </ul>
                            <?php }
                            
                            else { echo 'There is no combo( Ghar ka Khana ).';} 
                            
                            
                            if($countSoupLI==0 && $countSaladLI==0 && $countSoupLI==0 || $countComboLIGharkakhana==0)
                            {
                                echo 'There is no favourite items of tomorrow';
                            }
                            ?>
                           

                        </div>

                    </div>
                    <!-- /catalog__wrap -->

                  

                </div>
                <!-- /catalog__frame -->

            </div>
            <!-- /catalog -->

<div id="myModalform" class="modal">
<!-- Modal content -->
<div class="modal-content">
<span class="close">&times;</span>
<div class="ordererrordata" style="display: none;clear: both;text-align: center;color:#a21e3b;font-size:16px;font-weight: 600;"></div>
</div>
</div>

        </div>
        <!-- /site__content -->


    </div>
    <!-- /site -->
    
    
<!-- 
<script src="<?php //echo $this->getSkinUrl();?>js/jquery-3.2.1.min.js"></script>
<script src="<?php //echo $this->getSkinUrl();?>js/perfect-scrollbar.jquery.min.js"></script>  -->





<script src="<?php echo $this->getSkinUrl('js');?>/jquery.alphaindex.js"></script>

<script> 

	jQuery(document).ready(function() {  //alert('before showing products');
           jQuery('#my-list').makeAlphaIndex({
                activateFirstIndex: false,
                showItemsCount: false
               })
                
			
		});
    var ordercustomerid = '';
                
    function getFavitems(custId)  {
      // alert(custId);
      //alert(jQuery('#meal_day').val());
      ordercustomerid = custId;
			jQuery('li').removeClass("highlight");
			jQuery("#loader").show();
        jQuery.ajax({
          url: "<?php echo Mage::getBaseUrl().'override/index/getcustomerfavitems' ?>",
          type: "POST",
          data: {
                  custid: custId,
                  day:jQuery('#meal_day').val()
                                
                },
          beforeSend: function(){
                jQuery("#loader").show();
          },
          success: function(response) {
          // alert(response);
            jQuery("#category-products-container").html(response);
            jQuery('#'+custId).addClass("highlight");
          },                              
          complete:function(){
            // Hide image container
          jQuery("#loader").hide();
        }
    }); 
  }
                
                
  function getFavouriteOfDay(day) {
                    
    jQuery.ajax({
      url: "<?php echo Mage::getBaseUrl().'override/index/getfavitemsofday' ?>",
      type: "POST",
      data: {
            day: day,
                                
          },
      beforeSend: function(){
          jQuery("#loader").show();
      },
      success: function(response) {
          //alert(response);
          jQuery("#category-products-container").html(response);

      },complete:function(){
          // Hide image container
          jQuery("#loader").hide();
        }
    }); 
  }


function OrderPlaceController(){
console.log(ordercustomerid);
var orderdate = jQuery("#orderdateplace").find(":selected").text();
if(orderdate === '' || orderdate =='Select' || ordercustomerid === ''){
  alert("Please Select The Order Date and Customer");
  return false;
}
console.log(orderdate);
var breakfastmenuitems = '';
var breakfastitemsdesc = '';
var lunchmenuitems = '';
var lunchitemsdesc = '';
var highteamenuitems = '';
var highteaitemsdesc = '';
var dinnermenuitems = '';
var dinneritemsdesc = '';
jQuery("input[name='breakfast']").each(function () {
//jQuery.each(jQuery("input[name='breakfast']:checked"), function(){ 
  if (jQuery(this).is(':checked')) {
     brekfastproductcode = jQuery(this).attr("productid");
     breakfastmenuitems = breakfastmenuitems + ' ' + jQuery(this).val()+',';
     breakfastitemsdesc = breakfastitemsdesc + ' ' + jQuery(this).val() + '_' + brekfastproductcode+ '_' +'1' +',';
  }
});

jQuery("input[name='lunch']").each(function () {
  if (jQuery(this).is(':checked')) {
     lunchproductcode = jQuery(this).attr("productid");
     lunchmenuitems = lunchmenuitems + ' ' + jQuery(this).val()+',';
     lunchitemsdesc = lunchitemsdesc + ' ' + jQuery(this).val() + '_' + lunchproductcode+ '_' +'1' +',';
  }
});

jQuery("input[name='hightea']").each(function () {
  if (jQuery(this).is(':checked')) {
     highteaproductcode = jQuery(this).attr("productid");
     highteamenuitems = highteamenuitems + ' ' + jQuery(this).val()+',';
     highteaitemsdesc = highteaitemsdesc + ' ' + jQuery(this).val() + '_' + highteaproductcode+ '_' +'1' +',';
  }
});

jQuery("input[name='dinner']").each(function () {
  if (jQuery(this).is(':checked')) {
     dinnerproductcode = jQuery(this).attr("productid");
     dinnermenuitems = dinnermenuitems + ' ' + jQuery(this).val()+',';
     dinneritemsdesc = dinneritemsdesc + ' ' + jQuery(this).val() + '_' + dinnerproductcode+ '_' +'1' +',';
  }
});



finalplaceOrder(ordercustomerid,orderdate,breakfastmenuitems,breakfastitemsdesc,lunchmenuitems,lunchitemsdesc,highteamenuitems,highteaitemsdesc,dinnermenuitems,dinneritemsdesc)

}



function finalplaceOrder(ordercustomerid,orderdate,breakfastmenuitems,breakfastitemsdesc,lunchmenuitems,lunchitemsdesc,highteamenuitems,highteaitemsdesc,dinnermenuitems,dinneritemsdesc){
  jQuery("#loader").show();
  
  jQuery("#cickbtnform").prop("disabled", true);
  //return false;
  jQuery.ajax({
        url: "<?php echo Mage::getBaseUrl().'heal/index/menuorder' ?>",
        type: "POST",
        data: {
          customerid: ordercustomerid, 
          name: "", 
          email: "",
          orderdate: orderdate,
          mobile: "",
          alernatemobile: "",
          foodtype: "",
          fooditems: "",
          breakfast: breakfastmenuitems,
          breakfastitemsdesc: breakfastitemsdesc,
          lunch: lunchmenuitems,
          lunchitemsdesc: lunchitemsdesc,
          hightea: highteamenuitems,
          highteaitemsdesc: highteaitemsdesc,
          dinner: dinnermenuitems,
          dinneritemsdesc: dinneritemsdesc,
          note: "",
          address: ""
        },
        success: function(response){
              jQuery(".ordererrordata").text("Your Order has been placed for date " +orderdate + " Thank You.");
              jQuery("#loader").hide();
              opennewpopupFunction();
              jQuery(".ordererrordata").show();
              jQuery("#cickbtnform").removeAttr('disabled');
          }
        });  
}

function opennewpopupFunction() {
jQuery(".loader").css("display", "none");
// Get the modal
var modal = document.getElementById('myModalform');
modal.style.display = "block";
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
}
</script>

<?php function checkMealDayAvailability($product,$DayToCheck)
{
    
    $favItemAvailableDay=array();
    if($product->getMonday()==1)
    {
        $favItemAvailableDay[] = 'Monday';
    }
      if($product->getTuesday()==1)
    {
         $favItemAvailableDay[] = 'Tuesday';
    }
      if($product->getWednesday()==1)
    {
        $favItemAvailableDay[] = 'Wednesday';
    }
      if($product->getThursday()==1)
    {
         $favItemAvailableDay[] = 'Thursday';
    }
      if($product->getFriday()==1)
    {
        $favItemAvailableDay[] = 'Friday';
    }
      if($product->getSaturday()==1)
    {
         $favItemAvailableDay[] = 'Saturday';
    }
      if($product->getSunday()==1)
    {
         $favItemAvailableDay[] = 'Sunday';
    }
    
  // echo '<pre>'; print_r($favItemAvailableDay); echo $DayToCheck; die;
    
    if(in_array($DayToCheck,$favItemAvailableDay) )
    {  //echo $product->getSku(); echo '<br>';
      return true;
    }else
    { return false;}
}


