<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/silverform.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/ratecard_min.css" type="text/css"/>
<!--Zoho Campaigns Web-Optin Form's Header Code Starts Here-->

<meta content="width=device-width,initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
<script type="text/javascript" src="https://feha.maillist-manage.in/js/optin.min.js" onload="setupSF('sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692','ZCFORMVIEW',false,'acc',false,'2')"></script>
<script type="text/javascript">
	function runOnFormSubmit_sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692(th){
		/*Before submit, if you want to trigger your event, "include your code here"*/
	};
</script>

<style>
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #customForm *:not(.dateClass){
-webkit-box-sizing: border-box !important;
-moz-box-sizing: border-box !important;
box-sizing: border-box !important;
word-break:break-word;
overflow-wrap: break-word;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .dateClass{
-webkit-box-sizing: unset!important;
-moz-box-sizing: unset !important;
box-sizing: unset !important;
word-break:break-word;
overflow-wrap: break-word;
}
/** RESPONSIVE START /
@media only screen and (max-width: 319px){
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:220px !important;
min-width:220px !important;
margin: 0px auto !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #SIGNUP_PAGE{
padding:0px !important	
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 [changeitem="SIGNUP_FORM_FIELD"]{
width:94% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .zcinputbox{
width:100% !important;
max-width:100% !important;
float:none !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaDiv{
width:69.5% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #relCaptcha{
margin-right:11px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(0.55);-webkit-transform:scale(0.55);transform-origin:0 0;-webkit-transform-origin:0 0;}
}
/*Major Mobiles*/
@media screen and (min-width: 320px) and (max-width: 580px){
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:280px !important;
min-width:280px !important;
margin: 0px auto !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .zcinputbox{
width:100% !important;
max-width:100% !important;
float:none !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 [changeitem="SIGNUP_FORM_FIELD"]{
width:95% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaDiv{
width:72% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaText{
width:96% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #relCaptcha{
margin-right:6px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #capRequired{
margin-right: -10px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(0.72);-webkit-transform:scale(0.75);transform-origin:0 0;-webkit-transform-origin:0 0;}
}
@media screen and (min-width:581px) and (max-width: 767px){
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:440px !important;
min-width:440px !important;
margin: 0px auto !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .zcinputbox{
width:100% !important;
max-width:100% !important;
float:none !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 [changeitem="SIGNUP_FORM_FIELD"]{
width:95% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaDiv{
width:84.4% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaText{
width:96% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #relCaptcha{
margin-right:14px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #capRequired{
margin-right: -10px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(1.13);-webkit-transform:scale(1.0);margin-bottom:40px;transform-origin:0 0;-webkit-transform-origin:0 0;}
}
/ Desktops and laptops ----------- /
@media only screen  and (min-width : 1025px) {
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:600px !important;
min-width:600px !important;
margin: 0px auto !important;	
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(1.03);-webkit-transform:scale(1.08);transform-origin:0 0;-webkit-transform-origin:0 0;}
}
/ Large Screens /
@media only screen  and (min-width : 1824px) {
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:600px !important;
min-width:600px !important;
margin: 0px auto !important;	
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(1.03);-webkit-transform:scale(1.08);transform-origin:0 0;-webkit-transform-origin:0 0;}
}
@media only screen and (min-device-width: 1200px) and (max-device-width:1200px){
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:600px !important;
min-width:600px !important;
margin: 0px auto !important;
}
}
/* iPads*/
@media only screen and (min-width : 768px) and (max-width : 1024px){
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #signupMainDiv{
width:500px !important;
min-width:240px !important;
margin: 0px auto !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #captchaDiv{
width:86.8% !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 #relCaptcha{
margin-right:12px !important;
}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .recaptcha{
transform:scale(0.90);-webkit-transform:scale(0.90);transform-origin:50% 50%;-webkit-transform-origin:0 0;}
}
/** RESPONSIVE END /
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .bdr_btm_hover{background-color:#f9f9f9; padding:10px;}
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .bdr_btm{padding:10px }
#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692 .f14{font-size:14px}
large_form_6_css [changeitem="SIGNUP_FORM_FIELD"]{
box-sizing:initial !important;
border-radius:0px !important;
}
</style>
<style>
	.btn-group{display:block;}
		.btn.primary:not(.outline) {
    color: #fff;
	font-size:14px;
    box-shadow: 0px 0px 5px rgba(0,0,0,.2);
    background: #ff8d59;
    background: -moz-linear-gradient(left,#ff8d59 0%,#ffb053 100%);
    background: -webkit-linear-gradient(left,#ff8d59 0%,#ffb053 100%);
    background: linear-gradient(to right,#ff8d59 0%,#ffb053 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff8d59',endColorstr='#ffb053',GradientType=1);
}
	.anh-quote, .kris-quote {
    padding: 0px 0;
    float: left;
    width: 100%;
		padding-top: 0px;
}
input[type="checkbox"] {
    position: relative;
    margin: 2px 0 0;
        margin-left: 0px;
    float: left;
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    left: 20px;
    top: 1px;
}
	.btn-block {
    display: block;
    width: 100% !important;
}
	
	.cross-sell-product-name{font-size:1.5em;}
	legend {
		font-size: 1em;}
	@media screen and (min-width:260px) and (max-width:760px)
	{
	.requestquote{display:block !important;}
	.text-medium {
  margin-top: 4%;
display: block;
float: left;
font-size: 1em;
margin-right: 1%;  
}
		.page-homepage .analysis-block .form-group span {
    font-size: 1em;
}
		.cross-sell-product-name{font-size:1em;}
	}
	.requestquote{display:none;}
	
</style>

<main id="content" tabindex="-1" class=" silver-plan  page-homepage">
<div id="pane">

<section class="hero full-img" id="orderOptions"> 
<div class="container">
<div class="intro-text-wrapper"> 
<img src="<?php echo $this->getSkinUrl('images/individualplan.png') ?>" class="silver-icon" alt="" style="width:100px;display:none;"> 
<h1 class="h2 fw-600 text-center">Lose Weight and Feel Great</h1> <br>
<h2 class="text-center h3"><em>Get Back on Track with Scientific Weight Loss</em></h2>
</div> 
<div id="product-pane" class="requestbox">	
<div class="product-image individual-image no-float full-img col-xs-12 col-md-12 col-sm-12 col-xl-7">
<p class="text-center text-uppercase"  style="display:none;"><strong>Because Every One Has Different Needs</strong></p> 
</div>
<div class="product-info no-float bmi-calculator analysis-block drop-shadow no-float text-center center-block col-xs-12 col-sm-12 col-md-12 col-xl-5"> 	
           <div class="bmi-border">
    <!--Zoho Campaigns Web-Optin Form's Header Code Ends Here--><!--Zoho Campaigns Web-Optin Form Starts Here-->

<div id="sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692" data-type="signupform">
	<div id="customForm">
		<input type="hidden" id="recapTheme" value="2">
		<input type="hidden" id="isRecapIntegDone" value="false">
		<input type="hidden" id="recapMode" value="38241000000134055">
		<input type="hidden" id="signupFormType" value="LargeForm_Vertical">
		<div name="SIGNUP_PAGE" id="SIGNUP_PAGE" class="SIGNUP_PAGE large_form_6_css" style="background-color: rgb(33, 145, 146); color: rgb(255, 255, 255); padding: 30px; font-size: 14px; font-family: Arial; text-align: center;">
			<div>
				<div name="" changeid="" changename="" style="margin:0px auto">
					<div id="imgBlock" name="LOGO_DIV" logo="true" style="width: 600px; margin: 0px auto; padding-top: 10px; padding-bottom: 10px; padding-right: 10px; text-align: center;"></div>
				</div>
				<br>
				<div id="signupMainDiv" style="margin: 0px auto; width: 100%; min-width: 230px; max-width: 600px;" name="SIGNUPFORM" changeid="SIGNUPFORM" changename="SIGNUPFORM">
					<div>
						<div style="position:relative;">
							<div id="Zc_SignupSuccess" style="display:none;position:absolute;margin-left:4%;width:90%;background-color: white; padding: 3px; border: 3px solid rgb(194, 225, 154);  margin-top: 10px;margin-bottom:10px;word-break:break-all">
								<table width="100%" cellpadding="0" cellspacing="0" border="0">
									<tbody>
										<tr>
											<td width="10%">
												<img class="successicon" src="https://feha.maillist-manage.in/images/challangeiconenable.jpg" align="absmiddle">
											</td>
											<td>
												<span id="signupSuccessMsg" style="color: rgb(73, 140, 132); font-family: sans-serif; font-size: 14px;word-break:break-word">&nbsp;&nbsp;Thank you for Signing Up</span>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<form method="POST" id="zcampaignOptinForm" style="margin:0px;" action="https://feha.maillist-manage.in/weboptin.zc" target="_zcSignup">
							<div id="SIGNUP_BODY_ALL" name="SIGNUP_BODY_ALL" style="border: 1px solid rgb(59, 166, 167);">
								<h1 style="color: rgb(255, 255, 255); background-color: rgb(59, 166, 167); word-break: break-word; overflow-wrap: break-word; margin: 0px; padding: 20px; font-size: 20px; font-family: Arial; border-width: 1px; border-color: rgb(237, 237, 237); border-style: none; text-align: center;" id="SIGNUP_HEADING" name="SIGNUP_HEADING" changeid="SIGNUP_MSG" changetype="SIGNUP_HEADER">Join Our Newsletter</h1>
								<div style="background-color: rgb(45, 157, 158); color: rgb(255, 255, 255); padding: 20px; bottom: 2px; font-size: 11px; font-family: Arial; text-align: center; opacity: 1;" id="SIGNUP_BODY" name="SIGNUP_BODY">
									<div style="margin:0px auto;text-align:left;">
										<div style="line-height:1.6;" class="" changeid="SIGNUP_MSG" id="SIGNUP_DESCRIPTION" changetype="SIGNUP_DESCRIPTION">Please complete this form to create an account, receive email updates and much more.</div>
										<div style="display:none;background-color:#FFEBE8;padding:10px 10px; color:#d20000; font-size:11px; margin:10px 0px;border:solid 1px #ffd9d3; margin-top:20px;" id="errorMsgDiv">&nbsp;&nbsp;Please correct the marked field(s) below.</div>
										<div>
											<div style="font-size:12px;  margin-top:10px;" name="fieldsdivSf" class="zcsffieldsdiv">
												<div style="padding:10px 0px 10px 0px;" class="zcsffield " fieldid="38241000000000023">
													<div style="">
														<div style="color: rgb(255, 255, 255); font-size: 13px; font-family: Arial;" name="SIGNUP_FORM_LABEL">Contact Email&nbsp;
															
															<span name="SIGNUP_REQUIRED" style="color: rgb(180, 0, 0); font-size: 11px; font-family: Arial;">*</span>
														
														</div>
														<div style="width:100%;  min-width:170px; margin-top:5px;"><!-- check to mark emailid field as type email, and other mandatory fields as type required -->
															<input name="CONTACT_EMAIL" changeitem="SIGNUP_FORM_FIELD" style="width: 97%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="email" required="true" value="">
															<span style="display:none" id="dt_CONTACT_EMAIL">1,true,6,Contact Email,2</span>
														</div>
													</div>
													
													
													
													
													<div style="clear:both"></div>
												
												
												
												
												</div>
												<div style="padding:10px 0px 10px 0px;" class="zcsffield " fieldid="38241000000000029">
													<div style="">
														<div style="color: rgb(255, 255, 255); font-size: 13px; font-family: Arial;" name="SIGNUP_FORM_LABEL">First Name&nbsp;</div>
														<div style="width:100%;  min-width:170px; margin-top:5px;"><!-- check to mark emailid field as type email, and other mandatory fields as type required -->
															<input name="FIRSTNAME" changeitem="SIGNUP_FORM_FIELD" style="width: 97%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="text" value="">
															<span style="display:none" id="dt_FIRSTNAME">1,false,1,First Name,2</span>
														</div>
													</div><div style="clear:both"></div></div>
												<div style="padding:10px 0px 10px 0px;" class="zcsffield " fieldid="38241000000000032">
													<div style="">
														<div style="color: rgb(255, 255, 255); font-size: 13px; font-family: Arial;" name="SIGNUP_FORM_LABEL">Last Name&nbsp;</div>
														<div style="width:100%;  min-width:170px; margin-top:5px;"><!-- check to mark emailid field as type email, and other mandatory fields as type required -->
															<input name="LASTNAME" changeitem="SIGNUP_FORM_FIELD" style="width: 97%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="text" value="">
															<span style="display:none" id="dt_LASTNAME">1,false,1,Last Name,2</span>
														</div>
													</div><div style="clear:both"></div></div>
												<div style="padding:10px 0px 10px 0px;" class="zcsffield " fieldid="38241000000105866">
													<div style="">
														<div style="color: rgb(255, 255, 255); font-size: 13px; font-family: Arial;" name="SIGNUP_FORM_LABEL">Weight&nbsp;</div>
														<div style="width:100%;  min-width:170px; margin-top:5px;"><!-- check to mark emailid field as type email, and other mandatory fields as type required -->
															<input name="CONTACT_CF17" changeitem="SIGNUP_FORM_FIELD" style="width: 97%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="text" value="">
															<span style="display:none" id="dt_CONTACT_CF17">2,false,1,Weight,2</span>
														</div>
													</div><div style="clear:both"></div></div>
												<div style="padding:10px 0px 10px 0px;" class="zcsffield " fieldid="38241000000105864">
													<div style="">
														<div style="color: rgb(255, 255, 255); font-size: 13px; font-family: Arial;" name="SIGNUP_FORM_LABEL">Height&nbsp;<span name="SIGNUP_REQUIRED" style="color: rgb(180, 0, 0); font-size: 11px; font-family: Arial;">*</span></div>
														<div style="width:100%;  min-width:170px; margin-top:5px;"><!-- check to mark emailid field as type email, and other mandatory fields as type required -->
															<input name="CONTACT_CF16" changeitem="SIGNUP_FORM_FIELD" style="width: 97%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="text" required="true" value="">
															<span style="display:none" id="dt_CONTACT_CF16">2,true,1,Height_feet,2</span>
														</div>
													</div><div style="clear:both"></div></div>
											</div><!-- Captcha for Signup -->
											<div class="recaptcha" style="padding: 10px 0px 10px 10px;" id="captchaOld" name="captchaContainer">
												<div style="">
													<div style="width: 59%; float: left; min-width: 170px; max-width: 70%;" id="captchaParent">
														<img src="//campaigns.zoho.in/images/refresh_icon.png" style="cursor: pointer;float:right;margin-right:4px" onclick="loadCaptcha('https://campaigns.zoho.in/campaigns/CaptchaVerify.zc?mode=generate',this,'#sf5f013982b20e27231ef4eb47bea472a7d71b62c3142be692');" id="relCaptcha">
														<div id="captchaDiv" captcha="true" name="" style="padding: 20px;background:#fff;border: 1px solid rgb(222, 222, 222);box-sizing: border-box;width:98.8%"></div>
														<input placeholder="Captcha" id="captchaText" name="captchaText" changeitem="SIGNUP_FORM_FIELD" style="margin-top: 5px; width: 98.7%; color: rgb(68, 68, 68); background-color: rgb(255, 255, 255); height: 28px; border: 3px solid rgb(255, 255, 255); font-family: Arial; text-indent: 5px; border-radius: 0px; padding: 3px; font-size: 13px; box-sizing: border-box;" maxlength="100" type="text">
														<span name="SIGNUP_REQUIRED" id="capRequired" style="color: rgb(180, 0, 0); margin-top: -16px; margin-right: -2px; float: right; font-size: 11px; font-family: Arial;">*</span>
													</div>
												</div>
												<div style="clear: both"></div>
											</div>
											<input type="hidden" id="secretid" value="6LdNeDUUAAAAAG5l7cJfv1AA5OKLslkrOa_xXxLs"><!-- Captcha for Signup End--><!-- Other Lists Subscription Start--><!-- Other Lists Subscription End-->
											<div style=" border-bottom:#ebebeb dotted 1px; margin-top:10px; clear:both;"></div>
											<div id="REQUIRED_FIELD_TEXT" changetype="REQUIRED_FIELD_TEXT" name="SIGNUP_REQUIRED" style="color: rgb(180, 0, 0); padding: 10px 10px 10px 0px; font-size: 11px; font-family: Arial;">*Required Fields</div>
											<div style="padding:10px; text-align:center;">
												<input type="submit" action="Save" id="zcWebOptin" name="SIGNUP_SUBMIT_BUTTON" changetype="SIGNUP_SUBMIT_BUTTON_TEXT" style="cursor: pointer; appearance: none; color: rgb(255, 255, 255); background-color: rgb(54, 54, 54); background-position: center bottom; background-repeat: repeat-x; outline: none medium; font-family: Arial; border-radius: 3px; font-size: 15px; border-color: rgb(102, 0, 0); border-width: 1px; border-style: none; padding: 5px 15px; text-align: center;" value="Join Now">
											</div><!-- Do not edit the below Zoho Campaigns hidden tags -->
											<input type="hidden" id="fieldBorder" value="rgb(255, 255, 255)">
											<input type="hidden" name="zc_trackCode" id="zc_trackCode" value="ZCFORMVIEW" onload="">
											<input type="hidden" name="viewFrom" id="viewFrom" value="URL_ACTION">
											<input type="hidden" id="submitType" name="submitType" value="optinCustomView">
											<input type="hidden" id="lD" name="lD" value="187dbfca4dcaa40">
											<input type="hidden" name="emailReportId" id="emailReportId" value="">
											<input type="hidden" name="zx" id="cmpZuid" value="1df8922b5f">
											<input type="hidden" name="zcvers" value="2.0">
											<input type="hidden" name="oldListIds" id="allCheckedListIds" value="">
											<input type="hidden" id="mode" name="mode" value="OptinCreateView">
											<input type="hidden" id="zcld" name="zcld" value="187dbfca4dcaa40">
											<input type="hidden" id="zctd" name="zctd" value="">
											<input type="hidden" id="document_domain" value="campaigns.zoho.in">
											<input type="hidden" id="zc_Url" value="feha.maillist-manage.in">
											<input type="hidden" id="new_optin_response_in" value="1">
											<input type="hidden" id="duplicate_optin_response_in" value="1">
											<input type="hidden" id="zc_formIx" name="zc_formIx" value="5f013982b20e27231ef4eb47bea472a7d71b62c3142be692"><!-- End of the campaigns hidden tags --></div>
									</div>
									<input type="hidden" id="isCaptchaNeeded" value="true">
									<input type="hidden" id="superAdminCap" value="0">
									<img src="https://feha.maillist-manage.in/images/spacer.gif" onload="referenceSetter(this)" id="refImage" style="display:none;">
								</div>
								<div style="margin: 0px auto;margin-top:20px;text-align:left;height:76px;" id="privacyNotes" identity="privacyNotes">
									<span>Note: It is our responsibility to protect your privacy and we guarantee that your data will be completely confidential.</span>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="zcOptinOverLay" oncontextmenu="return false" style="display:none;text-align: center; background-color: rgb(0, 0, 0); opacity: 0.5; z-index: 100; position: fixed; width: 100%; top: 0px; left: 0px; height: 988px;"></div>
<div id="zcOptinSuccessPopup" style="display:none;z-index: 9999;width: 800px; height: 40%;top: 84px;position: fixed; left: 26%;background-color: #FFFFFF;border-color: #E6E6E6; border-style: solid; border-width: 1px;  box-shadow: 0 1px 10px #424242;padding: 35px;">
	<span style="position: absolute;top: -16px;right:-14px;z-index:99999;cursor: pointer;" id="closeSuccess">
		<img src="https://feha.maillist-manage.in/images/videoclose.png">
	</span>
	<div id="zcOptinSuccessPanel"></div>
</div>

<!--Zoho Campaigns Web-Optin Form Ends Here-->
<!-- module-closing-div   	 -->
<p>Sign up for free tips &amp; weight loss info!</p>
</div> 		
</div> 	
</div> 
</section>

<div class="anh-quote">
 <div class="container">
    <div class="">
       <div class="col-sm-5 col-lg-4">
          <img src="<?php echo $this->getSkinUrl('images/anh-quote-2020.jpg') ?>" class="img-responsive center-block" alt="Anh in a bathing suit smiling on the beach">
          <p class="small hidden-xs" style="display:none;">Average weight loss expected 6 Kgs per month.</p>
       </div>
       <div class="col-sm-7 col-lg-offset-1"><h2 class="fw-400 h6">ADITYA LOST 24 KGS .</h2>
          <hr>
		   <br>
          <h3>“I NEVER THOUGHT I WOULD BE ABLE TO LOSE WEIGHT AND HAD TRIED EVERYTHING BEFORE. I DIDN'T EVEN HAVE TO EXERCISE”</h3>
          
          <p class="small" style="display:none;">Average weight loss expected 6 Kgs per month.</p>
		    <div class="text-left" style="margin: 20px auto auto auto;">
                <a class="bg-white btn btn-default btn-lg scroll-to" style="color: #fff;background-color: #f28424  !important;">Get Started</a>
             </div>
       </div>
    </div>
 </div>
</div>

<div class="typical-day">
 <div class="container">
    
    <div class="text-center collapse-link">
       <a role="span" class="read-more-link collapsed" data-toggle="collapse" href="#typicalDayCollapse" aria-expanded="false" aria-controls="typicalDayCollapse" onclick="omni_track('SeeWhatsCooking');" style="display:none;">
          <img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt="open">
          <img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt="close">
          <strong>Example Dishes</strong></a></div>
    <div id="typicalDayCollapse">
       <div class=""></div> 
       <!-- breakfast -->
          <div class="col-sm-push-6 breakfast-text">
             <hr class="meal-time">
             <h3 class="text-uppercase">We Are All Different</h3>
             <p>Our plan is optimized for your specific needs</p>
			  <h3 class="text-uppercase">Metabolic Analysis</h3>
             <p>We look to the root source of your excess weight and begin the journey from there</p>			 
		   
		   </div>
          <div class="col-sm-pull-6 breakfast">
             <img src="<?php echo $this->getSkinUrl('images/meta1.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
		 <div class="clearfix"></div>
          <!-- lunch -->
          <div class="lunch-text">
             <hr class="meal-time lunch-rule">
             <div class="clearfix"></div>
             <h3 class="text-uppercase">Scientific Approach</h3>
             <p>We look beyond just calories to
physical and physiological balance and wellbeing</p>  
			    <h3 class="text-uppercase">Results Oriented</h3>
             <p>We tailor a diet that will help you to adjust your lifestyle choices based on your needs</p>
		   </div>
          <div class="lunch">
             <img src="<?php echo $this->getSkinUrl('images/meta2.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
          <!-- dinner -->
          <div class="clearfix"></div>
          <div class="col-sm-push-6 dinner-text">
             <hr class="meal-time customized-rule">
             <h3 class="text-uppercase">Dedicated Nutritionist</h3>
             <p>A dedicated nutritionist will call twice a week to review success and problems</p> 
			  <h3 class="text-uppercase">Metabolism Repair</h3>
             <p>In addition to offering nutritional advice, we guide you to create healthy lifestyle habits and achieve healthy balance of your metabolism</p> 
		   </div>
          <div class="dinner col-sm-pull-6">
             <img src="<?php echo $this->getSkinUrl('images/meta3.jpg') ?>" class="img-responsive center-block" alt="">
          </div>
          <div class="container  hidden-xs hidden-lg hidden-md hidden-sm">
            <div class="col-xs-12 text-center">
              <a data-target="#moreMenuModal" data-toggle="modal" href="#moreMenuModal" id="moremenu-modal-mob" onclick="omni_track('MoreMenuMbl')" class="btn btn-default bg-white btn-menu">Example Dishes</a>
            </div>
         </div>
       </div>
  
 </div>
</div>
<div class="plus-sect">
 <div class="container">
 <div class="plus-sect-wrap">
    <div class="plus-bg">
       <div class="plus-wrap"><span class="caveat">Add On!</span></div>
       <h3 class="text-uppercase fw-700 h5">RECIPES AND TECHNIQUES</h3>
    </div>
    <div class="desc plus-bg">
       <h4 class="fw-400 h6">From our very own kitchen, we will give you needed recipes and all our healthy cooking techniques</h4>
    </div>
 </div>
 </div>
 <div class="container hidden-xs hidden-lg hidden-md hidden-sm">
   <div class="col-xs-12 text-center">
     <a data-target="#moreMenuModal" data-toggle="modal" href="#moreMenuModal" id="moremenu-modal" onclick="omni_track('MoreMenu')" class="btn btn-default bg-white btn-menu">Example Dishes</a>
   </div>
 </div>
</div>
	<div class="more-menu-modal modal fade" id="moreMenuModal" tabindex="-1" role="dialog" aria-labelledby="reboot-modal" style="display: none;">
   <div class="modal-dialog" role="document">
       <div class="modal-content">
           <div class="modal-header">
               <span type="span" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">
                      <img src="https://lifeheal.in/skin/frontend/rwd/default/images/x-circle-icon.svg" class="center-block x-circle" alt="close" style="width: 30px;">
                   </span>
               </span>
               <h4 class="modal-title">Delicious Meals. Delicious Variety!</h4>
           </div>
           <div class="modal-body">
               <p class="ms-margin-btm" style="display:none;">Check out some of the delicious menu variety you’ll enjoy on the Gold and Platinum Plan:</p>
               <p><strong>Breakfasts</strong><br>
               <ul>
			   <li>Red Rice Idli with Sambhar + Chutney</li>
			    <li>Egg White Frittata</li>
			    <li>Dal chilla with Vegetable Stuffing</li>
			    <li>Red Rice Poha</li>
			    <li>Vegan Keema Parantha with Green Vegetable & Oil Free Pickle</li>
			   </ul>
			   </p>
			   <p><strong>Beverages</strong><br>
				  <ul>
		         <li> Almond Milk, Turkish Kefir, Green Smoothie</li>
		        </ul>
			   </p>			   
               <p><strong>Lunches</strong><br>
               <ul>
			   <li>Mixed Greens with Seeds and Fresh Dressing, Mushroom Soup, Jalfrezi, Shahi Paneer, Lauki Roti, Probiotic</li>
			    <li>Kuchumber Salad, Dal Soup, Beetroot & Tofu Kebab</li>
			    <li>Minestrone Soup, Sauteed Herbed Vegetables, Tofu Steak with Bar-be-que Sauce</li>
			    <li>Apple & Arugula Salad, Tomato Shorba, Nizami Handi Sabji, Vegan Kadhi, Lauki Roti, Probiotic</li>
			    <li>Shredded Bokchoy Salad, Clear Lemon & Coriander Soup, Vegetable in Garlic Sauce,  Quinoa and Brown Fried Rice</li>			   
			   </ul>	  
               </p>
			    <p><strong>Snacks</strong><br>
			    <ul>
			   <li>Wholegrain Momos</li>
			    <li>Matara Chaat</li>
			    <li>Ragi Nachos with Fresh Salsa Dip</li>
			    <li>Multigrain Cookies</li>
			    <li>Savory Namkeens</li>			    
			   </ul>	
			   </p>
               <p><strong>Dinners</strong><br>
               <ul>
			   <li>Italian Vegetable Soup, Sauteed Vegetable, Homemade Fresh Pasta with Pesto Sauce</li>
			    <li>Spiralized Salad, Tom Yum Soup, Red Thai Curry, Steamed Rice with Quinoa</li>
			    <li>Cucumber & Tomato Salad, Cream of Carrot Soup, Bhindi Takatak, Dal Makhani, Brown Rice & Quinoa Biryani</li>
			    <li>Som Tam Salad, Manchow Soup, Manchurian with Gravy, Veggie Noodles, Wholegrain Momos</li>
			    <li>Pickled Vegetable Salad, Spinach Soup, Cauliflower Mash, Garlic Herb Chicken with Redwine Sauce</li>
			   </ul>
	           </p>
           </div>
           <div class="modal-footer">
               <span type="span" class="btn btn-info btn-block visible-xs" aria-label="Close" data-dismiss="modal">
                   <span class="mobile-close" aria-hidden="true">×</span> Close
               </span>
           </div>
       </div>
   </div>
</div>
<div class="faqs">
<div class="container">
 <h2 class="h4 text-center fw-600"><strong class="highlight"><span>Frequently Asked Questions</span></strong></h2>
 <div class="">
   <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
     <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingOne">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseOne" aria-expanded="false" aria-controls="faq-collapseOne" onclick="omni_track('Faq1');">Will I be hungry on the Plan?</a></h3>
         </div>
         <div id="faq-collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingOne">
           <div class="panel-body">
			   <p>On any of our Plans, you will be recommended a variety of nutrient dense—high in protein and healthy fat—foods throughout the day to help keep you feeling full. Our portion suggestions are also surprisingly large, and most clients say they are unable to finish their entire meals. If you feel that you are still hungry after eating, you have the flexibility to enjoy additional servings of snacks recommended by your dedicated nutritionist.</p>
             </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingTwo">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseTwo" aria-expanded="false" aria-controls="faq-collapseTwo" onclick="omni_track('Faq2');">Do the suggested foods taste good?</a></h3>
         </div>
         <div id="faq-collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingTwo">
           <div class="panel-body">
             <p>Our Plans offers a wide variety of delicious, healthy breakfast, lunch, and dinner options, and sweet and savory snacks, in a range of globally inspired flavors that you’ll love, including Indian, Mughlai, Chinese, Continental, and Italian. Our consulting chefs are previously from 5-star hotel kitchens; we know our Food Plans must be delicious to be successful!</p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingThree">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseThree" aria-expanded="false" aria-controls="faq-collapseThree" onclick="omni_track('Faq3');">Is this a Keto diet?</a></h3>
         </div>
         <div id="faq-collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingThree">
           <div class="panel-body">
             <ul>
			   <li>As keto continues to be a growing trend in the health and wellness world, we’ve created some Keto options in our Plans to help people lose weight.</li>
				 <li>Depending on your requirements, we recommend different levels of Keto-Friendly foods. This means you’ll enjoy more quality carbs, higher protein levels and more food variety, including foods that are off-limits on the keto diet like milk, whole grains and beans.</li>
				 <li>Our keto–friendly approach to weight loss delivers below 50 grams of net carbs per day. (Net carbs are the total carbohydrates in a food or beverage, minus dietary fiber and erythritol, a type of sugar alcohol.)</li>
				 <li>While our's is a low-carb, good-fat approach, it’s not “strictly keto” or intended to allow individuals to achieve or maintain nutritional ketosis.</li>
				 
			   </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFour">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFour" aria-expanded="false" aria-controls="faq-collapseFour" onclick="omni_track('Faq4');">Are the Plans gluten-free?</a></h3>
         </div>
         <div id="faq-collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFour">
           <div class="panel-body">
             <p>If required, we can suggest gluten free ingredients, and you can customize further with your dedicated nutritionist.</p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFive">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFive" aria-expanded="false" aria-controls="faq-collapseFive" onclick="omni_track('Faq5');">Can a vegan be on the Plan?</a></h3>
         </div>
         <div id="faq-collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFive">
           <div class="panel-body">
             <p>Yes, our Plans are very aligned with a Vegan diet and can be further customized with your dedicated nutritionist.</p>
           </div>
         </div>
       </div>  
	      </div>
   </div>
 </div>	
	 
    <div class="collapse" id="faqCollapse">
       <div class="" style="padding-top:0px;"> 
		      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
     <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingSix">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseSix" aria-expanded="false" aria-controls="faq-collapseFive" onclick="omni_track('Faq6');">What to do if I cheat or feel like cheating on the Plan?
</a></h3>
         </div>
         <div id="faq-collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingSix">
           <div class="panel-body">
             <ul>
			   <li>We understand cravings occur. If you do “cheat” please inform your dedicated nutritionist. She will adjust your calories for the day to help you stay within your health goals. She can also offer advice on how to avoid cheating again in the future or substitute options to satiate the same craving. Don’t worry, you will not be reprimanded, rather coached to discourage the same thing happening too often.</li>
				 <li>If you feel like “cheating”, let your nutritionist know which craving you have, and she will offer you healthier substitute options or even customize your plan to include a healthier version of your craving.</li>
			   </ul>
           </div>
         </div>
       </div> 	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingSeven">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseSeven" aria-expanded="false" aria-controls="faq-collapseSeven" onclick="omni_track('Faq7');">Am I only allowed to the eat the recommended foods?</a></h3>
         </div>
         <div id="faq-collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingSeven">
           <div class="panel-body">
             <p>To maximize disease reversal and weight loss, yes, you should ideally only be eating the suggested foods from your Plan. Even with the best of intentions, unplanned meals tend to be too high in carbohydrates or unhealthy fats. So to truly achieve your goals, please stick as close to the plan as possible.</p>
           </div>
         </div>
       </div> 
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingEight">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseEight" aria-expanded="false" aria-controls="faq-collapseEight" onclick="omni_track('Faq8');">What if I have to attend a social event or want to eat out?</a></h3>
         </div>
         <div id="faq-collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingEight">
           <div class="panel-body">
             <ul>
			   <li>We understand social commitments will happen as well as the desire to eat from outside once in a while. If you do eat out please inform your dedicated nutritionist. She will adjust your calories to help you stay within your health goals. She can also offer advice on how to make healthy choices while eating out in a restaurant or at a social event.</li>
				 <li>Your dedicated nutritionist can also share healthy recipes for your favorite dishes so you can occasionally cook at home.</li>
			   </ul>
           </div>
         </div>
       </div>
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingNine">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseNine" aria-expanded="false" aria-controls="faq-collapseNine" onclick="omni_track('Faq9');">What are probiotics and why should I consume them?</a></h3>
         </div>
         <div id="faq-collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingNine">
           <div class="panel-body">
             <p>Probiotics are live microorganisms that may be able to help prevent and treat some illnesses. Promoting a healthy digestive tract and a healthy immune system are their most widely studied benefits. These are also commonly known as friendly, good, or healthy bacteria. LHF incorporates probiotics into our meals to keep your body, specifically your gut, as healthy as possible, which is now known to play a very important role in overall health.</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingTen">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseTen" aria-expanded="false" aria-controls="faq-collapseTen" onclick="omni_track('Faq10');">Can I drink alcohol on the Plan?</a></h3>
         </div>
         <div id="faq-collapseTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingTen">
           <div class="panel-body">
             <p>Our principles do allow minimal alcohol: it is recommended to limit consumption to 2 servings per week and pay attention to portion sizes. Choose only dry wines and avoid sweet wines and wine coolers, as they provide more sugar and carbohydrates. Limit beer to light beers to keep the carbohydrates lower and avoid serving liquor with high sugar mixers. Also discuss with your dedicated nutritionist so she may adjust your calories to maintain your health goals.</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading11">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse11" aria-expanded="false" aria-controls="faq-collapse11" onclick="omni_track('Faq11');">How many times can I eat non-veg?</a></h3>
         </div>
         <div id="faq-collapse11" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading11">
           <div class="panel-body">
             <p>For patients on insulin, we do not recommend consuming non-veg, but if you are truly craving it, speak with your dedicated nutritionist so she may coach you and offer some more options. If you are not diabetic, we recommend having non-veg not more than 1-2 times a week.</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading12">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse12" aria-expanded="false" aria-controls="faq-collapse12" onclick="omni_track('Faq12');">Are there restrictions on who can be on the Plans?</a></h3>
         </div>
         <div id="faq-collapse12" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading12">
           <div class="panel-body">
             <ul>
			   <li>Under 18 years of age without parental supervision</li>
				 <li>Allergies: NUTS, SOY, LATEX</li>
				 <li>Anorexia, Bulimia Nervosa</li>
				 <li>Breastfeeding an Infant under 4 month of age</li>
				 <li>Celiac disease</li>
				 <li>Congestive Heart Failure</li>
				 <li>Dialysis</li>
				 <li>Hypoglycemia</li>
				 <li>Kidney Disease, Renal Disease, Renal Failure</li>
			   <li>Pregnancy without OB supervision	</li>
				 <p>*This list is not exhaustive. Other medical conditions exist that may restrict you from following the LHF Program. You should consult with your healthcare provider before beginning this or any diet program.</p>
			   </ul>
           </div>
         </div>
       </div>	   
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading13">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse13" aria-expanded="false" aria-controls="faq-collapse13" onclick="omni_track('Faq13');">What do the Plans Include?</a></h3>
         </div>
         <div id="faq-collapse13" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading13">
           <div class="panel-body">
             <p>Depending on which Plan you choose, a nutritionist will guide you appropriately to a more healthful state of life. You may be suggested specific foods to boost immunity or specific meal items. Each person is unique and we design each Plan with that in mind. We share your journey and are committed to your success.</p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading14">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse14" aria-expanded="false" aria-controls="faq-collapse14" onclick="omni_track('Faq14');">How does the Plan work?</a></h3>
         </div>
         <div id="faq-collapse14" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading14">
           <div class="panel-body">
             <p>Our passion is to help as many people as possible reverse their disease, lose weight, and stay healthy and fit. We also aim to teach our clients how to live a high-quality, healthy life, without hunger or deprivation. The LHF Program is a safe, effective method of disease remission, weight loss, and introduces easy-to-follow principles that allow people to enjoy eating and achieve optimal health. LHF will deliver your customized meals for FREE. You have to simply heat and eat!</p>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading15">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse15" aria-expanded="false" aria-controls="faq-collapse15" onclick="omni_track('Faq15');">Can I follow one of your Plans if I have diabetes?</a></h3>
         </div>
         <div id="faq-collapse15" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading15">
           <div class="panel-body">
             <p>Yes, this is actually our most popular program. please choose the Diabetes Program (this should be a clickable link) to begin your journey to better health.</p>
           </div>
         </div>
       </div>	   
	   
	     
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading17">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse17" aria-expanded="false" aria-controls="faq-collapse17" onclick="omni_track('Faq17');">How is "Stay Fit" different from the other Plans?</a></h3>
         </div>
         <div id="faq-collapse17" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading17">
           <div class="panel-body">
             <p>Yes, this is actually our most popular program. please choose the Diabetes Program (this should be a clickable link)  from the disease reversal program options. </p>
           </div>
         </div>
       </div>
	   
	 
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading18">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse18" aria-expanded="false" aria-controls="faq-collapse18" onclick="omni_track('Faq18');">How is "Stay Fit" different from the other LHF Programs?</a></h3>
         </div>
         <div id="faq-collapse18" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading18">
           <div class="panel-body">
             <p>Our Stay Fit Program (clickable link) is ideal for those clients who want to maintain a healthful diet. Stay fit is also recommended for people who want to stay as healthy as possible and maintain their weight and maximize nutrition levels.</p>
           </div>
         </div>
       </div>
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading19">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse19" aria-expanded="false" aria-controls="faq-collapse19" onclick="omni_track('Faq19');">Do I have to exercise while on the Plans?</a></h3>
         </div>
         <div id="faq-collapse19" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading19">
           <div class="panel-body">
             <p>Exercise is encouraged on any Plan for optimal health, but is not required. We recommend at least 30 minutes of activity each day as it is important to move your body and stay active. This can even be light yoga or evening walks.</p>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading20">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse20" aria-expanded="false" aria-controls="faq-collapse20" onclick="omni_track('Faq20');">How much weight will I lose on the Plan?</a></h3>
         </div>
         <div id="faq-collapse20" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading20">
           <div class="panel-body">
             <ul>
			   <li>Experts agree that losing 0.5-1 kg per week is a healthy and sustainable weight loss range, and you can expect to lose weight within this range on the Weight Loss Plan .(clickable link)</li>
			   <li>On average, participants on the LHF Program lose an average of 6 kg per month.</li>
			   </ul>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading21">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse21" aria-expanded="false" aria-controls="faq-collapse21" onclick="omni_track('Faq21');">Is there a maintenance program?</a></h3>
         </div>
         <div id="faq-collapse21" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading21">
           <div class="panel-body">
             <p>Yes. After you have reached your disease reversal or weight loss goal, you can transition to the Stay Fit (clickable link) Program. </p>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading22">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse22" aria-expanded="false" aria-controls="faq-collapse22" onclick="omni_track('Faq22');">What is the cancellation policy?</a></h3>
         </div>
         <div id="faq-collapse22" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading22">
           <div class="panel-body">
             <ul>
			   <li>A Trial Plan is non refundable.</li>
			   <li>A 1-Month Plan is non refundable.</li>
			<li>After 10 days of a 3-Month, the Plan can be cancelled and the remaining balance can be used as store credit towards any purchase from Life Heal. Reimbursements are not possible at this time.</li>
		    <li>Any balance store credit can be used towards any plan, product or service in case the client wants to change their plan.</li>
				 <li>Store credit can be transferred to another client for a Rs 500 administrative fee.</li>
				 <li>Your services can be cancelled by us for any reason.</li>
				 <li>Prices subject to change.</li>
			   </ul>
           </div>
         </div>
       </div>   
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading23">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse23" aria-expanded="false" aria-controls="faq-collapse23" onclick="omni_track('Faq23');">How much weight will I lose on the LHF Program?</a></h3>
         </div>
         <div id="faq-collapse23" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading23">
           <div class="panel-body">
             <ul>
			   <li>Experts agree that losing 0.5-1 kg per week is a healthy and sustainable weight loss range, and you can expect to lose weight within this range on the LHF Weight Loss Program (clickable link)</li>
			   
			   </ul>
           </div>
         </div>
       </div>
	   
	   
	   
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading25">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse25" aria-expanded="false" aria-controls="faq-collapse25" onclick="omni_track('Faq25');">Is there a referral program?</a></h3>
         </div>
         <div id="faq-collapse25" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading25">
           <div class="panel-body">
          <ul>
		      <li>Yes, Get a Referral to Join and both you and they will save 20%</li>	   
			 <li>Terms & Conditions:</li>	
			  <li>Referrals save 20% on sign up</li>	
			  <li>Referee's earn store credit in the same amount of savings as their referral to apply towards next renewal or extra days</li>	
			  <li>Offer valid only for new sign ups to the program</li>			 
			  <li>If new sign up cancels then store credit to the referee is also withdrawn.</li>
			  <li>Cannot be combined with any other promotions or discounts</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading26">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse26" aria-expanded="false" aria-controls="faq-collapse26" onclick="omni_track('Faq26');">Is there a referral program?</a></h3>
         </div>
         <div id="faq-collapse26" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading26">
           <div class="panel-body">
			    <p>Yes, Get a Referral to Join and both you and they will save 20% </p>	
			   <p>Terms & Conditions:</p>	
          <ul>		        
			  <li>Referrals save 20% on sign up</li>	
			  <li>Referee's earn store credit in the same amount of savings as their referral to apply towards next renewal or extra days</li>	
			  <li>Offer valid only for new sign ups to the program</li>			 
			  <li>If new sign up cancels then store credit to the referee is also withdrawn.</li>
			  <li>Cannot be combined with any other promotions or discounts</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	    <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading27">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse27" aria-expanded="false" aria-controls="faq-collapse27" onclick="omni_track('Faq27');">How is delivery done? </a></h3>
         </div>
         <div id="faq-collapse27" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading27">
           <div class="panel-body">
		
          <ul>		        
			  <li>For any of our subscriptions, all meals will be delivered together.</li>	
			  <li>Our delivery person can only wait at your door for 5 minutes to not cause delay in other deliveries. Please be aware and respectful of that time limit.</li>	
			  <li>At this same time, please give our delivery person your bag and dishes from the previous day. (Remember, to stay cost effective and eco-friendly, we reuse/recycle all containers. There is also a Rs100 charge for any stainless steel container which is not returned.)</li>	 
			  <li>Please place your food in the refrigerator asap.</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading28">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse28" aria-expanded="false" aria-controls="faq-collapse28" onclick="omni_track('Faq28');">What will happen when I leave the LHF Program completely ?
</a></h3>
         </div>
         <div id="faq-collapse28" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading28">
           <div class="panel-body">
		<p>After you have reached your disease reversal or weight loss goal, you can transition to the Stay Fit (clickable link) Program. Also, throughout your full plan, your dedicated nutritionist will have helped you to understand how to make good food choices, how to prepare healthful meals at home and will also offer you to stay on a consulting only package. You can also purchase some products (Clickable link) directly from LHF to aid you in food preparation at home.</p>
           </div>
         </div>
       </div>
	   
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading29">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse29" aria-expanded="false" aria-controls="faq-collapse29" onclick="omni_track('Faq29');">Will I get any discounts ?</a></h3>
         </div>
         <div id="faq-collapse29" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading29">
           <div class="panel-body">
		<p>Yes, Get a Referral to Join and both you and they will save 20%</p>
			   <p>Terms & Conditions:</p>
          <ul>		        
			  <li>Referrals save 20% on sign up</li>	
			  <li>Referee's earn store credit in the same amount of savings as their referral to apply towards next renewal or extra days</li>	
			  <li>Offer valid only for new sign ups to the program</li>			 
			  <li>If new sign up cancels then store credit to the referee is also withdrawn.</li>
			  <li>Cannot be combined with any other promotions or discounts</li>
	     </ul>
           </div>
         </div>
       </div>
	   
	   
	   <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-heading30">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapse30" aria-expanded="false" aria-controls="faq-collapse30" onclick="omni_track('Faq30');">Will LHF help me to get 6 pack abs ?
</a></h3>
         </div>
         <div id="faq-collapse30" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-heading30">
           <div class="panel-body">
		<p>With the LHF plan and dedicated fitness goals, you may be able to achieve the fittest, healthy body possible. To achieve “6 pack” abdominals, you may also need to include a fitness instructor into your health regimine who can guide you specifically to shape the body parts you want. We have numerous athletes on our program who have achieved and even surpassed their fitness goals.+
			   </p>
           </div>
         </div>
       </div>
	   
		</div>
	   </div>
	 </div>
	</div>
	  <div class="text-center collapse-link">
       <a role="span" class="read-more-link collapsed" data-toggle="collapse" href="#faqCollapse" aria-expanded="false" aria-controls="faqCollapse" onclick="omni_track('SeeWhatsCooking');">
          <img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt="open">
          <img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt="close">
          <strong>See more FAQ's</strong></a></div>
	 <!--morefaqs-->
	 
	 </div>
	</div>

<div class="bg-secondary closer">
 <div class="container">
    <div class="">
       <div class="col-xs-12 center-block no-float text-white">
          <div class="row">
             <div class="col-xs-12 col-lg-7 col-lg-offset-1 col-md-6 col-md-offset-1 col-sm-7 text-wrapper"  style="padding:0px;">
                <h3 class="text-white">Lose weight fast with <br>the Weight Loss Individual Health!</h3></div>
             <div class="col-xs-12 span-wrapper col-md-3 col-sm-5">
                <a class="bg-white btn btn-default btn-lg scroll-to">Get Started</a>
             </div>
          </div>
       </div>
    </div>
 </div>
</div>
<div class="btn primary get-btn requestquote" style="width:100%;float:left;position:fixed;bottom:0;z-index:2;">Buy Plan</div>
	</div>
</main>

<script>
jQuery(document).ready(function () {
  jQuery('.requestquote').click(function() {
 jQuery('html, body').animate({
    scrollTop: jQuery(".requestbox").offset().top
  }, 1000)
})
	});

 
/*
	function myFunctionedit() {
  var x = document.getElementsById("delivery-options-collapse");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
	*/
	jQuery(document).ready(function () {
  jQuery('.scroll-to').click(function() {
 jQuery('html, body').animate({
    scrollTop: jQuery("#orderOptions").offset().top
  }, 1000)
})
	});
jQuery(document).ready(function(){
 jQuery("#choose-delivery").click(function(){
   jQuery(".delivery-options-collapse").toggle();
  });
});
</script>

