
	<!-- Hero Start -->
	<div class="home-hero">
	    
	    <!-- Banner -->
	    <div class="home-hero-banner">
	        <div class="home-hero-banner-container">
	        	
	        	<!-- Search -->
	        	<div class="home-hero-banner-search">
		            <div class="banner-search-text">
		                <h1>WELCOME TO THE LIFEHEAL.<br><span>WHAT WOULD YOU LIKE TO DO?</span></h1>
		            </div>
		            <div class="banner-search-field">
		            	<form role="search" method="get" class="search-form" action="">
							<input type="search" class="search-field" placeholder="Search..." value="" name="s" title="" />
							<input type="button" class="search-submit" value="&#xf002" />
    					</form>
    					<div class="search-suggestion">
    						<ul>
    							<li><a href="<?php echo $this->getUrl('weight-management') ?>">Reduce Weight</a></li>
						    <li><a href="<?php echo $this->getUrl('pre-marriage-glow')?>">Pre-Wedding Weight Loss</a></li>
								<li><a href="<?php echo $this->getUrl('gut-health')?>">Gut Health & Digestion</a></li>
								
								
    							<li><a href="<?php echo $this->getUrl('heal-diabetes') ?>">Diabetes Reduction</a></li>
						   <li><a href="<?php echo $this->getUrl('gestational-diabetes')?>">Gestational Diabetes</a></li> 
								<li><a href="<?php echo $this->getUrl('pcod-pcos') ?>">PCOS/PCOD</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('heart-health')?>">Heart Health</a></li>
								<li><a href="<?php echo $this->getUrl('hypertension')?>">Blood Pressure</a></li>
								<li><a href="<?php echo $this->getUrl('hypothyroid')?>">Hypothyroid</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('liver-health')?>">Liver Disorders</a></li>
								<li><a href="<?php echo $this->getUrl('fertility')?>">Boost Fertility</a></li>
								<li><a href="<?php echo $this->getUrl('inflammation')?>">Inflammation Reduction</a></li>
								
								
								<li><a href="<?php echo $this->getUrl('auto-immune')?>">Auto-Immune Disorders</a></li>	
    							<li><a href="<?php echo $this->getUrl('cancer-risk')?>">Reduce Cancer Risk</a></li>								
    						</ul>
    					</div>
		            </div>
		        </div>
		        
		        <!-- Hero Image -->
		        <div class="home-hero-banner-image">
		           <img src="<?php echo $this->getSkinUrl('images/home-hero-banner.png') ?>"/>
		        </div>
		        
	        </div>
	    </div>
	    
	    <!-- CTA -->
	    <div class="home-hero-cta">
	    	<div class="home-hero-cta-container">
	    		<h2>
	    			<!--Start your healthy and delicious journey with us.-->
	    			Book a 1-on-1 consultation with our Certified experts	    			
	    		</h2>	    		
	    		<a href="<?php echo Mage::getBaseUrl()."startnow" ?>" class="button cta-button"> FIRST CALL ONLY RS. 200 </a>

	    	</div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- Home Carousel Start -->
	
	<div class="home-carousel">
		<div class="home-carousel-container">
			
			<!-- Carousel Start -->
			<div class="home-carousel-wrapper">
				
				<div class="home-carousel-detail">
					<div class="home-carousel-detail-wrapper">
						<h4>SPECIAL OFFER FOR YOU</h4>
						<h2 style="text-transform: uppercase">SAVE 50% ON OUR WEIGHT LOSS PLAN <br><span style="font-size: 1.1rem;">START HEALING</span></h2>
						<p>
						Let’s face it. We all want to lose some weight. Take advantage of this offer while it lasts. 
						</p>
						<ul>
							<li> Learn the root cause of your obesity
							<li> Track over 65 biomarkers using the In-Health system</li>
							<li> Support from Certified Diabetes Educators</li>
							<li> Doctor's approved </li>
							<li> Learn to keep off that weight for good</li>
						</ul>
						<span class="use-code">Use code FIT50.</span>

						<a href="<?php echo $this->getUrl('weight-management') ?>" class="button cta-home-carousel">CHOOSE PLAN</a>
					</div>
				</div>				
				<div class="home-carousel-image" style="background-image:  url('<?php echo $this->getSkinUrl("images/home-carousel-image-1.png");?>')">
				</div>				
			</div>
			<!-- Carousel End -->
			
			<!-- Carousel Start -->
			<div class="home-carousel-wrapper">				
				<div class="home-carousel-detail">
					<div class="home-carousel-detail-wrapper">
						<h4>SPECIAL OFFER FOR YOU</h4>
						<h2 style="text-transform: uppercase">ATTEND OUR WEBINAR<br><span style="font-size: 1.1rem;">FREE FOR A LIMITED TIME </span></h2>
						<p>For a limited time our live webinars are free. You will also get your health questions answered. Learn cutting edge science and improve your health.</p>
						<a href="<?php echo $this->getUrl('webinar') ?>" class="button cta-home-carousel">REGISTER NOW</a>
					</div>
				</div>				
				<div class="home-carousel-image" style="background-image: url('<?php echo $this->getSkinUrl("images/home-carousel-image-2.png");?>')">
				</div>				
			</div>
			<!-- Carousel End -->
			
		</div>
	</div>
	
	<!-- Home Carousel End -->
	
	<!-- Home Featured Items Start -->
	<div class="home-featured">
		<div class="home-featured-container">
			
			<div class="home-featured-left" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<div class="home-featured-wrapper">
					<h2>OUR WEIGHT LOSS AND DISEASE REMISSION PLAN</h2>
					 <img src="<?php echo $this->getSkinUrl('images/home-featured-image-1.png') ?>"/>
					<p>Looking for a reliable and effective meal plan? LifeHeal has got your back. We have presented at medical conferences with our diet plans that are scientifically proven with results. They also include coaching and support to ensure success. These meal plans are focused on healing the body for long lasting gains. </p>
					<a href="<?php echo $this->getUrl('weight-management') ?>" class="button cta-home-featured-left">CHOOSE MEAL PLAN</a>
				</div>
			</div>
			
			<div class="home-featured-right" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<div class="home-featured-wrapper">
					<h2>LIFEHEAL’S FOOD SUBSCRIPTION PLAN</h2>
					 <img src="<?php echo $this->getSkinUrl('images/home-featured-image-2.png') ?>"/>
					<p>Are you tired and confused about meal portions? Is healthy eating stressing you out? If yes, then our food subscription plan is perfect for you. Our professional chefs meticulously prepare various mouthwatering cuisines with our secret techniques. Meals are precisely weighed and delivered to you. All your body’s healing is tracked via blood tests and more. We go beyond weight.</p>
					<!--<a href="<?php echo $this->getUrl('foodmealplan') ?>" class="button cta-home-featured-right">CHOOSE FOOD SUBSCRIPTION</a>-->

					<a href="<?php echo $this->getUrl('foodsubscription') ?>" class="button cta-home-featured-right">CHOOSE FOOD SUBSCRIPTION</a>

				</div>
			</div>
			
		</div>
	</div>
	
	<!-- Home Featured Items End -->
	
	
	<!-- Home Meal Plans Start -->
	<div class="home-meal-plans">
		<div class="home-meal-plans-container">
			
			<div class="home-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>OTHER MEAL PLANS</h2>
			</div>
			
			<div class="home-meal-plans-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Diabetes Reversal Plans</h3>
						<p>Low-sugar meals with the perfect balance of carbohydrates, healthy fats, and protein to keep your Diabetes in check. </p>
						<a href="<?php echo $this->getUrl('heal-diabetes') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Heart Care Meal Plans</h3>
						<p>Arterial plaque reversing meals with a bounty of nuts, seeds, and fiber-rich foods, just perfect for people with heart ailments.    </p>
						<a href="<?php echo $this->getUrl('heart-health') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Liver Health Plans</h3>
						<p>Mood-boosting meals with the right combo of antioxidants, beta-carotene, and protein.</p>
						<a href="<?php echo $this->getUrl('liver-health') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
						
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Thyroid Control</h3>
						<p>Nutrient rich meals with abundant iodine, selenium, and zinc to combat fatigue and weight gain caused by hypothyroidism. </p>
						<a href="<?php echo $this->getUrl('hypothyroid') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>				
				
								
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Pregnancy Diabetes</h3>
						<p>Nutrient-rich meals comprising green leafy vegetables, fortified cereals, beans, and nuts that increase your fertility and control sugar. </p>
						<a href="<?php echo $this->getUrl('fertility') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>PCOD meals</h3>
						<p>Sumptuous low carb, high Vitamin D, Vitamin B, Iodine, and Magnesium meals that reduce weight and PCOD symptoms</p>
						<a href="<?php echo $this->getUrl('pcod-pcos') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="home-meal-plans-detail">
					<div class="home-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/home-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="home-meal-plans-detail-text">
						<h3>Pre-Marriage Weight Loss</h3>
						<p>Holistic weight loss plans that helps reduce 10, 20 and even 30 kgs to usher in the big day.</p>
						<a href="<?php echo $this->getUrl('pre-marriage-glow') ?>" class="button cta-home-meal-plans-detail-text">Know more details</a>
					</div>
				</div>
			
			</div>
			
		</div>
	</div>
	<!-- Home Meal Plans End -->
	
	
	<!-- Home Meet Expert Start -->
	<div class="home-meet-expert">
		
		<div class="home-meet-expert-container">
			
			<div class="home-meet-expert-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h2>MEET OUR EXPERT COACH<br><span>JUNIOR ANAND GUPTA</span></h2>
				<p>Junior A. Gupta is the founder of LifeHeal. He hails from a family with a history of Diabetes. Mr. Gupta says that "Growing up, the question wasn't If I would get diabetes, but When." He wanted to change the Indian mindset about Diabetes being genetic and irreversible. After many years of research, he realized that well-balanced diets are proven to control Diabetes. He started LifeHeal in 2018 to help people live healthier, stronger, and longer. He has degrees from Babson and MIT in the USA. He's a receiver of APJ Abdul Kalam's "Goodness Award" and also a TedX speaker.</p>
				<a href="<?php echo $this->getUrl('aboutus') ?>" class="button cta-home-meet-expert">KNOW MORE</a>
			</div>
			<div class="home-meet-expert-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				 <img src="<?php echo $this->getSkinUrl('images/home-expert-jr.png') ?>"/>
			</div>
			
		</div>
		
	</div>
	<!-- Home Meet Expert End -->
	
	<!-- Home Impact Story Start -->
	<div class="home-impact-story">
		<div class="home-impact-story-container">			
			<div class="home-impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				 <img src="<?php echo $this->getSkinUrl('images/aditya_pic.jpg') ?>"/>
			</div>
			<div class="home-impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL ADITYA LOST 24KGS WITHOUT ANY EXERCISE</h2>
				<h3>Aditya Dutta, 31 Years, Executive, <span>Delhi</span></h3>
				<p>I started at 100 kg and lost a total of 24 kg on the LifeHeal program. I did not exercise at all for the first 20 kg. As a bonus everyone now says I look different and I feel so great</p>
				<div class="home-impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=F4dGdYQEp2w" data-youtube-id="F4dGdYQEp2w" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/aditya-video-1.jpg') ?>"/>
					</a>
				</div>
			</div>
		</div>
	</div>	
	<!-- Home Impact Story End -->
	
	
	<!-- Home Why Choose Us Start -->
	<div class="home-why-choose-us">
		
		<div class="home-why-choose-us-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHY CHOOSE US</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">LifeHeal has presented at some of India’s top hospitals. Directors, Chairmen, CEO’s - all the top notch. If you want a company that’s bringing in the most current science in disease reversal you have found the right place.</p>
			
			
			<div class="home-why-choose-us-details-wrapper">
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-1.png') ?>"/>
					<h3>Doctor Reviewed</h3>
					<p>13 years of research. Observed by many of India's top doctors to deliver multi-fold benefits.
					 </p>
				</div>
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-2.png') ?>"/>
					<h3>Staff Certifications</h3>
					<p>You will enjoy working with our team of Certified Diabetes Educators.</p>
				</div>
				
				<!-- Details -->
				<div class="home-why-choose-us-details" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/home-why-choose-us-3.png') ?>"/>
					<h3>A.I. Support</h3>
					<p>Over 70 metabolic markers are tracked to understand your health using our InHealth system.</p>
				</div>
				
			</div>
			
		</div>
		
	</div>
	
	<!-- Home Why Choose Us End -->
	
	
	<!-- Home Stats Start -->
	
	<div class="home-stats">
		<div class="home-stats-container">
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
			
			<!-- Stats -->
			<div class="home-stats-detail">
				<h2><span class="home-stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	
	<!-- Home Stats End -->
	
	<!-- Home Testimonials Start -->
	
	<div class="home-testimonials" style="display: none;">
		<div class="home-testimonials-container">
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS FOR LIFEHEAL</h2>
			
			<div class="home-testimonials-videos" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-1.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-2.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-1.png') ?>"/>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/home-impact-story-detail-video-2.png') ?>"/>
				</a>
			
			</div>
		</div>
	</div>
	
	<!-- Home Testimonials End -->
	
	
	<!-- Home Contact Start -->
	
	<div class="home-contact">
		<div class="home-contact-container">
			<div class="home-contact-title">
				 <img src="<?php echo $this->getSkinUrl('images/home-contact-title-image.png') ?>"/>
				<h2>LIFEHEAL KEEPS YOU ONE STEP AHEAD IN LIFE WITH HEALTHY MEAL PLANS</h2>
			</div>
		</div>
	</div>
	
	<div class="home-contact-form-wrapper">
		<div class="home-contact-form-container">
			<div class="home-contact-form-left" style="background-image: url('<?php echo $this->getSkinUrl("images/home-contact-form.png");?>')"></div>
			<div class="home-contact-form-right">
				<h3>Have any question/feedback?</h3>
				<p>We love hearing from our customers. At LifeHeal, we strive to make our customers happy and healthy. Please fill out the form below regarding any questions and feedback that you may have. Our customer support associates will get back to you within 3 business days. Stay Happy and Healthy! </p>
				<span id="thanksMsg" style="color:red"></span>
				<!--<form action="" method="POST" id="home-contact-form">
					<input type="text" id="name" name="name" placeholder="*Your Name" required>
					<input type="email" id="email" name="email" placeholder="*Your Email" required>
					<textarea name="message" id="message" rows="4" placeholder="*Your message..." required></textarea>
					<input type="button" value="SUBMIT" onclick="sendEmail()">
				</form>-->
				<form id="home-contact-form" action='https://crm.zoho.in/crm/WebToLeadForm' name=WebToLeads126676000004927007 method='POST' onSubmit='javascript:document.charset="UTF-8"; return checkMandatory126676000004927007()' accept-charset='UTF-8'>
 					<input type='text' style='display:none;' name='xnQsjsdp' value='b43efcd5d07598c5a2dec7cbbd9f0a4a4778bde7ffbd77b08070784d65801fa2'></input> 
 					<input type='hidden' name='zc_gad' id='zc_gad' value=''></input> 
 					<input type='text' style='display:none;' name='xmIwtLD' value='5f229f01e98885a79974c37c8c9fe2b5cddbe2463c5fd7e1d97c404fd6cc2c74'></input> 
 					<input type='text'  style='display:none;' name='actionType' value='TGVhZHM='></input>
 					<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;startlifeheal.com&#x2f;' > </input>
	 				<!-- Do not remove this code. -->
	 				<input type='text' style='display:none;' id='ldeskuid' name='ldeskuid'></input>
	 				<input type='text' style='display:none;' id='LDTuvid' name='LDTuvid'></input>
	 				<!-- Do not remove this code. -->
					<input type='text' id='Last_Name' name='Last Name' placeholder="*Your Name" required></input>	
					<input type='text' ftype='email' id='Email' name='Email' placeholder="*Your Email" required></input>
					<textarea id='Description' name='Description' rows="4" placeholder="*Your message..." required></textarea>
					<input type='submit' id='formsubmit' class='formsubmit zcwf_button' value='Submit' title='Submit'>
					<input type='reset' style="display: none;" class='zcwf_button' name='reset' value='Reset' title='Reset'>
				</form>
			</div>
		</div>
	</div>

	<script>
	function validateEmail126676000004927007()	{
		var form = document.forms['WebToLeads126676000004927007'];
		var emailFld = form.querySelectorAll('[ftype=email]');
		var i;
		for (i = 0; i < emailFld.length; i++)
		{
			var emailVal = emailFld[i].value;
			if((emailVal.replace(/^\s+|\s+$/g, '')).length!=0 )
			{
				var atpos=emailVal.indexOf('@');
				var dotpos=emailVal.lastIndexOf('.');
				if (atpos<1 || dotpos<atpos+2 || dotpos+2>=emailVal.length)
				{
					alert('Please enter a valid email address. ');
					emailFld[i].focus();
					return false;
				}
			}
		}
		return true;
	}

 	  function checkMandatory126676000004927007() {
		var mndFileds = new Array('Last Name');
		var fldLangVal = new Array('Last\x20Name');
		for(i=0;i<mndFileds.length;i++) {
		  var fieldObj=document.forms['WebToLeads126676000004927007'][mndFileds[i]];
		  if(fieldObj) {
			if (((fieldObj.value).replace(/^\s+|\s+$/g, '')).length==0) {
			 if(fieldObj.type =='file')
				{ 
				 alert('Please select a file to upload.'); 
				 fieldObj.focus(); 
				 return false;
				} 
			alert(fldLangVal[i] +' cannot be empty.'); 
   	   	  	  fieldObj.focus();
   	   	  	  return false;
			}  else if(fieldObj.nodeName=='SELECT') {
  	   	   	 if(fieldObj.options[fieldObj.selectedIndex].value=='-None-') {
				alert(fldLangVal[i] +' cannot be none.'); 
				fieldObj.focus();
				return false;
			   }
			} else if(fieldObj.type =='checkbox'){
 	 	 	 if(fieldObj.checked == false){
				alert('Please accept  '+fldLangVal[i]);
				fieldObj.focus();
				return false;
			   } 
			 } 
			 try {
			     if(fieldObj.name == 'Last Name') {
				name = fieldObj.value;
 	 	 	    }
			} catch (e) {}
		    }
		}
		trackVisitor();
		if(!validateEmail126676000004927007()){return false;}
		document.querySelector('.crmWebToEntityForm .formsubmit').setAttribute('disabled', true);
	}

function tooltipShow126676000004927007(el) {
	var tooltip = el.nextElementSibling;
	var tooltipDisplay = tooltip.style.display;
	if(tooltipDisplay == 'none'){
		var allTooltip = document.getElementsByClassName('zcwf_tooltip_over');
		for(i=0; i<allTooltip.length; i++){
			allTooltip[i].style.display='none';
		}
		tooltip.style.display = 'block';
	}else{
		tooltip.style.display='none';
	}
}
</script>
<script type='text/javascript' id='VisitorTracking'>var $zoho= $zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode:'e8e4f602aa5edc51dc202b69cc12c9c7cd951725c39c9b29b67993e145d995db', values:{},ready:function(){}};var d=document;s=d.createElement('script');s.type='text/javascript';s.id='zsiqscript';s.defer=true;s.src='https://salesiq.zoho.in/widget';t=d.getElementsByTagName('script')[0];t.parentNode.insertBefore(s,t);function trackVisitor(){try{if($zoho){var LDTuvidObj = document.forms['WebToLeads126676000004927007']['LDTuvid'];if(LDTuvidObj){LDTuvidObj.value = $zoho.salesiq.visitor.uniqueid();}var firstnameObj = document.forms['WebToLeads126676000004927007']['First Name'];if(firstnameObj){name = firstnameObj.value +' '+name;}$zoho.salesiq.visitor.name(name);var emailObj = document.forms['WebToLeads126676000004927007']['Email'];if(emailObj){email = emailObj.value;$zoho.salesiq.visitor.email(email);}}} catch(e){}}</script>
	<!-- Do not remove this --- Analytics Tracking code starts --><script id='wf_anal' src='https://crm.zohopublic.in/crm/WebFormAnalyticsServeServlet?rid=5f229f01e98885a79974c37c8c9fe2b5cddbe2463c5fd7e1d97c404fd6cc2c74gidb43efcd5d07598c5a2dec7cbbd9f0a4a4778bde7ffbd77b08070784d65801fa2gid534cb20477b1d28b5f45f7cc241888c5gid4ee3a7e9ace6ab1be7c541b329164307'></script>

	
<script type="text/javascript">
  
function sendEmail()	{  		
		var name = jQuery("#name").val();
		var fromEmail = jQuery("#email").val();
		var message = jQuery("#message").val();
		
		//alert(orderDate);
		if(name!='' && fromEmail!='' && message!='') {		
			jQuery.ajax({
						url: "<?php echo Mage::getBaseUrl().'override/index/addzoholead' ?>",
						type: "POST",
						data: {
						 name: name,
						 email:fromEmail,
						 message:message
						},
						  success: function(response)
						 {  
							
								//var msg="Thank you for contacting us.";
								jQuery("#thanksMsg").html(response);
							    jQuery("#thanksMsg").show("slow").delay(3000).hide("slow");
							
								jQuery("#name").val('');
								jQuery("#email").val('');
								jQuery("#message").val('');
						 }
			});
		} else {
			var msg="Please fill the required fields.";
			jQuery("#thanksMsg").html(msg);
			jQuery("#thanksMsg").show("slow").delay(5000).hide("slow");
			}
	}

	 jQuery(".search-form").focusin(function() {
            jQuery('.search-suggestion').show();
        });
 
        jQuery(document).on("click", function(e) {
            if (jQuery(e.target).is(".search-field") === false) {
                jQuery('.search-suggestion').hide();
            }
        });
</script>
	
	<!-- Home Contact End -->
	
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
<style type="text/css">
	.home-carousel-detail-wrapper ul{
		margin: 0 0 8px 0;
		padding-left: 20px;
	}
	.home-carousel-detail-wrapper ul li{
		font-weight: 400;
		font-size: 16px;
		position: relative;
		padding-left: 20px;
		list-style: none;
		padding-bottom: 6px;
		color: #fff;
	}
	.home-carousel-detail-wrapper ul li:after{
		content: '';
		position: absolute;
		left:0;
		top:4px;
		width:8px;
		height: 8px;
		background: #0eb58f;
		border-radius: 100%;
	}
	.use-code{
		display: inline-block;
		font-weight: 700;
		color: #fff;
		padding: 0 0 15px 20px;		
	}
	.home-carousel-detail-wrapper p {
    	padding-bottom: 1rem;
	}
</style>
