<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/how-it-works.css" type="text/css"/>
<style>
.navbar-light .navbar-nav #nav-view-plan {
    background:#fff;
    color: #000 !important;
}
	.navbar-light .navbar-nav #how-it-work {
    background: rgb(26, 204, 205);
    color: #fff !important;
}
</style>
<div class="southbeach page-how-it-works">
<div id="content">
  <div class="hero">
    <div class="container">
      <div class="">
        <div class="text-center col-xs-12">
          <h1 class="h2"><strong>How The Life Heal <br class="visible-xs" aria-hidden="true">Program Works</strong></h1>
          <p class="lead text-center fw-400">We have more than nine years of experience customizing meal plans for disease reversal and weight loss.</p>
        </div>
      </div>
      <div class="below-hero">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="">
            <div class="panel panel-default col-xs-12 col-sm-4">
              <div class="panel-heading accordion" role="tab" id="headingOne">
                <div class="">
                  <div class=""> <img src="<?php echo $this->getSkinUrl('images/Scientific.png') ?>" class="center-block bolt-icon" alt="line drawing of fork, plate and knife"> </div>
                </div>
                <h2 class="text-center h4">IT’S SCIENTIFIC</h2>
                <p class="text-center strong">We look beyond calories <br>to your overall health.</p>
                <p class="panel-title text-center h5"> <a role="button" class="read-more-link" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" onclick="omni_track('ReadMore1');"><img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt=""><img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt=""><strong>Read More</strong></a> </p>
              </div>
              <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body text-center">Extensive research has proven various positive effects of nutrition. Diet affects us at a macro level, and can even affect gene expression with the power to turn on and off many genes found in the body.</div>
              </div>
            </div>
            <div class="panel panel-default col-xs-12 col-sm-4">
              <div class="panel-heading accordion" role="tab" id="headingTwo">
                <div class="">
                  <div class=""> <img src="<?php echo $this->getSkinUrl('images/Customize.png') ?>" class="center-block heart-icon" alt="line drawing of red and white lifesaver ring"> </div>
                </div>
                <h2 class="text-center h4">IT’S CUSTOMIZED</h2>
                <p class="text-center strong">Designed by specialists to burn fat and transform your metabolism</p>
                <p class="panel-title text-center"> <a class="collapsed read-more-link" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" onclick="omni_track('ReadMore2');"><img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt=""><img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt=""><strong>Read More</strong></a> </p>
              </div>
              <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body text-center">Our team works closely with each client to understand their preferences and customize each meal to their liking. We understand food needs to be tasty and satisfying for the program to be a success. We also customize according to your health requirements, be it weight loss or disease remission.</div>
              </div>
            </div>
            <div class="panel panel-default col-xs-12 col-sm-4">
              <div class="panel-heading accordion" role="tab" id="headingThree">
                <div class="">
                  <div class=""> <img src="<?php echo $this->getSkinUrl('images/Reports.png') ?>" class="center-block head-icon" alt="line drawing of an umbrella and bucket inside a beach cart"> </div>
                </div>
                <h2 class="text-center h4">IT’S RESULTS ORIENTED</h2>
                <p class="text-center strong">For maximum results, your plan is tailored to your lifestyle and preferences</p>
                <p class="panel-title text-center"> <a class="collapsed read-more-link" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" onclick="omni_track('ReadMore3');"><img src="<?php echo $this->getSkinUrl('images/plus-circle-icon.svg') ?>" class="center-block plus-circle" alt=""><img src="<?php echo $this->getSkinUrl('images/x-circle-icon.svg') ?>" class="center-block x-circle" alt=""><strong>Read More</strong></a> </p>
              </div>
              <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body text-center">We strive hard for your success. We combine your preferences with your health needs, and create food that will help you meet your goals. It is fool-proof as now as all you have to do is eat!</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="quote1">
    <div class="container">
      <div class="">
        <div class="col7q no-padding-mob">
            <img src="<?php echo $this->getSkinUrl('images/how-aditya.jpg') ?>" class="img-responsive center-block" alt="couple laughing while laying in a hammock together">
        </div>
        <div class="col5q">
            <p class="h3"><strong>“It’s so easy—All you have to do is eat!”</strong></p>
            <p class="h4 fw-300">Aditya <strong>lost 24 kgs.<sup>*</sup></strong> | Real <br class="visible-xs" aria-hidden="true">Success Story</p>
          <div class="cta-wrapper" style="display:none;"> <a href="https://lifeheal.in/weightlossplan" class="btn btn-default" onclick="omni_track('GetStartedTop');"> View Plans</a> </div>
          <p class="small">*Average weight loss expected 6 Kgs per month.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="what-you-get">
    <div class="container">
      <h2 class="text-center fw-600">What you get.</h2>
      <hr>
      <div class="">
        <div class="col6w no-padding-mob"> <img src="<?php echo $this->getSkinUrl('images/shake-vanilla-cutout.png') ?>" class="food-cutout hidden-xs" alt=""><img src="<?php echo $this->getSkinUrl('images/750x557-top-banner.jpg') ?>" class="img-responsive center-block food-cutout-top" alt="Farmstand garden and cheese omelet and edamame Chicken, with a Beach Shack Chocolate Shake on a table" role="presentation"> </div>
        <div class="col6w">
          <ul class="list-checked check-primary">
            <li class="fw-400">Your choice of easy-to-follow <a href="https://lifeheal.in/plans">plans</a> with a dedicated nutritionist and focus on your health goal</li>
            <li class="fw-400" style="display:none;">Delicious, nutritious, fully prepared Life Heal meals</li>
            <li class="fw-400" style="display:none;">FREE doorstep delivery</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="what-you-do fixed-height">
    <div class="container">
      <h2 class="text-center fw-600">What you do.</h2>
      <hr>
      <div class="">
        <div class="col6w">
          <div class="times-day"> <img src="<?php echo $this->getSkinUrl('images/554x560-1stbanner.png') ?>" class="img-responsive center-block visible-xs" alt="Plate of chicken primavera" role="presentation">
            <div class="bg-white">
              <h3 class="h4 fw-700 offset-bg"><span>LIVE HEALTHY</span></h3>
              <p>The Life Heal Program is a safe, effective method of disease remission, weight loss, and introduces easy-to-follow principles that allow our clients to enjoy eating and achieve optimal health.</p>
            </div>
          </div>
        </div>
        <div class="col6w nutrition">
          <div class="bg-white">
            <h3 class="h4 fw-700 offset-bg"><span>GET BALANCED&nbsp;</span><span>NUTRITION</span></h3>
            <p>Life Heal plans include the right mix of nutrients from a wide variety of wholesome foods. You’ll reduce disease, lose weight and learn how to keep it off!</p>
            <div class="text-center"> <img src="https://content.southbeachdiet.com/images/sbd/how-it-works/balanced-foods-3.svg" class="" alt="line drawings of a fish representing lean proteins, broccoli representing good carbs, bottle of olive oil representing healthy fats"> </div>
          </div>
        </div>
      </div>
      <div class="">
        <div class="col6w">
          <div class="flexibility">
            <div class="bg-white">
              <h3 class="h4 fw-700 offset-bg"><span>CUSTOMIZED WELLNESS</span></h3>
              <p>Your dedeicated nutritionist will create a specific meal plan for you and will guide to success!</p>
            </div>
            <img src="<?php echo $this->getSkinUrl('images/554x560-(2)-2ndbanner.png') ?>" class="visible-xs img-responsive" alt="Cod with almond basil relish with a side of brocolli on a table">
          </div>
        </div>
        <div class="col6w">
          <div class="claim">
            <div class="bg-white">
              <div class="text-center">
                <h3 class="offset-bg"><strong><span>Lose up to 10 Kgs</span><br aria-hidden="true">
                  <span>in a&nbsp;</span><span>month</span></strong></h3>
                <p class="fw-600">followed by a steady weight loss, until you reach your goal!</p>
                <p class="small">*results may vary</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="faqs">
    <div class="container">
      <h2 class="text-center fw-600">Frequently Asked Questions</h2>
      <hr>
      <div class="">
        <div class="col8f">
          <div class="panel-group" id="faq-accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingOne">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseOne" aria-expanded="false" aria-controls="faq-collapseOne" onclick="omni_track('Faq1');">Will I be hungry on the Plan?</a></h3>
         </div>
         <div id="faq-collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingOne">
           <div class="panel-body">
			   <p>On any of our Plans, you will be recommended a variety of nutrient dense—high in protein and healthy fat—foods throughout the day to help keep you feeling full. Our portion suggestions are also surprisingly large, and most clients say they are unable to finish their entire meals. If you feel that you are still hungry after eating, you have the flexibility to enjoy additional servings of snacks recommended by your dedicated nutritionist.</p>
             </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingTwo">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseTwo" aria-expanded="false" aria-controls="faq-collapseTwo" onclick="omni_track('Faq2');">Do the suggested foods taste good?</a></h3>
         </div>
         <div id="faq-collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingTwo">
           <div class="panel-body">
             <p>Our Plans offers a wide variety of delicious, healthy breakfast, lunch, and dinner options, and sweet and savory snacks, in a range of globally inspired flavors that you’ll love, including Indian, Mughlai, Chinese, Continental, and Italian. Our consulting chefs are previously from 5-star hotel kitchens; we know our Food Plans must be delicious to be successful!</p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingThree">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseThree" aria-expanded="false" aria-controls="faq-collapseThree" onclick="omni_track('Faq3');">Is this a Keto diet?</a></h3>
         </div>
         <div id="faq-collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingThree">
           <div class="panel-body">
             <ul>
			   <li>As keto continues to be a growing trend in the health and wellness world, we’ve created some Keto options in our Plans to help people lose weight.</li>
				 <li>Depending on your requirements, we recommend different levels of Keto-Friendly foods. This means you’ll enjoy more quality carbs, higher protein levels and more food variety, including foods that are off-limits on the keto diet like milk, whole grains and beans.</li>
				 <li>Our keto–friendly approach to weight loss delivers below 50 grams of net carbs per day. (Net carbs are the total carbohydrates in a food or beverage, minus dietary fiber and erythritol, a type of sugar alcohol.)</li>
				 <li>While our's is a low-carb, good-fat approach, it’s not “strictly keto” or intended to allow individuals to achieve or maintain nutritional ketosis.</li>
				 
			   </ul>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFour">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFour" aria-expanded="false" aria-controls="faq-collapseFour" onclick="omni_track('Faq4');">Are the Plans gluten-free?</a></h3>
         </div>
         <div id="faq-collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFour">
           <div class="panel-body">
             <p>If required, we can suggest gluten free ingredients, and you can customize further with your dedicated nutritionist.</p>
           </div>
         </div>
       </div>
       <div class="panel panel-default">
         <div class="panel-heading accordion" role="tab" id="faq-headingFive">
           <h3 class="panel-title"> <a class="collapsed" role="span" data-toggle="collapse" data-parent="#faq-accordion" href="#faq-collapseFive" aria-expanded="false" aria-controls="faq-collapseFive" onclick="omni_track('Faq5');">Can a vegan be on the Plan?</a></h3>
         </div>
         <div id="faq-collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="faq-headingFive">
           <div class="panel-body">
             <p>Yes, our Plans are very aligned with a Vegan diet and can be further customized with your dedicated nutritionist.</p>
           </div>
         </div>
       </div>  
          </div>
        </div>
      </div>
    </div>
  </div>
  <section class="closer bg-secondary">
    <div class="container">
      <div class="">
        <div class="center-block no-float text-white col-xs-12">
          <div class="row">
            <div class="text-wrapper col-xs-12 col-sm-7 col-md-7 col-md-offset-1 col-lg-6 col-lg-offset-2">
              <h3 class="text-white">Lose weight fast with <br> the Deep Insight Consulting Plan!</h3>
            </div>
            <div class="button-wrapper col-xs-12 col-sm-4 col-md-3"> <a href="https://lifeheal.in/weightlossplan" class="btn btn-default btn-lg bg-white" onclick="omni_track('GetStartedBottom');">View Plans</a> </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script src="https://content.southbeachdiet.com/js/sbd/how-it-works/how-it-works.js"></script>
</div>
	</div>