<div id="wsite-content" class="wsite-elements wsite-not-footer">
	<div class="wsite-section-wrap">
	<div class="wsite-section wsite-body-section wsite-background-2">
		<div class="wsite-section-content">
          <div class="container">
			<div class="wsite-section-elements">
            
            <h1 class="arial default-transform large">The Cure My Diabetes Program : How The Diabetes Reversal Program Works </h1>

<div class="wsite-spacer" style="height:50px;"></div>

<div><div class="wsite-multicol"><div class="wsite-multicol-table-wrap" style="margin:0 -15px;">
	<table class="wsite-multicol-table">
		<tbody class="wsite-multicol-tbody">
			<tr class="wsite-multicol-tr">
				<td class="wsite-multicol-col" style="width:33.838383838384%; padding:0 15px; vertical-align: top;">
					
						

<h2 class="wsite-content-title" style="text-align:left;"><font size="4">How We Work</font></h2>

<div class="paragraph" style="text-align:justify;"><font size="3"><span>We provide customized food delivered to your home, in subscription packages.<br><br>The food is customized around you and our focus is to bring the desired changes to the HbA1c and weight loss that you need. This is individualized based on your starting parameters and needs.<br>​</span><br><span>Our food research is centered around reversing diabetes but all of these diseases are related and people will get relief in: </span><br><span>• Diabetes</span><br>•&nbsp;<span>Blood Pressure<br>• Obesity<br>• Heart Disease<br>• High Cholesterol<br>• Many other chronic degenerative diseases.</span></font></div>


					
				</td>				<td class="wsite-multicol-col" style="width:66.161616161616%; padding:0 15px;">
					
						

<div><div class="wsite-image wsite-image-border-none " style="padding-top:15px;padding-bottom:10px;margin-left:0px;margin-right:0px;text-align:center">
<a>
<img src="<?php echo $this->getSkinUrl('images/img-4755-1_1_orig.jpg') ?>" alt="Picture" style="width:auto;max-width:100%">
</a>
<div style="display:block;font-size:90%">Kale, Bell Pepper &amp; Tofu Salad With Nutri-Boost Dressing</div>
</div></div>

<h2 class="wsite-content-title">Mission</h2>

<div class="paragraph"><span><font size="3">To help the body need a minimum amount of medicines and have maximum immunity.</font></span><br><span></span></div>

<h2 class="wsite-content-title">Vision</h2>

<div class="paragraph"><span><font size="3">A world where more people eat well and have minimum chronic diseases and better quality life</font></span></div>


					
				</td>			</tr>
		</tbody>
	</table>
</div></div></div>





<div><div style="height: 40px; overflow: hidden; width: 100%;" class="whiteer"></div>
<hr class="styled-hr" style="width:100%;">
<div style="height: 40px; overflow: hidden; width: 100%;" class="whiteer"></div></div>





<div><div class="wsite-multicol"><div class="wsite-multicol-table-wrap" style="margin:0 -25px;">
	<table class="wsite-multicol-table">
		<tbody class="wsite-multicol-tbody">
			<tr class="wsite-multicol-tr">
				<td class="wsite-multicol-col" style="width:33.265993265993%; padding:0 25px;">
					
						

<h2 class="wsite-content-title" style="text-align:left;"><span style="font-weight:normal"></span><span style="color:rgb(77.738000%, 0.094000%, 24.910000%)">WHAT WE DO:&nbsp;</span><br><span style="font-weight:normal"></span></h2>

<div class="paragraph" style="text-align:left;"><span><font size="3">We give customized food to patients of chronic diseases to help their body need a minimum amount of medicines and have maximum immunity &amp; vitality</font></span></div>


					
				</td>				<td class="wsite-multicol-col" style="width:33.400673400673%; padding:0 25px;">
					
						

<h2 class="wsite-content-title" style="text-align:left;"><span style="color:rgb(77.738000%, 0.094000%, 24.910000%)">HOW DO WE DO:&nbsp;</span></h2>

<div class="paragraph" style="text-align:left;"><span><font size="3">We provide food ideal for your health needs delivered with the maximum convenience</font></span></div>


					
				</td>				<td class="wsite-multicol-col" style="width:33.333333333333%; padding:0 25px;">
					
						

<h2 class="wsite-content-title" style="text-align:left;"><span style="color:rgb(77.738000%, 0.094000%, 24.910000%)">WHY DO WE DO:&nbsp;</span></h2>

<div class="paragraph" style="text-align:left;"><span><font size="3">We have family members and friends with chronic diseases. This journey is to maximize their health, lengthen their life, and along the way to help others just like ourselves</font></span></div>


					
				</td>			</tr>
		</tbody>
	</table>
</div></div></div>


</div>
</div>
</div>
</div>
</div>
</div>