<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>How Does It Work?</b>
            </div>
            <div class="easypara">
            <p>All you have to do is eat!</p>
<p>We do the planning, cooking and delivery of therapeutic meals. The food is delivered right to your 
doorstep.</p>
    <p>It is 24 hrs of food. It will reach before 7 pm and will include :</p>       
            <ul>
            <li>Dinner
            </li>
            <li>
         Next Day's Breakfast
            </li>
            <li>Next Days's Lunch
</li>
<li>Next Day's High Tea</li>
            </ul>
            <p>The food is packed in reusable glass jars. The driver will come back next day and deliver more 
food and pick up the old used glass jars. This is repeated everyday till you have hit your targeted 
health goals.</p>
            <p>In case of travel you can cancel your food delivery one day prior. There is no cancellation charge.</p>
            <p>You can cancel your subscription any time and get reimbursed for unused days of food. However 
any free services or add-ons which are included with a monthly package are charged if the whole 
month's subscription is not completed. Please see pricing page for more details.</p>
            </div>
            </div>
            </section>