<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              <b>How Do I Start?</b>
            </div>
            <div class="easypara">
            <p>Starting works as follows :</p>
     
            <ul>
            <li><b>MEET OUR DIETICIAN:</b> You can come in to our center or our dietician can come and visit you at 
      home. We will learn about your medical history and what are typical problems for you. We will 
      also note your weight, HBA1c and other important details.
            </li>
            <li>
          <b>INSTALL GLUCOSE MONITORING CHIP:</b> This chip is installed on you to get a closer look at how 
      your body's sugar moves during the day. This data is collected for 48-72 hours and reviewed 
      before starting the delivery program. 
            </li>
            <li><b>DOCTOR REVIEW:</b> The doctor will review your glucose levels and your current medications. Any 
      medication changes will be advised by the doctor. 
</li>
<li><b>FOOD DELIVERY BEGINS:</b> Food delivery begins. We work with you to understand your tastes 
      and preferences. So far everyone has complained that there is too much food and they cannot 
      finish it.</li>
      <li><b>GLUCOSE LEVEL REVIEW AND MEDICINE ADJUSTMENT:</b> We review how the food is impacting 
      your blood glucose levels and the doctor adjusts medication accordingly. We keep reviewing 
      your glucose levels and weight to ensure we keep moving forward.</li>
            </ul>
           
            </div>
            </div>
            </section>