
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	
	<link href="<?php echo $this->getSkinUrl();?>css/mixin.css" type="text/css" rel="stylesheet"/>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Latest compiled and minified JavaScript -->


	
	<div id="wrap">
			<div class="conteudo">
				<div class="container-fluid" style="padding:0px;">
					<div class="resize-message">
						<div class="container">
							<div class="width1100">
						<div class="searchbarwelcome"><h2>Welcome to the LifeHeal.</h2>
<h2 class="white">What would you like to do?</h2>
						<div class="search-container">
    <form action="/action_page.php">
		<span  onclick="myFunction()">
      <input type="text" placeholder="Search.." name="search">
     <i class="fa fa-search"></i>
		</span>
		 <div id="myDropdown" class="dropdown-content">
    <a href="#obesity-management">Reduce Weight</a>
    <a href="#base">Diabetes</a>
    <a href="#blog">Blood Pressure</a>
    <a href="#contact">Look Younger</a>
    <a href="#custom">Pre-baby diabetes</a>
    <a href="#support">Hypertension</a>
    <a href="#tools">Hormonal Issues</a>
	<a href="#fattyliver">Fatty Liver</a>
    <a href="#pcod">PCOD</a>
    <a href="#health">Health and Fitness</a>
    <a href="#thyroid">Thyroid</a>
    <a href="#infla">Inflammation</a>
    <a href="#pre-mar">Pre-marriage Fitness</a>
    <a href="#cardiac">Cardiac Disease</a>
    <a href="#auto">Auto-Immune</a>
			 
  </div>
    </form>
  </div>
						</div>
						<div class="welcomeimage"><img src="<?php echo $this->getSkinUrl('images/Layer@4X.webp') ?>"/></div>
					</div>
				</div>
						</div>
				</div>
				<div class="container-fluid" style="padding:0px;">
				<div class="author">
					<div class="container">
				<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>	
					<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="bookappoint">Book your appointment</a>
					</div>
				</div>
					</div>
				</div>
					<!--slidertestimonuial-->
		<div class="container-fluid" style="padding:0px;">
		<div class="testm">
			
			
			<div class="maintest">
<div class="container">
  <div class="slider">

    <div class="buttons">
      <div class="previous"></div>
      <div class="next"></div>
    </div>
    <div class="slide">
      <div class="testimonial">
        <blockquote><p style="text-transform: uppercase">Special Offer for you</p>
		  <h3>30% off on meal plans<br>
when placing First Order </h3>
		  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 
			  sed diam nonumy eirmod tempor invidunt ut labore et 
			  dolore magna aliquyam erat, sed diam voluptua. At 
			  vero eos et accusam et justo duo dolores et ea rebum. 
			  Stet clita kasd gubergren, no sea tak</p></blockquote>
        <a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="bookappointbtn">Choose Meal Plan</a>
        
      </div>

      <div class="slider-img">
       <img src="<?php echo $this->getSkinUrl('images/SaladRoasted.png') ?>"/>
      </div>

    </div>

    <div class="slide">
      <div class="testimonial">
        <blockquote><p style="text-transform: uppercase">Special Offer for you</p>
		  <h3>30% off on meal plans<br>
when placing First Order </h3>
		  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p></blockquote>
        <a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="bookappointbtn">Choose Meal Plan</a>
        
      </div>

      <div class="slider-img">
       <img src="<?php echo $this->getSkinUrl('images/SaladRoasted.png') ?>"/>
      </div>


    </div>

  </div>

				</div>
				</div>
			
				</div>
			</div>
			<div class="container-fluid" style="padding:0px;">
		<div class="boxleftright">
		
			<div class="container">
			<div class="boxcolorange"><h3>Our Weight Management &
Disease remission Meal Plans</h3><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p>
			<img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;"/>
			<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="mealplanbtn">Choose Meal Plan</a>
			</div>
			
			<div class="boxcolpurple"><h3>Subscribe for Lifeheals
Food Subscription plans</h3><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p>
			<img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;"/>
			<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="mealplanbtn">Choose Meal Plan</a></div>
			</div>
			</div>
			</div>
		<!--sliderbox-->
		<div class="container-fluid" style="padding:0px;">
		<div class="sliderboxmeal">
			<div class="container">
		<h2>Other Meal Plans</h2>
		<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
			<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/imagefood.png') ?>" style="width:100%;" class="image"/>
  <div class="downbox">Diabetes Reversal<br>Meal Plan</div>
  <div class="overlay">
    <div class="text"><h3>Diabetes Reversal<br>Meal Plan</h3>
<p>Know how our customised meal plan works and choose meal plan which suits you best. </p>
<a href="https://www.davidsonsilva.com.br?utm_source=codepen" target="_blank" class="slidebtn">Know more details 
	<img src="<?php echo $this->getSkinUrl('images/arrow-right@1X.png') ?>"/></a>
</div>
  </div>
</div>
			</div>
			</div>
		</div>
		<!--expertcoach-->
		<div class="container-fluid" style="padding:0px;">
		<div class="meetexpert">
			<div class="container">
		<div class="boxone">
			<h2>Meet our Expert Coach-<br>
				<b style="color:#fff;">Junior Anand Gupta</b></h2>
		
		<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p>
			
			</div>
			<img src="<?php echo $this->getSkinUrl('images/businessman.webp') ?>"/>
		</div>
		</div>
		</div>
		<!--video-->
		<div class="container-fluid" style="padding:0px;">
		<div class="videobox">
			<div class="container">
			<div class="boxone">
				<img src="<?php echo $this->getSkinUrl('images/monika.png') ?>"/>
			</div>
			<div class="boxone">
			<small>user impact Stories</small>
				<h3>With LifeHeal Monika lost 16 Kg
in just 3 months before marriage</h3>
				<p><b>Monika singh</b>, 26 Years, Student, New Delhi</p>
				<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.</p>
				<img src="<?php echo $this->getSkinUrl('images/video1.png') ?>" style="width:49%;"/>
				<img src="<?php echo $this->getSkinUrl('images/video2.png') ?>" style="width:49%;"/>
				<p style="margin: 20px auto;"><b>Create your impact story with LifeHeal</b> <a href="https://www.davidsonsilva.com.br?utm_source=codepen" style="background:#0EB58F;margin: -10px 5px;float: right;" target="_blank" class="mealplanbtn">Choose Meal Plan</a></p>
			</div>
			</div>
		</div>
		</div>
		<!--whychoose-->
		<div class="container-fluid" style="padding:0px;">
		<div class="whychoose">
			<div class="container">
			<h2>Why Choose Us</h2>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p>
			<div class="divideinthree">
			<center><img src="<?php echo $this->getSkinUrl('images/Path52@4X.png') ?>"/></center>
				<h4>Reason One</h4>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit</p>
			</div>
			<div class="divideinthree">
			<center><img src="<?php echo $this->getSkinUrl('images/Path56@4X.png') ?>"/></center>
				<h4>Reason One</h4>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit</p>
			</div>
			<div class="divideinthree">
			<center><img src="<?php echo $this->getSkinUrl('images/Group64@4X.png') ?>"/></center>
				<h4>Reason One</h4>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit</p>
			</div>
		</div>
		</div>
		</div>
		<!--rabk-->
		<div class="container-fluid" style="padding:0px;">
		<div class="rank">
			<div class="container">
			<div class="rankbox">
			<h2>5K+</h2>
			<p>Happy<br>
LifeHealers</p>
			</div>
			<div class="rankbox">
			<h2>8K+</h2>
			<p>Meal Plans<br>
Served</p>
			</div>
			<div class="rankbox">
			<h2>1200</h2>
			<p>Food<br>
Suscribers</p>
			</div>
			<div class="rankbox">
			<h2>834</h2>
			<p>Lorem<br>
Ipsum dolor</p>
			</div>
			</div>
		</div>
		</div>
		<!--testimonial for lifeheal-->
		<div class="container-fluid" style="padding:0px;">
		<div class="customervideo">
		<div class="container">
			<h2>Testimonials for Lifeheal</h2>
			<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/video1.png') ?>" style="width:100%;" class="image"/>
			</div>
			<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/video1.png') ?>" style="width:100%;" class="image"/>
			</div>
			<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/video1.png') ?>" style="width:100%;" class="image"/>
			</div>
			<div class="containerslideup">
  <img src="<?php echo $this->getSkinUrl('images/video1.png') ?>" style="width:100%;" class="image"/>
			</div>
			
		
		</div>
			</div>
		</div>
		<!--keepushappy-->
		<div class="container-fluid" style="padding:0px;">
		<div class="keepushappy">
		<div class="container">
		<div class="boxkeepblue">
			<img src="<?php echo $this->getSkinUrl('images/Path1@3X.png') ?>"/>
		
			<span>LifeHeal Keeps you one step ahead in life
with healthy meal plans</span>
			</div>
		
		<div class="formbox">
		<div class="formimg"><img src="<?php echo $this->getSkinUrl('images/13-SM903720-1@3X.png') ?>"/></div>
		<div class="startform">
			<h4>Have any question/feedback?</h4>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak</p>
			<div class="containerform">
  <form action="/action_page.php">
  <div class="group-inline">

    <input type="text" id="fname" name="firstname" placeholder="Your Name">
</div>
<div class="group-inline">
  
    <input type="text" id="lname" name="email" placeholder="Email">
</div>


    <textarea id="subject" name="subject" placeholder="Your Message" style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>
			</div>			
			</div>
			</div>
			</div>
		</div>
<!--wrap-->
</div>
		<script>
		const next = document.querySelector(".next");
const prev = document.querySelector(".previous");
const slides = document.querySelectorAll(".slide");

let index = 0;
display(index);

function display(index) {
  slides.forEach((slide) => {
    slide.style.display = "none";
  });
  slides[index].style.display = "flex";
}

function nextSlide() {
  index++;
  if (index > slides.length - 1) {
    index = 0;
  }
  display(index);
}

function prevSlide() {
  index--;
  if (index < 0) {
    index = slides.length - 1;
  }
  display(index);
}

next.addEventListener("click", nextSlide);
prev.addEventListener("click", prevSlide);
	(function($) {
    var size;
	
		//SMALLER HEADER WHEN SCROLL PAGE
    function smallerMenu() {
        var sc = $(window).scrollTop();
        if (sc > 40) {
            $('#header-sroll').addClass('small');
        }else {
            $('#header-sroll').removeClass('small');
        }
	};

    // VERIFY WINDOW SIZE
    function windowSize() {
        size = $(document).width();
        if (size >= 991) {
            $('body').removeClass('open-menu');
            $('.hamburger-menu .bar').removeClass('animate');
        }
    };

     // ESC BUTTON ACTION
    $(document).keyup(function(e) {
        if (e.keyCode == 27) {
            $('.bar').removeClass('animate');
            $('body').removeClass('open-menu');
            $('header .desk-menu .menu-container .menu .menu-item-has-children a ul').each(function( index ) {
                $(this).removeClass('open-sub');
            });
        }
    });

    $('#cd-primary-nav > li').hover(function() {
        $whidt_item = $(this).width();
        $whidt_item = $whidt_item-8;

        $prevEl = $(this).prev('li');
        $preWidth = $(this).prev('li').width();
        var pos = $(this).position();
        pos = pos.left+4;
        $('header .desk-menu .menu-container .menu>li.line').css({
            width:  $whidt_item,
            left: pos,
            opacity: 1
        });
    });

     // ANIMATE HAMBURGER MENU
    $('.hamburger-menu').on('click', function() {
        $('.hamburger-menu .bar').toggleClass('animate');
        if($('body').hasClass('open-menu')){
            $('body').removeClass('open-menu');
        }else{
            $('body').toggleClass('open-menu');
        }
    });

    $('header .desk-menu .menu-container .menu .menu-item-has-children ul').each(function(index) {
        $(this).append('<li class="back"><a href="#">Voltar</a></li>');
    });

    // RESPONSIVE MENU NAVIGATION
    $('header .desk-menu .menu-container .menu .menu-item-has-children > a').on('click', function(e) {
        e.preventDefault();
        if(size <= 991){
            $(this).next('ul').addClass('open-sub');
        }
    });

    // CLICK FUNCTION BACK MENU RESPONSIVE
    $('header .desk-menu .menu-container .menu .menu-item-has-children ul .back').on('click', function(e) {
        e.preventDefault();
        $(this).parent('ul').removeClass('open-sub');
    });

    $('body .over-menu').on('click', function() {
        $('body').removeClass('open-menu');
        $('.bar').removeClass('animate');
    });

    $(document).ready(function(){
        windowSize();
    });

    $(window).scroll(function(){
        smallerMenu();
    });

    $(window).resize(function(){
        windowSize();
    });

})(jQuery);
			
	</script>
	
<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
  var input, filter, ul, li, a, i;
  div = document.getElementById("myDropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>
