<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/liver_disease_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/liver_disease_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	
		        	<h1>Energize the powerhouse organ</h1>
					<p>Reverse liver disease and boost up your body with LifeHeal’s plans</p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- How it Works Start -->
	<style>
		.disease-single-how-it-works h2, .disease-single-how-it-works h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works disease-single-how-it-works">
		
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">Our plans reverse fatty liver by changing your insulin resistance through food & fasting. You will see fatty liver stages reverse from 3 to 2, or from 2 to 1. For those with ultrasound or FibroScans, you will visibly see the results. </p>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000"><span>Steps included in liver disease management</span></p>
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Body Analysis</h3>
					<p>Our experts analyze specific blood tests not commonly used in India to see where your liver health is headed. Where possible ultrasounds will be used to establish the baseline.  </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>Counselling</h3>
					<p>Your lifestyle and history are assessed, and the roots of your fatty liver will be discovered. We will explain what has brought you here.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Creating Your Plan</h3>
					<p>Your personal plan will use a 360<span>&deg;</span> approach to health. Besides food we also monitor sleep, stress, and eating patterns. We start simple, and then improve in all areas.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Personal Follow Up</h3>
					<p>Through our personal follow ups, we motivate and nudge you to make better food choices. We follow up on key items of our liver protocols. Weekly check-ups ensure you’re staying on track. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Inspect & Educate</h3>
					<p>As your health improves, we guide you through the next steps. We educate you on fatty liver causes, relation to obesity and more. This helps form habits which last a lifetime.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 6</h4>
					<h3>Medical Review</h3>
					<p>Periodically lab tests are conducted to see how the markers of your liver health are improving. These are always compared with your original tests. You will see your blood tests and ultrasounds improve.</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->	
	<!-- Meal Plans Start -->
	<style>
	
		.disease-single-meal-plans {
			background-color: #0EB58F;
		}
		
		.disease-single-meal-plans .single-meal-plans-title {
			color: #FFFFFF;
		}
		
	</style>
	<div class="single-meal-plans disease-single-meal-plans full-height">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>Fatty Liver Reduction Plans </h2>
				<p>At LifeHeal, we reverse fatty liver through food, nutrition, intermittent fasting, and more. Plans are customized based on severity and whether you have diabetes or not. The body has self-repair mechanisms, and we activate these processes. Through our plans, fasting blood sugar and liver enzyme levels will reduce. Anyone facing abdominal pain and swelling will notice improvements. Doctors will see changes in ultrasound and FibraScan results.</p>
			</div>
			
			<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Liver Recovery Plan</h3>
						<h2>Rs. 8,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2643)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Liver Recovery Plan</h3>
						<h2>Rs. 6,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2642)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Liver Recovery Plan</h3>
						<h2>Rs. 5,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2641)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Liver Recovery Plan</h3>
						<h2>Rs. 4,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2640)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Meal Plans End -->
	<!-- Impact Story Start -->
	<div class="impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
			<img src="<?php echo $this->getSkinUrl('images/impact-story-image.png') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL MONIKA LOST 16 KG IN JUST 3 MONTHS BEFORE MARRIAGE</h2>
				<h3>Monika Singh, <span>A success story</span></h3>
				<p>Losing weight was tough for me. I weighed 70kg when I got engaged. I didn't want to wear an oversized lehenga for my wedding. Thankfully, LifeHeal came to my rescue. After religiously following the LifeHeal diet for 3 months, I lost around 20kg.</p>
				<div class="impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=hrB-_nIer88" data-youtube-id="hrB-_nIer88" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-1.png') ?>"/>
					</a>
					<a href="https://www.youtube.com/watch?v=dX3k_QDnzHE" data-youtube-id="dX3k_QDnzHE" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
						
					</a>
				</div>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->
	
	<!-- Stats Start -->
	<div class="stats">
		<div class="stats-container">
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
					
			
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	<!-- Stats End -->
	
	<!-- Testimonials Start -->
	<style>
		.disease-single-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
	<div class="testimonials disease-single-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHAT OUR USERS SAY ABOUT OUR MEAL PLANS</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>LifeHeal's fatty liver plan changed my life forever. My doctors were surprised to see my fasting sugar levels decrease to 89-110 from a soaring high 200. My PP levels also reduced to 110-125 from 300+, and my liver improved from a Grade II to a Grade I. My diabetes medicine was reduced to half with improvement in sugar levels, and my blood pressure medicines stopped altogether.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test3.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Ajeet Gupta, Fatty <br>Liver Grade II to Grade I</h3>
							<p>55 Years, Businessman, Delhi</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
					<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I was a little nervous and skeptical before starting my diet. I was afraid I'd have to give up my favorite foods. But surprisingly, the diet created by LifeHeal had all my favorite foods, of course, with delicious tweaks and modifications. The progress was simply tremendous. Within a few weeks, my blood sugar levels started coming down from 300+ to 150.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test9.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Shalini Mehta, Diabetes reduction</h3>
							<p>50 Years, Homemaker, kanpur</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>Coming from a hardcore non-vegetarian, foody family, it was challenging for me to adapt to healthy eating. With LifeHeal's guidance, I started doing intermittent fasting, and their meals gave me alternatives to my favorite foods. A task that once seemed impossible was achieved with the help of LifeHeal. Within 4 months, I was able to do a 32 hour fast and lost significant weight.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test15.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Ashish Dutta, Lost 17 kgs</h3>
							<p>31 Years, Working Professional, Delhi</p>
						</div>
					</div>
				</div>
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans. Additionally, we offer a 30% discount on your first order. </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
	
	
