<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<style>
.sticky-container{
  height:40px;
  position:relative;
}
.sticky-box{
  position: -webkit-sticky;
  position: sticky;
  /*the following is how far from the top of the screen you want your element to stick if you change it to 20px it will start to stick 20px from the top of the screen*/
  top: 0;
}
</style>
<!-- Top Navbar -->
<div class="container-fluid imgfood">
  <img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/foodmenu.jpg" alt="food menu" class="desktopbanner"/>
   <img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/CMD-Menu-Mobile-Banner.jpg" alt="food menu" class="mobbanner"/>
  <div class="calenderarea">
  <div class="calenderbox">Date:Sat, 09 march</div>
  <div class="pureveg">Order 24 Hours in Advance</div>
  <div class="result">100% Results</div>
  </div>
  </div>
<section class="container" style="padding: 0;float: left;">
  <section class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        
        <div class="panel-body">
<div role="tabpanel" id="myScrollspy">

  <!-- Nav tabs -->
<!--  <nav id="navbar-example" class="navbar navbar-light bg-faded">
--> <ul class="tabs">
 <h4 style="font-size: 16px;text-transform: uppercase;color: #000; margin:0px;"><u>Weekly Food Menu</u></h4>

  <li class="nav-item active" rel="tab1"><a class="nav-link" aria-controls="item1" role="tab" data-toggle="tab" href="#item1">Wed 13, March</a></li>
                    <li class="nav-item" rel="tab2">
                        <a class="nav-link" href="#item2" aria-controls="item2" role="tab" data-toggle="tab">Thur 14, March</a>
                         <!--<ul class="nav flex-sm-column small ml-md-3 ml-1 hidden-sm-down">
                            <li class="nav-item"><a class="nav-link" href="#item2a">Wed 13, March</a></li>
                            <li class="nav-item"><a class="nav-link" href="#item2b">Two b</a></li>
                            <li class="nav-item"><a class="nav-link" href="#item2c">Two c</a></li>
                        </ul>-->
                    </li>
                    <li class="nav-item" rel="tab3"><a class="nav-link" aria-controls="item3" role="tab" data-toggle="tab" href="#item3">Fri 15, March</a></li>
                     <li class="nav-item" rel="tab4"><a class="nav-link" aria-controls="item4" role="tab" data-toggle="tab" href="#item4">Sat 16, March</a></li>
                      <li class="nav-item" rel="tab5"><a class="nav-link" aria-controls="item5" role="tab" data-toggle="tab" href="#item5">Sun 17, March</a></li>
                      
                </ul>
            <!--</nav>-->
  

 <div class="tab_container">
 <div class="sticky-container">
  <h3 class="d_active tab_drawer_heading sticky-box" rel="tab1">Wed 13, March</h3>
  </div>
  <div id="tab1" class="tab_content scrollspy-example info" data-spy="scroll" data-target="#navbar-example" data-offset="0">
   <h4 style="font-size: 16px;color: #000;">Breakfast</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Rolled oats poha<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Kefir With Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chickpea & Vegetable Omlette<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   </div>
               </div>
              <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               
               
               <h4 style="font-size: 16px;color: #000;">Lunch</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Lauki Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Sabji<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chilke Wali Dal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Salad Of The Day<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Probiotic<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Big Salad Bowl<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Cookie<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
               
               <br/>
                  <h4 style="font-size: 16px;color: #000;">High Tea</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Spinach Hummus<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Vegetable Sticks<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mixed Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
              
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Almond Milk<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               <h4 style="font-size: 16px;color: #000;">Dinner</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mix Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mung Daal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Bajra Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Grilled Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Health Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Fruit Cream<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Homemade Pasta With Arrabiata Sauce<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Minestrone Soup<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
              
               <br/>
                <div class="preference"><h4 style="font-size: 16px;color: #000;">Preference</h4>
    <p class="col-xs-6 col-sm-6"><small>Extra Instructions</small></p><p class="col-xs-6 col-sm-6 p2"><small>List any special requests</small></p>
    <textarea rows="4" cols="50" class="input-text"></textarea><br/>
    
     <button type="button" class="button submit" onClick="callController()"><span>Submit</span></button> 
           
             </div>
  </div>

  <!-- #tab1 -->
  
 <div class="sticky-container">
  
   <h3 class="tab_drawer_heading sticky-box" rel="tab2">Thur 14, March</h3>
   </div>
  <div id="tab2"  class="tab_content scrollspy-example info"  data-spy="scroll" data-target="#navbar-example" data-offset="0">
 <h4 style="font-size: 16px;color: #000;">Breakfast</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Rolled oats poha<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Kefir With Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chickpea & Vegetable Omlette<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   </div>
               </div>
              <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               
               
               <h4 style="font-size: 16px;color: #000;">Lunch</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Lauki Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Sabji<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chilke Wali Dal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Salad Of The Day<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Probiotic<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Big Salad Bowl<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Cookie<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
               
               <br/>
                  <h4 style="font-size: 16px;color: #000;">High Tea</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Spinach Hummus<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Vegetable Sticks<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mixed Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
              
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Almond Milk<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               <h4 style="font-size: 16px;color: #000;">Dinner</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mix Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mung Daal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Bajra Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Grilled Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Health Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Fruit Cream<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Homemade Pasta With Arrabiata Sauce<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Minestrone Soup<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
              
               <br/>
                <div class="preference"><h4 style="font-size: 16px;color: #000;">Preference</h4>
    <p class="col-xs-6 col-sm-6"><small>Extra Instructions</small></p><p class="col-xs-6 col-sm-6 p2"><small>List any special requests</small></p>
    <textarea rows="4" cols="50" class="input-text"></textarea><br/>
    
     <button type="button" class="button submit"><span>Submit</span></button> 
           
             </div>
  </div>
  
  <!-- #tab2 -->
  <div class="sticky-container">
  <h3 class="tab_drawer_heading sticky-box" rel="tab3">Fri 15, March</h3>
  </div>
  <div id="tab3"  class="tab_content scrollspy-example info"  data-spy="scroll" data-target="#navbar-example" data-offset="0">
  <h4 style="font-size: 16px;color: #000;">Breakfast</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Rolled oats poha<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Kefir With Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chickpea & Vegetable Omlette<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   </div>
               </div>
              <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               
               
               <h4 style="font-size: 16px;color: #000;">Lunch</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Lauki Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Sabji<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chilke Wali Dal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Salad Of The Day<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Probiotic<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Big Salad Bowl<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Cookie<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
               
               <br/>
                  <h4 style="font-size: 16px;color: #000;">High Tea</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Spinach Hummus<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Vegetable Sticks<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mixed Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
              
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Almond Milk<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               <h4 style="font-size: 16px;color: #000;">Dinner</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mix Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mung Daal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Bajra Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Grilled Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Health Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Fruit Cream<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Homemade Pasta With Arrabiata Sauce<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Minestrone Soup<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
              
               <br/>
                <div class="preference"><h4 style="font-size: 16px;color: #000;">Preference</h4>
    <p class="col-xs-6 col-sm-6"><small>Extra Instructions</small></p><p class="col-xs-6 col-sm-6 p2"><small>List any special requests</small></p>
    <textarea rows="4" cols="50" class="input-text"></textarea><br/>
    
     <button type="button" class="button submit"><span>Submit</span></button> 
           
             </div>
  </div>

  <!-- #tab3 -->
 <div class="sticky-container">
  <h3 class="tab_drawer_heading sticky-box" rel="tab4">Sat 16, March</h3>
  </div>
  <div id="tab4"  class="tab_content scrollspy-example info"  data-spy="scroll" data-target="#navbar-example" data-offset="0">
 <h4 style="font-size: 16px;color: #000;">Breakfast</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Rolled oats poha<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Kefir With Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chickpea & Vegetable Omlette<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   </div>
               </div>
              <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               
               
               <h4 style="font-size: 16px;color: #000;">Lunch</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Lauki Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Sabji<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chilke Wali Dal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Salad Of The Day<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Probiotic<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Big Salad Bowl<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Cookie<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
               
               <br/>
                  <h4 style="font-size: 16px;color: #000;">High Tea</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Spinach Hummus<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Vegetable Sticks<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mixed Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
              
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Almond Milk<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               <h4 style="font-size: 16px;color: #000;">Dinner</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mix Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mung Daal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Bajra Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Grilled Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Health Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Fruit Cream<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Homemade Pasta With Arrabiata Sauce<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Minestrone Soup<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
              
               <br/>
                <div class="preference"><h4 style="font-size: 16px;color: #000;">Preference</h4>
    <p class="col-xs-6 col-sm-6"><small>Extra Instructions</small></p><p class="col-xs-6 col-sm-6 p2"><small>List any special requests</small></p>
    <textarea rows="4" cols="50" class="input-text"></textarea><br/>
    
     <button type="button" class="button submit"><span>Submit</span></button> 
           
             </div>
  </div>
  
  <!-- #tab4 --> 
  
 <div class="sticky-container">
  <h3 class="tab_drawer_heading sticky-box" rel="tab5">Sun 17, March</h3>
  </div>
  <div id="tab5"  class="tab_content scrollspy-example info"  data-spy="scroll" data-target="#navbar-example" data-offset="0">
 <h4 style="font-size: 16px;color: #000;">Breakfast</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Rolled oats poha<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Kefir With Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chickpea & Vegetable Omlette<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   </div>
               </div>
              <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               
               
               <h4 style="font-size: 16px;color: #000;">Lunch</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Lauki Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>

    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Sabji<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Chilke Wali Dal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Salad Of The Day<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Probiotic<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Karela Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Big Salad Bowl<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Cookie<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
               
               <br/>
                  <h4 style="font-size: 16px;color: #000;">High Tea</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Spinach Hummus<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Vegetable Sticks<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mixed Nuts<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
              
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Almond Milk<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>
               <br/>
               <h4 style="font-size: 16px;color: #000;">Dinner</h4>
                <p><span>1 Item</span></p>
    <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mix Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
      <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Mung Daal<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
    </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
                
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Bajra Roti<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Grilled Vegetable<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Health Shot<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Fruit Cream<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Homemade Pasta With Arrabiata Sauce<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
               
               
                <div class="col-xs-12 col-sm-6 itemmenubox"><div class="itemone" itemscope="">
   
    <span class="icon-foodSymbol food-red food-adjust food-green"><img src="http://cure.americanarearugs.com/skin/frontend/rwd/default/images/vegicon.jpg" alt=""></span>
    <div class="GaqmA"><div>
    
    <div class="btnright">
  <input type="checkbox" name="food">
</div> 
 
    
    <div class="itembox">
    <div class="itemname">
    <div class="itemproperty" itemprop="name">Minestrone Soup<br/>
    <small>Crunchy, deep-fried vada soaked in spicy sambhar.</small>
  </div>
    </div>
    </div>
   
   </div>
   
    </div>
</div>
               </div>
            <p class="hrline"><small>Note: Condiments come standard (Beetroot chutney, Chatpata tomato & onion)</small></p>  
              
               <br/>
                <div class="preference"><h4 style="font-size: 16px;color: #000;">Preference</h4>
    <p class="col-xs-6 col-sm-6"><small>Extra Instructions</small></p><p class="col-xs-6 col-sm-6 p2"><small>List any special requests</small></p>
    <textarea rows="4" cols="50" class="input-text"></textarea><br/>
    
     <button type="button" class="button submit"><span>Submit</span></button> 
           
             </div>
  </div>
  
  <!--tab5-->
</div>
<!-- .tab_container -->
</div>
</div>
</div>
</div>
</section>
</section>


<script>
 // tabbed content
    // http://www.entheosweb.com/tutorials/css/tabs.asp
    jQuery(".tab_content").hide();
    jQuery(".tab_content:first").show();

  /* if in tab mode */
    jQuery("ul.tabs li").click(function() {
		
      jQuery(".tab_content").hide();
      var activeTab = jQuery(this).attr("rel"); 
      jQuery("#"+activeTab).fadeIn();		
		
      jQuery("ul.tabs li").removeClass("active");
      jQuery(this).addClass("active");

	  jQuery(".tab_drawer_heading").removeClass("d_active");
	  jQuery(".tab_drawer_heading[rel^='"+activeTab+"']").addClass("d_active");
	  
    });
	/* if in drawer mode */
	jQuery(".tab_drawer_heading").click(function() {
      
      jQuery(".tab_content").hide();
      var d_activeTab = jQuery(this).attr("rel"); 
      jQuery("#"+d_activeTab).fadeIn();
	  
	  jQuery(".tab_drawer_heading").removeClass("d_active");
      jQuery(this).addClass("d_active");
	  
	  jQuery("ul.tabs li").removeClass("active");
	  jQuery("ul.tabs li[rel^='"+d_activeTab+"']").addClass("active");
    });
	
	
	/* Extra class "tab_last" 
	   to add border to right side
	   of last tab */
	jQuery('ul.tabs li').last().addClass("tab_last");
  function callController(){
    jQuery.ajax({
      url: "<?php echo Mage::getBaseUrl().'heal/index/menuorder' ?>",
      type: "POST",
      data: {Name: 'Sant Yadav'},
      success: function(response){
          console.log(response);
      }
    });
  }
	
</script>
<script>
var stickyElements = document.getElementsByClassName('sticky-box');

for (var i = stickyElements.length - 1; i >= 0; i--) {
    Stickyfill.add(stickyElements[i]);
}
</script>
