<!-- Hero Banner Start -->
	<div class="hero">
		
		<style>
			.disease-single {
				background-image: url('<?php echo $this->getSkinUrl("images/pre_wedding_web.png")?>');
			}
			
			@media only screen and (max-width: 768px) {
				.disease-single {
					background-image: url('<?php echo $this->getSkinUrl("images/pre_wedding_mobile.png")?>');
				}	
			}
			
			.disease-single h1 {
				color: #FFFFFF;
			} 
		</style>
	    
	    <!-- Banner -->
	    <div class="hero-banner disease-single">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1>Eat wise, drop a size!</h1>
		        	<p>Look flawless on your big day, with LifeHeal’s holistic plans.</p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	
	<!-- How it Works Start -->
	<style>
		.disease-single-how-it-works h2, .disease-single-how-it-works h3 {
			color: #0EB58F;
		} 
	</style>
	<div class="how-it-works disease-single-how-it-works">
		
		<div class="how-it-works-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">HOW IT WORKS</h2>
			<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">You decide the speed and weight and we make the plan for you. Look right on your wedding day. </p>
			<!--<p data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000"><span>Steps included in weight management</span></p>-->
			
			<div class="how-it-works-detail-wrapper">
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-1.png') ?>"/>
					<h4>STEP 1</h4>
					<h3>Deep Dive</h3>
					<p>You get a computerized analysis of your weight factors using our A.I. tool. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-2.png') ?>"/>
					<h4>STEP 2</h4>
					<h3>Customizing</h3>
					<p>Your plan is built around you using your inputs, goals and current capacity. </p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-3.png') ?>"/>
					<h4>STEP 3</h4>
					<h3>Start</h3>
					<p>You get positive changes in energy, mood and biomarkers.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-4.png') ?>"/>
					<h4>STEP 4</h4>
					<h3>Support</h3>
					<p>Most failures happen in the mind. We give a plan and support you through it.</p>
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-5.png') ?>"/>
					<h4>STEP 5</h4>
					<h3>Track & Guide</h3>
					<p>You are skillfully guided to your next steps. We track over 65 biomarkers.</p>					
				</div>
				
				<!-- Details -->
				<div class="how-it-works-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					 <img src="<?php echo $this->getSkinUrl('images/disease-single-how-it-works-6.png') ?>"/>
					<h4>STEP 6</h4>					
					<h3>Success</h3>
					<p>You achieve your target weight within your time limit.</p>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- How it Works End -->
	
	<!-- Meal Plans Start -->
	<style>
	
		.disease-single-meal-plans {
			background-color: #0EB58F;
		}
		
		.disease-single-meal-plans .single-meal-plans-title {
			color: #FFFFFF;
		}
		
	</style>
	<div class="single-meal-plans disease-single-meal-plans full-height">
		<div class="single-meal-plans-container">
			
			<div class="single-meal-plans-title" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>Pre-Marriage Plans </h2>
				<p>At LifeHeal, we understand that fitting into the perfect lehnga for your big day can be taxing. Our plans take a holistic approach by placing equal emphasis on proper nutrition and a healthy lifestyle. This helps you keep your weight at bay, even post wedding. Our plans never compromise with your glow. We help you lose weight, without loosing your glow & charm. </p>
			</div>
			
			<div class="single-meal-plans-wrapper expanded" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						 <img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-1.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>1 Month Pre-Wedding Glow Diet Plan</h3>
						<h2>
							<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
								<span style="font-size: 18px; color: #fff;">Rs. 8,000/month </span> 
							</s>
						</h2>
						<h2 class="offer">Rs. 4,000/month  </h2>
					
						<a href="javascript:void"  onclick="addItemToCart(2667)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-2.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>3 Months Pre-Wedding Glow Diet Plan</h3>
						<h2>
							<s style="color:#e1340d; text-decoration-thickness: 3px;"> 
								<span style="font-size: 18px; color: #fff;">Rs. 3,000/month </span> 
							</s>
						</h2>
						<h2 class="offer">Rs. 6,000/month  </h2>
						
						<a href="javascript:void"   onclick="addItemToCart(2666)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-3.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>6 Months Pre-Wedding Glow Diet Plan</h3>
						<h2>&nbsp;</h2>
						<h2>Rs. 5,000/month</h2>
						<a href="javascript:void"  onclick="addItemToCart(2665)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
				<!-- Plan Details -->
				<div class="single-meal-plans-detail">
					<div class="single-meal-plans-detail-image">
						<img src="<?php echo $this->getSkinUrl('images/single-meal-plans-detail-image-4.png') ?>"/>
					</div>
					<div class="single-meal-plans-detail-text">
						<h3>12 Months Pre-Wedding Glow Diet Plan</h3>
						<h2>&nbsp;</h2>
						<h2>Rs. 4,000/month</h2>
						<a href="javascript:void"   onclick="addItemToCart(2664)" class="button cta-single-meal-plans-detail-text">Choose this Meal Plan</a>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<!-- Meal Plans End -->
	
	<!-- Impact Story Start -->
	<div class="impact-story">
		<div class="impact-story-container">
			
			<div class="impact-story-image" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
			<img src="<?php echo $this->getSkinUrl('images/jasmeet-testimonials.jpg') ?>"/>
			</div>
			<div class="impact-story-detail" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
				<h4>USER IMPACT STORY</h4>
				<h2>WITH LIFEHEAL JASMEET LOST 6 KGS IN ONE MONTH AND SAW IMPROVEMENT IN HER SKIN</h2>
				<h3>Jasmeet Kaur, 27 Years, Manager, <span> Delhi</span></h3>
				 
				<p>I was detected with PCOD when I was 15. I tried everything at my disposal, from homeopathic to allopathic, which affected my social life a lot and only improved my symptoms for short-term With advise from qualified nutritionists at LifeHeal, I started balancing my meals while maintaining my social life and regular workouts, which not only helped me loose 6kgs in a month but my cycle became regular and my facial hair started reducing making me feel even more pretier.</p>
				<div class="impact-story-detail-videos">
					<a href="https://www.youtube.com/watch?v=FytMIDrmnLM" data-youtube-id="FytMIDrmnLM" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-1.png') ?>"/>
					</a>
					<a href="https://www.youtube.com/watch?v=tnrTY9sIlBo" data-youtube-id="tnrTY9sIlBo" class="video-thumb js-trigger-video-modal">
						<img src="<?php echo $this->getSkinUrl('images/impact-story-detail-video-2.png') ?>"/>
						
					</a>
				</div>
			</div>
			
		</div>
	</div>
	<!-- Impact Story End -->

	<style>
		.impact-story-detail-videos{
			display: none;
		}
	</style>
	
	<!-- Stats Start -->
	<div class="stats">
		<div class="stats-container">
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">2</span>K+</h2>
				<p>Happy <br>LifeHealers</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">98</span>%</h2>
				<p>Customer <br>Satisfaction</p>
			</div>
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">50</span>K+</h2>
				<p>Meal <br>Served</p>
			</div>
					
			
			<!-- Stats -->
			<div class="stats-detail">
				<h2><span class="stats-counter">100</span>%</h2>
				<p>Goal <br>Oriented</p>
			</div>
		</div>
	</div>
	<!-- Stats End -->
	
	<!-- Testimonials Start -->
	<style>
		.disease-single-testimonials h2 {
		    color: #0EB58F    
		}
	</style>
<div class="testimonials disease-single-testimonials">
		
		<div class="testimonials-container">
			<h4 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">TESTIMONIALS</h2>
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">WHAT OUR USERS SAY ABOUT OUR MEAL PLANS</h2>
			
			<div class="testimonials-detail-wrapper">
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>I'm a big-time emotional eater, slightest of stress, and I run towards food. This eventually started affecting my health and weight. I decided to join LifeHeal and haven't looked back since then. Their weekly check-ups ensure I'm staying on track and not reaching for that ice-cream pint after an emotional turmoil. I was able to lose 8kgs within a month without starving. My cravings have reduced now and my stomach feels much lighter.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test2.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Rajat Arora, Lost 8 kgs By<br/> Reducing Inflammation In Gut</h3>
							<p>25 Years, Student, Lucknow</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>LifeHeal's plans go beyond weight. With their holistic approach and personal motivation, I started losing fat around my belly. I was surprised when I realized that I was becoming stronger, even on a vegan diet. I could feel the difference while lifting weights at the gym.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test8.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Vishu Sehgal, Lost 4 inches</h3>
							<p>26 Years, Student, Mumbai</p>
						</div>
					</div>
				</div>
				
				<!-- Details -->
				<div class="testimonials-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
					<p>As a fitness geek, my focus was on having a protein-loaded diet. I practically lived on protein powder until I was introduced to LifeHeal. I learned you could increase your endurance by adding variety to your meals and having a well-balanced diet. My fat % reduced from 22 to 17 and without compromising my muscle mass.</p>
					<div class="testimonials-detail-profile">
						<div class="testimonials-detail-profile-photo" style="background-image: url('<?php echo $this->getSkinUrl("images/test11.png")?>')">
						</div>
						<div class="testimonials-detail-profile-detail">
							<h3>Jatin Bhatia, Gained muscle mass</h3>
							<p>36 Years, Athlete, Haryana</p>
						</div>
					</div>
				</div>
				
				
			</div>
			
		</div>
		
	</div>
	<!-- Testimonials End -->
	
	<!-- FAQ Start -->
	<div class="faq">
		<div class="faq-container">
			<h2>FREQUENTLY ASKED QUESTIONS</h2>
			<div class="accordion-wrapper">
				
				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Will I be hungry with LifeHeal meal plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				      <p>Our experts have created a well-balanced meal plan to ensure that you never stay hungry and reach out for those chips. Our diet plan includes 5 small meals with loads of fresh fruits and healthy snacks to keep your hunger at bay. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do I have to pay extra for counseling sessions? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>Based on your meal subscription, we provide a weekly check-in with a Dietician to ensure you are on track. In case you need further help, we also have additional prepaid 1-1 coaching sessions. Check them out here. </p>
				    </div>
  				</div>
  				<!-- Accordion -->
				<div class="accordion">
				    <div class="accordion-header"><h4>Do you offer trial plans? </h4><i class="fas fa-chevron-down"></i></div>
				    <div class="accordion-content">
				       <p>We don't offer trial plans since we are a meal subscription. But you can delay meal plans 3 weeks in advance for impromptu meal plans. Additionally, we offer a 30% discount on your first order. </p>
				    </div>
  				</div>
  				
			</div>
		</div>
	</div>
	<!-- FAQ End -->
	
	<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->


	<!-- Floating CTA Start -->
	<div style="min-height: 76px; background-color: #144F5A">
		<div class="floating-cta">
			<div class="floating-cta-container">
				<h2>Book a 1-on-1 consultation with our Certified experts</h2>
				<a class="button cta-button" href="<?php echo $this->getUrl('startnow') ?>">
					FIRST CALL ONLY RS. 200
				</a>
			</div>
		</div>
	</div>
	<!-- Floating CTA End -->
	
	