<section>
<div class="container">
<div class="banner bandiabetes">
  <img src="<?php echo $this->getSkinUrl('images/HT-Diabetes-1280x640.jpg') ?>"  alt="Diabetes">
</div>
</div>
</section>
<section class="padd-10">
        <div class="container">
            <div class="sec-start-head">
              Starting The Diabetes Reversal Program Is Easy. 
             <!-- <b>Convenience is the Cure My Diabetes Goal</b>-->
            </div>
            <div class="easyway">
            <p>The whole Cure My Diabetes concept started with 2 simple problems to fix :</p>
           
            <ul style="border-bottom:0px;">
            <li><b>No one has time</b> to go to any diabetes center for 30 days, or even go to a location within your own city.
            People need food delivered to them if they will have any luck completing 30 - 60 day meal plan.
            </li>
            <li>
           <b> It is very hard</b> to prepare 4 meals a day that is cutting edge science, specially if you have kids in the
            house and need to make normal food for them too.
            </li>
            </ul>
            </div>
            </div>
            </section>
             <div class="container">
            <section class="sec-solution">
             <div class="container-fluid">
             <div class="oursolution">
             <h4>Our Solution :</h4>
             <ul>
             <li>
             <strong>Focus on helping the client succeed. What is their body weight, how much medicine are they taking, 
             what is their weight and then customize the food to&nbsp;<em>their</em>&nbsp;needs.&nbsp;</strong></li>
             <li>We will deliver a customized 30 day meal plan to you including lunch, high tea and dinner, plus snacks in case your sugar goes low.
             </li>
             <li>We will deliver juices and vegetable boosters your body needs to recover.</li>
             <li>We will deliver amazingly tasty salads that you know you should eat but have a hard time getting along with your food.</li>
             <li>We will deliver super healthy yet tasty home cooked meals because we are upscale and quality and taste is the most important thing to us.</li>
             <li>We are expensive so we don't have to think twice in giving you the best of ingredients and the most ornate of food preparations.</li>
             </ul>
             <span>See:&nbsp;<a href="menu.html" target="_blank" style="color: #a61d3f;">MENU EXAMPLE</a></span>
             <p>SIGN UP NOW. Call 9999-84-6622</p>
             </div>
             </div>
            </section>
            </div>
            <section class="padd-10">
        <div class="container">
          <div class="easyway" style="border-top: 2px solid rgba(0,0,0,0.1);">
         <p style="margin-top:20px;"> Below Is a Link to two articles that explains some of the basics of our nutrition approach.</p>
<ul style="border:0px;" class="articlesec">
<li><a href="http://www.curemydiabetes.com/blog/the-basic-concept" target="_blank" style="color: #a61d3f; text-decoration:underline;">-&nbsp;The Basic Concept Of Achieving Better Health</a></li>
<li><a href="http://www.curemydiabetes.com/blog/eat-as-much-as-you-want-and-not-get-fat" target="_blank" style="color: #a61d3f; text-decoration:underline;">-&nbsp;Eat as much as you want and not get fat.</a></li>
</ul>
            </div>
            </div>
            </section>