<?php @ob_start();
if(isset($_POST['submit'])){	
	//echo '<pre>';
	//print_r($_POST); 
	//die; 
	$fields="";
	$values="";
	$size= sizeof($_POST);
	
	$config  = Mage::getConfig()->getResourceConnectionConfig("default_setup");
	$dbinfo = array("host" => $config->host,"user" => $config->username,"pass" => $config->password,"dbname" => $config->dbname);
  
  	$host      = $dbinfo["host"];
  	$username  = $dbinfo["user"];
  	$password  = $dbinfo["pass"];
  	$dbname    = $dbinfo["dbname"]; 
  
  	$con = mysqli_connect($host, $username,  $password ,$dbname);

  if ($mysqli -> connect_errno) {
  	echo "Failed to connect to MySQL: " . $mysqli -> connect_error;
  	exit();
	}     

    $count=0;
	$formData='';
	foreach($_POST as $key=>$value)	{
		$count++;
		if($key!='submit')	{
			//$key= str_replace("-","_",$key);
			$fields.=$key;
			$values.="'".trim(htmlentities($value,ENT_QUOTES))."'";
			
			$formData.= $key.'=>'.trim(htmlentities($value,ENT_QUOTES));
			$formData.='<br>';
			
			if($count<($size-1) ) {
				$fields.=',';   		
			    $values.=','; 
			 }			
		}		
	}
	
	$custId = $_POST['custid'];
	$customer = Mage::getModel('customer/customer')->load($custId);
	$customerName = str_ireplace("Dear","",$customer->getFirstname())." ".$customer->getLastname();
	$mobileNo = $_POST['mobileno'];
	$date = date('Y-m-d');
	$param = $_POST['param'];
	
	 $checkQuery = "select * from patientintakeform where custid='".$custId."' and mobileno='".$mobileNo."' and date='".$date."'";
	$checkRowResult = mysqli_query($con,$checkQuery);
	 $countExisting = mysqli_num_rows($checkRowResult); 
	$last_id ='';
	
	
	           $to ="st.homespice@gmail.com,ajeetdesign@gmail.com,jasmine.chanana@lifeheal.in";
				$from ="team@lifeheal.in";

				   // Always set content-type when sending HTML email
				$headers = "MIME-Version: 1.0" . "\r\n";
				$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

				// More headers
				$headers .= "From: ".$from . "\r\n";
				$subject = "Patientintake Form Filled Data Of ".$customerName." (".$mobileNo.") on ".date('d-m-Y');
				//$message="Hi, a new customer ".$customerName." (".$mobileNo.") filled patientintake form on ".date("d-m-Y");
				$message = $formData;
				mail($to,$subject,$message,$headers); 
	
	
	
	
	
	if($countExisting==0) {	
	
	$query="insert into patientintakeform(";
	$query.=$fields.") values(".$values.")";
	//echo $query;  die;	
          
          try
		  {		  
                mysqli_query($con, $query); 
				$last_insert_id = mysqli_insert_id($con);
				$last_id=base64_encode($last_insert_id);
				
				
				$to ="diet@lifeheal.in,st.homespice@gmail.com, nehabhale@gmail.com, yash.munot@gmail.com,junior@lifeheal.in,jasmine.chanana@lifeheal.in";
				$from ="team@lifeheal.in";

				   // Always set content-type when sending HTML email
				$headers = "MIME-Version: 1.0" . "\r\n";
				$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

				// More headers
				$headers .= "From: ".$from . "\r\n";
				$subject = "New Customer Registered through Patientintake Form";
				$message="Hi, a new customer ".$customerName." (".$mobileNo.") filled patientintake form on ".date("d-m-Y");
				mail($to,$subject,$message,$headers); 
				
			//	echo $query; 
            
		  }
		  catch(Exception $e) {
			   $errorMessage = $e->getMessage()."_".$query;
			  
			    $to ="st.homespice@gmail.com,ajeetdesign@gmail.com";
			   $from ="team@lifeheal.in";

				   // Always set content-type when sending HTML email
				$headers = "MIME-Version: 1.0" . "\r\n";
				$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

				// More headers
				$headers .= "From: ".$from . "\r\n";
				$subject = "Insert error of patientintake form ";
				$message="Insert Error Message Of Patientintakeform on ".date("d-m-Y")." <br><br> ".$errorMessage;
				mail($to,$subject,$message,$headers); 
			}
			
			//die;
	}
	else{
		
         $row   = '';
		 while ($rowInfo = mysqli_fetch_assoc($checkRowResult)) {
            
			 $row = $rowInfo;
         }
		 $last_id=base64_encode($row['patientid'] );
		 $count=0;
		 $updateFields='';
		 foreach($_POST as $key=>$value) {
			$count++;
			if($key!='submit')	{
				if($value!='')	{
					$updateFields.=$key."='".trim(htmlentities($value,ENT_QUOTES))."'";
					if($count<($size-1) )	{
						$updateFields.=',';   		
					}
				}
			}
		}
		if($updateFields!='')	{
		   $query="update patientintakeform ";
		   $query.="set ".$updateFields." where patientid=".$row['patientid'];
		   try
		   {
				   mysqli_query($con, $query);
				   
				   
				   $to ="diet@lifeheal.in,st.homespice@gmail.com, nehabhale@gmail.com, yash.munot@gmail.com,junior@lifeheal.in,jasmine.chanana@lifeheal.in";
					$from ="team@lifeheal.in";

					   // Always set content-type when sending HTML email
					$headers = "MIME-Version: 1.0" . "\r\n";
					$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

					// More headers
					$headers .= "From: ".$from . "\r\n";
					$subject = "New Customer Registered through Patientintake Form";
					$message="Hi, a new customer ".$customerName." (".$mobileNo.") filled patientintake form on ".date("d-m-Y");
					mail($to,$subject,$message,$headers); 
					
					//echo $query; 
			}
		    catch(Exception $e) {
			    $errorMessage = $e->getMessage()."_".$query;
			  
			    $to ="st.homespice@gmail.com,ajeetdesign@gmail.com";
			   $from ="team@lifeheal.in";

				   // Always set content-type when sending HTML email
				$headers = "MIME-Version: 1.0" . "\r\n";
				$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

				// More headers
				$headers .= "From: ".$from . "\r\n";
				$subject = "Update error of patientintake form ";
				$message="Update Error Message Of Patientintakeform on ".date("d-m-Y")." <br><br> ".$errorMessage;
				mail($to,$subject,$message,$headers); 
			  
			  
			}
	    }				
	}
	
	
	
	

	//die;
}
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<style>
body, html {
  height: 100%;
  margin: 0;
}
.main {
    width: 100%;
    margin-top: 5.5rem;
    height: 100%;
    background: #f5f5f5;
}
.anh-quote .h6{
	margin-top: 24px;
	font-size: 1em;
	font-weight:lighter;
	color: #000;
}
.anh-quote h3 {
   	font-size: 1.2em;
	font-weight: lighter;
	color: #000;
}
.anh-quote hr, .kris-quote hr {
    border-top: 5px solid #10cfc9;
    margin: 0 0 12px;
    width: 65px;border-bottom: 0;
    text-align: left;
}
.thankyou_container{
	width: 100%;
    max-width: 78.25rem;
    margin: 0 auto;
    padding: 2rem 3rem;
}
.bgimg {  
  font-size: 25px;
    width: 100%;
    min-height: 25rem;
    background: transparent linear-gradient(0deg, #144F5A 0%, #0EB58F 100%) 0% 0% no-repeat padding-box;
    border-radius: 0.5rem;
    position: relative;    
    padding: 4rem 3rem;
    text-align: center;
    color: #FFFFFF;
    margin: 30px auto;
}

.topcenter{
margin: auto;
width: 4rem;
float: none;
display: block;
}

.bottomleft {
    margin: 0 auto;   
    float: none;
    display: block;
    text-align: center;
}
.bottomleft a{
	   display: block;
    border: solid 2px #FFFFFF;
    background-color: transparent;
    color: #FFFFFF;
    width: 100%;
    max-width: 22rem;
    line-height: 3.2rem;
    border-radius: 1.6rem;
    margin: 0 auto;
    margin-top: 1rem;
    font-size: 1.2rem;
}
.middle {
  position: relative;   
  text-align: center;
}
.middle h1{
	text-transform: capitalize;
	color:#fff;
	font-size: 1.75rem;
    line-height: 1.25;
    padding-top: 2rem;
}
.middle p{
	color:#fff;
	font-size: 1.3rem;
    line-height: 1.5;
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
}
.middle p a{
	display: inline-block;
	color: #fff;
}
hr {
  margin: auto;
  width: 40%;
	}
@media screen and (min-width:640px) and (max-width:767px){
.logomob {
    width: 25% !important;
    float: right;
    margin-left: 0;
    margin-top: 0%;
}
.main {   
    margin-top: 4rem;  
}
.bgimg {  
    padding: 2rem; 
    min-height: 25rem;   
}
.thankyou_container{
	width: 100%;
    max-width: 100%;   
    padding: 2rem;
}

.anh-quote h3 {
    font-size:20px;
    font-weight: lighter;
    color: #000;
}
.container {
    max-width: 670px;
}
.middle p{	
	font-size: 1.1rem;
}
}
@media screen and (min-width:260px) and (max-width:640px){
		.anh-quote h3 {
    font-size:20px;
    font-weight: lighter;
    color: #000;
}
.main {   
    margin-top: 2.5rem;   
}
.bgimg {      
    padding: 2rem; 
    min-height: 25rem; 
}
.thankyou_container{
	width: 100%;
    max-width: 100%;   
    padding: 2rem;
}
.middle p{	
	font-size: 1rem;    
}

}
@media screen and (min-width:800px) and (max-width:1200px) {
.anh-quote h3 {
    font-size: 1em;
    font-weight: lighter;
    color: #000;
}

}
@media screen and (min-width:768px) and (max-width:999px)	{
.anh-quote h3 {
    font-size: 1em;
    font-weight: lighter;
    color: #000;
}

}
</style>
<div class="thankyou_container">
	<div class="bgimg">
	  <div class="topcenter">
	    <img src="<?php echo $this->getSkinUrl('images/check.png') ?>" >
	  </div>
	  <div class="middle">
	    <h1>Thank you</h1>    
	    <p id="demo">Thank you, our team will get in touch with you. <br/> See you at the consultation.<br/> For any queries please email <a href="mailto:diet@lifeheal.in"> diet@lifeheal.in </a> 
	    	<!--<br/> Your Next Steps:</p>-->
	  </div>
	  <!--<div class="bottomleft">	
		  	<a href="<?php //echo Mage::getBaseUrl();?>foodmealplan">Sign up for a 10 day trial</a>	
		   	<a href="https://lifeheal.zohobookings.in/#/customer/healthreview">Book a consultation</a>	 
	  </div>-->
	</div>
</div>
