<!-- Hero Banner Start -->
	<div class="hero">	    
	    <!-- Banner -->
	    <div class="hero-banner webinar">
	        <div class="hero-banner-container">
	        	
	        	<div class="hero-banner-text">
		        	<h1><!--Diabetes and Obesity are the twin evils of our time but the way to treat them is right in front of us-->
		        	Treat the disease, not the symptoms
		        	</h1>
		        	<p><strong>Junior Anand Gupta</strong>, <!--Health&nbsp;Expert-->CEO,&nbsp;LifeHeal</p>
		        </div>
		        
	        </div>
	    </div>
	    
	</div>
	<!-- Hero Banner End -->
	
	<!-- Webinar Detail Start -->
	<div class="webinar-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
		<div class="webinar-detail-container">
			
			<div class="webinar-detail-left">
				<h2>Obesity and weight loss is no <br> longer about calories</h2>
					<p>With new science we have learnt that cutting calories has not helped the world lose weight. In this webinar, we will discuss new lessons in the science of weight loss and how only looking at calories is outdated. You will learn the new lens through which we see weight loss today and how this can affect your journey.</p>
					<!--<ul>
						<li>Topic 1</li>
						<li>Topic 2</li>
						<li>Topic 3</li>
					</ul>	-->										
			</div>
			
			<div class="webinar-detail-right">
					
				
					<div class="webinar-date-wrapper">
						
						<div class="webinar-date-day">FRIDAY</div>
						<div class="webinar-date-date">20</div>
						<div class="webinar-date-month">AUG</div>
						
					</div>
					
					<div class="webinar-date-wrapper">
						
							<div class="webinar-date-day">FRIDAY</div>
						<div class="webinar-date-date">27</div>
						<div class="webinar-date-month">AUG</div>
						
					</div>
					<div class="webinar-registration-wrapper">
						<!--<p>Registration</p>
						<h3>Rs. 500 </h3>-->
						<a href="https://showtime.zoho.in/join#/50003091195/7785000000129094/register?talkId=7785000000150471" target="_blank" class="button cta-webinar-registration">Register Now</a>
					</div>
					
			</div>
			
		</div>
	</div>
	
	<!-- Webinar Detail End -->
	
	<!-- Webinar Detail Start -->
	<div class="webinar-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
		<div class="webinar-detail-container">
			
			<div class="webinar-detail-left">
					<h2>How To Start Intermittent <br>Fasting and Its Benefits</h2>
					<p>Learn the science behind Intermittent Fasting, why it works. Learn about the benefits it will bring you. We will then explain how you can start Intermittent Fasting including:</p>
					<ul>
						<li>Basic Techniques and Fasts</li>
						<li>Tips to Help Begin Fasting</li>
						<li>Key Benefits of Fasting</li>
					</ul>											
			</div>
			
			<div class="webinar-detail-right">
					
						<div class="webinar-date-wrapper">
						
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">21</div>
						<div class="webinar-date-month">AUG</div>
						
					</div>
					
					<div class="webinar-date-wrapper">
						
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">28</div>
						<div class="webinar-date-month">AUG</div>
							
					</div>
					
					<div class="webinar-registration-wrapper">
						<!--<p>Registration</p>
						<h3>Rs. 500 </h3>-->
						<a href="https://showtime.zoho.in/join#/50003091195/7785000000150411/register?talkId=7785000000150414" target="_blank" class="button cta-webinar-registration">Register Now</a>
					</div>
					
			</div>
			
		</div>
	</div>
	
	<!-- Webinar Detail End -->
	
	<!-- Webinar Detail Start -->
	<!--<div class="webinar-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
		<div class="webinar-detail-container">
			
			<div class="webinar-detail-left">
					<h2>DIABETES REMISSION <br>IN EARLY STAGE</h2>
					<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit</p>
					<ul>
						<li>Topic 1</li>
						<li>Topic 2</li>
						<li>Topic 3</li>
					</ul>											
			</div>
			
			<div class="webinar-detail-right">
					
					<div class="webinar-date-wrapper">
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">12</div>
						<div class="webinar-date-month">JUNE</div>
					</div>
					
					<div class="webinar-date-wrapper">
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">19</div>
						<div class="webinar-date-month">JUNE</div>
					</div>
					
					<div class="webinar-registration-wrapper">
						<p>Registration</p>
						<h3>Rs. 500 </h3>
						<a href="#" class="button cta-webinar-registration">Register Now</a>
					</div>
					
			</div>
			
		</div>
	</div>-->
	
	<!-- Webinar Detail End -->
	
	<!-- Webinar Detail Start -->
	<!--<div class="webinar-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
		<div class="webinar-detail-container">
			
			<div class="webinar-detail-left">
					<h2>WORK LIFE BALANCE <br>& WEIGHT MANAGEMENT</h2>
					<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit</p>
					<ul>
						<li>Topic 1</li>
						<li>Topic 2</li>
						<li>Topic 3</li>
					</ul>											
			</div>
			
			<div class="webinar-detail-right">
					
					<div class="webinar-date-wrapper">
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">26</div>
						<div class="webinar-date-month">JUNE</div>
					</div>
					
					<div class="webinar-date-wrapper">
						<div class="webinar-date-day">SATURDAY</div>
						<div class="webinar-date-date">3</div>
						<div class="webinar-date-month">JULY</div>
					</div>
					
					<div class="webinar-registration-wrapper">
						<p>Registration</p>
						<h3>Rs. 500 </h3>
						<a href="#" class="button cta-webinar-registration">Register Now</a>
					</div>
					
			</div>
			
		</div>
	</div>-->
	
	<!-- Webinar Detail End -->
	
	<!-- About Speaker Start -->
	
	<div class="webinar-speaker">
		<div class="webinar-speaker-container">
			<div class="webinar-speaker-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h4>ABOUT SPEAKER</h4>
				<h2>JUNIOR ANAND GUPTA</h2>
				<p>Junior A. Gupta is the founder of LifeHeal. His family has a strong history of Diabetes. Mr. Gupta says that "Growing up, the question wasn't If I would get diabetes, but When." He wanted to change the Indian mindset about Diabetes being genetic and irreversible. After many years of research, he realized that well-balanced diets are proven to control Diabetes. He started LifeHeal in 2018 to help people live healthier, stronger, and longer. He has degrees from Babson and MIT in the USA. He's a receiver of APJ Abdul Kalam's "Goodness Award" and also a TedX speaker.</p>
			</div>
		</div>
	</div>
	
	<!-- About Speaker End -->
	
	<!-- Next Webinar Start -->
	
	<div class="webinar-next">
		<div class="webinar-next-container">
			<div class="webinar-next-left">
				<img src="<?php echo $this->getSkinUrl('images/webinar-speaker-jr.png') ?>"/>
				
			</div>
			<div class="webinar-next-right" id="webinar-next-right" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				<h2>NEXT WEBINAR STARTS IN</h2>
				<div id="countdown">
	              <ul>
	                <li><span id="days"></span>DAYS</li>
	                <li><span id="hours"></span>HOURS</li>
	                <li><span id="minutes"></span>MINUTES</li>
	                <li><span id="seconds"></span>SECONDS</li>
	              </ul>
	            </div>
				<a href="#" class="button cta-webinar-next">Claim your spot now</a>
			</div>
		</div>
	</div>
	
	<script>
	
		(function () {
		const second = 1000,
	        minute = second * 60,
	        hour = minute * 60,
	        day = hour * 24;
        

		let webinarTime = "June 12, 2021 17:27:00",
		      countDown = new Date(webinarTime).getTime(),
		      x = setInterval(function() {    
		        
		        let current = new Date().toLocaleDateString('en-US', { month: 'long', day: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: "h23", timeZone: 'Asia/Kolkata' });
		
		        let now = new Date(current).getTime(),
		            distance = countDown - now;
		
		        document.getElementById("days").innerText = Math.floor(distance / (day)),
		          document.getElementById("hours").innerText = Math.floor((distance % (day)) / (hour)),
		          document.getElementById("minutes").innerText = Math.floor((distance % (hour)) / (minute)),
		          document.getElementById("seconds").innerText = Math.floor((distance % (minute)) / second);
		
		
		        if (distance < 0) {
					let webinar_container = document.getElementById("webinar-next-right");
						
					webinar_container.style.display = "none";
					clearInterval(x);
		        }
		      }, 0)
		  }());
		  
	</script>
	
	<!-- Next Webinar End -->
	
	<!-- Home Testimonials Start -->
	<?php /*<div class="pastwebinar">
	<div class="home-testimonials">
		<div class="home-testimonials-container">
			
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">PAST WEBINARS</h2>
			
			<div class="home-testimonials-videos" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<!-- Testimonials Videos -->
				<a href="https://www.youtube.com/watch?v=B06HuGBxO48" data-youtube-id="B06HuGBxO48" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video1.jpg') ?>"/>
					<h3>Webinar Improve Sugar Control</h3>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://youtube.com/watch?v=gtS3R-zTmss" data-youtube-id="gtS3R-zTmss" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video2.png') ?>"/>
					<h3>Obesity is no longer about calories</h3>
				</a>
				
				<!-- Testimonials Videos -->
				<a href="https://youtube.com/watch?v=0ALPFrKIdwo" data-youtube-id="0ALPFrKIdwo" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video3.jpeg') ?>"/>
					<h3>Diabetes Reversal With Dr Joel Fuhrman</h3>
				</a>
			
			</div>
		</div>
	</div>
	</div>
	*/?>
	<!-- Home Testimonials End -->
	<!-- Past Webinars Start -->
	
	<div class="past-webinars">
		<div class="past-webinars-container">
			<h2 data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">PAST WEBINARS</h2>
			<div class="past-webinars-detail-wrapper" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
				
				<div class="past-webinars-detail">
					<div class="past-webinars-detail-image">
						<a href="https://www.youtube.com/watch?v=B06HuGBxO48" data-youtube-id="B06HuGBxO48" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video1.jpg') ?>"/>
						</a>
					</div>
					<div class="past-webinars-detail-text">
						<h3>Webinar Improve Sugar Control</h3>
					</div>
				</div>
				</a>
				<div class="past-webinars-detail">
					<div class="past-webinars-detail-image">
						<a href="https://youtube.com/watch?v=gtS3R-zTmss" data-youtube-id="gtS3R-zTmss" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video2.png') ?>"/>
						</a>
					</div>
					<div class="past-webinars-detail-text">
						<h3>Obesity is no longer about calories</h3>
					</div>
				</div>
				
				<div class="past-webinars-detail">
					<div class="past-webinars-detail-image">
						<a href="https://youtube.com/watch?v=0ALPFrKIdwo" data-youtube-id="0ALPFrKIdwo" class="video-thumb js-trigger-video-modal">
					 <img src="<?php echo $this->getSkinUrl('images/video3.jpeg') ?>"/>
						</a>
					</div>
					<div class="past-webinars-detail-text">
						<h3>Diabetes Reversal With Dr Joel Fuhrman</h3>
					</div>
				</div>
				
				
			</div>
		</div>
	</div>
	
	<!-- Past Webinars End -->
	
		<!-- Video Modal Start -->
	<div class="video-modal">
		<!-- Modal Content Wrapper -->
		<div id="video-modal-content" class="video-modal-content">
			<!-- iframe -->
			<iframe id="youtube" width="100%" height="100%" frameborder="0" allow="autoplay" allowfullscreen src=></iframe>
			<a href="#" class="close-video-modal">
				<!-- X close video icon -->
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve" width="24" height="24">
					<g id="icon-x-close">
						<path fill="#ffffff" d="M30.3448276,31.4576271 C29.9059965,31.4572473 29.4852797,31.2855701 29.1751724,30.980339 L0.485517241,2.77694915 C-0.122171278,2.13584324 -0.104240278,1.13679247 0.52607603,0.517159487 C1.15639234,-0.102473494 2.17266813,-0.120100579 2.82482759,0.477288136 L31.5144828,28.680678 C31.9872448,29.1460053 32.1285698,29.8453523 31.8726333,30.4529866 C31.6166968,31.0606209 31.0138299,31.4570487 30.3448276,31.4576271 Z" id="Shape"></path>
						<path fill="#ffffff" d="M1.65517241,31.4576271 C0.986170142,31.4570487 0.383303157,31.0606209 0.127366673,30.4529866 C-0.12856981,29.8453523 0.0127551942,29.1460053 0.485517241,28.680678 L29.1751724,0.477288136 C29.8273319,-0.120100579 30.8436077,-0.102473494 31.473924,0.517159487 C32.1042403,1.13679247 32.1221713,2.13584324 31.5144828,2.77694915 L2.82482759,30.980339 C2.51472031,31.2855701 2.09400353,31.4572473 1.65517241,31.4576271 Z" id="Shape"></path>
					</g>
				</svg>
			</a>
		</div>
		<!-- End modal content wrapper -->
		<!-- Clickable overlay element -->
		<div class="overlay"></div>
	</div>
	<!-- Video Modal End -->
<style>
.webinar {
	background-image: url('<?php echo $this->getSkinUrl("images/webinar-hero-banner.jpg")?>');
}
			
@media only screen and (max-width: 768px) {
	.webinar {
		background-image: url('<?php echo $this->getSkinUrl("images/webinar-hero-banner-mobile.jpg")?>');
				
	}	
}			
.webinar h1 {
	/*color: #7F4CA7;*/
	color: #fff;
}			
.webinar p {
	color: #FFFFFF;
}		
			
</style>	