	<div class="webinar-wrapper">
	<!-- Hero Banner Start -->
		<div class="hero">	    
		    <!-- Banner -->
		    <div class="hero-banner webinar">
		        <div class="hero-banner-container">	        	
		        	<div class="hero-banner-text">
			        	<h1>  Managing PCOS with Lifestyle  </h1>
			        	<h4 style="color:#fff;">Learn all that you need to know about PCOS</h4>
			        	
			        	<p><strong>Presented by: Jasmine Channa</strong>, <br/> Chief Dietitian,&nbsp;LifeHeal</p>
			        </div>		        
		        </div>
		    </div>	    
		</div>
		<!-- Hero Banner End -->

		<!-- Webinar Detail Start -->
		<div class="webinar-detail" data-aos="fade-up" data-aos-offset="0" data-aos-duration="1000">
			<div class="webinar-detail-container">			
				<div class="webinar-detail-left">
					<h2>Learn How to Manage PCOS / PCOD</h2>
					<p>One in three women suffer from PCOD today. But, can PCOS be reversed?  Yes! It can totally be reversed with the right eating habits and lifestyle modification.</p>

					<p>In this webinar, learn about:</p>
					<ul>
						<li>How to be diagnosed with PCOS</li>
						<li>Types of PCOS</li>
						<li>Various ways to improve your symptoms</li>					
					</ul>
					<p>Plus, get your personal questions answered in the Q&A session.</p>
					<div class="webinar-date-inner">
						<div class="webinar-date-wrapper">
							<div class="webinar-date-day">SATURDAY</div>
							<div class="webinar-date-date">27</div>
							<div class="webinar-date-month">
								NOVEMBER <br/><span>12:00 - 1:00 pm</span>
							</div>
						</div>
						<a href="#appointment_success">
							<span class="limited-seat">Limited Seats.</span> Register Below.</a>
					</div>
				</div>
				
				<div class="webinar-detail-right">	
					<div class="webinar-top-pic">
						<img src="<?php echo $this->getSkinUrl("images/webinar-top-1.jpg")?>" />
					</div>
					<div class="webinar-bottom-pic">
						<div class="webinar-bottom-pic-left">
							<img src="<?php echo $this->getSkinUrl("images/webinar-top-2.jpg")?>" />
						</div>
						<div class="webinar-bottom-pic-right">
							<img src="<?php echo $this->getSkinUrl("images/webinar-top-3.jpg")?>" />
						</div>
					</div>
				</div>
			</div>
		</div>
	
		<!-- Webinar Detail End -->
		<div class="webinar-counter">
			<div class="webinar-detail-container">
				<div class="counter-inner">
					<div class="counter-left aos-init aos-animate" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
						<p>November 27, 2021 @ 12:00 - 1:00 pm</p>
						<h3>Don’t forget to attend this event</h3>
					</div>
					<div class="counter-right aos-init aos-animate" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">
					  	<div class="timer-unit" id="days"></div>
					  	<div class="timer-unit" id="hours"></div>
					  	<div class="timer-unit" id="minutes"></div>
					  	<div class="timer-unit" id="seconds"></div>
					</div>
					
				</div>
			</div>
		</div>



		<!-- Success Start -->
		<div class="webinar-bottom-sec">
			<div class="webinar-detail-container">
				<div class="webinar-bottom-sec-inner">
					<div class="webinar-bottom-sec-left aos-init aos-animate" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">				
						<img src="<?php echo $this->getSkinUrl("images/webinar-registration.jpg")?>" />
					</div>
					<div class="webinar-bottom-sec-right aos-init aos-animate" data-aos="fade-right" data-aos-offset="0" data-aos-duration="1000">	
						<div class="appointment-success" id="appointment_success">
							<iframe id='st_registerform_iframe' src='https://showtime.zoho.in/embedform#sessionId=7785000000322003&zaid=50003091195&utm_st_source=embed&header=true' frameborder='0' allowfullscreen='' > </iframe>
						</div>
					</div>
				</div>
			</div>
		</div>		
	</div><!-- Success End -->
	<div class="bottom-static"><a href="#appointment_success">Register Now</a></div>


<style>
	html {
		scroll-behavior: smooth;
	}

	.webinar-wrapper{
		position: relative;
	}
	.bottom-static{	width: 100%; position: fixed; right: 0; bottom: 0;  left: 0; z-index: 6000; display: none;}
	.bottom-static a{
		color: #fff; text-decoration: none; display: block;
		text-transform: capitalize;	background: #144f5a;
		text-align: center;	padding: 8px 0; font-size: 1.3rem;
	}
	.webinar-detail { border-bottom: 0;	}
	.webinar-detail-left h2 { 	font-size: 1.9rem;
    	text-transform: capitalize;	}
	.webinar-detail-right {	flex-wrap: wrap; }
	.webinar-detail-left { display: flex;  	flex-wrap: wrap; }
	.webinar-date-wrapper {  text-align: center; }
	.webinar-date-wrapper span { font-size: 12px;	}
	.webinar-top-pic{width:100%; margin-bottom: 14px;	}
	.webinar-bottom-pic{width: 100%;	display: flex;
		flex-wrap: wrap; justify-content: space-between;	}
	.webinar-bottom-pic-left, .webinar-bottom-pic-right{
		width:calc(50% - 7px);	}
	.webinar-bottom-pic img, .webinar-top-pic img,
	.webinar-bottom-sec-left img{
		width:100%;	display: block;
	}
	.webinar-detail-left a{	display: inline-block;    	
    	text-decoration: none; 	font-weight: 700; color:#3551aa;
	}
	.webinar-detail-left ul{padding-left: 20px;	}
	.webinar-detail-left ul li{	font-weight: 400; font-size: 16px;
		position: relative;	padding-left: 20px;
		list-style: none;	padding-bottom: 7px; font-weight: 600;
	}
	.webinar-detail-left ul li:after{
		content: ''; position: absolute;
		left:0;	top:4px; width:8px; height: 8px;
		background: #471d58; border-radius: 100%;
	}
	.webinar-detail-right  span{
		padding-top: 4px; display: block;
		font-size: 12px; text-align: center;
	}
	.webinar-counter{
		background: #7f4ca7; padding: 0;
		box-sizing: border-box;	width: 100%;		
	}
	.webinar {
		background-image: url('<?php echo $this->getSkinUrl("images/webinar-hero-banner-jasmine.jpg")?>');
	}			
	.webinar h1 { color: #fff;	}			
	.webinar p {color: #FFFFFF;	}
	.appointment-success{width:100%; margin:0 auto;	padding:  0;}
	.appointment-success iframe{ height: 490px; width:100%;	}
	.appointment-success .btn {    	
    	padding: 12px 10px !important;
	}
	.counter-inner, .webinar-bottom-sec-inner,
		.webinar-date-inner, .counter-right{
			display: flex;	width:100%;	
		}
		.webinar-date-inner{ align-content: center;
			align-items: center;
		}
		.counter-inner, .webinar-bottom-sec-inner{
			flex-wrap: wrap; justify-content: space-between;
		}
		.webinar-bottom-sec-left, .webinar-bottom-sec-right{
			width: 48%;	}
		.counter-left{	width:40%;}
		.counter-right{	width:55%; flex-wrap: wrap;
			justify-content: space-between;	}
		.timer-unit{color: #fff;	background: #471d58;
			padding: 30px 20px;
     		background-color: rgba(0, 0, 0, 0.07);
    		font-size: 40px; text-align: center;
    		min-width: 130px; min-height: 120px;
    		line-height: 1;
    		box-shadow: 0 1px 1px 1px rgb(0 0 0 0.15);
		}
		.counter-left{	display: flex;	flex-wrap: wrap;
			color: #fff; align-content: center;
			background-color: rgba(0, 0, 0, 0.07);
    		text-align: center;    		
    		box-shadow: 0 1px 1px 1px rgb(0 0 0 0.15);
		}
		.counter-left p, .counter-left h3{	width: 100%;}
		.timer-unit span{display: block; font-size: 18px;	}
		.webinar-bottom-sec{background: #f5f5f5;}

	@media only screen and (max-width: 768px) {		
		.webinar {
			background-image: url('<?php echo $this->getSkinUrl("images/webinar-hero-banner-mobile-jasmine.jpg")?>');
		}
		.webinar h1 {	font-size: 1.6rem;	}
		.appointment-success{	width:100%;	}
		.webinar-detail-left p{	text-align: justify;}
		.webinar-detail-right { justify-content: center; margin-bottom: 15px;}
		.webinar-detail-container {	padding: 2rem 1.5rem 0 1.5rem;}
		.webinar-detail-left {	padding-bottom: 0rem;}
		.counter-left, .counter-right,
		.webinar-bottom-sec-left, .webinar-bottom-sec-right  {
    		width: 100%;
		}
		.counter-left{margin-bottom: 20px;	padding: 15px 0;}
    	.timer-unit{ min-width: 145px; margin-bottom:20px;}
    	.appointment-success iframe { height: 560px;}
		.embed-register-show .embed-register-head {
    			padding: 10px !important;    
			}
		.embed-register-show .embed-register-body {
    		padding: 15px 10px 10px !important;
			}	
	}
	@media only screen and (max-width: 620px) {
		.bottom-static{display: block;}
		.hero {	height: 50vh; min-height: 26rem;}
		.hero-banner-container { padding: 0;}
		.hero-banner-text { margin-top: 3rem; }
		.webinar-detail-left h2 { font-size: 1.1rem;}
		.counter-left h3{ margin-top: 6px; font-size: 1rem;	}
		.webinar-detail-left ul{margin-bottom: 30px;}
		.limited-seat{display: block; width: 100%;}
	}	
</style>
<script type="text/javascript">
	function makeTimer() {	
		var endTime = new Date("27 November 2021 12:00:00 GMT+05:30");			
		endTime = (Date.parse(endTime) / 1000);

		var now = new Date();
		now = (Date.parse(now) / 1000);

		var timeLeft = endTime - now;

		var days = Math.floor(timeLeft / 86400); 
		var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
		var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
		var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));
  
		if (hours < "10") { hours = "0" + hours; }
		if (minutes < "10") { minutes = "0" + minutes; }
		if (seconds < "10") { seconds = "0" + seconds; }

		document.getElementById("days").innerHTML = days + "<span>Days</span>";
		document.getElementById("hours").innerHTML = hours + "<span>Hours</span>";
		document.getElementById("minutes").innerHTML = minutes + "<span>Minutes</span>";
		document.getElementById("seconds").innerHTML = seconds + "<span>Seconds</span>";

	}	
	setInterval(function() { makeTimer(); }, 1000);
</script>