<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/viewpagebootstrap.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>css/shop-plans.css" type="text/css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<style>
		.list-inline > li#diabetes a{font-weight:500;}
		.list-inline > li#weightloss a{font-weight:600;background: #1acccd;}
		.list-inline > li#silver a{font-weight:500;}
		.list-inline > li#gold a{font-weight:500;}
		.list-inline > li#body-reboot a{font-weight:500;}
	
	.navbar-light .navbar-nav #how-it-work {
    background:#fff;
    color: #000 !important;
}
	.list-checkedplan p{font-size:1em}
	.columnsplan {
   float: left;
width: 28%;
padding: 5px;
margin: auto 2%;
}
	.navbar-light .navbar-nav #nav-view-plan {
    background: rgb(26, 204, 205);
    color: #fff !important;
}
	.priceplan .headerplan{height:auto;}
* {
  box-sizing: border-box;
}
	
	.startingheight{height: 70px;
margin-top: 10% !important;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 17.5%;
text-align: center;
margin-top: 7.2%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;}
	.btn{font-weight:600; font-size:1.2em;}
.digitalbox {    height:440px;
    margin-bottom: 40px;
}
	.analysis{height:520px}
@media only screen and (max-width: 600px) {
	.starting{margin-top: 12%;}
  .columnsplan {padding:0px;
    width: 100%;margin:auto;
  }
	.digitalbox {height:auto;margin-bottom:20px;}
	.analysis{height:auto;}
	.columnspanh2{font-size: 20px;
position: absolute;
width: 87%;
text-align: center;
margin-top:27%;
color: red;
line-height: 1;
transform: rotateZ(-5deg);
margin-left: .5%;
margin-right: .5%;
float: none;
display: inline-block;
background: #fff;}
}
		@media screen and (min-width:768px) and (max-width:999px)
	{
		
.logomob img {
    width: 60%;
    float: right;
    margin-right: 6%;
}
		.columnsplan {
    float: left;
    width: 33%;
    padding: 5px;
    margin: auto;
}
.hero-bg .well {
    padding: 0px;
    margin-bottom: 0;
}		
		
.priceplan { padding: 0 5px;}
		ul {
    padding: 0 0px 0 0px;
}
		.list-checkedplan > li {
    padding: 0px 0px;
    text-align: center;
			width:100%;
			float:left;
    border-bottom: 0px solid #eee;
    font-size: 11px !important;
    line-height: 1.4 !important;
}
		.digitalbox {
    height: 530px;
    margin-bottom: 40px;
}
	}
		@media screen and (min-width:800px) and (max-width:1200px)
	{
		.columnsplan {
    float: left;
    width: 33%;
    padding: 5px;
    margin: auto;
}
		ul {
    padding: 0 0px 0 0px;
}
		.list-checkedplan > li {
    padding: 0px 0px;
    text-align: center;
			width:100%;
			float:left;
    border-bottom: 0px solid #eee;
    font-size: 13px !important;
    line-height: 1.4 !important;
}
		.digitalbox {
    height: 430px;
    margin-bottom: 40px;
}
		
	}
</style>

<div class="southbeach shop-plans hero-bg card-row" id="top-cards">
		
<div class="container">
<h1 class="h2 text-center text-sentence fw-600 bot-mar-0">Lose Weight At Home</h1>
	<h2 class="h4 text-center text-sentence fw-400">Consulting plans derived from years of research and practical experience</h2>

		<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox" style="border:4px solid #f25153;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/metabolic.png') ?>" style="width: 50px;margin: auto;"/>
		Immunity <br> Report Card</li>
	    <li class="well text-center bg-white">
			<div  class="weekly-price-container">
			<h2>Rs 3,000</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Great for Those with Frequent Colds</p></li>
    <li class="greyplan"><a href="#" class="buttonplan" onclick="addtocartAndWelcome('1998')">Buy Now</a></li>
	 <a data-toggle="collapse" href="#gold-bull-mob" class="text-gray-darker more-info-link border-top GoldbullMoreInfo" aria-expanded="false" aria-controls="gold-bull-mob" onclick="$(this).hide();omni_track('GoldbullMoreInfo');"><span style="width: 120px;float: none;margin: auto;text-align: center;display: block;">
	more info <i class="material-icons" aria-hidden="true">
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512.011 512.011" style="enable-background:new 0 0 512.011 512.011;width:14px;height: 24px;float: right;margin-top: 8%;" xml:space="preserve">
	<g>
		<path d="M505.755,123.592c-8.341-8.341-21.824-8.341-30.165,0L256.005,343.176L36.421,123.592c-8.341-8.341-21.824-8.341-30.165,0
			s-8.341,21.824,0,30.165l234.667,234.667c4.16,4.16,9.621,6.251,15.083,6.251c5.462,0,10.923-2.091,15.083-6.251l234.667-234.667
			C514.096,145.416,514.096,131.933,505.755,123.592z"></path>
	</g>
</svg></i>
	</span></a>
	<ul class="list-checkedplan list-checked text-left collapse moreinfo-collapse" id="gold-bull-mob" aria-expanded="false">
     <p class=" text-left fw-600 list-head text-uppercase">Enhancing Your Immunity</p>
    <li>Learn what is Lacking in your Immunity</li>
    <li>Fend off Sickness and Increase Vitality</li>
    </ul>
  </ul>
</div>
	
	<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox"  style="border:4px solid #5ca157;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/familyplan.png') ?>" style="width:170px;margin: auto;"/>
		Healthy Home <br>
Family Plan</li>
	    <li class="well text-center bg-white">			
			<div  class="weekly-price-container">
			<p>Starting at</p>
			<h2>
			Rs 6,000/mo
			</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Reducing Risk Factors of Coronavirus</p></li>
    <li class="greyplan"><a href="familyplan" class="buttonplan">Select</a></li>
	<a data-toggle="collapse" href="#silver-bull-mob" class="text-gray-darker more-info-link border-top SilverbullMoreInfo" aria-expanded="false" aria-controls="silver-bull-mob" onclick="$(this).hide();omni_track('SilverbullMoreInfo');"><span style="width: 120px;float: none;margin: auto;text-align: center;display: block;">
	more info <i class="material-icons" aria-hidden="true">
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512.011 512.011" style="enable-background:new 0 0 512.011 512.011;width:14px;height: 24px;float: right;margin-top: 8%;" xml:space="preserve">
	<g>
		<path d="M505.755,123.592c-8.341-8.341-21.824-8.341-30.165,0L256.005,343.176L36.421,123.592c-8.341-8.341-21.824-8.341-30.165,0
			s-8.341,21.824,0,30.165l234.667,234.667c4.16,4.16,9.621,6.251,15.083,6.251c5.462,0,10.923-2.091,15.083-6.251l234.667-234.667
			C514.096,145.416,514.096,131.933,505.755,123.592z"></path>
	</g>
</svg></i>
	</span></a>
	<ul class="list-checkedplan list-checked text-left collapse moreinfo-collapse" id="silver-bull-mob" aria-expanded="false">	  
	<p class=" text-left fw-600 list-head text-uppercase">Weight Loss + Immunity<br>Right From Home</p>
    <li>Boost Immunity for the Whole Family</li>
    <li>Lose Weight & Simplify Task of <br>Meal Planning</li>
    </ul>
  </ul>
</div>
	<div class="columnsplan body-reboot">
  <ul class="priceplan digitalbox" style="border:4px solid #edce1d;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/individualplan.png') ?>" style="width:85px;margin: auto;"/>
		Fit &amp; Fabulous<br>Individual Plan</li>
	    <li class="well text-center bg-white">			
			<div  class="weekly-price-container">
		<p>Starting at</p>
			<h2>
			Rs 4,000/mo
			</h2>
			</div>
	  </li> 
	  <li><p class="h6 fw-300">Attacking the Root Cause of Obesity</p></li>
    <li class="greyplan"><a href="individualplan" class="buttonplan">Select</a></li>
	 <a data-toggle="collapse" href="#reboot-bull-mob" class="text-gray-darker more-info-link border-top BodyRebootMoreInfo" aria-expanded="false" aria-controls="reboot-bull-mob" onclick="$(this).hide();omni_track('BodyRebootMoreInfo');"><span style="width: 120px;float: none;margin: auto;text-align: center;display: block;">
	more info <i class="material-icons" aria-hidden="true">
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512.011 512.011" style="enable-background:new 0 0 512.011 512.011;width:14px;height: 24px;float: right;margin-top: 8%;" xml:space="preserve">
	<g>
		<path d="M505.755,123.592c-8.341-8.341-21.824-8.341-30.165,0L256.005,343.176L36.421,123.592c-8.341-8.341-21.824-8.341-30.165,0
			s-8.341,21.824,0,30.165l234.667,234.667c4.16,4.16,9.621,6.251,15.083,6.251c5.462,0,10.923-2.091,15.083-6.251l234.667-234.667
			C514.096,145.416,514.096,131.933,505.755,123.592z"></path>
	</g>
</svg></i>
	</span></a>
	<ul class="list-checkedplan list-checked text-left collapse moreinfo-collapse" id="reboot-bull-mob" aria-expanded="false">
	<p class=" text-left fw-600 list-head text-uppercase">Scientific Approach<br>Looking Beyond Calories</p>
    <li>Validated by Over 300 Doctors</li>
    <li>Repairs Metabolism</li>
    <li>Proven Results</li>
    </ul>
  </ul>
</div>
	
	

	
		<div class="columnsplan" style="display:none;">
			<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/Basic.jpg') ?>" style="width: 50px;margin: auto;"/>Silver
Plan</li>
	  <li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs400 / Day </span></span><br>Rs 300 / Day</h2></li>  
	  <li class="greyplan"><a href="weightlosesilverplan" class="buttonplan">View Menu</a></li>
     <ul class="list-checkedplan">
      <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>1 Oil Free Salad Dressing and 2 Soups a day</li>
    </ul>
  </ul>
</div>
	<div class="columnsplan" style="display:none;">
		<h2 class="columnspanh2">unavailable <br>due to <br>lockdown</h2>
  <ul class="priceplan digitalbox"  style="pointer-events: none;opacity: 0.4;">
    <li class="headerplan"><img src="<?php echo $this->getSkinUrl('images/popular.png') ?>" style="width: 50px;margin: auto;"/>Gold Plan</li>
	<li class="starting">Starting at<h2><span style="color:red;text-decoration:line-through;"><span style="color:black">Rs700 / Day </span></span><br>Rs 600 / Day</h2></li> 
	<li class="greyplan"><a href="weightlosegoldplan" class="buttonplan">View Menu</a></li>
      <ul class="list-checkedplan">
     <li>Includes Deep Insight Consulting</li>
    <li>Customized, oil free food</li>
    <li>Dedicated Nutritionist</li>
    <li>Includes Pro Biotics</li>
    <li>2 Meals a day</li>
    </ul>
    
  </ul>
</div>


	</div>
		<div class="bg-white">
  <div class="container">
  <div class="row below-plan-sect">
		<div class="col-xs-12 col-sm-12 c ol-md-12 col-lg-12">
  <h3 class="h4 text-secondary fw-600" style="text-align: center;text-transform: uppercase;">Our Services Cover But Are Not Limited To:</h3>
</div>
      <div class="col-xs-12 col-sm-4 col-lg-4 col-lg-offset-3 col-sm-offset-2 col-md-offset-2">
        <h3 class="h4 text-secondary fw-600" style="display:none;">With All Of Our Plans You'll :</h3>
        <ul class="list-checked pink-bullet">
          <li class="h6 fw-300">Weight Management</li>
          <li class="h6 fw-300">Overall Health</li>
          <li class="h6 fw-300">Diabetes Management</li>
		  <li class="h6 fw-300">Gastrointestinal Disorders</li>
			<li class="h6 fw-300">Emotional Eating</li>
			<li class="h6 fw-300">Cholesterol</li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-4 col-lg-4">
        <hr class="visible-xs">
        <h3 class="h5 text-primary text-uppercase fw-600" style="display:none;">Safe &amp; Healthy Weight Loss</h3>
        <ul class="list-checked blue-check">
          <li class="h6 fw-300">Blood Pressure</li>
          <li class="h6 fw-300">Pediatrics</li>
          <li class="h6 fw-300">Kidney Disease</li>
			<li class="h6 fw-300">Sports Nutrition</li>
			<li class="h6 fw-300">Thyroid</li>
			<li class="h6 fw-300">PCOD</li>
        </ul>
      
      </div>
    </div>
  </div>
</div>
	<div class="closer bg-secondary">
  <div class="container ">
    <div class="row ">
      <div class="center-block no-float text-white col-xs-12 ">
        <div class="row ">
          <div class="text-wrapper col-xs-12 col-sm-6 col-md-4 col-md-offset-2">
            <h2 class="h3 text-white ">Get&nbsp;Healthier Today</h2>
          </div>
          <div class="button-wrapper col-xs-12 col-sm-4 col-md-3" id="top"> <a href="#top-cards" class="btn btn-default scroll-to bg-white">Get It Now</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>
	</div>
	<script>
	// Select all »a« elements with a parent class »links« and add a function that is executed on click
jQuery( '#top a' ).on( 'click', function(e){
	
  // Define variable of the clicked »a« element (»this«) and get its href value.
  var href = jQuery(this).attr( 'href' );
  
  // Run a scroll animation to the position of the element which has the same id like the href value.
  jQuery( 'html, body' ).animate({
		scrollTop: jQuery( href ).offset().top
  }, '300' );
	
  // Prevent the browser from showing the attribute name of the clicked link in the address bar
  e.preventDefault();

});
			jQuery(document).ready(function(){
 jQuery(".GoldbullMoreInfo").click(function(){
   jQuery("#gold-bull-mob").toggle();
  });
});
	jQuery(document).ready(function(){
 jQuery(".SilverbullMoreInfo").click(function(){
   jQuery("#silver-bull-mob").toggle();
  });
});
	jQuery(document).ready(function(){
 jQuery(".BodyRebootMoreInfo").click(function(){
   jQuery("#reboot-bull-mob").toggle();
  });
});
</script>
	
