<?php
if(Mage::getSingleton('customer/session')->isLoggedIn()){
	$LoggedIncustomer = Mage::helper('customer')->getCustomer();
    $customerId = $LoggedIncustomer->getId();
    $customerName = $LoggedIncustomer->getFirstname();
    $mobileno = $LoggedIncustomer->getPrimarymobileno();
	?>
<!-- Success Start -->
	<div class="sign-in-success">
		<div class="sign-in-success-container">
			<div class="sign-in-success-detail-wrapper">
				<div class="sign-in-success-detail">
					<img src="<?php echo $this->getSkinUrl("images/check.png")?>">
					<h2>Thank You <?php $customerName;?>!</h2>
					<p>Your account has been created successfully. You&nbsp;can&nbsp;now continue using links below.</p>
					
					<!--<a href="https://lifeheal.zohobookings.in/#/customer/healthreview" class="primary">Book a paid consultation</a>	-->				

					<a href="<?php echo Mage::getBaseUrl();?>booking" class="primary">Book a paid consultation</a>

					<a href="<?php echo $this->getUrl('meal-plan-coaching') ?>">Shop our meal plans</a>
					<!--<a href="<?php echo Mage::getBaseUrl();?>customer/account/login">Check your Account</a>-->
					<a href="<?php echo $this->getUrl('webinar') ?>" >Join free webinar</a>
					<a href="<?php echo Mage::getBaseUrl();?>customer/account/organhealth">Go to your account</a>
				</div>
			</div>
		</div>
		<?php } else { echo '<div class="pleae-login">please login</div>'; } ?>
	</div>
	<!-- Success End -->
	

