<?php 
$liver_all_tests =['sgot','sgpt','bilirubin','fattyliverultrasound','fattyliverfirbscan','fattyliverescore'];

$liver_db_tests =['sgot','sgpt','bilirubin','fattyliverultrasound','fattyliverfirbscan','fattyliverescore'];
$liver_unit =['U/l','U/l','mg/dL','unit','dB/m','kPa'];

$heart_db_tests =['hscrp','triglycerides','hdl','ldl','homocysteine'];
$heart_unit =['mg/L','mg/dL','mg/dL','mg/dL','mcmol/L'];

$kidney_db_tests =['creatinine','urea','sodium','potassium','uricacid'];
$kidney_unit =['mg/dL','mg/dL','mEq/L','mmol/L','mg/dL'];

$Pancreas_db_tests =['hba1c','homa','waist','fasting_glucose'];
$Pancreas_unit =['%','unit','W/H','mg/dl'];

$eye_db_tests =['hba1c','bp_systolic','waist','hscrp'];
$eye_unit =['%','mmHg','W/H','mg/L'];

$bp_systolicdata =[];
$alldates = [];
$hba1cdata = [];    
$homadata= [];
$waistdata = [];
$fasting_glucosedata = [];
$ppsugardata = [];
$allliverid= [];
$allliverdata=[]; 
$allliverdate=[]; 

$heart =[];
$liver =[];
$kidney =[];
$Pancreas =[];
$eye =[];
$datearr =[];

$weightdata =[];
$weightdate =[];
$waistdata =[];
$waistdate =[];

$LoggedIncustomer = Mage::helper('customer')->getCustomer();
$custId = $LoggedIncustomer->getId();
$customerName = $LoggedIncustomer->getFirstname();
$mobileNo = $LoggedIncustomer->getPrimarymobileno();
$config  = Mage::getConfig()->getResourceConnectionConfig("default_setup");
$dbinfo = array("host" => $config->host,"user" => $config->username,"pass" => $config->password,"dbname" => $config->dbname);
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
    
$host      = $dbinfo["host"];
$username  = $dbinfo["user"];
$password  = $dbinfo["pass"];
$dbname    = $dbinfo["dbname"]; 
  
$con = mysqli_connect($host  , $username,  $password ,$dbname);
  if ($mysqli -> connect_errno) {
  	echo "Failed to connect to MySQL: " . $mysqli -> connect_error;
  	exit();
	}
if($groupId == 4 || $groupId == 5){
    //$sql_str = "SELECT * FROM patientintakeform ORDER BY name ASC";
    $sql_str = "SELECT DISTINCT custid, name, mobileno FROM patientintakeform  WHERE custid !='' and name !='' and mobileno !='' ORDER BY name ASC";
    $customerCollection = mysqli_query($con, $sql_str);
    $customerLi='';
    foreach($customerCollection as $custinfo) {
        $customerId = $custinfo['custid'];
		$customer = Mage::getModel('customer/customer')->load($customerId);
		$customerMealstatus = $customer->getMealstatus();
        $customerName =  $custinfo['name'];
        $mobileNo = $custinfo['mobileno']; 
        $customerName = str_replace("Dear ","",$customerName); 
        $customerName = str_replace("Dr.","",$customerName);      
		 if($customerMealstatus==1){      
        $customerLi.='<li id="'.$customerId.'" value="'.$customerId.'" onclick="showReportbtn('.$customerId.','.$mobileNo.')">'.$customerName.'<span class="csmall">'.$customerId.'</span></li>';
		 }
    }

    if(isset($_GET["custid"])) {
        $gcustid = $_GET["custid"];
        $gmno = $_GET["mno"];
        $gcudate = $_GET["cudate"];
        $sql = "SELECT * FROM patientintakeform where custid='".$gcustid."' and mobileno='".$gmno."' ORDER BY date ASC";
        $sql2 = "SELECT * FROM patientintakeform where custid = '".$gcustid."' and date ='".$gcudate."'";

    }

}else{
        $sql = "SELECT * FROM patientintakeform where custid='".$custId."' and mobileno='".$mobileNo."' ORDER BY date ASC";
        if (isset($_GET["patientid"])) {
            $sql2 = "SELECT * FROM patientintakeform where patientid =".$_GET["patientid"];
        }else{
            $sql2 = "SELECT * FROM patientintakeform where custid = '".$custId."' and mobileno='".$mobileNo."' ORDER BY date DESC LIMIT 1";
            }
    }

if (isset($_GET["patientid"]) && ($groupId == 4 || $groupId == 5)){
            $sql = "SELECT * FROM patientintakeform where custid='".$_GET["custId"]."' ORDER BY date ASC";
            $sql2 = "SELECT * FROM patientintakeform where patientid =".$_GET["patientid"];
        }           

$result = mysqli_query($con, $sql);
$result2 = mysqli_query($con, $sql2);

while($row = mysqli_fetch_array($result)) {   

    $datearr[] = $row["date"];
    $alldates[] = $row['date'];

    if($row['name']!=''){
        $cname = $row['name'];
    }
    if($row['gender']!=''){
        $cgender = $row['gender'];
    }
    if($row['age']!=''){
        $cage = $row['age'];
    }
    if($row['height']!=''){
        $cheight = $row['height'];
    }

    if($row['waist']!=''){
        $waistdata[] = $row['waist'];
        $waistdate[] = $row['date']; 
    }
    if($row['weight']!=''){
        $weightdata[] = $row['weight'];
        $weightdate[] = $row['date']; 
    } 

    if($row['sgot']!=''){
        $sgotdata[] = (float)$row['sgot'];
        $sgotdate[] = $row['date']; 

        $temp['life_heal_id'] = 'sgot';
        $temp['value'] = (float)$row['sgot'];
        $temp['uom'] = 'U/l';
        $temp['date'] = $row['date']; 
        $liveroverAllData['organ'] = "Liver";      
        $liveroverAllData["tests"][] = $temp; 
    }
    if($row['sgpt']!=''){       
        $sgptdata[] = (float)$row['sgpt'];
        $sgptdate[] = $row['date']; 

        $temp['life_heal_id'] = 'sgpt';
        $temp['value'] = (float)$row['sgpt'];
        $temp['uom'] = 'U/l';
        $temp['date'] = $row['date'];
        $liveroverAllData['organ'] = "Liver"; 
        $liveroverAllData["tests"][] = $temp; 
    } 
    if($row['bilirubin']!=''){      
        $bilirubindata[] = (float)$row['bilirubin'];
        $bilirubindate[] = $row['date'];

        $temp['life_heal_id'] = 'bilirubin';
        $temp['value'] = (float)$row['bilirubin'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $liveroverAllData['organ'] = "Liver"; 
        $liveroverAllData["tests"][] = $temp;           
    }
    if($row['fattyliverultrasound']!=''){       
        $fattyliverultrasounddata[] = (float)$row['fattyliverultrasound'];
        $fattyliverultrasounddate[] = $row['date'];

        $temp['life_heal_id'] = 'fattyliverultrasound';
        $temp['value'] = (float)$row['fattyliverultrasound'];
        $temp['uom'] = 'unit';
        $temp['date'] = $row['date'];
        $liveroverAllData['organ'] = "Liver"; 
        $liveroverAllData["tests"][] = $temp;  
    } 
    if($row['fattyliverfirbscan']!=''){     
        $fattyliverfirbscandata[] = (float)$row['fattyliverfirbscan'];
        $fattyliverfirbscandate[] = $row['date'];

        $temp['life_heal_id'] = 'fattyliverfirbscan';
        $temp['value'] = (float)$row['fattyliverfirbscan'];
        $temp['uom'] = 'dB/m';
        $temp['date'] = $row['date'];
        $liveroverAllData['organ'] = "Liver"; 
        $liveroverAllData["tests"][] = $temp;  

    }
    if($row['fattyliverescore']!=''){       
        $fattyliverescoredata[] = (float)$row['fattyliverescore'];
        $fattyliverescoredate[] = $row['date'];

        $temp['life_heal_id'] = 'fattyliverescore';
        $temp['value'] = (float)$row['fattyliverescore'];
        $temp['uom'] = 'kPa';
        $temp['date'] = $row['date'];
        $liveroverAllData['organ'] = "Liver"; 
        $liveroverAllData["tests"][] = $temp;  
    } 


    if($row['hscrp']!=''){       
        $hscrpdata[] = (float)$row['hscrp'];
        $hscrpdate[] = $row['date'];

        $temp['life_heal_id'] = 'hscrp';
        $temp['value'] = (float)$row['hscrp'];
        $temp['uom'] = 'mg/L';
        $temp['date'] = $row['date'];

        $heartoverAllData["organ"] = "Heart";
        $heartoverAllData["tests"][] = $temp;

        $eyeoverAllData["organ"] = "Eye";
        $eyeoverAllData["tests"][] = $temp;
    } 
    if($row['triglycerides']!=''){       
        $triglyceridesdata[] = (float)$row['triglycerides'];
        $triglyceridesdate[] = $row['date'];

        $temp['life_heal_id'] = 'triglycerides';
        $temp['value'] = (float)$row['triglycerides'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $heartoverAllData["organ"] = "Heart";
        $heartoverAllData["tests"][] = $temp;
    } 
    if($row['hdl']!=''){       
        $hdldata[] = (float)$row['hdl'];
        $hdldate[] = $row['date'];

        $temp['life_heal_id'] = 'hdl';
        $temp['value'] = (float)$row['hdl'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $heartoverAllData["organ"] = "Heart";
        $heartoverAllData["tests"][] = $temp;
    } 
    if($row['ldl']!=''){       
        $ldldata[] = (float)$row['ldl'];
        $ldldate[] = $row['date'];

        $temp['life_heal_id'] = 'ldl';
        $temp['value'] = (float)$row['ldl'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $heartoverAllData["organ"] = "Heart";
        $heartoverAllData["tests"][] = $temp;
    } 
    if($row['homocysteine']!=''){       
        $homocysteinedata[] = (float)$row['homocysteine'];
        $homocysteinedate[] = $row['date'];

        $temp['life_heal_id'] = 'homocysteine';
        $temp['value'] = (float)$row['homocysteine'];
        $temp['uom'] = 'mcmol/L';
        $temp['date'] = $row['date'];
        $heartoverAllData["organ"] = "Heart";
        $heartoverAllData["tests"][] = $temp;
    } 


    if($row['creatinine']!=''){       
        $creatininedata[] = (float)$row['creatinine'];
        $creatininedate[] = $row['date'];

        $temp['life_heal_id'] = 'creatinine';
        $temp['value'] = (float)$row['creatinine'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $kidneyoverAllData["organ"] = "Kidney";
        $kidneyoverAllData["tests"][] = $temp;
    } 
    if($row['urea']!=''){       
        $ureadata[] = (float)$row['urea'];
        $ureadate[] = $row['date'];

        $temp['life_heal_id'] = 'urea';
        $temp['value'] = (float)$row['urea'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $kidneyoverAllData["organ"] = "Kidney";
        $kidneyoverAllData["tests"][] = $temp;
    } 
    if($row['sodium']!=''){       
        $sodiumdata[] = (float)$row['sodium'];
        $sodiumdate[] = $row['date'];

        $temp['life_heal_id'] = 'sodium';
        $temp['value'] = (float)$row['sodium'];
        $temp['uom'] = 'mEq/L';
        $temp['date'] = $row['date'];
        $kidneyoverAllData["organ"] = "Kidney";
        $kidneyoverAllData["tests"][] = $temp;
    } 
    if($row['potassium']!=''){       
        $potassiumdata[] = (float)$row['potassium'];
        $potassiumdate[] = $row['date'];

        $temp['life_heal_id'] = 'potassium';
        $temp['value'] = (float)$row['potassium'];
        $temp['uom'] = 'mmol/L';
        $temp['date'] = $row['date'];
        $kidneyoverAllData["organ"] = "Kidney";
        $kidneyoverAllData["tests"][] = $temp;
    } 
    if($row['uricacid']!=''){       
        $uricaciddata[] = (float)$row['uricacid'];
        $uricaciddate[] = $row['date'];

        $temp['life_heal_id'] = 'uricacid';
        $temp['value'] = (float)$row['uricacid'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $kidneyoverAllData["organ"] = "Kidney";
        $kidneyoverAllData["tests"][] = $temp;
    } 
    

    if($row['hba1c']!=''){       
        $hba1cdata[] = (float)$row['hba1c'];
        $hba1cdate[] = $row['date'];

        $temp['life_heal_id'] = 'hba1c';
        $temp['value'] = (float)$row['hba1c'];
        $temp['uom'] = '%';
        $temp['date'] = $row['date'];

        $pancreasoverAllData["organ"] = "Pancreas";
        $pancreasoverAllData["tests"][] = $temp;

        $eyeoverAllData["organ"] = "Eye";
        $eyeoverAllData["tests"][] = $temp;
    } 
    if($row['homa']!=''){       
        $homadata[] = (float)$row['homa'];
        $homadate[] = $row['date'];

        $temp['life_heal_id'] = 'homa';
        $temp['value'] = (float)$row['homa'];
        $temp['uom'] = 'unit';
        $temp['date'] = $row['date'];

        $pancreasoverAllData["organ"] = "Pancreas";
        $pancreasoverAllData["tests"][] = $temp;
    } 
    if($row['waist']!=''){       
        $waistdata[] = (float)$row['waist'];
        $waistdate[] = $row['date'];

        $temp['life_heal_id'] = 'waist';
        $temp['value'] = (float)$row['waist'];
        $temp['uom'] = 'W/H';
        $temp['date'] = $row['date'];

        $pancreasoverAllData["organ"] = "Pancreas";
        $pancreasoverAllData["tests"][] = $temp;

        $eyeoverAllData["organ"] = "Eye";
        $eyeoverAllData["tests"][] = $temp;
    } 
    if($row['fasting_glucose']!=''){       
        $fasting_glucosedata[] = (float)$row['fasting_glucose'];
        $fasting_glucosedate[] = $row['date'];

        $temp['life_heal_id'] = 'fasting_glucose';
        $temp['value'] = (float)$row['fasting_glucose'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $pancreasoverAllData["organ"] = "Pancreas";
        $pancreasoverAllData["tests"][] = $temp;
    } 
    if($row['ppsugar']!=''){       
        $ppsugardata[] = (float)$row['ppsugar'];
        $ppsugardate[] = $row['date'];

        $temp['life_heal_id'] = 'ppsugar';
        $temp['value'] = (float)$row['ppsugar'];
        $temp['uom'] = 'mg/dL';
        $temp['date'] = $row['date'];
        $pancreasoverAllData["organ"] = "Pancreas";
        $pancreasoverAllData["tests"][] = $temp;
    } 
        
    if($row['bp_systolic']!=''){       
        $bp_systolicdata[] = (float)$row['bp_systolic'];
        $bp_systolicdate[] = $row['date'];

        $temp['life_heal_id'] = 'bp_systolic';
        $temp['value'] = (float)$row['bp_systolic'];
        $temp['uom'] = 'mmHg';
        $temp['date'] = $row['date'];
        $eyeoverAllData["organ"] = "Eye";
        $eyeoverAllData["tests"][] = $temp;
    }

    if(!empty($liveroverAllData)) {       
        $testallLiver[]=  $liveroverAllData;         
    }
    if(!empty($heartoverAllData)) {        
        $testallheart[]=  $heartoverAllData;        
    } 
    if(!empty($kidneyoverAllData)) {       
        $testallkidney[]=  $kidneyoverAllData;         
    } 
    if(!empty($pancreasoverAllData)) {     
        $testallpancreas[]=  $pancreasoverAllData;          
    } 
    if(!empty($eyeoverAllData)) {        
        $testalleye[]=  $eyeoverAllData;         
    } 
      
    $liveroverAllData ='';
    $heartoverAllData ='';
    $kidneyoverAllData ='';
    $pancreasoverAllData ='';
    $eyeoverAllData ='';           
}

$allOrganTests[] = $testallLiver;
$allOrganTests[] = $testallkidney;
$allOrganTests[] = $testallheart;
$allOrganTests[] = $testallpancreas;
$allOrganTests[] = $testalleye;

/*echo "<pre>";
print_r($testallkidney);
echo "<br>";
print_r($allOrganTests);
echo "</pre>";*/

for($i=0; $i<=count($allOrganTests)-1; $i++){
    for($j=0; $j<=count($allOrganTests[$i])-1; $j++){ 
        $jsonallOrganTests = json_encode($allOrganTests[$i][$j]);
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => 'http://15.207.163.47/calculator',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS =>$jsonallOrganTests,
            CURLOPT_HTTPHEADER => array( 'Content-Type: application/json' ),
        ));   
        $response = curl_exec($curl);       
        $tempdecodeval[] = json_decode($response);   
        curl_close($curl);  
    }
    $decodeorganval[] =$tempdecodeval;
    $tempdecodeval ="";
}

for($i = 0; $i <= count($decodeorganval)-1; $i++ ){
    for($j = 0; $j <= count($decodeorganval[$i])-1; $j++ ){
        if($i == 0){
            $liveroveralldata[] = round((float)$decodeorganval[$i][$j]->data->value);
            $liveroveralldate[] = $testallLiver[$j]['tests'][0]['date']; 
        }

        if($i == 1){
            $kidneyoveralldata[] = round((float)$decodeorganval[$i][$j]->data->value);
            $kidneyoveralldate[] = $testallkidney[$j]['tests'][0]['date']; 
        }

        if($i == 2){
            $heartoveralldata[] = round((float)$decodeorganval[$i][$j]->data->value);
            $heartoveralldate[] = $testallheart[$j]['tests'][0]['date']; 
        }

        if($i == 3){
            $pancreasoveralldata[] = round((float)$decodeorganval[$i][$j]->data->value);
            $pancreasoveralldate[] = $testallpancreas[$j]['tests'][0]['date']; 
        }

        if($i == 4){
            $eyeoveralldata[] = round((float)$decodeorganval[$i][$j]->data->value);
            $eyeoveralldate[] = $testalleye[$j]['tests'][0]['date']; 
        }        
    }   
}

if(!empty($liveroveralldata)) {
    $liver_tests_name[]= 'Health Score';
    $liver_units_name[]= '%';
    $liver['graphdata'][] = $liveroveralldata;
    $liver['graphdate'][] = $liveroveralldate;  
}

if(!empty($sgotdata)) {
    $liver_tests_name[]= 'SGOT';
    $liver_units_name[]= 'U/l';
    $liver['graphdata'][] = $sgotdata;
    $liver['graphdate'][] = $sgptdate;    
}
if(!empty($sgptdata)) {
    $liver_tests_name[]= 'SGPT';
    $liver_units_name[]= 'U/l';
    $liver['graphdata'][] = $sgptdata;
    $liver['graphdate'][] = $sgptdate;    
}
if(!empty($bilirubindata)) {
    $liver_tests_name[]= 'Bilirubin';
    $liver_units_name[]= 'mg/dL';
    $liver['graphdata'][] = $bilirubindata;
    $liver['graphdate'][] = $bilirubindate;    
}
if(!empty($fattyliverultrasounddata)) {
    $liver_tests_name[]= 'Fatty Liver Ultra Sound Stage';
    $liver_units_name[]= 'unit';
    $liver['graphdata'][] = $fattyliverultrasounddata;
    $liver['graphdate'][] = $fattyliverultrasounddate;    
}
if(!empty($fattyliverfirbscandata)) {
    $liver_tests_name[]= 'Fatty Liver Fibroscan CAP score';
    $liver_units_name[]= 'dB/m';
    $liver['graphdata'][] = $fattyliverfirbscandata;
    $liver['graphdate'][] = $fattyliverfirbscandate;    
}
if(!empty($fattyliverescoredata)) {
    $liver_tests_name[]= 'Fatty Liver Fibroscan E score';
    $liver_units_name[]= 'kPa';
    $liver['graphdata'][] = $fattyliverescoredata;
    $liver['graphdate'][] = $fattyliverescoredate;    
}


if(!empty($kidneyoveralldata)) {
    $kidney_tests_name[]= 'Health Score';
    $kidney_units_name[]= '%';
    $kidney['graphdata'][] = $kidneyoveralldata;
    $kidney['graphdate'][] = $kidneyoveralldate;  
}

if(!empty($creatininedata)) {
    $kidney_tests_name[]= 'Creatinine';
    $kidney_units_name[]= 'mg/dL';
    $kidney['graphdata'][] = $creatininedata;
    $kidney['graphdate'][] = $creatininedate;    
}
if(!empty($ureadata)) {
    $kidney_tests_name[]= 'Urea';
    $kidney_units_name[]= 'mg/dL';
    $kidney['graphdata'][] = $ureadata;
    $kidney['graphdate'][] = $ureadate;    
}
if(!empty($sodiumdata)) {
    $kidney_tests_name[]= 'Sodium';
    $kidney_units_name[]= 'mEq/L';
    $kidney['graphdata'][] = $sodiumdata;
    $kidney['graphdate'][] = $sodiumdate;    
}
if(!empty($potassiumdata)) {
    $kidney_tests_name[]= 'Potassium';
    $kidney_units_name[]= 'mmol/L';
    $kidney['graphdata'][] = $potassiumdata;
    $kidney['graphdate'][] = $potassiumdate;    
}
if(!empty($uricaciddata)) {
    $kidney_tests_name[]= 'Uric acid';
    $kidney_units_name[]= 'mg/dL';
    $kidney['graphdata'][] = $uricaciddata;
    $kidney['graphdate'][] = $uricaciddate;    
}


if(!empty($heartoveralldata)) {
    $heart_tests_name[]= 'Health Score';
    $heart_units_name[]= '%';
    $heart['graphdata'][] = $heartoveralldata;
    $heart['graphdate'][] = $heartoveralldate;  
}
if(!empty($hscrpdata)) {
    $heart_tests_name[]= 'HSCRP';
    $heart_units_name[]= 'mg/L';
    $heart['graphdata'][] = $hscrpdata;
    $heart['graphdate'][] = $hscrpdate; 
}
if(!empty($triglyceridesdata)) {
    $heart_tests_name[]= 'TriGlycerides';
    $heart_units_name[]= 'mg/L';
    $heart['graphdata'][] = $triglyceridesdata;
    $heart['graphdate'][] = $triglyceridesdate;    
}
if(!empty($hdldata)) {
    $heart_tests_name[]= 'HDL';
    $heart_units_name[]= 'mg/L';
    $heart['graphdata'][] = $hdldata;
    $heart['graphdate'][] = $hdldate;    
}
if(!empty($ldldata)) {
    $heart_tests_name[]= 'LDL';
    $heart_units_name[]= 'mg/L';
    $heart['graphdata'][] = $ldldata;
    $heart['graphdate'][] = $ldldate;    
}
if(!empty($homocysteinedata)) {
    $heart_tests_name[]= 'Homocysteine';
    $heart_units_name[]= 'mcmol/L';
    $heart['graphdata'][] = $homocysteinedata;
    $heart['graphdate'][] = $homocysteinedate;    
}

if(!empty($pancreasoveralldata)) {
    $pancreas_tests_name[]= 'Health Score';
    $pancreas_units_name[]= '%';
    $pancreas['graphdata'][] = $pancreasoveralldata;
    $pancreas['graphdate'][] = $pancreasoveralldate;  
}

if(!empty($hba1cdata)) {
    $pancreas_tests_name[]= 'HbA1c';
    $pancreas_units_name[]= '%';
    $pancreas['graphdata'][] = $hba1cdata;
    $pancreas['graphdate'][] = $hba1cdate;
}
if(!empty($homadata)) {
    $pancreas_tests_name[]= 'HOMA IR';
    $pancreas_units_name[]= 'unit';
    $pancreas['graphdata'][] = $homadata;
    $pancreas['graphdate'][] = $homadate;
}
if(!empty($waistdata)) {
    $pancreas_tests_name[]= 'Waist To Height';
    $pancreas_units_name[]= 'W/H';
    $pancreas['graphdata'][] = $waistdata;
    $pancreas['graphdate'][] = $waistdate;
}
if(!empty($fasting_glucosedata)) {
    $pancreas_tests_name[]= 'Fasting Glucose';
    $pancreas_units_name[]= 'mg/dL';
    $pancreas['graphdata'][] = $fasting_glucosedata;
    $pancreas['graphdate'][] = $fasting_glucosedate;    
}
if(!empty($ppsugardata)) {
    $pancreas_tests_name[]= 'P P Sugar';
    $pancreas_units_name[]= 'mg/dL';
    $pancreas['graphdata'][] = $ppsugardata;
    $pancreas['graphdate'][] = $ppsugardate;    
}

if(!empty($eyeoveralldata)) {
    $eye_tests_name[]= 'Health Score';
    $eye_units_name[]= '%';
    $eye['graphdata'][] = $eyeoveralldata;
    $eye['graphdate'][] = $eyeoveralldate;  
}

if(!empty($hscrpdata)) {    
    $eye_tests_name[]= 'HSCRP';
    $eye_units_name[]= 'mg/L';
    $eye['graphdata'][] = $hscrpdata;
    $eye['graphdate'][] = $hscrpdate;    
}
if(!empty($hba1cdata)) {    
    $eye_tests_name[]= 'HbA1c';
    $eye_units_name[]= '%';
    $eye['graphdata'][] = $hba1cdata;
    $eye['graphdate'][] = $hba1cdate;     
}
if(!empty($waistdata)) {    
    $eye_tests_name[]= 'Waist To Height';
    $eye_units_name[]= 'W/H';
    $eye['graphdata'][] = $waistdata;
    $eye['graphdate'][] = $waistdate;     
}
if(!empty($bp_systolic)) {   
    $eye_tests_name[]= 'Blood Pressure';
    $eye_units_name[]= 'mmHg';
    $eye['graphdata'][] = $bp_systolicdata;
    $eye['graphdate'][] = $bp_systolicdate;     
}

$liver['id'] =1;
$liver['title'] ='Liver Graph';
$liver['sname'] = $liver_tests_name;
$liver['units'] = $liver_units_name;

$kidney['id'] =2;
$kidney['title'] ='Kidney Graph';
$kidney['sname'] = $kidney_tests_name;
$kidney['units'] = $kidney_units_name;

$heart['id'] =3;
$heart['title'] ='Heart Graph';
$heart['sname'] = $heart_tests_name;
$heart['units'] = $heart_units_name;

$pancreas['id'] =4;
$pancreas['title'] ='Pancreas Graph';
$pancreas['sname'] = $pancreas_tests_name;
$pancreas['units'] = $pancreas_units_name;

$eye['id'] =5;
$eye['title'] ='Eye Graph';
$eye['sname'] = $eye_tests_name;
$eye['units'] = $eye_units_name;

$newgraphdata[1] =   $liver;
$newgraphdata[2] =   $kidney;
$newgraphdata[3] =   $heart;
$newgraphdata[4] =   $pancreas;
$newgraphdata[5] =   $eye;

/*echo "<br/>";
echo '<pre>';
print_r($newgraphdata[1]);
echo '</pre>';
echo "<br/>";*/

while($row2 = mysqli_fetch_array($result2)) {
    $heartdatastr2 ='';
    $liverdatastr2 ='';
    $kidneydatastr2 ='';
    $Pancreasdatastr2 ='';
    $eyedatastr2 ='';
    $jsondate = $row2["date"];

    if($row2['report_file']!=''){
        $pdf = $row2['report_file'];
    }

    for($i=0; $i < count($heart_db_tests); $i++){
        $j = $heart_db_tests[$i];
        $row2[$j]=='' ? $heartdatastr2 = $heartdatastr2.''.' ' : $heartdatastr2 = $heartdatastr2.$row2[$j].' ';
    }

    for($i=0; $i < count($liver_db_tests); $i++){
        $j = $liver_db_tests[$i];
        $row2[$j]=='' ? $liverdatastr2 = $liverdatastr2.''.' ' : $liverdatastr2 = $liverdatastr2.$row2[$j].' ';
    }

    for($i=0; $i < count($kidney_db_tests); $i++){
        $j = $kidney_db_tests[$i];
        $row2[$j]=='' ? $kidneydatastr2 = $kidneydatastr2.''.' ' : $kidneydatastr2 = $kidneydatastr2.$row2[$j].' ';
    }

    for($i=0; $i < count($Pancreas_db_tests); $i++){
        $j = $Pancreas_db_tests[$i];
        $row2[$j]=='' ? $Pancreasdatastr2 = $Pancreasdatastr2.''.' ' : $Pancreasdatastr2 = $Pancreasdatastr2.$row2[$j].' ';
    }  

    for($i=0; $i < count($eye_db_tests); $i++){
        $j = $eye_db_tests[$i];
        $row2[$j]=='' ? $eyedatastr2 = $eyedatastr2.''.' ' : $eyedatastr2 = $eyedatastr2.$row2[$j].' ';
    }   
}

$latestliverval = explode(" ",substr_replace($liverdatastr2 ,"",-1));
$latestheartval = explode(" ",substr_replace($heartdatastr2 ,"",-1));
$latestkidneyval = explode(" ",substr_replace($kidneydatastr2 ,"",-1));
$latestPancreasval = explode(" ",substr_replace($Pancreasdatastr2 ,"",-1));
$latesteyeval = explode(" ",substr_replace($eyedatastr2 ,"",-1));

$mainjsondata =[];
$liverjsondata['organ'] = "Liver";
$kidneyjsondata['organ'] = "Kidney";
$heartjsondata['organ'] = "Heart";
$Pancreasjsondata['organ'] = "Pancreas";
$eyejsondata['organ'] = "Eye";

for($i=0; $i<count($liver_db_tests); $i++){
    if($latestliverval[$i]!=''){
        $livertest["life_heal_id"] =$liver_db_tests[$i];
        $livertest["value"] = floatval($latestliverval[$i]);
        $livertest["uom"] = $liver_unit[$i];;
        $livertest["date"]=$jsondate;
        $liverjsondata['tests'][]=$livertest;
    }
}

for($i=0; $i<count($heart_db_tests); $i++){
    if($latestheartval[$i]!=""){
        $hearttest["life_heal_id"] = $heart_db_tests[$i];
        $hearttest["value"] = floatval($latestheartval[$i]);
        $hearttest["uom"] = $heart_unit[$i];
        $hearttest["date"]=$jsondate;
        $heartjsondata['tests'][]=$hearttest;
    }
}

for($i=0; $i<count($kidney_db_tests); $i++){
    if($latestkidneyval[$i]!=""){
        $kidneytest["life_heal_id"] = $kidney_db_tests[$i];
        $kidneytest["value"] = floatval($latestkidneyval[$i]);
        $kidneytest["uom"] = $kidney_unit[$i];
        $kidneytest["date"]=$jsondate;
        $kidneyjsondata['tests'][]=$kidneytest;
    }
}

for($i=0; $i<count($Pancreas_db_tests); $i++){
    if($latestPancreasval[$i]!=""){
        $Pancreastest["life_heal_id"] = $Pancreas_db_tests[$i];
        $Pancreastest["value"] = floatval($latestPancreasval[$i]);
        $Pancreastest["uom"] = $Pancreas_unit[$i];
        $Pancreastest["date"]=$jsondate;
        $Pancreasjsondata['tests'][]=$Pancreastest;
    }
}

for($i=0; $i<count($eye_db_tests); $i++){
    if($latesteyeval[$i]!=""){
        $eyetest["life_heal_id"] = $eye_db_tests[$i];
        $eyetest["value"] = floatval($latesteyeval[$i]);
        $eyetest["uom"] = $eye_unit[$i];
        $eyetest["date"]=$jsondate;
        $eyejsondata['tests'][]=$eyetest;
    }
}

$mainjsondata[] = $liverjsondata;
$mainjsondata[] = $kidneyjsondata;
$mainjsondata[] = $heartjsondata;
$mainjsondata[] = $Pancreasjsondata;
$mainjsondata[] = $eyejsondata;

/*echo "<br/>";
echo '<pre>';
print_r($mainjsondata[1]);
echo '</pre>';
echo "<br/>";*/

for($i=0; $i<count($mainjsondata); $i++){
    $jsonDataEncoded = json_encode($mainjsondata[$i]);
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_URL => 'http://15.207.163.47/calculator',
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => '',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_POSTFIELDS =>$jsonDataEncoded,
      CURLOPT_HTTPHEADER => array(
        'Content-Type: application/json'
      ),
    ));

    $response = curl_exec($curl);
    curl_close($curl);  
    $decodeval[] = json_decode($response);
}

/*echo "<br/>";
echo '<pre>';
print_r($decodeval);
echo '</pre>';
echo "<br/>";*/

$mydata =[
    ["id"=>1,"organ"=>"Liver Health","qty"=>intval($decodeval[0]->data->value),"pic"=>"human-liver.png","desc"=>$decodeval[0]->data->possibility],
    ["id"=>2,"organ"=>"Kidney Health","qty"=>intval($decodeval[1]->data->value),"pic"=>"human-kidney.png","desc"=>$decodeval[1]->data->possibility],
    ["id"=>3,"organ"=>"Cardiac Health","qty"=>intval($decodeval[2]->data->value),"pic"=>"human-heart.png","desc"=>$decodeval[2]->data->possibility],
    ["id"=>4,"organ"=>"Diabetic Health","qty"=>intval($decodeval[3]->data->value),"pic"=>"human-pancreas.png","desc"=>$decodeval[3]->data->possibility],
     ["id"=>5,"organ"=>"Vision Health","qty"=>intval($decodeval[4]->data->value),"pic"=>"human-eye.png","desc"=>$decodeval[4]->data->possibility]              
];

$ta1 = count($decodeval[0]->matches);
$ta2 = count($decodeval[1]->matches);
$ta3 = count($decodeval[2]->matches);
$ta4 = count($decodeval[3]->matches);
$ta5 = count($decodeval[4]->matches);
$tt1=''; $tv1=''; $ts1=''; $tw1=''; $tr1=''; $tb1='';
$tt2=''; $tv2=''; $ts2=''; $tw2=''; $tr2=''; $tb2='';
$tt3=''; $tv3=''; $ts3=''; $tw3=''; $tr3=''; $tb3='';
$tt4=''; $tv4=''; $ts4=''; $tw4=''; $tr4=''; $tb4='';
$tt5=''; $tv5=''; $ts5=''; $tw5=''; $tr5=''; $tb5='';

for($t1 =0; $t1 < count($decodeval[0]->matches); $t1++){
    if($t1 < ($ta1-1)){
        $tt1.=$decodeval[0]->matches[$t1]->name.',';
        $tv1.=$decodeval[0]->matches[$t1]->value.',';
        $ts1.=$decodeval[0]->matches[$t1]->scoring.',';
        $tw1.=$decodeval[0]->matches[$t1]->test_weitage.',';
        $tr1.=$decodeval[0]->matches[$t1]->range.',';
        $tb1.=$decodeval[0]->matches[$t1]->behavior.',';
    }else{
        $tt1.=$decodeval[0]->matches[$t1]->name;
        $tv1.=$decodeval[0]->matches[$t1]->value;
        $ts1.=$decodeval[0]->matches[$t1]->scoring;
        $tw1.=$decodeval[0]->matches[$t1]->test_weitage;
        $tr1.=$decodeval[0]->matches[$t1]->range;
        $tb1.=$decodeval[0]->matches[$t1]->behavior;
    }
}

for($t2 =0; $t2 < count($decodeval[1]->matches); $t2++){
    if($t2 < ($ta2-1)){
        $tt2.=$decodeval[1]->matches[$t2]->name.',';
        $tv2.=$decodeval[1]->matches[$t2]->value.',';
        $ts2.=$decodeval[1]->matches[$t2]->scoring.',';
        $tw2.=$decodeval[1]->matches[$t2]->test_weitage.',';
        $tr2.=$decodeval[1]->matches[$t2]->range.',';
        $tb2.=$decodeval[1]->matches[$t2]->behavior.',';
    }else{
        $tt2.=$decodeval[1]->matches[$t2]->name;
        $tv2.=$decodeval[1]->matches[$t2]->value;
        $ts2.=$decodeval[1]->matches[$t2]->scoring;
        $tw2.=$decodeval[1]->matches[$t2]->test_weitage;
        $tr2.=$decodeval[1]->matches[$t2]->range;
        $tb2.=$decodeval[1]->matches[$t2]->behavior;
    }
}

for($t3 =0; $t3 < count($decodeval[2]->matches); $t3++){
    if($t3 < ($ta3-1)){
        $tt3.=$decodeval[2]->matches[$t3]->name.',';
        $tv3.=$decodeval[2]->matches[$t3]->value.',';
        $ts3.=$decodeval[2]->matches[$t3]->scoring.',';
        $tw3.=$decodeval[2]->matches[$t3]->test_weitage.',';
        $tr3.=$decodeval[2]->matches[$t3]->range.',';
        $tb3.=$decodeval[2]->matches[$t3]->behavior.',';
    }else{
        $tt3.=$decodeval[2]->matches[$t3]->name;
        $tv3.=$decodeval[2]->matches[$t3]->value;
        $ts3.=$decodeval[2]->matches[$t3]->scoring;
        $tw3.=$decodeval[2]->matches[$t3]->test_weitage;
        $tr3.=$decodeval[2]->matches[$t3]->range;
        $tb3.=$decodeval[2]->matches[$t3]->behavior;
    }
}

for($t4 =0; $t4 < count($decodeval[3]->matches); $t4++){
    if($t4 < ($ta4-1)){
        $tt4.=$decodeval[3]->matches[$t4]->name.',';
        $tv4.=$decodeval[3]->matches[$t4]->value.',';
        $ts4.=$decodeval[3]->matches[$t4]->scoring.',';
        $tw4.=$decodeval[3]->matches[$t4]->test_weitage.',';
        $tr4.=$decodeval[3]->matches[$t4]->range.',';
        $tb4.=$decodeval[3]->matches[$t4]->behavior.',';
    }else{
        $tt4.=$decodeval[3]->matches[$t4]->name;
        $tv4.=$decodeval[3]->matches[$t4]->value;
        $ts4.=$decodeval[3]->matches[$t4]->scoring;
        $tw4.=$decodeval[3]->matches[$t4]->test_weitage;
        $tr4.=$decodeval[3]->matches[$t4]->range;
        $tb4.=$decodeval[3]->matches[$t4]->behavior;
    }
}

for($t5 =0; $t5 < count($decodeval[4]->matches); $t5++){
    if($t5 < ($ta5-1)){
        $tt5.=$decodeval[4]->matches[$t5]->name.',';
        $tv5.=$decodeval[4]->matches[$t5]->value.',';
        $ts5.=$decodeval[4]->matches[$t5]->scoring.',';
        $tw5.=$decodeval[4]->matches[$t5]->test_weitage.',';
        $tr5.=$decodeval[4]->matches[$t5]->range.',';
        $tb5.=$decodeval[4]->matches[$t5]->behavior.',';
    }else{
        $tt5.=$decodeval[4]->matches[$t5]->name;
        $tv5.=$decodeval[4]->matches[$t5]->value;
        $ts5.=$decodeval[4]->matches[$t5]->scoring;
        $tw5.=$decodeval[4]->matches[$t5]->test_weitage;
        $tr5.=$decodeval[4]->matches[$t5]->range;
        $tb5.=$decodeval[4]->matches[$t5]->behavior;
    }
}

$tabledata =[
    ["id"=>1,"tests"=>$tt1,"Test_Value"=>$tv1,"Test_Score"=>$ts1,"Weightage"=>$tw1,"range"=>$tr1,"behavior"=>$tb1,"numerator"=>round((float)$decodeval[0]->numerator,2),"denominator"=>round((float)$decodeval[0]->denominator,2),"alltests"=>"SGOT,SGPT,Bilirubin,Fatty Liver Ultrasound,FibroScan CAP Score,FibroScan E Score"],

    ["id"=>2,"tests"=>$tt2,"Test_Value"=>$tv2,"Test_Score"=>$ts2,"Weightage"=>$tw2,"range"=>$tr2,"behavior"=>$tb2,"numerator"=>round((float)$decodeval[1]->numerator,2),"denominator"=>round((float)$decodeval[1]->denominator,2),"alltests"=>"Creatinine,Urea or Blood Urea Nitrogen (BUN),Sodium,Potassium,Uric acid"],

    ["id"=>3,"tests"=>$tt3,"Test_Value"=>$tv3,"Test_Score"=>$ts3,"Weightage"=>$tw3,"range"=>$tr3,"behavior"=>$tb3,"numerator"=>round((float)$decodeval[2]->numerator,2),"denominator"=>round((float)$decodeval[2]->denominator,2),"alltests"=>"HSCRP,Triglyceride,HDL,LDL,Homocysteine"],

    ["id"=>4,"tests"=>$tt4,"Test_Value"=>$tv4,"Test_Score"=>$ts4,"Weightage"=>$tw4,"range"=>$tr4,"behavior"=>$tb4,"numerator"=>round((float)$decodeval[3]->numerator,2),"denominator"=>round((float)$decodeval[3]->denominator,2),"alltests"=>"HbA1c,Homa-IR,Waist To Height,Fasting Glucose,Post Prandial Sugar"],

     ["id"=>5,"tests"=>$tt5,"Test_Value"=>$tv5,"Test_Score"=>$ts5,"Weightage"=>$tw5,"range"=>$tr5,"behavior"=>$tb5,"numerator"=>round((float)$decodeval[4]->numerator,2),"denominator"=>round((float)$decodeval[4]->denominator,2),"alltests"=>"HbA1c,Blood Pressure - Systolic,Waist To Height,HSCRP"]            
];

$totalTab = count($newgraphdata);
$cnt = 1; 
$gcnt = 1;
$xaxisnumber = count($datearr);

echo  "<script type=\"text/javascript\">";
    echo "var dict ={};";
    echo "var tablecontent ={};";
    echo "var graphcontent = {};";
    echo "var currentindex = 1;\n";
    echo "var totalTab = ".$totalTab.";\n";
    echo "var xaxisnumber = ".$xaxisnumber.";\n";
    echo "dict.ids = new Array();\n";
    echo "tablecontent.ids = new Array();\n";
echo  "</script>"; 

for($i=0; $i < count($mydata); $i++ ) {
    echo  "<script type=\"text/javascript\">";
        echo "var tempObj = [];"; 
        echo "var key = '';";   
        echo "key='".$mydata[$i]['id']."';";
        if($cnt < 2)

        echo "initialkey = '".$mydata[$i]['id']."';";   

        echo "var tempid = '".$mydata[$i]['id']."';";  
        echo "dict.ids.push(tempid);\n"; 
        echo "tempObj[\"hiddenid\"] = '".$mydata[$i]['id']."';"; 
        echo "tempObj[\"questionnum\"] = '".$cnt."';";  
        echo "tempObj[\"organ\"] = '".$mydata[$i]['organ']."';"; 
        echo "tempObj[\"qty\"] = '".$mydata[$i]['qty']."';"; 
        echo "tempObj[\"pic\"] = '".$mydata[$i]['pic']."';";        
        echo "tempObj[\"desc\"] = '".$mydata[$i]['desc']."';";
        echo "dict[key] = tempObj;";   
        //echo "alert(tempObj);";
        // echo "alert(tempObj['desc']);";
        //echo "alert('dict== '+dict[key]);";            
    echo  "</script>"; 
    $cnt++;
}

for($m=0; $m < count($tabledata); $m++ ) {
    echo  "<script type=\"text/javascript\">";
        echo "var tableObj = [];"; 
        echo "var tablekey = '';";   
        echo "tablekey='".$tabledata[$m]['id']."';";

        if($tnt < 2)
        echo "initialTkey = '".$tabledata[$m]['id']."';";   

        echo "var tempTid = '".$tabledata[$m]['id']."';";  
        echo "tablecontent.ids.push(tempTid);\n";        
        echo "tableObj[\"tests\"] = '".$tabledata[$m]['tests']."';"; 
        echo "tableObj[\"Test_Value\"] = '".$tabledata[$m]['Test_Value']."';";  
        echo "tableObj[\"Test_Score\"] = '".$tabledata[$m]['Test_Score']."';";
        echo "tableObj[\"Weightage\"] = '".$tabledata[$m]['Weightage']."';";
        echo "tableObj[\"range\"] = '".$tabledata[$m]['range']."';";
        echo "tableObj[\"behavior\"] = '".$tabledata[$m]['behavior']."';";
        echo "tableObj[\"numerator\"] = '".$tabledata[$m]['numerator']."';";
        echo "tableObj[\"denominator\"] = '".$tabledata[$m]['denominator']."';";
        echo "tableObj[\"alltests\"] = '".$tabledata[$m]['alltests']."';";
        echo "tablecontent[tablekey] = tableObj;";                   
    echo  "</script>"; 
    $tnt++;
}

?>

 <link rel="stylesheet"  href="<?php echo $this->getSkinUrl('css/circle.css') ?>">
<script src="<?php echo $this->getSkinUrl('js/highcharts.js') ?>"></script>
<script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>

<section class="main-newdashboard">    
    <?php       
    if($groupId == 4 || $groupId == 5){?> 
        <div> 
            <label>Select Patient:</label>              
            <ul id="my-list"> <?php echo $customerLi;?> </ul>
            <ul class="report_btn_list" id="report_btn_list">  </ul>
            <ul id="alldates"></ul>
        </div>
    <?php }
    ?>
     
	<section class="main-newdashboard-top">
        <div class="personal-information">
            <li>Name: <?php if(isset($cname)){ echo ucfirst($cname); } ?></li>
            <li>Age: <?php if(isset($cage)){ echo $cage; } ?></li>
            <li>Height: <?php if(isset($cheight)){ echo $cheight; } ?> inch</li>
            <li>Sex: <?php if(isset($cgender)){ echo ucfirst($cgender); } ?></li>
        </div>
		<div class="main-newdashboard-top-left">			
            <div class="organ-pic">
                <div class="mycheck" id="mycheck"></div>
                <img src="<?php echo Mage::getDesign()->getSkinUrl();?>images/dashboard-body.png" usemap="#humanbody"/>
            </div>            
		</div>

		<div class="main-newdashboard-top-right">
			<div class="newdashboard-top-head" id="give_shadow">
				<div class="arrow-box">
					<div class="arrow-box-inner" id="arrow_box_inner">
						
					</div>
				</div>
				<div class="newdashboard-top-head-content">
					<div class="top-head-content-left">
						<div id="graph_id">
                            <span id="circle_qty"></span>
                            <div class="slice">
                                <div class="bar"></div>
                                <div class="fill"></div>
                            </div>
                        </div>
					</div>
					<div class="top-head-content-right">
						<h2 id="organ_name"></h2>                        
					</div>
				</div>
			</div>
			<!--<div class="newdashboard-top-bottom">
				<p id="mytxt">If you want to live without disease you need a healthy Liver as it effect the whole of your body functioning.</p>
			</div>-->
		</div>
	</section>

    <div class="demotable" id="demotable">
        <table>
            <thead>
                <tr>
                    <td>Test Name</td>
                    <td>Test Value</td>
                    <td>Score</td>
                    <td> Weightage </td>
                    <td> Range </td>
                    <td> Interpretation </td>
                </tr>
            </thead>
            <tbody id="tablebody">   </tbody>
        </table>
    </div>

    <section class="main-newdashboard-bottom">
        <div class="newdashboard-bottom-top">
            <div class="weight-waist">
                <div class="weight_graphcnt" id="weight_graphcnt"></div>
                <div class="waist_graphcnt" id="waist_graphcnt"></div>           
            </div>
            <div class="graphtestbtn">
                <ul id="graphtestbtn">  </ul>
            </div>
            <div id="graph_container">  </div>
            
        </div>
    </section>
	
</section>
<script src="<?php echo $this->getSkinUrl('js');?>/jquery.alphaindex.js"></script>
<style type="text/css">
li{	list-style: none;	margin:0;	padding: 0;}
.main-container.col2-left-layout.newdashboard { background: #faf8f9;
    width: 100%;    max-width: 100%;}
.main-newdashboard{	width:96%;	margin-left:4%;}
.main-newdashboard-top{	margin-bottom: 1px;	display: flex;
	flex-wrap: wrap;	justify-content: space-between;}
.main-newdashboard-top-left{	width:350px;	box-sizing: border-box;
	padding:20px 30px 0 30px;	border-radius: 25px;	background: #fff;}
.main-newdashboard-top-right{	width: calc(100% - 390px);}
.newdashboard-top-head{	width:100%;	box-sizing: border-box;
	margin-top: 35px;	border-radius: 20px;	background: #fff;
	padding: 30px;	position: relative;}
.top-head-content-left {  margin: 0 auto;    width: 75%;}
.arrow-box{	position: absolute;	width: 100%;
	height: 100%;	left:0;	bottom: 0;}
.arrow-box-inner { display: flex; flex-wrap: wrap; 
    justify-content: space-between;  align-items: center; height: 100%;}
.arrow-box-inner li{display: inline-block; font-size: 3.5rem;
	padding: 0 15px; cursor: pointer;}
.arrow-box-inner li:nth-child(2){	color:#269a9b;}
.top-head-content-right{text-align: center;}
.top-head-content-right h2{	font-size: 2.5rem;	color:#269a9b;	}
.top-head-content-right span{display: inline-block;	color: #269a9b;
	font-size: 1.2rem;	cursor: pointer;}
.newdashboard-top-bottom p{font-size: 1.2rem;}
.demotable table{box-sizing: border-box;  width:100%; background: #fff;  margin-bottom: 25px;box-shadow: 0 0 9px 2px rgba(0,0,0,0.1);  border: 5px solid #269a9b; }
.demotable table tr td{padding:8px 20px; border-bottom:1px solid rgba(0,0,0,0.2);}
.demotable thead{background:#269a9b;  color: #fff;}
.highlight { color:#fff;  background:#269a9b !important;}
ul.alpha-index-list li{background:rgba(255,255,255,0.4);}
.csmall{font-size: 10px; display: inline-block; padding: 0 6px;}
ul#alldates li{ display: inline-block;  width:auto; margin:15px 25px 5px 0;
    font-size: 1.1em;    padding: 6px 15px; cursor:pointer;
    border: 1px solid silver;  background:rgba(255,255,255,0.4);}
.na{ color: darkgray;  font-size: 13px;}
.demotable a { display: inline-block;  padding: 8px 10px; background: #23b3b4;
    color: #fff; font-size: 16px;}
.organ-pic{  position: relative;}
.mycheck{position: absolute; left:0; top:0; width:100%; height: 100%;} 
.weight-waist{ display: flex;   flex-wrap: wrap;  justify-content: space-between;
        margin-bottom: 20px; } 
.waist_graphcnt, .weight_graphcnt{ width:49%; } 

.graphtestbtn ul, .graphtestbtn ul li{  list-style: none;}
.graphtestbtn ul li{ display: inline-block; padding: 8px;  border:1px solid #ccc;
    cursor: pointer;   font-size: 13px;}
.graphtestbtn{background: #fff; display: flex; justify-content: center;
    box-sizing: border-box; padding: 14px;}
.toggle_na{cursor: pointer; font-weight: 800; } 
.showna{display: none;} 
.personal-information{width:100%; display: flex; justify-content: space-between; padding: 10px 0;}             
</style>

<script type="text/javascript">
jQuery(document).ready(function() {    
    jQuery('#my-list').makeAlphaIndex({
        activateFirstIndex: false,
        showItemsCount: false
    });
}); 


function showReportbtn(custId,mobileNo) {    
    jQuery('li').removeClass("highlight");
    jQuery('#'+custId).addClass("highlight");  
    var formData = {
            'mobileno':mobileNo,            
            'custid':custId  
        };
    jQuery.ajax({
        url: "<?php echo Mage::getBaseUrl().'override/index/getalldates' ?>",
        type:'POST',
        data: formData  
        })
        .done(function(data){            
            jQuery('#alldates').html(data);                      
            console.log(data);                                          
        })                  
        .fail(function(textStatus){
            alert(textStatus)
        }); 
}
function editScreen(cId,mobiNo,custdate) {                         
    var redirect = "<?php echo Mage::getBaseUrl().'customer/account/organhealth?custid=' ?>"+cId+"&mno="+mobiNo+"&cudate="+custdate; 
    window.location.href = redirect;
   //var redirect = "<?php echo '/customer/account/organhealth?custid=' ?>"+cId+"&mno="+mobiNo+"&cudate="+custdate;   
   // window.history.pushState('dahsboard','',redirect);       
}    
</script>

<script type="text/javascript"> 

<?php
$maingraphdata = json_encode($newgraphdata);
echo "var js_maingraphdata = ". $maingraphdata . ";\n";
?>

function nextclicked(currentindex, initialgkey){
    //alert('clicked== '+currentindex);
    if(currentindex < totalTab){       
        currentindex++; 
        //var mykey = dict['ids'][(currentindex-1)];       
        changescreen(currentindex,0); 
        }
    }

 //////////////PREVIOUS CLICKED//////////////////////////////////

function prevclicked(currentindex, initialgkey){
    if(currentindex > 1){       
        currentindex--;
        //var mykey = dict['ids'][(currentindex - 1)]; 
        changescreen(currentindex,0);
        }
    }  

 function  gaphCnt(currindex,graphkey){     
 //alert( `gaphCnt gkey ${gkey}`);  
    jQuery("[data-target]").removeClass("highlight"); 
    jQuery(`[data-target='${currindex}${graphkey}']`).addClass("highlight");     
    const arrStr = js_maingraphdata[currindex]['graphdata'][graphkey];
    const gdata = arrStr.map((i) => Number(i)); 
    Highcharts.chart('graph_container', {
        chart:{
            type:'line',
            zoomType:'x'            
        },
        credits:{
            enabled:false
        },
        title:{
            text: js_maingraphdata[currindex]['title']
        },
        background: {
    		color: 'red'   
		},
        colors:['#79b4e5'],
        xAxis: {
            categories: js_maingraphdata[currindex]['graphdate'][graphkey]
        },
        yAxis: {
            title: {
                text:'Date Value'
            }
        },
        tooltip: {
            valueSuffix: ' '+js_maingraphdata[currindex]['units'][graphkey]
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: js_maingraphdata[currindex]['sname'][graphkey],
            data: gdata
        }]
    });
 } 


<?php
echo "var js_waistdata = ".json_encode($waistdata). ";\n";
echo "var js_waistdate = ".json_encode($waistdate). ";\n";
echo "var js_weightdata = ".json_encode($weightdata). ";\n";
echo "var js_weightdate = ".json_encode($weightdate). ";\n";
?> 
js_waistdata = js_waistdata.map(Number);
js_weightdata = js_weightdata.map(Number);

function  waistgaph(){    
    Highcharts.chart('waist_graphcnt', {
            title: {
            text: 'Waist Chart',
            x: -20 //center
        },
        credits:{
            enabled:false
        },
        xAxis: {
            categories: js_waistdate
        },
        yAxis: {
            title: {
                text: 'Waist in (inch)'
            }
        },
        tooltip: {
            valueSuffix: ' inch'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Waist',
            data: js_waistdata
        }]
    
        });
 }


 function  weightgaph(){    
    Highcharts.chart('weight_graphcnt', {
            title: {
            text: 'Weight Chart',
            x: -20 //center
        },
        credits:{
            enabled:false
        },
        xAxis: {
            categories: js_weightdate
        },
        yAxis: {
            title: {
                text: 'Weight in (Kg)'
            }
        },
        tooltip: {
            valueSuffix: ' kg'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Weight',
            data: js_weightdata
        }]
    
        });
 }       
</script>


<script type="text/javascript">
	 function emptyClass(){   
        document.getElementById('graph_id').className ='';
    }

    function whiteall(){
    	for(x in dict){
    	//alert(x+" jjjjjj  "+dict[x]['name']);
    	document.getElementById(x).style.background="#ccc";
    	}
	}

    function downloadPdf(pdf){
        var baseUrl = window.location.origin;
        var pdfPath = baseUrl+'/media/upload/'+pdf;
        //alert(pdfPath);

        var req = new XMLHttpRequest();
        req.open("GET", pdfPath, true);
        req.responseType = "blob";

        req.onload = function (event) {
        var blob = req.response;
        console.log(blob.size);
        var link=document.createElement('a');
        link.href=window.URL.createObjectURL(blob);
        link.download=pdf;
        link.click();
        };

        req.send();
    }

	function changescreen(currentindex,graphkey){
        //alert( `changescreen currentindex ${currentindex}`);       
		gaphCnt(currentindex,graphkey);
        waistgaph();
        weightgaph();		
		emptyClass();
		document.getElementById('graph_id').classList.add("c100", "big", "p"+dict[currentindex]['qty']);
		document.getElementById('organ_name').innerHTML = dict[currentindex]['organ'];	
	document.getElementById('circle_qty').innerHTML= dict[currentindex]['qty']+"%";
    document.getElementById('mycheck').innerHTML = "<img src=\"<?php echo Mage::getDesign()->getSkinUrl();?>images/"+dict[currentindex]['pic']+"\"/>"; 

	if(currentindex==1){
        document.getElementById('arrow_box_inner').innerHTML = "<li></li>"+
            "<li onClick=\"nextclicked('"+currentindex+"','"+graphkey+"');\">&gt;</li>";

    }else if(currentindex==totalTab){
        document.getElementById('arrow_box_inner').innerHTML = "<li onClick=\"prevclicked('"+currentindex+"','"+graphkey+"');\">&lt;</li>"+
            "<li></li>";

    }else if(currentindex>1 && currentindex<totalTab){
        document.getElementById('arrow_box_inner').innerHTML = "<li onClick=\"prevclicked('"+currentindex+"','"+graphkey+"');\">&lt;</li>"+
            "<li onClick=\"nextclicked('"+currentindex+"','"+graphkey+"');\">&gt;</li>";
    }

        var testbtnrow='';
        for(var k=0; k < js_maingraphdata[currentindex]['sname'].length; k++){
            testbtnrow += `<li data-target="${currentindex}${k}" onClick="gaphCnt(${currentindex},${k});">${js_maingraphdata[currentindex]['sname'][k]}</li>`;
        }
        document.getElementById('graphtestbtn').innerHTML = testbtnrow;

        var organ_tests = tablecontent[currentindex]['tests'].split(",");
        var tests_value = tablecontent[currentindex]['Test_Value'].split(",");
        var tests_score = tablecontent[currentindex]['Test_Score'].split(",");
        var tests_weightage = tablecontent[currentindex]['Weightage'].split(",");
        var trange = tablecontent[currentindex]['range'].split(",");
        var tbehavior = tablecontent[currentindex]['behavior'].split(",");
        var alltests = tablecontent[currentindex]['alltests'].split(",");

        let difference = alltests.filter(x => organ_tests.indexOf(x) === -1);
        var trow='';
        var trowna='';

        for(var k=0; k < organ_tests.length; k++){             
            trow += `<tr><td>${organ_tests[k]}</td><td>${tests_value[k]}</td><td>${tests_score[k]}</td><td>${tests_weightage[k]}</td><td>${trange[k]}</td><td>${tbehavior[k]}</td></tr>`;
        } 

        if(difference.length!=0){           
            for(var y=0; y < difference.length; y++){
                trowna += `<tr class="showna">
                        <td>${difference[y]}</td>
                        <td><span class="na">N/A</span></td>
                        <td><span class="na">N/A</span></td>
                        <td><span class="na">N/A</span></td>
                        <td><span class="na">N/A</span></td>
                        <td><span class="na">N/A</span></td>
                    </tr>`;
            }
            trow += `<tr><td colspan="6"><span class="toggle_na">Tests with no data <span class="toggle_na_2">+</span></span>${trowna}</td></tr>`; 
            
        } 

        <?php 
        if(isset($pdf)){
            $pdftag =  '<a href="javascript:void(0)" onclick="downloadPdf(""'.$pdf.'"")" title="'.$pdf.'">Download Report</a>';
        }else{
            $pdftag ='';
        }
        ?>

        trow += `<tr>               
                <td>Numerator = ${tablecontent[currentindex]['numerator']}</td> 
                <td>Denominator = ${tablecontent[currentindex]['denominator']}</td>
                <td colspan="2"><?php echo $pdftag; ?></td>
                <td colspan="2">
                <a href="https://lifeheal.in/testreport/">Submit Report</a>
                </td> 
                </tr>`; 
        document.getElementById('tablebody').innerHTML = trow; 

        jQuery(`[data-target='${currentindex}${graphkey}']`).addClass("highlight");


        shownaData();      
   

	}
	changescreen(currentindex,0);
    
   function shownaData(){
        jQuery(".toggle_na").click(function(){       
            jQuery(".showna").toggle(function(){           
                if(jQuery(".showna").is(":visible")){
                   jQuery('.toggle_na_2').text('-');
                } else{
                    jQuery('.toggle_na_2').text('+');
                }
            });
        });
    }
</script>