  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>
                
               
<?php    $uniqueCustomersJson = Mage::helper('heal')->getUniqueCustomersJson();  ?>
  <script>
 

  var customers = <?php echo $uniqueCustomersJson;?>;
  
  $( function() {
    $( "#datepicker-from" ).datepicker();
	$( "#datepicker-to" ).datepicker();
	   $("#tooltip-1").tooltip();
	  
	   $("#customers").select2({
				  data: customers
				});
				
	 
	    <?php if(isset($_POST['customers'])) { ?>
		
		$("#customers").val("<?php echo  $_POST['customers'];?>");
	        $('#customers').trigger('change');
	 
			<?php } ?>
	   
	    
  } );
  </script>
  
	<style>	

.sticky {
  position: sticky;
  top: 0;
  width: 100%;
}

.sticky + .table-scroll {
  padding-top:0px;
}
		.table-scroll{float: left;
width: 100%;
padding: 0px;
margin-bottom: 20px;
}
		.Theadbox{float: left;width: 100%;background: #d7d4d4;}
		#datewise{width: 100%;
  padding: 50px 0;
  text-align: center;
  background-color: lightblue;
  margin-top: 20px;}
		
	.select2-container {
    box-sizing: border-box;
    display: inline-block;
    margin: 0;
    position: relative;
    vertical-align: middle;
        width: 100% !important;
    height: 35px;
    line-height: 35px;
    padding: 0px 10px;
}
		.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 35px;
		}
		.select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 26px;
    position: absolute;
    top:5px;
    right: 10px;
    width: 20px;
}
		.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 35px;
}
	.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin: 4px;
}
	.breadcrumbs{display:none;}	
	#myHeaderhead, #oldfooter, .navbar{font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    max-width: 100% !important;
    margin: 0 !important;
	}
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;text-align: center;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;text-align: center;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}

#customerMealResport{text-align: center;font-size: 20px;margin: 30px auto;
	text-transform: capitalize;width: 100%;display: block;}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #a61d3f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  max-width:560px;
  margin:auto;
}
h2{font-weight: normal;margin: auto;
width: 560px;font-size:17px;
height:60px;color: #000;
line-height:60px;}
		.tabledata td, .tabledata th{padding:10px;font-size:18px;width: auto;}
		.dataalign{    float: left;
    text-align: center;
    width: 33%;
    margin: 10px auto}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}

.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}
@media print
{
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 18px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
}

@media all {
.page-break { display: none; }
}

@media print {
.page-break { display: block; page-break-before: always; }
}
@media screen and (min-width:260px) and (max-width:767px){
	.tabledata{width:100%;overflow:scroll;}
	#myHeadertop, .table-scroll{width:600px,font-size: 14px;}
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 68%;
}	
	.dataalign{float: left;
text-align: center;
width: 100%;
margin: 10px;}
#printdate select {
    font-size: 17px;
    margin: 10px;
    width: 68%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
@media screen and (min-width:768px) and (max-width:999px){
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}

}

.hideme{display:none;}
</style>
<?php
$choosenDate='';
$choosenCity='';
$msg ="";
$foundWeeklyReport='no';
$settingModel = Mage::getModel("setting/setting")->load(1);	
$weekNumber = $settingModel->getValue();
if (isset($_POST["submit"]) )
{
	 
	  $choosenCustomer    = $_POST['customers'];
          
         
           if($choosenCustomer=='')
          {
             $msg.="Please select the customer<br>" ;
          }
		  
		  $weekNumber = $_POST["weekno"];
}
	

//echo "Week number--".$weekNumber; echo "<br>";
?>
<div class="noprint">
<form method="POST" action="<?php echo Mage::getBaseUrl().'customer-weekly-report';?>" >

<h1 class="noprint" style="text-align: center;font-size: 24px;margin-bottom: 30px;text-transform: capitalize;">Customer Weekly Meal Report</h1>
<table width="1000" border="1" align="center" id="printdate" style="padding-left: 20px;margin:auto;padding-top:10px;" rules="none">

  <tbody class="noprint">
       
	  <tr>  
               <td class="dataalign">
				<span style="width:100%;float:left;height: 35px;line-height: 35px;">Select Customer:</span>
				 </td>
				<td class="dataalign">
                     <select id="customers" name="customers"></select>
                </td>
		 </tr>
		<tr> <td class="dataalign">
				   
                <span style="width:100%;float:left;height: 35px;line-height: 35px;">Week No:</span>
				 </td>
				 <td class="dataalign"><input type="text" name="weekno" id="weekno" value="<?php echo $weekNumber;?>" /></td>
               
 	     </tr>
		 <tr >
		  <td colspan="2" style="float: left;margin: 10px auto;text-align: right;width: 33%;"><input type="submit" name="submit" value="Submit" style="padding: 0px 10px;background: #c31f41;border: 1px solid #a61d3f;color: #fff;font-size: 14px;height: 35px;border-radius: 4px;line-height: 35px;text-align:center;width:100%;"></td>
        </tr>
        <?php if($msg!=''){?>
        <tr><td colspan="2"  style="float: left;margin: auto;text-align: left;width: 100%;color:red"><?php echo $msg;?></td>
	  
	  </tr>
        <?php } ?>
     
  </tbody>
</table>
</form>
</div>
<?php 

if (isset($_POST["submit"]) && $_POST['customers']!='')
{
	 $requiredWeekNumber = trim($_POST["weekno"]);
	 
	 $settingModel->setValue($requiredWeekNumber);
	 $settingModel->save();
    $mealsByWeekNumber=array();
        $customerEmail  = strtolower($_POST['customers']);
       //$customerEmail  =  '9599912540@curemydiabetes.com';//
        $msg='';
        $dbRead      = Mage::getSingleton('core/resource')->getConnection('core_read');
        $selectDatewiseOrders='';
        $cuccrentDate = date('Y-m-d');
      
        if($customerEmail!='')
        {
           $selectDatewiseOrders= "select * from healorder where email='$customerEmail' order by formatted_orderdate asc";
           $customerResult = $dbRead->fetchAll($selectDatewiseOrders);
        }
        else
        {
           $msg="Please select the customer name";

        }



        if($msg=='' && count($customerResult)>0)
        {
             $customerEmail = $_POST['customers'];
            //   $customerEmail  =  '9599912540@curemydiabetes.com';//
             $customer = Mage::getModel("customer/customer"); 
             $customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
             $customer->loadByEmail($customerEmail);
             $name = $customer->getFirstname(). " ".  $customer->getLastname();  
             
             
            
         foreach($customerResult as $row)
         { 
                 $orderId   =  $row['id']; 
                 $orderInfo =  Mage::getModel("heal/order")->load($orderId);
                 $customerEmail = $orderInfo->getEmail();
               
                $orderFormattedDate = $orderInfo->getFormattedOrderdate();
                
                $weekNumber = getWeeknumber($orderFormattedDate ); 
                 
             //$weekNumber =   $requiredWeekNumber;
             
                 if(array_key_exists($weekNumber,$mealsByWeekNumber) )
                 {
                     $mealsByWeekNumber[$weekNumber][]= $orderId;
                 }
                 else
                 {
                      $mealsByWeekNumber[$weekNumber][0]= $orderId;
                 }
            }
           $mealsInformation = getWeeklyItemsArray($mealsByWeekNumber);   
          foreach($mealsInformation as $week => $finalArray)
          {
			  if($week==$requiredWeekNumber)
			  {
				  $foundWeeklyReport='yes';
			  }
		  }			  
            ?>
<div class="print">
<span id="customerMealResport"><b><?php echo $name;?> </b> Weekly Meal Report </b></span>
    <div class="tabledata">
	
	
	<?php if($foundWeeklyReport=='yes'){?>
	<div class="Theadbox" id="myHeadertop">
       <div  style="font-weight:600;float: left;width:20%;padding: 10px;">Week</div><div  style="font-weight:600;float: left;width: 14%;padding: 10px;">Cal</div><div  style="font-weight:600;float: left;width: 14%;padding: 10px;">Protein (Gm)</div><div  style="font-weight:600;float: left;width: 14%;padding: 10px;">Fat (Gm)</div><div  style="font-weight:600;float: left;width: 14%;padding: 10px;">Carbs (Gm)</div><div  style="font-weight:600;float: left;width: 14%;padding: 10px;">Fiber (Gm)</div><div style="font-weight:600;float: left;width: 10%;padding: 10px;">Weight</div>
    </div>
	<?php } ?>
		<div class="table-scroll">
    <?php 
  
          foreach($mealsInformation as $week => $finalArray)
          {
			  if($week==$requiredWeekNumber)
			  {
				  $foundWeeklyReport='yes';
              ?>
            <div id="<?php echo $week;?>" class="collapsiblereport" collapsiblereport="<?php echo $week;?>" style="width: 100%;float: left;">
                 <div  style="float: left;width: 20%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><span style="height: 14px;width: 14px;display: inline-block;position: relative;color: white;border: 2px solid white;border-radius: 14px;box-shadow: 0 0 3px #444;box-sizing: content-box;text-align: center;font-family: 'Courier New', Courier, monospace;line-height: 14px;content: '+';background-color: #31b131;">&#43;</span> Week <?php echo $week;?></div>
                 <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><?php echo (int)$finalArray['totalDesc']['sumCal'];?></div>
                 <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><?php echo (int)$finalArray['totalDesc']['sumProt'];?></div>
                 <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><?php echo (int)$finalArray['totalDesc']['sumFat'];?></div>
                 <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><?php echo (int)$finalArray['totalDesc']['sumCarbs'];?></div>
                 <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;"><?php echo (int)$finalArray['totalDesc']['sumFiber'];?></div>
                 <div style="float: left;width: 10%;padding: 10px;border-bottom: 1px solid #ccc;border-right: 1px solid #ccc;height: 58px;line-height: 50px;">&nbsp;</div>
            </div>
	        <div id="datewise_<?php echo $week;?>" style="width: 100%;float: left;display: none;" class="collapsiblereportprint">
				<?php
			 
			  foreach($finalArray['weeklyItems'] as $dayMealInfo){ ?>
                     	
						
                                   <div style="float: left;width: 20%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['date'];?></div>
                                   <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['calory'];?></div>
                                   <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['protein'];?></div>
                                   <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['fat'];?></div>
                                   <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['carbs'];?></div>
                                   <div style="float: left;width: 14%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;"> <?php echo (int)$dayMealInfo['fiber'];?></div>
                                   <div style="float: left;width: 10%;padding: 10px;border-bottom: 1px solid #ccc;background: rgb(243, 242, 241);border-right: 1px solid #ccc;height: 58px;line-height: 50px;">&nbsp;</div>
                                  
                              

                         <?php } ?>  

		</div>
            
			  <?php }
          }
    ?>
      
           
			 </div> 
     <div>
	     <?php if($foundWeeklyReport=='yes'){?>
		 <div colspan="7" style="text-align:center" class="noprint"> <input type="button" value="Print" 
		onclick="changeprint();" style="padding: 0px 10px;background: #c31f41;border: 1px solid #a61d3f;color: #fff;font-size: 14px;height: 35px;line-height: 35px;text-align:center;    margin: auto 10px;"/>
		 <?php } else {  ?>	 
		 <div style="text-align: center">No meal record found.</div>
		 <?php }?>
		 </div>
			</div>
  
       
 <?php
}
else {  ?>
            <div style="text-align: center">No meal record found.</div>
<?php }

}


function getWeeknumber($checkDate)
{
    $tmpDate = explode("-", $checkDate);
    $date  = mktime(0, 0, 0, $tmpDate[1], $tmpDate[2], $tmpDate[0]);
   return $week  = (int)date('W', $date);
    
}

function getMealDate($checkDate)
{
    $tmpDate = explode("-", $checkDate);
    $date  = mktime(0, 0, 0, $tmpDate[1], $tmpDate[2], $tmpDate[0]);
    $week  = (int)date('W', $date);
    $dateToShow   = date('d',$date);
    $day = date('D',$date);
    $month = date('M',$date);
    $year = date('y',$date);
    
    return $dateToShow.'-'.$month.'-'.$year.' ( '. $day.' )'; 
}


  
  
  function getWeeklyItemsArray($mealsByWeekNumber)
  {
      $finalArray = array();
      
         foreach($mealsByWeekNumber as $weekNumber=>$weekItemArray)
         {  
             
          $recordCount=0;
         $weekCount=1;
         $weekDay=0;  
         $weekDayCounter=0;

         $allDinnerCal=0;
         

         $allBreakfastCal=0;
         
         $allLunchCal=0;
        

         $allHighteaCal=0;
         

         $totalCal=0;
         $totalProteinGm=0;
         $totalFatGm=0;
         $totalCarbohydreteGm=0;
         $totalFiberGm=0;
         
         $countWeeklyMeals=0;
         
         $weeklyItems = array();
             foreach($weekItemArray as $key=>$orderId)
             {
                
                $rowTotalCal=0;
                $rowTotalFiberGm=0;
                $rowTotalProteinGm=0;
                $rowTotalFatGm=0;
                $rowTotalCarbohydreteGm=0;
                 
                 $countWeeklyMeals = count($weekItemArray);
            
                 $recordCount++;  
                 $weekNumer = $weekNumber;

                // $orderId   =  $row['id']; 
                 $orderInfo =  Mage::getModel("heal/order")->load($orderId);
                 
                 $customerEmail = $orderInfo->getEmail();
                 $orderFormattedDate = date_create($orderInfo->getFormattedOrderdate());
              
                 $orderDate = date_format($orderFormattedDate,'d-M-Y');

                 $dinnerTotalCalories = $orderInfo->getDinnerTotalCalories(); $rowTotalCal+=$dinnerTotalCalories;
                 
                 $allDinnerCal+= $dinnerTotalCalories; 
                
                 $breakfastTotalCalories = $orderInfo->getBreakfastTotalCalories();  $rowTotalCal+=$breakfastTotalCalories;
                
                 $allBreakfastCal+=     $breakfastTotalCalories; 
                
                 $lunchTotalCalories = $orderInfo->getLunchTotalCalories();    $rowTotalCal+=$lunchTotalCalories;
                 
                 $allLunchCal+=     $lunchTotalCalories; 
                
                 $highteaTotalCalories = $orderInfo->getHighteaTotalCalories();  $rowTotalCal+=$highteaTotalCalories;
                 
                 $allHighteaCal+=     $highteaTotalCalories; 
                

                  $totalCal+=$rowTotalCal;
                  
                  
                  $weekDayToShow = getMealDate($orderInfo->getFormattedOrderdate());
                  
                 
                  $rowTotalCarbohydreteGm =  $orderInfo->getTotalCarbohydrates();
                  $rowTotalProteinGm      =  $orderInfo->getTotalProtein();
                   $rowTotalFatGm          =  $orderInfo->getTotalFat();
                  $rowTotalFiberGm        = $orderInfo->getTotalFiber();
                  
                  $totalCarbohydreteGm+= $rowTotalCarbohydreteGm;
                  $totalProteinGm+= $rowTotalProteinGm;
                 // echo "totalProteinGm=".$totalProteinGm.'------rowTotalProteinGm='.$rowTotalProteinGm;echo "<br>";
                  $totalFatGm+= $rowTotalFatGm;
                  $totalFiberGm+= $rowTotalFiberGm;
                  
                  $weeklyItems[] = array('date'=>$weekDayToShow,'calory'=>$rowTotalCal,'carbs'=>$rowTotalCarbohydreteGm,'protein'=>$rowTotalProteinGm,'fat'=>$rowTotalFatGm,'fiber'=>$rowTotalFiberGm);
            
               
       }
       
        $finalArray[$weekNumer]['totalDesc'] = array('sumCal'=>$totalCal,'sumProt'=>$totalProteinGm,'sumFat'=>$totalFatGm,'sumCarbs'=>$totalCarbohydreteGm,'sumFiber'=>$totalFiberGm) ;
        $finalArray[$weekNumer]['weeklyItems'] = $weeklyItems;
    }
  
      
      
       return $finalArray;
  }
			

?>
 
	 </div> 
</div>
<script>
	window.onscroll = function() {myFunction()};

var header = document.getElementById("myHeadertop");
var sticky = header.offsetTop;
function changeprint()
	{
		$(".collapsiblereportprint").show();
		print();
	}
	
	
	function myFunctiontophead() {
  if (window.pageYOffset > sticky) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}
$(document).ready(function(){
  $(".collapsiblereport").click(function(){
	    var title = $(this).attr("collapsiblereport");
	    
	  	$("#datewise_"+title).toggle();
  });
});
</script>
