<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>
                
               
<?php    $uniqueCustomersJson = Mage::helper('heal')->getUniqueCustomersJson();  ?>
  <script>
 

  var customers = <?php echo $uniqueCustomersJson;?>;
  
  $( function() {
    $( "#datepicker-from" ).datepicker();
	$( "#datepicker-to" ).datepicker();
	   $("#tooltip-1").tooltip();
	  
	   $("#customers").select2({
				  data: customers
				});
				
	 
	    <?php if(isset($_POST['customers'])) { ?>
		
		$("#customers").val("<?php echo  $_POST['customers'];?>");
	        $('#customers').trigger('change');
	 
			<?php } ?>
	   
	    
  } );
  </script>
  
	<style>
		.main {
    width: 100%;
    margin-top: 7rem;
    height: 100%;
    margin-bottom: 1.5rem;
}
		.select2-container {
    box-sizing: border-box;
    display: inline-block;
    margin: 0;
    position: relative;
    vertical-align: middle;
        width: 100% !important;
    height: 35px;
    line-height: 35px;
    padding: 0px 10px;
}
		.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 35px;
		}
		.select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 26px;
    position: absolute;
    top:5px;
    right: 10px;
    width: 20px;
}
		.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 35px;
}
	.btn-danger {
    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    margin: 4px;
}
	.breadcrumbs{display:none;}	
	#myHeaderhead, #oldfooter, .navbar{font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    max-width: 100% !important;
    margin: 0 !important;
	}
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;text-align: center;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;text-align: center;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
.ui-datepicker td {
    border: 0;
    padding: 1px;
    width: 10%;
}

#customerMealResport{text-align: center;font-size: 20px;margin: 30px auto;
	text-transform: capitalize;width: 100%;display: block;}
* {box-sizing: border-box}
.loader {
  position: fixed;
  left: 40%;
  top: 50%;
  z-index: 9999;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #0eb58f;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  max-width:560px;
  margin:auto;
}
h2{font-weight: normal;margin: auto;
width: 560px;font-size:17px;
height:60px;color: #000;
line-height:60px;}
		.tabledata td, .tabledata th{padding:10px;font-size:18px;width: auto;}
		.dataalign{    float: left;
    text-align: center;
    width: 33%;
    margin: 10px auto}
.noprint {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}

.modal-footer{margin: auto;width: 560px;padding: 10px 0px;}
@media print
{
.noprint {display:none;font-family: arial, sans-serif;border-collapse: collapse;width: 100%;max-width: 560px;margin: 20px auto;}
}

@media print {
    @page {
      size: A4; /* DIN A4 standard, Europe */
      margin:0;
    }
    html, body {
        width: 210mm;
        /* height: 297mm; */
        height: 282mm;
        font-size: 18px;
        background: #FFF;
        overflow:visible;
    }
    body {
        padding-top:15mm;
    }
}

@media all {
.page-break { display: none; }
}

@media print {
.page-break { display: block; page-break-before: always; }
}
@media screen and (min-width:260px) and (max-width:760px){
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 68%;
}	
	.dataalign{float: left;
text-align: center;
width: 100%;
margin: 10px;}
#printdate select {
    font-size: 17px;
    margin: 10px;
    width: 68%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}
@media screen and (min-width:768px) and (max-width:999px){
	#printdate input[type="text"] {
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
    margin: 10px;
    width: 80%;
}	
#printdate select {
    font-size: 14px;
    margin: 10px;
    width: 80%;
    max-width: 100%;
    background: #f6fcfc;
    height: 35px;
    box-shadow: 0 0 2px rgba(0, 0, 0, .3);
    border: 0;
}

}

.hideme{display:none;}
</style>
<?php
$choosenDate='';
$choosenCity='';
$msg ="";
if (isset($_POST["submit"]) )
{
	 
	  $choosenCustomer    = $_POST['customers'];
          
         
           if($choosenCustomer=='')
          {
             $msg.="Please select the customer<br>" ;
          }
}
	   
?>
<div class="noprint">
<form method="POST" action="<?php echo Mage::getBaseUrl().'heal/index/customermeals';?>" >

<h1 class="noprint" style="text-align: center;font-size: 24px;margin-bottom: 30px;text-transform: capitalize;">Customer Meal Calory Report</h1>
<table width="1000" border="1" align="center" id="printdate" style="padding-left: 20px;margin:auto;padding-top:10px;" rules="none">

  <tbody class="noprint">
       
	  <tr>  
               <td class="dataalign">
				   
                <span style="width:100%;float:left;height: 35px;line-height: 35px;">Select Customer:</span>
				 </td>
				 <td class="dataalign">
                <select id="customers" name="customers">
		</select>
               
 	     </td>
		  <td style="float: left;margin: 10px auto;text-align: right;width: 33%;"><input type="submit" name="submit" value="Submit" style="padding: 0px 10px;background: #0EB58F;border: 1px solid #0eb58f;color: #fff;font-size: 14px;height: 35px;border-radius: 4px;line-height: 35px;text-align:center;width:100%;"></td>
        </tr>
        <?php if($msg!=''){?>
        <tr><td style="float: left;margin: auto;text-align: left;width: 100%;color:red"><?php echo $msg;?></td>
	  
	  </tr>
        <?php } ?>
     
  </tbody>
</table>
</form>
</div>
<?php 

if (isset($_POST["submit"]) && $_POST['customers']!='')
{
        $customerEmail  = strtolower($_POST['customers']);
        $msg='';
        $dbRead      = Mage::getSingleton('core/resource')->getConnection('core_read');
        $selectDatewiseOrders='';
        $cuccrentDate = date('Y-m-d');
      
        if($customerEmail!='')
        {
           $selectDatewiseOrders= "select * from healorder where email='$customerEmail' order by formatted_orderdate asc";
           $customerResult = $dbRead->fetchAll($selectDatewiseOrders);
        }
        else
        {
           $msg="Please select the customer name";

        }



        if($msg=='' && count($customerResult)>0)
        {
             $customerEmail = $_POST['customers'];
             $customer = Mage::getModel("customer/customer"); 
             $customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
             $customer->loadByEmail($customerEmail);
             $name = $customer->getFirstname(). " ".  $customer->getLastname();  
            ?>
<div class="print" >
<span id="customerMealResport"><b><?php echo $name;?> </b> Weekly Meal Report </b></span>
    <table cellpadding="0" cellspacing="0" border="1" class="tabledata container">
        <tr><th>&nbsp;</th><th  style="font-weight:600;">Day</th><th  style="font-weight:600;">Cal</th><th  style="font-weight:600;">Protein (gm)</th><th  style="font-weight:600;">Fat (gm)</th><th  style="font-weight:600;">Carbs (gm)</th><th  style="font-weight:600;">Fiber (gm)</th><th style="font-weight:600;">Weight</th></tr>

    <?php 
         $recordCount=0;
         $weekCount=1;
         $weekDay=0;  
         $weekDayCounter=0;

         $allDinnerCal=0;
         $allDinnerFiber=0;
         $allDinnerProtein=0;
         $allDinnerFat=0;
         $allDinnerCarbohydrete=0;


         $allBreakfastCal=0;
         $allBreakfastFiber=0;
         $allBreakfastProtein=0;
         $allBreakfastFat=0;
         $allBreakfastCarbohydrete=0;

         $allLunchCal=0;
         $allLunchFiber=0;
         $allLunchProtein=0;
         $allLunchFat=0;
         $allLunchCarbohydrete=0;

         $allHighteaCal=0;
         $allHighteaFiber=0;
         $allHighteaProtein=0;
         $allHighteaFat=0;
         $allHighteaCarbohydrete=0;

         $totalCal=0;
         $totalFiber=0;
         $totalProtein=0;
         $totalFat=0;
         $totalCarbohydrete=0;

         $rowTotalCal=0;
         $rowTotalFiber=0;
         $rowTotalProtein=0;
         $rowTotalFat=0;
         $rowTotalCarbohydrete=0;
           
         foreach($customerResult as $row)
         { 
                  $recordCount++;  
                  $weekNumer = 'Week '.$weekCount;

                  $allDinnerCal=0;
                  $allDinnerFiber=0;
                  $allDinnerProtein=0;
                  $allDinnerFat=0;
                  $allDinnerCarbohydrete=0;


                  $allBreakfastCal=0;
                  $allBreakfastFiber=0;
                  $allBreakfastProtein=0;
                  $allBreakfastFat=0;
                  $allBreakfastCarbohydrete=0;

                  $allLunchCal=0;
                  $allLunchFiber=0;
                  $allLunchProtein=0;
                  $allLunchFat=0;
                  $allLunchCarbohydrete=0;

                  $allHighteaCal=0;
                  $allHighteaFiber=0;
                  $allHighteaProtein=0;
                  $allHighteaFat=0;
                  $allHighteaCarbohydrete=0;

                  $rowTotalCal=0;
                  $rowTotalFiber=0;
                  $rowTotalProtein=0;
                  $rowTotalFat=0;
                  $rowTotalCarbohydrete=0;

                  if($recordCount%7==0)
                 {
                     $weekCount++;
                     $weekDay=0;
                     $weekDayCounter=7;



                 }
                 else
                 {
                        $weekDay++;
                        $weekDayCounter=0;
                 }

                 $weekDayToShow = 'Day '. ($weekDay+$weekDayCounter);  



                 $orderId   =  $row['id']; 
                 $orderInfo =  Mage::getModel("heal/order")->load($orderId);
                 $customerEmail = $orderInfo->getEmail();
                 $orderFormattedDate = date_create($orderInfo->getFormattedOrderdate());
                 $orderDate = date_format($orderFormattedDate,'d-M-Y');

                 $dinnerTotalCalories = $orderInfo->getDinnerTotalCalories(); $rowTotalCal+=$dinnerTotalCalories;
                 $dinnerTotalFiber    = $orderInfo->getDinnerTotalFiber();    $rowTotalFiber+=$dinnerTotalFiber;
                 $dinnerTotalProtein  = $orderInfo->getDinnerTotalProtein();  $rowTotalProtein+=$dinnerTotalProtein;    
                 $dinnerTotalFat      = $orderInfo->getDinnerTotalFat();      $rowTotalFat+=$dinnerTotalFat;
                 $dinnerTotalCarbohydrates = $orderInfo->getDinnerTotalCarbohydrates(); $rowTotalCarbohydrete+=$dinnerTotalCarbohydrates;

                 $allDinnerCal+= $dinnerTotalCalories; 
                 $allDinnerFiber+=$dinnerTotalFiber;
                 $allDinnerProtein+= $dinnerTotalProtein;
                 $allDinnerFat+=$dinnerTotalFat;
                 $allDinnerCarbohydrete+=$dinnerTotalCarbohydrates;

                 $breakfastTotalCalories = $orderInfo->getBreakfastTotalCalories();  $rowTotalCal+=$breakfastTotalCalories;
                 $breakfastTotalFiber    = $orderInfo->getBreakfastTotalFiber();     $rowTotalFiber+=$breakfastTotalFiber;
                 $breakfastTotalProtein  = $orderInfo->getBreakfastTotalProtein();   $rowTotalProtein+=$breakfastTotalProtein;  
                 $breakfastTotalFat      = $orderInfo->getBreakfastTotalFat();        $rowTotalFat+=$breakfastTotalFat;
                 $breakfastTotalCarbohydrates = $orderInfo->getBreakfastTotalCarbohydrates(); $rowTotalCarbohydrete+=$breakfastTotalCarbohydrates;

                 $allBreakfastCal+=     $breakfastTotalCalories; 
                 $allBreakfastFiber+=   $breakfastTotalFiber;
                 $allBreakfastProtein+= $breakfastTotalProtein;
                 $allBreakfastFat+=      $breakfastTotalFat;
                 $allBreakfastCarbohydrete+=$breakfastTotalCarbohydrates;

                 $lunchTotalCalories = $orderInfo->getLunchTotalCalories();    $rowTotalCal+=$lunchTotalCalories;
                 $lunchTotalFiber    = $orderInfo->getLunchTotalFiber();        $rowTotalFiber+=$lunchTotalFiber;
                 $lunchTotalProtein  = $orderInfo->getLunchTotalProtein();      $rowTotalProtein+=$lunchTotalProtein;  
                 $lunchTotalFat      = $orderInfo->getLunchTotalFat();          $rowTotalFat+=$lunchTotalFat;
                 $lunchTotalCarbohydrates = $orderInfo->getLunchTotalCarbohydrates();  $rowTotalCarbohydrete+=$lunchTotalCarbohydrates;

                 $allLunchCal+=     $lunchTotalCalories; 
                 $allLunchFiber+=   $lunchTotalFiber;
                 $allLunchProtein+= $lunchTotalProtein;
                 $allLunchFat+=      $lunchTotalFat;
                 $allLunchCarbohydrete+=$lunchTotalCarbohydrates;

                 $highteaTotalCalories = $orderInfo->getHighteaTotalCalories();  $rowTotalCal+=$highteaTotalCalories;
                 $highteaTotalFiber    = $orderInfo->getHighteaTotalFiber();      $rowTotalFiber+=$highteaTotalFiber;
                 $highteaTotalProtein  = $orderInfo->getHighteaTotalProtein();     $rowTotalProtein+=$highteaTotalProtein;  
                 $highteaTotalFat      = $orderInfo->getHighteaTotalFat();                $rowTotalFat+=$highteaTotalFat;     
                 $highteaTotalCarbohydrates = $orderInfo->getHighteaTotalCarbohydrates();  $rowTotalCarbohydrete+=$highteaTotalCarbohydrates;

                 $allHighteaCal+=     $highteaTotalCalories; 
                 $allHighteaFiber+=   $highteaTotalFiber;
                 $allHighteaProtein+= $highteaTotalProtein;
                 $allHighteaFat+=      $highteaTotalFat;
                 $allHighteaCarbohydrete+=$highteaTotalCarbohydrates;


                  $totalCal+=$rowTotalCal;
                  $totalFiber+=$rowTotalFiber;
                  $totalProtein+=$rowTotalProtein;
                  $totalFat+=$rowTotalFat;
                  $totalCarbohydrete+=$rowTotalCarbohydrete;
            ?>

             <tr>   
                  <?php if($weekDay==1){ ?>
                    <td rowspan="7" style="text-align:left;padding-left: 2px;"><?php echo $weekNumer;?>
                  <?php } ?>
                     <td  style="font-weight:600;"><?php echo $weekDayToShow;?> </td>
                     <td><?php echo $rowTotalCal;?></td>
                     <td><?php echo $rowTotalProtein;?></td>
                     <td><?php echo $rowTotalFat ;?></td>
                     <td><?php echo $rowTotalCarbohydrete;?></td>
                     <td><?php echo $rowTotalFiber;?></td>
                     <td>&nbsp;</td>
             </tr>

             <?php
             if($recordCount%7==0){ ?>
              <tr>   
                     <td style="font-weight:600;"><?php echo $weekNumer;?> Total</td>
                     <td>&nbsp;</td>
                     <td><?php echo $totalCal;?></td>
                     <td><?php echo $totalProtein;?></td>
                     <td><?php echo $totalFat ;?></td>
                     <td><?php echo $totalCarbohydrete;?></td>
                     <td><?php echo $totalFiber;?></td>
                     <td>&nbsp;</td>
               </tr>
             <?php }

                 if($recordCount%7==0)
                  {
                     $totalCal=0;
                     $totalFiber=0;
                     $totalProtein=0;
                     $totalFat=0;
                     $totalCarbohydrete=0;
                  }
       }
  ?>
            
     <tr><td colspan="9" style="text-align:center" class="noprint"> <input type="button" value="Print" onclick="print();" style="padding: 0px 10px;background: #0EB58F;border: 1px solid #0eb58f;color: #fff;font-size: 14px;height: 35px;line-height: 35px;text-align:center"/></td></tr>
   </table>
</div>          
 <?php
}
else {  ?>
            <div style="text-align: center">No meal record found.</div>
<?php }

}