<?php 
if (Mage::getSingleton('customer/session')->isLoggedIn()):
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $email = $customer->getEmail();
    $firstName = $customer->getFirstname();
    $lastName = $customer->getLastname();

   $videopermission =$customer->getVideopermission();
    if($videopermission==1)
   {
	     $videoquantity =$customer->getVideoquantity();
		 $videoPacks = getAllVideos($videoquantity);
		// $videos = $customer->getVideos();
		 $startingdate = date("Y-m-d",strtotime($customer->getStartingdate())); //echo "<br>";
         $endingdate    = date('Y-m-d', strtotime($customer->getEndingdate())); //echo "<br>";
		$currentDate = date('Y-m-d');
		if( $currentDate !=  $endingdate)
		{ ?>
		<table cellpadding="0" cellspacing="0" width="100%" >	
        <tr><td style="width:70%;text-align:top">
		  <?php
		        $param = Mage::app()->getRequest()->getParam('vid');
				$vid=1;
				$videoDetails = getVideoDetails($vid);
				
				if(isset($param) && ( $param>1 && $param<=12 ) )
				{
					$vid=$param;
					$videoDetails = getVideoDetails($vid);
				}
				?>
				<div style="alignment-adjust:central">Hi <?php echo $firstName."&nbsp;".$lastName;?>, you can view the videos till <strong><?php echo date('d-M-Y', strtotime($endingdate));?></strong></div>
		   		
                <?php
                if($videoquantity==6 || $videoquantity==12 )
				{?>
					<video id="video" width="640" height="360" poster="<?php echo $videoDetails['poster']; ?>" preload="auto" controls disablepictureinpicture  controlsList="nodownload" autoplay="autoplay">
			         <?php echo $videoDetails['source'];?>
		           </video>
                    <?php echo $videoDetails['title'];?>
				<?php }
				
		 ?> 
         </td>
         <td style="width:10%; background-color:#FFF">&nbsp;</td>
         <td style="width:20%; background-color:#FFF;margin-left:40px">
           <?php 
		   if(sizeof($videoPacks) >0)
		   {
			   foreach($videoPacks as $videoInfo)
			   {
		   ?>
           <p><a href="<?php echo $videoInfo['url'];?>"><img src="<?php echo $videoInfo['poster'];?>" height="70px" width="100px" title="<?php echo $videoInfo['title'];?>" /> <?php echo $videoInfo['title'];?></a></p>
           <?php }
		   } ?>
       </td>  </tr>
        </table>
		<?php
        } 
		else
		{
		  echo "<strong>Your video's subscription time has completed, please renew it, thanks.</strong>";
	    }
   
   }
   else
   {
	   echo "<strong>You have not enrolled any videos.</strong>";   
	}
endif;
 

function getVideoDetails($vid)
{
	$source =array();
    if($vid==1)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video1"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/1";
	}
	if($vid==2)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video2"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/2";
	}
	if($vid==3)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video3"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/3";
	}
	if($vid==4)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>';  
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video4"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/4";
	}
	if($vid==5)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video5"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/5";
	}
	if($vid==6)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video6"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/6";
	}
	if($vid==7)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video7"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/7";
	}
	if($vid==8)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video8"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/8";
	}
	if($vid==9)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video9"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/9";
	}
	if($vid==10)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video10"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/10";
	}
	if($vid==11)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/rain.mp4" type="video/mp4" />';  
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video11"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/11";
	}
	if($vid==12)
	{
		$source["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source["title"]="Video12"; 
		$source["url"]=Mage::getBaseUrl()."customer/account/video/vid/12";
	}
	return $source;
	
}

function getAllVideos($videoquantity)
{
   	$source = array();
	if($videoquantity==6)
	{
		$source[1]["source"]="<source src='".Mage::getBaseUrl()."video/rain.mp4' type='video/mp4' />"; 
		$source[1]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[1]["title"]="Video1"; 
		$source[1]["url"]=Mage::getBaseUrl()."customer/account/video/vid/1";
		
		$source[2]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[2]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[2]["title"]="Video2"; 
		$source[2]["url"]=Mage::getBaseUrl()."customer/account/video/vid/2";
		
		$source[3]["source"]="<source src='".Mage::getBaseUrl()."video/rain3.mp4' type='video/mp4' />"; 
		$source[3]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[3]["title"]="Video3"; 
		$source[3]["url"]=Mage::getBaseUrl()."customer/account/video/vid/3";
		
		$source[4]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[4]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[4]["title"]="Video4"; 
		$source[4]["url"]=Mage::getBaseUrl()."customer/account/video/vid/4";
		
		$source[5]["source"]="<source src='".Mage::getBaseUrl()."video/rain5.mp4' type='video/mp4' />"; 
		$source[5]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[5]["title"]="Video5"; 
		$source[5]["url"]=Mage::getBaseUrl()."customer/account/video/vid/5";
		
		$source[6]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[6]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[6]["title"]="Video6"; 
		$source[6]["url"]=Mage::getBaseUrl()."customer/account/video/vid/6";
		
	}
	else if($videoquantity==12)
	{
		$source[1]["source"]="<source src='".Mage::getBaseUrl()."video/rain.mp4' type='video/mp4' />"; 
		$source[1]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[1]["title"]="Video1"; 
		$source[1]["url"]=Mage::getBaseUrl()."customer/account/video/vid/1";
		
		$source[2]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[2]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[2]["title"]="Video2"; 
		$source[2]["url"]=Mage::getBaseUrl()."customer/account/video/vid/2";
		
		$source[3]["source"]="<source src='".Mage::getBaseUrl()."video/rain3.mp4' type='video/mp4' />"; 
		$source[3]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[3]["title"]="Video3"; 
		$source[3]["url"]=Mage::getBaseUrl()."customer/account/video/vid/3";
		
		$source[4]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[4]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[4]["title"]="Video4"; 
		$source[4]["url"]=Mage::getBaseUrl()."customer/account/video/vid/4";
		
		$source[5]["source"]="<source src='".Mage::getBaseUrl()."video/rain5.mp4' type='video/mp4' />"; 
		$source[5]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[5]["title"]="Video5"; 
		$source[5]["url"]=Mage::getBaseUrl()."customer/account/video/vid/5";
		
		$source[6]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[6]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[6]["title"]="Video6"; 
		$source[6]["url"]=Mage::getBaseUrl()."customer/account/video/vid/6";
		
		$source[7]["source"]="<source src='".Mage::getBaseUrl()."video/rain7.mp4' type='video/mp4' />"; 
		$source[7]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[7]["title"]="Video7"; 
		$source[7]["url"]=Mage::getBaseUrl()."customer/account/video/vid/7";
		
		$source[8]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[8]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[8]["title"]="Video8"; 
		$source[8]["url"]=Mage::getBaseUrl()."customer/account/video/vid/8";
		
		$source[9]["source"]="<source src='".Mage::getBaseUrl()."video/rain9.mp4' type='video/mp4' />"; 
		$source[9]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[9]["title"]="Video9"; 
		$source[9]["url"]=Mage::getBaseUrl()."customer/account/video/vid/9";
		
		$source[10]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[10]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[10]["title"]="Video10"; 
		$source[10]["url"]=Mage::getBaseUrl()."customer/account/video/vid/10";
		
		$source[11]["source"]="<source src='".Mage::getBaseUrl()."video/rain11.mp4' type='video/mp4' />"; 
		$source[11]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[11]["title"]="Video11"; 
		$source[11]["url"]=Mage::getBaseUrl()."customer/account/video/vid/11";
		
		$source[12]["source"]='<source src="'.Mage::getBaseUrl().'video/BigBuckBunnysmall.mp4" type="video/mp4"/>'; 
		$source[12]["poster"]="https://addpipe.com/sample_vid/poster.png";
		$source[12]["title"]="Video12"; 
		$source[12]["url"]=Mage::getBaseUrl()."customer/account/video/vid/12";
	}
	return $source;
	
}

?> 


