<?php
 
									  
	$uploadDir = Mage::getBaseDir('media').DS.'foodpdf'.DS;	
	
   							  
	if(isset($_POST['submit']))
	{
            
     	$fileName ='';	
		if ( isset( $_FILES['pdfFile'] ) )
		{
			$source_file = $_FILES['pdfFile']['tmp_name'];
			$fileName =$_FILES['pdfFile']['name'];
			$dest_file = $uploadDir.$fileName;
				   
			move_uploaded_file( $source_file, $dest_file )
			or die ("Error!!");
			header("Location:".Mage::getBaseUrl()."foodpdf/index/uploadcsv?action=1");
				
        }
   }

		
	
	
	
	
 ?>

 <div class="container mypdf">

	<form class="pdf_form" action="<?php echo Mage::getBaseUrl();?>foodpdf/index/index" method="post" enctype="multipart/form-data">
		<div class="form-row">	
			<div class="form-upload">	  		
	   			<input type="file" name="pdfFile" id="pdfFile" />
	   			<span>Upload Pdf</span>
	   		</div>
	   	</div>
	   
	    
			<input type="submit" value="Save Meal Item" name="submit">
	  		
	  		
	 
	</form>
</div>


<style type="text/css">
.mypdf .pdf_form{
	width: 60%;
	padding: 30px;
	box-sizing: border-box;	
	margin: 30px auto;
	box-shadow: 0 0 1px 0 rgba(0,0,0,0.2); 
	position: relative;
}
.form-row{
	/*margin-bottom: 1.8rem;*/
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
}

.select-category, .form-upload, .select-status{
	box-sizing: border-box;
	width:100%;
	position: relative;
	height:40px;
	border:1px solid #dadada;
	background: #fff;
	border-right: 0;
	margin-bottom: 20px;
}
.form-upload{	
	padding: 5px 25px;
	border:1px solid #dadada;
}
/*.select-status{
	width:32%;
}*/
.pdf_form input[type="text"] {
	border:0;
	border:1px solid #dadada;
	width:100%;
	height: 40px;
	box-sizing: border-box;
	outline: none;
	padding: 0 15px;
	background:#fff;
	margin-bottom: 20px;
}

.select-category select, .select-status select {
	width: 100%;
	display: block;
	box-sizing: border-box;
	position: relative;
	appearance:none;
	-webkit-appearance:none;
	-moz-appearance:none;
	background: transparent;
	cursor: pointer;
	height:40px;
	border:0;
	outline: none;
	z-index: 100;
	padding: 0 15px;
}
	
.select-category:before, .select-status:before {
	position: absolute;
	content: '';
	right:0;
	width:40px;
	height: 40px;
	background: #0eb58f;
	border:1px solid #0eb58f;
	z-index: 5;			
} 

.select-category:after, .select-status:after {
	content: '';
	position: absolute;	
	top:20px;
	right: 12px;
	z-index: 5;
	width: 0; 
  	height: 0; 
	border-left: 8px solid transparent;
  	border-right: 8px solid transparent;  
  	border-top: 8px solid #fff
}
.pdf_form input[type="submit"]{
	display: block;
	width:230px;
	margin:0 auto;
	height: 45px;
	line-height: 45px;
	text-align: center;
	cursor: pointer;
	border:0;
	outline: none;
	/*background: #007f00;
    border: 1px solid #66d50d;
    background: #d31f02;
    border: 1px solid #fe5a52;*/
    background: #0eb58f;
    border: 1px solid #0eb58f;
    color: #fff;
    font-size: 1.3rem;
    font-weight: 500;
}
.mypdf	.outer_table{
	width:100%;
	padding: 20px;
	box-sizing: border-box;
	/*box-shadow: 0 2px 1px 1px rgba(0,0,0,0.2);*/
}
.cat_table{
	width:100%;
	border:1px solid #dadada;
	border-collapse: collapse;
}
.cat_table th{ 
    padding: 10px 15px;
    border:1px solid #dadada;
}
.cat_table td { 
    padding: 2px 15px;
    border:1px solid #dadada;
}
.cat_table tr:nth-child(even) { 
    background:#f6f6f6;
}
.table-icon{
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
}
.form-footer{
	position: relative;
}
.cancel{
	position: absolute;
	right: 27px;
	bottom: 30px;
	border:0;
	outline: none;
	cursor: pointer;	
    color: #fff;   
    font-weight: 600;
    padding: 0 25px;
    font-size: 1.2rem;
    height: 45px;
	line-height: 45px;
	text-align: center;	
    background: #0eb58f;
    border: 1px solid #0eb58f;
}
.msg-box{
	text-align: center;
    font-size: 1.5rem;  
    font-weight: 600;
}
.green_msg{
	  color: green;
}
.red_msg{
	  color: red;
}


</style>